const TRANS_WEST = {
  fr: {
    nav_logo: "Tarifer les D\u00e9g\u00e2ts",
    nav_how: "Fonctionnement",
    nav_principles: "Principes",
    nav_examples: "Exemples",
    nav_questions: "Questions ouvertes",
    nav_join: "Rejoindre",
    hero_label: "Un cadre politique pour la crise climatique",
    hero_title: "Rendre la pollution<br><em>co\u00fbteuse</em>.",
    hero_subtitle: "Chaque produit comporte un co\u00fbt environnemental cach\u00e9. Nous proposons une redevance en \u00e9quivalent CO\u2082 sur l\u2019ensemble de la cha\u00eene d\u2019approvisionnement \u2014 transformant les d\u00e9g\u00e2ts \u00e9cologiques en pression \u00e9conomique, tout en redistribuant les recettes pour prot\u00e9ger les citoyens.",
    hero_btn_primary: "D\u00e9couvrir le fonctionnement \u2193",
    hero_btn_secondary: "Rejoindre le mouvement",
    how_label: "01 \u2014 M\u00e9canisme",
    how_title: "Une redevance \u00e0 chaque \u00e9tape",
    how_desc: "Des redevances en \u00e9quivalent CO\u2082 sont appliqu\u00e9es en amont, \u00e0 chaque \u00e9tape de la cha\u00eene d\u2019approvisionnement. Le co\u00fbt total s\u2019accumule dans le prix final \u2014 rendant les produits \u00e0 fortes \u00e9missions naturellement plus chers.",
    stage1_title: "Extraction",
    stage1_desc: "Extraction mini\u00e8re, forage p\u00e9trolier, r\u00e9colte",
    stage2_title: "Production",
    stage2_desc: "Fabrication, raffinage, transformation",
    stage3_title: "Transport",
    stage3_desc: "Exp\u00e9dition, fret, logistique",
    stage4_title: "Distribution &amp; utilisation",
    stage4_desc: "Distribution, phase d\u2019utilisation par le consommateur",
    stage5_title: "\u00c9limination",
    stage5_desc: "Fin de vie via la responsabilit\u00e9 \u00e9largie du producteur",
    stage_fee: "+ redevance CO\u2082",
    pipeline_result: "Les donn\u00e9es existent d\u00e9j\u00e0. Les <strong>analyses de cycle de vie (ACV)</strong> et les empreintes carbone des produits couvrent l\u2019ensemble de la cha\u00eene \u2014 de l\u2019extraction \u00e0 l\u2019\u00e9limination. Nous n\u2019avons pas besoin de nouvelles recherches. Nous avons besoin de volont\u00e9 politique.",
    manifesto: "Transformer l\u2019impact environnemental en <em>pression \u00e9conomique in\u00e9vitable</em>, puis redistribuer l\u2019argent pour maintenir la stabilit\u00e9 sociale tout en for\u00e7ant le march\u00e9 \u00e0 se <em>d\u00e9carboner</em>.",
    principles_label: "02 \u2014 Principes",
    principles_title: "Ce que nous d\u00e9fendons",
    principles_desc: "Il ne s\u2019agit pas de campagnes de sensibilisation ou d\u2019engagements volontaires. Il s\u2019agit de repenser les incitations \u00e9conomiques depuis la base.",
    p1_title: "Le prix, pas la sensibilisation",
    p1_text: "Des d\u00e9cennies de campagnes de sensibilisation n\u2019ont pas infl\u00e9chi la courbe des \u00e9missions. Les signaux de prix modifient les comportements \u00e0 grande \u00e9chelle \u2014 automatiquement, universellement et imm\u00e9diatement.",
    p2_title: "Prot\u00e9ger les citoyens, pas les pollueurs",
    p2_text: "Les recettes financent les biens publics et un revenu minimum pour compenser la hausse des prix. Pas de subventions pour que les entreprises \u00ab deviennent vertes \u00bb. Si vous polluez, vous payez. L\u2019argent prot\u00e8ge les citoyens.",
    p3_title: "Co\u00fbt social du carbone",
    p3_text: "La redevance par tonne est fond\u00e9e sur les d\u00e9g\u00e2ts r\u00e9els caus\u00e9s par le CO\u2082. Un prix plus \u00e9lev\u00e9 entra\u00eene un changement de comportement plus fort \u2014 mais exige aussi une redistribution sociale plus importante pour rester \u00e9quitable.",
    p4_title: "Mise en \u0153uvre \u00e0 l\u2019\u00e9chelle europ\u00e9enne",
    p4_text: "Une mise en \u0153uvre exclusivement nationale fausse les \u00e9changes au sein du march\u00e9 unique. Cela n\u00e9cessite une coordination \u00e0 l\u2019\u00e9chelle de l\u2019UE \u2014 ou des taxes nationales soigneusement con\u00e7ues qui ne cr\u00e9ent pas d\u2019avantages d\u00e9loyaux.",
    examples_label: "03 \u2014 Chiffres concrets",
    examples_title: "\u00c0 quoi cela ressemble-t-il\u00a0?",
    examples_desc: "En utilisant les donn\u00e9es existantes d\u2019analyse de cycle de vie et un prix du carbone de $100 par tonne d\u2019\u00e9quivalent CO\u2082.",
    ex_case: "\u00c9tude de cas",
    ex_beef: "B\u0153uf",
    ex_oil: "P\u00e9trole brut",
    ex_lifecycle: "\u00c9missions sur le cycle de vie",
    ex_carbon_price: "Prix du carbone appliqu\u00e9",
    ex_additional_kg: "Co\u00fbt suppl\u00e9mentaire par kg",
    ex_additional_barrel: "Co\u00fbt suppl\u00e9mentaire par baril",
    ex_beef_insight: "Inclut la production d\u2019aliments pour animaux (engrais d\u2019origine p\u00e9troli\u00e8re), le m\u00e9thane du b\u00e9tail, le changement d\u2019affectation des sols et la transformation. La majeure partie des \u00e9missions provient de la biologie \u2014 pas seulement des intrants \u00e9nerg\u00e9tiques.",
    ex_oil_insight: "Impact significatif sur le prix \u2014 mais les co\u00fbts se diluent lorsque le p\u00e9trole est r\u00e9parti entre des milliers de produits d\u00e9riv\u00e9s. L\u2019impact le plus fort touche les processus concentr\u00e9s \u00e0 fortes \u00e9missions comme l\u2019\u00e9levage, pas uniquement les intrants industriels.",
    questions_label: "04 \u2014 Zones d\u2019ombre",
    questions_title: "Questions ouvertes",
    questions_desc: "Nous ne pr\u00e9tendons pas avoir toutes les r\u00e9ponses. Voici les probl\u00e8mes difficiles qui n\u00e9cessitent une intelligence collective.",
    q1: "Quel prix exact du carbone est n\u00e9cessaire pour modifier significativement le comportement des consommateurs et de l\u2019industrie sans provoquer de choc \u00e9conomique\u00a0?",
    q2: "Comment garantir une comptabilit\u00e9 pr\u00e9cise du cycle de vie \u00e0 l\u2019\u00e9chelle mondiale, lorsque les cha\u00eenes d\u2019approvisionnement traversent des dizaines de pays aux normes diff\u00e9rentes\u00a0?",
    q3: "Comment traiter les importations en provenance de pays non conformes\u00a0? Les ajustements carbone aux fronti\u00e8res sont prometteurs mais politiquement et logistiquement complexes.",
    q4: "Quelle est la voie r\u00e9aliste vers la faisabilit\u00e9 politique au sein des structures europ\u00e9ennes \u2014 et comment construire la coalition n\u00e9cessaire\u00a0?",
    q5: "Quelle vitesse de transition est possible sans d\u00e9stabiliser les moyens de subsistance\u00a0? Quel est le juste \u00e9quilibre entre urgence et stabilit\u00e9 sociale\u00a0?",
    join_label: "05 \u2014 Agir",
    join_title: "Rejoignez le mouvement",
    join_desc: "Cette id\u00e9e a besoin d\u2019\u00e9conomistes, de d\u00e9cideurs politiques, de militants et de citoyens convaincus que c\u2019est le prix \u2014 et non la culpabilit\u00e9 \u2014 qui change le monde. Faites entendre votre voix.",
    join_placeholder: "votre@email.com",
    join_btn: "S\u2019inscrire",
    join_btn_done: "Ajout\u00e9 \u2713",
    join_note: "Pas de spam. Des mises \u00e0 jour sur l\u2019avanc\u00e9e des politiques, la recherche et les actions que vous pouvez entreprendre.",
    footer_mechanism: "M\u00e9canisme",
    footer_data: "Donn\u00e9es",
    calc_label: "03.5 \u2014 Essayez vous-m\u00eame",
    calc_title: "Chiffrer les d\u00e9g\u00e2ts",
    calc_desc: "D\u00e9couvrez ce que co\u00fbteraient r\u00e9ellement les produits du quotidien si les d\u00e9g\u00e2ts environnementaux \u00e9taient inclus dans le prix.",
    calc_cat_label: "Cat\u00e9gorie",
    calc_prod_label: "Produit",
    calc_qty_label: "Quantit\u00e9",
    calc_unit_label: "Unit\u00e9",
    calc_price_label: "Prix du carbone",
    calc_cat_food: "Alimentation & boissons",
    calc_cat_clothing: "V\u00eatements (par mati\u00e8re)",
    calc_cat_electronics: "\u00c9lectronique (par taille)",
    calc_cat_travel: "Transports",
    calc_cat_fuel: "Combustibles",
    calc_price_50: "$50 / ton",
    calc_price_100: "$100 / ton",
    calc_price_150: "$150 / ton",
    calc_price_200: "$200 / ton",
    calc_eco_label: "\u00c9cocertifi\u00e9 / source biologique (r\u00e9duit l\u2019estimation d\u2019environ 15\u00a0%)",
    calc_result_label: "Empreinte CO\u2082",
    calc_sources: "Sources\u00a0: Poore & Nemecek (2018), <a href=\"https://doi.org/10.1126/science.aaq0216\" target=\"_blank\" rel=\"noopener\"><em>Science</em> 360:987</a> (alimentation) \u00b7 <a href=\"https://www.gov.uk/government/collections/government-conversion-factors-for-company-reporting\" target=\"_blank\" rel=\"noopener\">UK DEFRA 2023</a> (combustibles/vols) \u00b7 Apple/Levi\u2019s Product Environmental Reports (\u00e9lectronique/v\u00eatements)",
    calc_damage_cost: "co\u00fbt des d\u00e9g\u00e2ts",
    calc_eco_note: "(\u00e9cocertifi\u00e9\u00a0: \u221215\u00a0%)",
    calc_prod_beef: "B\u0153uf",
    calc_prod_chicken: "Poulet",
    calc_prod_cheese: "Fromage",
    calc_prod_milk: "Lait (vache)",
    calc_prod_rice: "Riz",
    calc_prod_coffee: "Caf\u00e9 (torr\u00e9fi\u00e9)",
    calc_prod_chocolate: "Chocolat noir",
    calc_prod_tomatoes: "Tomates",
    calc_prod_potatoes: "Pommes de terre",
    calc_prod_eggs: "\u0152ufs",
    calc_prod_bread: "Pain (bl\u00e9)",
    calc_prod_cotton_tshirt: "Coton \u2014 T-shirt (250\u00a0g)",
    calc_prod_cotton_jeans: "Coton \u2014 Jean (denim)",
    calc_prod_polyester_shirt: "Polyester \u2014 Chemise",
    calc_prod_polyester_jacket: "Polyester \u2014 Veste",
    calc_prod_wool_sweater: "Laine \u2014 Pull",
    calc_prod_wool_coat: "Laine \u2014 Manteau",
    calc_prod_leather_shoes: "Cuir \u2014 Chaussures",
    calc_prod_nylon_sneakers: "Nylon/Mixte \u2014 Baskets",
    calc_prod_smartphone: "Format t\u00e9l\u00e9phone (smartphone)",
    calc_prod_tablet: "Format tablette (10\u2033)",
    calc_prod_laptop: "Format portable (13\u201316\u2033)",
    calc_prod_monitor: "Format \u00e9cran (24\u201327\u2033)",
    calc_prod_tv: "Format TV (50\u201365\u2033)",
    calc_prod_desktop: "PC de bureau (tour)",
    calc_prod_flight_short: "Vol \u2014 court-courrier (<3\u00a0h)",
    calc_prod_flight_long: "Vol \u2014 long-courrier (>6\u00a0h)",
    calc_prod_car_petrol: "Voiture \u2014 essence (moy.)",
    calc_prod_car_diesel: "Voiture \u2014 diesel (moy.)",
    calc_prod_train: "Train (r\u00e9seau national)",
    calc_prod_bus: "Bus (longue distance)",
    calc_prod_petrol: "Essence",
    calc_prod_diesel: "Diesel",
    calc_prod_natural_gas: "Gaz naturel (chauffage)",
    calc_prod_electricity_eu: "\u00c9lectricit\u00e9 (moy. UE)",
    calc_note_beef: "ACV m\u00e9diane mondiale\u00a0; fourchette 20\u2013105\u00a0kg CO\u2082e/kg",
    calc_note_chicken: "Inclut utilisation des sols, alimentation animale, transformation",
    calc_note_cheese: "~10\u00a0litres de lait par kg de fromage",
    calc_note_milk: "Inclut la fermentation ent\u00e9rique et l\u2019utilisation des sols",
    calc_note_rice: "Le m\u00e9thane des rizi\u00e8res inond\u00e9es domine",
    calc_note_coffee: "Fourchette 3,5\u201328,5\u00a0; tr\u00e8s d\u00e9pendant de l\u2019utilisation des sols",
    calc_note_chocolate: "Forte composante de d\u00e9forestation dans la cha\u00eene d\u2019approvisionnement du cacao",
    calc_note_tomatoes: "Valeur en plein champ\u00a0; serre chauff\u00e9e ~2,1",
    calc_note_potatoes: "L\u2019un des f\u00e9culents \u00e0 plus faibles \u00e9missions",
    calc_note_eggs: "~12\u00a0\u0153ufs par kg",
    calc_note_bread: "Pain de bl\u00e9 standard",
    calc_note_cotton_tshirt: "La culture du coton repr\u00e9sente environ la moiti\u00e9 de l\u2019empreinte",
    calc_note_cotton_jeans: "Cycle de vie complet\u00a0: de la culture \u00e0 la fin de vie",
    calc_note_polyester_shirt: "Fibre d\u00e9riv\u00e9e de combustibles fossiles",
    calc_note_polyester_jacket: "Rembourrage synth\u00e9tique + enveloppe \u00e0 base de p\u00e9trole",
    calc_note_wool_sweater: "M\u00e9thane des moutons + transformation",
    calc_note_wool_coat: "Laine lourde\u00a0; fort impact m\u00e9thane + teinture",
    calc_note_leather_shoes: "\u00c9levage bovin + produits chimiques de tannage",
    calc_note_nylon_sneakers: "Mat\u00e9riaux mixtes\u00a0; domin\u00e9 par la fabrication",
    calc_note_smartphone: "La fabrication repr\u00e9sente ~80\u00a0% de l\u2019empreinte\u00a0; dur\u00e9e de vie 3\u00a0ans",
    calc_note_tablet: "Impact entre celui du t\u00e9l\u00e9phone et du portable",
    calc_note_laptop: "Fourchette 150\u2013400\u00a0kg\u00a0; d\u00e9pend des composants",
    calc_note_monitor: "Fabrication de l\u2019\u00e9cran + utilisation pluriannuelle",
    calc_note_tv: "Grand \u00e9cran + \u00e9lectricit\u00e9 de la phase d\u2019utilisation sur 7\u00a0ans",
    calc_note_desktop: "Consommation \u00e9lectrique plus \u00e9lev\u00e9e\u00a0; dur\u00e9e de vie des composants plus longue",
    calc_note_flight_short: "Par passager, classe \u00e9conomique\u00a0; inclut le for\u00e7age radiatif",
    calc_note_flight_long: "Plus efficace par km sur les longues distances",
    calc_note_car_petrol: "Voiture essence europ\u00e9enne moyenne ~210\u00a0g CO\u2082/km",
    calc_note_car_diesel: "L\u00e9g\u00e8rement moins de CO\u2082 par km que l\u2019essence",
    calc_note_train: "Varie \u00e9norm\u00e9ment selon le mix \u00e9lectrique\u00a0; moyenne UE",
    calc_note_bus: "Par passager\u00a0; taux de remplissage \u00e9lev\u00e9 suppos\u00e9",
    calc_note_petrol: "Du puits \u00e0 la roue, y compris extraction en amont",
    calc_note_diesel: "L\u00e9g\u00e8rement plus \u00e9lev\u00e9 par litre que l\u2019essence",
    calc_note_natural_gas: "Combustion + fuites de m\u00e9thane en amont",
    calc_note_electricity_eu: "Moyenne du r\u00e9seau UE\u00a0; varie selon le pays",
  },

  de: {
    nav_logo: "Sch\u00e4den bepreisen",
    nav_how: "Funktionsweise",
    nav_principles: "Grunds\u00e4tze",
    nav_examples: "Beispiele",
    nav_questions: "Offene Fragen",
    nav_join: "Mitmachen",
    hero_label: "Ein politischer Rahmen f\u00fcr die Klimakrise",
    hero_title: "Verschmutzung<br><em>teuer</em> machen.",
    hero_subtitle: "Jedes Produkt verursacht versteckte Umweltkosten. Wir schlagen eine CO\u2082-\u00c4quivalent-Abgabe entlang der gesamten Lieferkette vor \u2014 \u00f6kologische Sch\u00e4den werden zu \u00f6konomischem Druck, w\u00e4hrend die Einnahmen umverteilt werden, um die Menschen zu sch\u00fctzen.",
    hero_btn_primary: "So funktioniert es \u2193",
    hero_btn_secondary: "Bewegung beitreten",
    how_label: "01 \u2014 Mechanismus",
    how_title: "Eine Abgabe auf jeder Stufe",
    how_desc: "CO\u2082-\u00c4quivalent-Abgaben werden vorgelagert an jedem Punkt der Lieferkette erhoben. Die Gesamtkosten akkumulieren sich im Endpreis \u2014 so werden emissionsintensive Produkte nat\u00fcrlicherweise teurer.",
    stage1_title: "Gewinnung",
    stage1_desc: "Rohstoffabbau, \u00d6lbohrung, Ernte",
    stage2_title: "Produktion",
    stage2_desc: "Fertigung, Raffinierung, Verarbeitung",
    stage3_title: "Transport",
    stage3_desc: "Versand, Fracht, Logistik",
    stage4_title: "Handel &amp; Nutzung",
    stage4_desc: "Distribution, Nutzungsphase durch Verbraucher",
    stage5_title: "Entsorgung",
    stage5_desc: "Lebensende durch erweiterte Herstellerverantwortung",
    stage_fee: "+ CO\u2082-Abgabe",
    pipeline_result: "Die Daten existieren bereits. <strong>\u00d6kobilanzen (LCAs)</strong> und produktbezogene CO\u2082-Fu\u00dfabdr\u00fccke decken die gesamte Kette ab \u2014 von der Gewinnung bis zur Entsorgung. Wir brauchen keine neue Wissenschaft. Wir brauchen politischen Willen.",
    manifesto: "Umweltauswirkungen in <em>unvermeidbaren \u00f6konomischen Druck</em> verwandeln, dann das Geld umverteilen, um die Gesellschaft stabil zu halten und den Markt zur <em>Dekarbonisierung</em> zu zwingen.",
    principles_label: "02 \u2014 Grunds\u00e4tze",
    principles_title: "Wof\u00fcr wir stehen",
    principles_desc: "Es geht nicht um Aufkl\u00e4rungskampagnen oder freiwillige Selbstverpflichtungen. Es geht darum, wirtschaftliche Anreize von Grund auf neu zu gestalten.",
    p1_title: "Preis statt Bewusstsein",
    p1_text: "Jahrzehntelange Aufkl\u00e4rungskampagnen haben die Emissionskurve nicht gesenkt. Preissignale ver\u00e4ndern Verhalten in gro\u00dfem Ma\u00dfstab \u2014 automatisch, universell und sofort.",
    p2_title: "Menschen sch\u00fctzen, nicht Verschmutzer",
    p2_text: "Die Einnahmen flie\u00dfen in \u00f6ffentliche G\u00fcter und ein Mindesteinkommen, um h\u00f6here Preise auszugleichen. Keine Subventionen, damit Unternehmen \u201egr\u00fcn werden\u201c. Wer verschmutzt, zahlt. Das Geld sch\u00fctzt die B\u00fcrgerinnen und B\u00fcrger.",
    p3_title: "Soziale Kosten des Kohlenstoffs",
    p3_text: "Die Abgabe pro Tonne basiert auf dem tats\u00e4chlichen Schaden, den CO\u2082 verursacht. Ein h\u00f6herer Preis bewirkt st\u00e4rkere Verhaltens\u00e4nderungen \u2014 erfordert aber auch eine st\u00e4rkere soziale Umverteilung, um gerecht zu bleiben.",
    p4_title: "EU-weite Umsetzung",
    p4_text: "Eine rein nationale Umsetzung verzerrt den Handel im Binnenmarkt. Dies erfordert eine EU-weite Koordination \u2014 oder sorgf\u00e4ltig gestaltete nationale Steuern, die keine unfairen Vorteile schaffen.",
    examples_label: "03 \u2014 Konkrete Zahlen",
    examples_title: "Wie sieht das aus?",
    examples_desc: "Auf Grundlage bestehender \u00d6kobilanzdaten und eines CO\u2082-Preises von $100 pro Tonne CO\u2082-\u00c4quivalent.",
    ex_case: "Fallstudie",
    ex_beef: "Rindfleisch",
    ex_oil: "Roh\u00f6l",
    ex_lifecycle: "Lebenszyklusemissionen",
    ex_carbon_price: "Angewandter CO\u2082-Preis",
    ex_additional_kg: "Mehrkosten pro kg",
    ex_additional_barrel: "Mehrkosten pro Barrel",
    ex_beef_insight: "Umfasst Futtermittelproduktion (erd\u00f6lbasierte D\u00fcngemittel), Methan aus der Rinderhaltung, Landnutzungs\u00e4nderungen und Verarbeitung. Der Gro\u00dfteil der Emissionen stammt aus biologischen Prozessen \u2014 nicht nur aus Energieeinsatz.",
    ex_oil_insight: "Erhebliche Preisauswirkung \u2014 aber die Kosten verd\u00fcnnen sich, wenn \u00d6l auf Tausende nachgelagerter Produkte verteilt wird. Die gr\u00f6\u00dfte Wirkung trifft konzentrierte emissionsintensive Prozesse wie die Viehwirtschaft, nicht nur industrielle Inputs.",
    questions_label: "04 \u2014 Offene Punkte",
    questions_title: "Offene Fragen",
    questions_desc: "Wir geben nicht vor, auf alles eine Antwort zu haben. Dies sind die schwierigen Probleme, f\u00fcr die wir kollektive Intelligenz brauchen.",
    q1: "Welcher genaue CO\u2082-Preis ist erforderlich, um das Verhalten von Verbrauchern und Industrie sp\u00fcrbar zu ver\u00e4ndern, ohne einen wirtschaftlichen Schock auszul\u00f6sen?",
    q2: "Wie l\u00e4sst sich eine pr\u00e4zise Lebenszyklusbilanzierung weltweit durchsetzen, wenn Lieferketten Dutzende L\u00e4nder mit unterschiedlichen Standards umfassen?",
    q3: "Wie sollen Importe aus nicht konformen L\u00e4ndern behandelt werden? CO\u2082-Grenzausgleichsmechanismen sind vielversprechend, aber politisch und logistisch komplex.",
    q4: "Was ist der realistische Weg zur politischen Machbarkeit innerhalb der EU-Strukturen \u2014 und wie bauen wir die n\u00f6tige Koalition auf?",
    q5: "Wie schnell k\u00f6nnen wir den \u00dcbergang gestalten, ohne Existenzgrundlagen zu gef\u00e4hrden? Wie sieht die richtige Balance zwischen Dringlichkeit und sozialer Stabilit\u00e4t aus?",
    join_label: "05 \u2014 Handeln",
    join_title: "Werden Sie Teil der Bewegung",
    join_desc: "Diese Idee braucht \u00d6konomen, politische Entscheidungstr\u00e4ger, Aktivisten und B\u00fcrger, die \u00fcberzeugt sind, dass der Preis \u2014 nicht das schlechte Gewissen \u2014 die Welt ver\u00e4ndert. Erheben Sie Ihre Stimme.",
    join_placeholder: "ihre@email.com",
    join_btn: "Anmelden",
    join_btn_done: "Hinzugef\u00fcgt \u2713",
    join_note: "Kein Spam. Neuigkeiten zu politischen Fortschritten, Forschung und M\u00f6glichkeiten zum Handeln.",
    footer_mechanism: "Mechanismus",
    footer_data: "Daten",
    calc_label: "03.5 \u2014 Selbst ausprobieren",
    calc_title: "Sch\u00e4den berechnen",
    calc_desc: "Sehen Sie, was Alltagsprodukte wirklich kosten w\u00fcrden, wenn Umweltsch\u00e4den im Preis enthalten w\u00e4ren.",
    calc_cat_label: "Kategorie",
    calc_prod_label: "Produkt",
    calc_qty_label: "Menge",
    calc_unit_label: "Einheit",
    calc_price_label: "CO\u2082-Preis",
    calc_cat_food: "Lebensmittel & Getr\u00e4nke",
    calc_cat_clothing: "Kleidung (nach Material)",
    calc_cat_electronics: "Elektronik (nach Gr\u00f6\u00dfe)",
    calc_cat_travel: "Reisen",
    calc_cat_fuel: "Brennstoffe",
    calc_price_50: "$50 / ton",
    calc_price_100: "$100 / ton",
    calc_price_150: "$150 / ton",
    calc_price_200: "$200 / ton",
    calc_eco_label: "\u00d6kozertifiziert / biologische Quelle (reduziert die Sch\u00e4tzung um ~15\u00a0%)",
    calc_result_label: "CO\u2082-Fu\u00dfabdruck",
    calc_sources: "Quellen: Poore & Nemecek (2018), <a href=\"https://doi.org/10.1126/science.aaq0216\" target=\"_blank\" rel=\"noopener\"><em>Science</em> 360:987</a> (Lebensmittel) \u00b7 <a href=\"https://www.gov.uk/government/collections/government-conversion-factors-for-company-reporting\" target=\"_blank\" rel=\"noopener\">UK DEFRA 2023</a> (Brennstoffe/Fl\u00fcge) \u00b7 Apple/Levi\u2019s Product Environmental Reports (Elektronik/Kleidung)",
    calc_damage_cost: "Schadenskosten",
    calc_eco_note: "(\u00f6kozertifiziert: \u221215\u00a0%)",
    calc_prod_beef: "Rindfleisch",
    calc_prod_chicken: "H\u00e4hnchen",
    calc_prod_cheese: "K\u00e4se",
    calc_prod_milk: "Milch (Kuh)",
    calc_prod_rice: "Reis",
    calc_prod_coffee: "Kaffee (ger\u00f6stet)",
    calc_prod_chocolate: "Zartbitterschokolade",
    calc_prod_tomatoes: "Tomaten",
    calc_prod_potatoes: "Kartoffeln",
    calc_prod_eggs: "Eier",
    calc_prod_bread: "Brot (Weizen)",
    calc_prod_cotton_tshirt: "Baumwolle \u2014 T-Shirt (250\u00a0g)",
    calc_prod_cotton_jeans: "Baumwolle \u2014 Jeans (Denim)",
    calc_prod_polyester_shirt: "Polyester \u2014 Hemd",
    calc_prod_polyester_jacket: "Polyester \u2014 Jacke",
    calc_prod_wool_sweater: "Wolle \u2014 Pullover",
    calc_prod_wool_coat: "Wolle \u2014 Mantel",
    calc_prod_leather_shoes: "Leder \u2014 Schuhe",
    calc_prod_nylon_sneakers: "Nylon/Mischgewebe \u2014 Sneaker",
    calc_prod_smartphone: "Telefongr\u00f6\u00dfe (Smartphone)",
    calc_prod_tablet: "Tabletgr\u00f6\u00dfe (10\u2033)",
    calc_prod_laptop: "Laptopgr\u00f6\u00dfe (13\u201316\u2033)",
    calc_prod_monitor: "Monitorgr\u00f6\u00dfe (24\u201327\u2033)",
    calc_prod_tv: "TV-Gr\u00f6\u00dfe (50\u201365\u2033)",
    calc_prod_desktop: "Desktop-PC (Tower)",
    calc_prod_flight_short: "Flug \u2014 Kurzstrecke (<3\u00a0h)",
    calc_prod_flight_long: "Flug \u2014 Langstrecke (>6\u00a0h)",
    calc_prod_car_petrol: "Auto \u2014 Benzin (Durchschn.)",
    calc_prod_car_diesel: "Auto \u2014 Diesel (Durchschn.)",
    calc_prod_train: "Zug (Fernverkehr)",
    calc_prod_bus: "Bus (Fernbus)",
    calc_prod_petrol: "Benzin",
    calc_prod_diesel: "Diesel",
    calc_prod_natural_gas: "Erdgas (Heizung)",
    calc_prod_electricity_eu: "Strom (EU-Durchschn.)",
    calc_note_beef: "Globaler LCA-Median; Spanne 20\u2013105\u00a0kg CO\u2082e/kg",
    calc_note_chicken: "Beinhaltet Landnutzung, Futtermittel, Verarbeitung",
    calc_note_cheese: "~10\u00a0Liter Milch pro kg K\u00e4se",
    calc_note_milk: "Beinhaltet enterische Fermentation und Landnutzung",
    calc_note_rice: "Methan aus gefluteten Reisfeldern dominiert",
    calc_note_coffee: "Spanne 3,5\u201328,5; stark landnutzungsabh\u00e4ngig",
    calc_note_chocolate: "Hoher Entwaldungsanteil in der Kakao-Lieferkette",
    calc_note_tomatoes: "Freilandwert; beheiztes Gew\u00e4chshaus ~2,1",
    calc_note_potatoes: "Eines der emissionsarmsten st\u00e4rkehaltigen Lebensmittel",
    calc_note_eggs: "~12\u00a0Eier pro kg",
    calc_note_bread: "Standard-Weizenbrot",
    calc_note_cotton_tshirt: "Baumwollanbau macht ~die H\u00e4lfte des Fu\u00dfabdrucks aus",
    calc_note_cotton_jeans: "Gesamter Lebenszyklus: vom Anbau bis zum Lebensende",
    calc_note_polyester_shirt: "Faser aus fossilen Brennstoffen",
    calc_note_polyester_jacket: "Synthetische F\u00fcllung + Schale auf Erd\u00f6lbasis",
    calc_note_wool_sweater: "Methan der Schafe + Verarbeitung",
    calc_note_wool_coat: "Schwere Wolle; hoher Methan- + F\u00e4rbeeinfluss",
    calc_note_leather_shoes: "Rinderhaltung + Gerbchemikalien",
    calc_note_nylon_sneakers: "Mischmaterialien; fertigungsdominiert",
    calc_note_smartphone: "Fertigung ~80\u00a0% des Fu\u00dfabdrucks; 3\u00a0Jahre Nutzungsdauer",
    calc_note_tablet: "Zwischen Telefon und Laptop im Impact",
    calc_note_laptop: "Spanne 150\u2013400\u00a0kg; abh\u00e4ngig von den Komponenten",
    calc_note_monitor: "Displayfertigung + mehrj\u00e4hrige Nutzung",
    calc_note_tv: "Gro\u00dfes Display + 7\u00a0Jahre Stromverbrauch in der Nutzungsphase",
    calc_note_desktop: "H\u00f6herer Stromverbrauch; l\u00e4ngere Komponentenlebensdauer",
    calc_note_flight_short: "Pro Passagier, Economy; inklusive Strahlungsantrieb",
    calc_note_flight_long: "Effizienter pro km auf l\u00e4ngeren Strecken",
    calc_note_car_petrol: "Durchschnittliches europ\u00e4isches Benzinauto ~210\u00a0g CO\u2082/km",
    calc_note_car_diesel: "Etwas weniger CO\u2082 pro km als Benzin",
    calc_note_train: "Variiert stark je nach Strommix; EU-Durchschnitt",
    calc_note_bus: "Pro Passagier; hohe Auslastung angenommen",
    calc_note_petrol: "Well-to-Wheel einschlie\u00dflich vorgelagerter F\u00f6rderung",
    calc_note_diesel: "Etwas h\u00f6her pro Liter als Benzin",
    calc_note_natural_gas: "Verbrennung + vorgelagerte Methanleckagen",
    calc_note_electricity_eu: "EU-Netzdurchschnitt; variiert nach Land",
  },

  es: {
    nav_logo: "Poner precio al da\u00f1o",
    nav_how: "C\u00f3mo funciona",
    nav_principles: "Principios",
    nav_examples: "Ejemplos",
    nav_questions: "Preguntas abiertas",
    nav_join: "Unirse",
    hero_label: "Un marco pol\u00edtico para la crisis clim\u00e1tica",
    hero_title: "Hacer que contaminar<br>sea <em>caro</em>.",
    hero_subtitle: "Cada producto conlleva un coste ambiental oculto. Proponemos una tasa de equivalente de CO\u2082 a lo largo de toda la cadena de suministro \u2014 convirtiendo el da\u00f1o ecol\u00f3gico en presi\u00f3n econ\u00f3mica, al tiempo que se redistribuyen los ingresos para proteger a la ciudadan\u00eda.",
    hero_btn_primary: "Ver c\u00f3mo funciona \u2193",
    hero_btn_secondary: "Unirse al movimiento",
    how_label: "01 \u2014 Mecanismo",
    how_title: "Una tasa en cada etapa",
    how_desc: "Las tasas de equivalente de CO\u2082 se aplican aguas arriba en cada punto de la cadena de suministro. El coste total se acumula en el precio final \u2014 haciendo que los productos con altas emisiones sean naturalmente m\u00e1s caros.",
    stage1_title: "Extracci\u00f3n",
    stage1_desc: "Miner\u00eda de materias primas, perforaci\u00f3n petrol\u00edfera, cosecha",
    stage2_title: "Producci\u00f3n",
    stage2_desc: "Fabricaci\u00f3n, refinado, procesamiento",
    stage3_title: "Transporte",
    stage3_desc: "Env\u00edo, carga, log\u00edstica",
    stage4_title: "Comercio &amp; uso",
    stage4_desc: "Distribuci\u00f3n, fase de uso por el consumidor",
    stage5_title: "Eliminaci\u00f3n",
    stage5_desc: "Fin de vida mediante responsabilidad ampliada del productor",
    stage_fee: "+ tasa CO\u2082",
    pipeline_result: "Los datos ya existen. Los <strong>an\u00e1lisis de ciclo de vida (ACV)</strong> y las huellas de carbono de productos cubren toda la cadena \u2014 de la extracci\u00f3n a la eliminaci\u00f3n. No necesitamos nueva ciencia. Necesitamos voluntad pol\u00edtica.",
    manifesto: "Convertir el impacto ambiental en <em>presi\u00f3n econ\u00f3mica inevitable</em>, y luego redistribuir el dinero para mantener la estabilidad social mientras se obliga al mercado a <em>descarbonizarse</em>.",
    principles_label: "02 \u2014 Principios",
    principles_title: "Lo que defendemos",
    principles_desc: "No se trata de campa\u00f1as de concienciaci\u00f3n ni de compromisos voluntarios. Se trata de redise\u00f1ar los incentivos econ\u00f3micos desde la base.",
    p1_title: "Precio, no concienciaci\u00f3n",
    p1_text: "D\u00e9cadas de campa\u00f1as de concienciaci\u00f3n no han doblado la curva de emisiones. Las se\u00f1ales de precio cambian el comportamiento a gran escala \u2014 de forma autom\u00e1tica, universal e inmediata.",
    p2_title: "Proteger a las personas, no a los contaminadores",
    p2_text: "Los ingresos se destinan a bienes p\u00fablicos y a una renta m\u00ednima para compensar el aumento de precios. Sin subvenciones para que las empresas \u00abse vuelvan verdes\u00bb. Si contaminas, pagas. El dinero protege a la ciudadan\u00eda.",
    p3_title: "Coste social del carbono",
    p3_text: "La tasa por tonelada se basa en el da\u00f1o real que causa el CO\u2082. Un precio m\u00e1s alto produce un mayor cambio de comportamiento \u2014 pero tambi\u00e9n exige una redistribuci\u00f3n social m\u00e1s fuerte para que sea justo.",
    p4_title: "Implementaci\u00f3n a escala europea",
    p4_text: "Una implementaci\u00f3n exclusivamente nacional distorsiona el comercio dentro del mercado \u00fanico. Se necesita coordinaci\u00f3n a escala de la UE \u2014 o impuestos nacionales cuidadosamente dise\u00f1ados que no generen ventajas desleales.",
    examples_label: "03 \u2014 Cifras reales",
    examples_title: "\u00bfC\u00f3mo se traduce esto?",
    examples_desc: "Utilizando datos existentes de an\u00e1lisis de ciclo de vida y un precio del carbono de $100 por tonelada de equivalente de CO\u2082.",
    ex_case: "Caso pr\u00e1ctico",
    ex_beef: "Carne de vacuno",
    ex_oil: "Petr\u00f3leo crudo",
    ex_lifecycle: "Emisiones del ciclo de vida",
    ex_carbon_price: "Precio del carbono aplicado",
    ex_additional_kg: "Coste adicional por kg",
    ex_additional_barrel: "Coste adicional por barril",
    ex_beef_insight: "Incluye la producci\u00f3n de pienso (fertilizantes derivados del petr\u00f3leo), el metano del ganado, el cambio de uso del suelo y el procesamiento. La mayor\u00eda de las emisiones provienen de la biolog\u00eda \u2014 no solo de los insumos energ\u00e9ticos.",
    ex_oil_insight: "Impacto significativo en el precio \u2014 pero los costes se diluyen cuando el petr\u00f3leo se distribuye entre miles de productos derivados. El mayor impacto recae sobre procesos concentrados de altas emisiones como la ganader\u00eda, no solo sobre los insumos industriales.",
    questions_label: "04 \u2014 Cuestiones pendientes",
    questions_title: "Preguntas abiertas",
    questions_desc: "No pretendemos tener todas las respuestas. Estos son los problemas dif\u00edciles que requieren inteligencia colectiva.",
    q1: "\u00bfQu\u00e9 precio exacto del carbono se necesita para modificar significativamente el comportamiento de consumidores e industria sin provocar un shock econ\u00f3mico?",
    q2: "\u00bfC\u00f3mo garantizar una contabilidad precisa del ciclo de vida a nivel global, cuando las cadenas de suministro atraviesan decenas de pa\u00edses con est\u00e1ndares diferentes?",
    q3: "\u00bfC\u00f3mo deber\u00edan tratarse las importaciones de pa\u00edses no conformes? Los ajustes de carbono en frontera son prometedores, pero pol\u00edtica y log\u00edsticamente complejos.",
    q4: "\u00bfCu\u00e1l es la v\u00eda realista hacia la viabilidad pol\u00edtica dentro de las estructuras de la UE \u2014 y c\u00f3mo construimos la coalici\u00f3n necesaria?",
    q5: "\u00bfCon qu\u00e9 rapidez podemos realizar la transici\u00f3n sin desestabilizar los medios de vida? \u00bfCu\u00e1l es el equilibrio adecuado entre urgencia y estabilidad social?",
    join_label: "05 \u2014 Act\u00fae",
    join_title: "\u00danase al movimiento",
    join_desc: "Esta idea necesita economistas, responsables pol\u00edticos, activistas y ciudadanos que crean que el precio \u2014 no la culpa \u2014 es lo que cambia el mundo. Haga o\u00edr su voz.",
    join_placeholder: "su@email.com",
    join_btn: "Suscribirse",
    join_btn_done: "A\u00f1adido \u2713",
    join_note: "Sin spam. Actualizaciones sobre avances pol\u00edticos, investigaci\u00f3n y acciones que puede emprender.",
    footer_mechanism: "Mecanismo",
    footer_data: "Datos",
    calc_label: "03.5 \u2014 Pru\u00e9belo t\u00fa mismo",
    calc_title: "Calcula el da\u00f1o",
    calc_desc: "Descubre cu\u00e1nto costar\u00edan realmente los productos cotidianos si el da\u00f1o ambiental estuviera incluido en el precio.",
    calc_cat_label: "Categor\u00eda",
    calc_prod_label: "Producto",
    calc_qty_label: "Cantidad",
    calc_unit_label: "Unidad",
    calc_price_label: "Precio del carbono",
    calc_cat_food: "Alimentaci\u00f3n y bebidas",
    calc_cat_clothing: "Ropa (por material)",
    calc_cat_electronics: "Electr\u00f3nica (por tama\u00f1o)",
    calc_cat_travel: "Transporte",
    calc_cat_fuel: "Combustibles",
    calc_price_50: "$50 / ton",
    calc_price_100: "$100 / ton",
    calc_price_150: "$150 / ton",
    calc_price_200: "$200 / ton",
    calc_eco_label: "Ecocertificado / fuente org\u00e1nica (reduce la estimaci\u00f3n en ~15\u00a0%)",
    calc_result_label: "Huella de CO\u2082",
    calc_sources: "Fuentes: Poore & Nemecek (2018), <a href=\"https://doi.org/10.1126/science.aaq0216\" target=\"_blank\" rel=\"noopener\"><em>Science</em> 360:987</a> (alimentaci\u00f3n) \u00b7 <a href=\"https://www.gov.uk/government/collections/government-conversion-factors-for-company-reporting\" target=\"_blank\" rel=\"noopener\">UK DEFRA 2023</a> (combustibles/vuelos) \u00b7 Apple/Levi\u2019s Product Environmental Reports (electr\u00f3nica/ropa)",
    calc_damage_cost: "coste del da\u00f1o",
    calc_eco_note: "(ecocertificado: \u221215\u00a0%)",
    calc_prod_beef: "Ternera",
    calc_prod_chicken: "Pollo",
    calc_prod_cheese: "Queso",
    calc_prod_milk: "Leche (vaca)",
    calc_prod_rice: "Arroz",
    calc_prod_coffee: "Caf\u00e9 (tostado)",
    calc_prod_chocolate: "Chocolate negro",
    calc_prod_tomatoes: "Tomates",
    calc_prod_potatoes: "Patatas",
    calc_prod_eggs: "Huevos",
    calc_prod_bread: "Pan (trigo)",
    calc_prod_cotton_tshirt: "Algod\u00f3n \u2014 Camiseta (250\u00a0g)",
    calc_prod_cotton_jeans: "Algod\u00f3n \u2014 Vaqueros (denim)",
    calc_prod_polyester_shirt: "Poli\u00e9ster \u2014 Camisa",
    calc_prod_polyester_jacket: "Poli\u00e9ster \u2014 Chaqueta",
    calc_prod_wool_sweater: "Lana \u2014 Jersey",
    calc_prod_wool_coat: "Lana \u2014 Abrigo",
    calc_prod_leather_shoes: "Cuero \u2014 Zapatos",
    calc_prod_nylon_sneakers: "Nailon/Mixto \u2014 Zapatillas",
    calc_prod_smartphone: "Tama\u00f1o tel\u00e9fono (smartphone)",
    calc_prod_tablet: "Tama\u00f1o tableta (10\u2033)",
    calc_prod_laptop: "Tama\u00f1o port\u00e1til (13\u201316\u2033)",
    calc_prod_monitor: "Tama\u00f1o monitor (24\u201327\u2033)",
    calc_prod_tv: "Tama\u00f1o TV (50\u201365\u2033)",
    calc_prod_desktop: "PC de escritorio (torre)",
    calc_prod_flight_short: "Vuelo \u2014 corta distancia (<3\u00a0h)",
    calc_prod_flight_long: "Vuelo \u2014 larga distancia (>6\u00a0h)",
    calc_prod_car_petrol: "Coche \u2014 gasolina (media)",
    calc_prod_car_diesel: "Coche \u2014 di\u00e9sel (media)",
    calc_prod_train: "Tren (red nacional)",
    calc_prod_bus: "Autob\u00fas (larga distancia)",
    calc_prod_petrol: "Gasolina",
    calc_prod_diesel: "Di\u00e9sel",
    calc_prod_natural_gas: "Gas natural (calefacci\u00f3n)",
    calc_prod_electricity_eu: "Electricidad (media UE)",
    calc_note_beef: "ACV mediana global; rango 20\u2013105\u00a0kg CO\u2082e/kg",
    calc_note_chicken: "Incluye uso del suelo, pienso, procesamiento",
    calc_note_cheese: "~10\u00a0litros de leche por kg de queso",
    calc_note_milk: "Incluye fermentaci\u00f3n ent\u00e9rica y uso del suelo",
    calc_note_rice: "Domina el metano de arrozales inundados",
    calc_note_coffee: "Rango 3,5\u201328,5; muy dependiente del uso del suelo",
    calc_note_chocolate: "Alto componente de deforestaci\u00f3n en la cadena de suministro del cacao",
    calc_note_tomatoes: "Valor en campo abierto; invernadero calefactado ~2,1",
    calc_note_potatoes: "Uno de los almidones con menores emisiones",
    calc_note_eggs: "~12\u00a0huevos por kg",
    calc_note_bread: "Pan de trigo est\u00e1ndar",
    calc_note_cotton_tshirt: "El cultivo del algod\u00f3n supone ~la mitad de la huella",
    calc_note_cotton_jeans: "Ciclo de vida completo: del cultivo al fin de vida",
    calc_note_polyester_shirt: "Fibra derivada de combustibles f\u00f3siles",
    calc_note_polyester_jacket: "Relleno sint\u00e9tico + exterior a base de petr\u00f3leo",
    calc_note_wool_sweater: "Metano de las ovejas + procesamiento",
    calc_note_wool_coat: "Lana pesada; alto impacto de metano + tinte",
    calc_note_leather_shoes: "Ganader\u00eda bovina + productos qu\u00edmicos de curtido",
    calc_note_nylon_sneakers: "Materiales mixtos; dominado por la fabricaci\u00f3n",
    calc_note_smartphone: "La fabricaci\u00f3n supone ~80\u00a0% de la huella; vida \u00fatil de 3\u00a0a\u00f1os",
    calc_note_tablet: "Impacto entre el tel\u00e9fono y el port\u00e1til",
    calc_note_laptop: "Rango 150\u2013400\u00a0kg; depende de los componentes",
    calc_note_monitor: "Fabricaci\u00f3n de la pantalla + uso plurianual",
    calc_note_tv: "Pantalla grande + electricidad de la fase de uso durante 7\u00a0a\u00f1os",
    calc_note_desktop: "Mayor consumo el\u00e9ctrico; mayor vida \u00fatil de los componentes",
    calc_note_flight_short: "Por pasajero, clase turista; incluye forzamiento radiativo",
    calc_note_flight_long: "M\u00e1s eficiente por km en largas distancias",
    calc_note_car_petrol: "Coche de gasolina europeo medio ~210\u00a0g CO\u2082/km",
    calc_note_car_diesel: "Ligeramente menos CO\u2082 por km que la gasolina",
    calc_note_train: "Var\u00eda mucho seg\u00fan la red el\u00e9ctrica; media UE",
    calc_note_bus: "Por pasajero; alta ocupaci\u00f3n supuesta",
    calc_note_petrol: "Del pozo a la rueda, incluida la extracci\u00f3n aguas arriba",
    calc_note_diesel: "Ligeramente m\u00e1s alto por litro que la gasolina",
    calc_note_natural_gas: "Combusti\u00f3n + fugas de metano aguas arriba",
    calc_note_electricity_eu: "Media de la red UE; var\u00eda seg\u00fan el pa\u00eds",
  },

  it: {
    nav_logo: "Dare un prezzo al danno",
    nav_how: "Come funziona",
    nav_principles: "Principi",
    nav_examples: "Esempi",
    nav_questions: "Domande aperte",
    nav_join: "Unisciti",
    hero_label: "Un quadro politico per la crisi climatica",
    hero_title: "Rendere l\u2019inquinamento<br><em>costoso</em>.",
    hero_subtitle: "Ogni prodotto comporta un costo ambientale nascosto. Proponiamo un contributo in equivalente di CO\u2082 lungo l\u2019intera catena di fornitura \u2014 trasformando il danno ecologico in pressione economica, redistribuendo al contempo le entrate per proteggere i cittadini.",
    hero_btn_primary: "Scopri come funziona \u2193",
    hero_btn_secondary: "Unisciti al movimento",
    how_label: "01 \u2014 Meccanismo",
    how_title: "Un contributo a ogni fase",
    how_desc: "I contributi in equivalente di CO\u2082 vengono applicati a monte in ogni punto della catena di fornitura. Il costo totale si accumula nel prezzo finale \u2014 rendendo i prodotti ad alte emissioni naturalmente pi\u00f9 costosi.",
    stage1_title: "Estrazione",
    stage1_desc: "Estrazione mineraria, trivellazione petrolifera, raccolta",
    stage2_title: "Produzione",
    stage2_desc: "Manifattura, raffinazione, lavorazione",
    stage3_title: "Trasporto",
    stage3_desc: "Spedizione, trasporto merci, logistica",
    stage4_title: "Commercio &amp; utilizzo",
    stage4_desc: "Distribuzione, fase d\u2019uso da parte del consumatore",
    stage5_title: "Smaltimento",
    stage5_desc: "Fine vita tramite responsabilit\u00e0 estesa del produttore",
    stage_fee: "+ contributo CO\u2082",
    pipeline_result: "I dati esistono gi\u00e0. Le <strong>analisi del ciclo di vita (LCA)</strong> e le impronte di carbonio dei prodotti coprono l\u2019intera catena \u2014 dall\u2019estrazione allo smaltimento. Non servono nuove scoperte scientifiche. Serve volont\u00e0 politica.",
    manifesto: "Trasformare l\u2019impatto ambientale in <em>pressione economica inevitabile</em>, poi redistribuire il denaro per mantenere la stabilit\u00e0 sociale costringendo il mercato a <em>decarbonizzarsi</em>.",
    principles_label: "02 \u2014 Principi",
    principles_title: "Cosa sosteniamo",
    principles_desc: "Non si tratta di campagne di sensibilizzazione o impegni volontari. Si tratta di riprogettare gli incentivi economici dalle fondamenta.",
    p1_title: "Il prezzo, non la sensibilizzazione",
    p1_text: "Decenni di campagne di sensibilizzazione non hanno piegato la curva delle emissioni. I segnali di prezzo cambiano i comportamenti su larga scala \u2014 in modo automatico, universale e immediato.",
    p2_title: "Proteggere le persone, non chi inquina",
    p2_text: "Le entrate vanno ai beni pubblici e a un reddito minimo per compensare l\u2019aumento dei prezzi. Nessun sussidio alle imprese per \u00abdiventare verdi\u00bb. Chi inquina, paga. Il denaro protegge i cittadini.",
    p3_title: "Costo sociale del carbonio",
    p3_text: "Il contributo per tonnellata si basa sul danno reale causato dal CO\u2082. Un prezzo pi\u00f9 alto produce un cambiamento comportamentale pi\u00f9 forte \u2014 ma richiede anche una redistribuzione sociale pi\u00f9 incisiva per garantire l\u2019equit\u00e0.",
    p4_title: "Attuazione a livello europeo",
    p4_text: "Un\u2019attuazione esclusivamente nazionale distorce gli scambi all\u2019interno del mercato unico. Serve un coordinamento a livello UE \u2014 o imposte nazionali attentamente progettate che non creino vantaggi sleali.",
    examples_label: "03 \u2014 Numeri concreti",
    examples_title: "Come si presenta nella pratica?",
    examples_desc: "Utilizzando dati esistenti di analisi del ciclo di vita e un prezzo del carbonio di $100 per tonnellata di equivalente di CO\u2082.",
    ex_case: "Caso di studio",
    ex_beef: "Carne bovina",
    ex_oil: "Petrolio greggio",
    ex_lifecycle: "Emissioni del ciclo di vita",
    ex_carbon_price: "Prezzo del carbonio applicato",
    ex_additional_kg: "Costo aggiuntivo per kg",
    ex_additional_barrel: "Costo aggiuntivo per barile",
    ex_beef_insight: "Include la produzione di mangimi (fertilizzanti di origine petrolifera), il metano bovino, il cambiamento di destinazione d\u2019uso dei suoli e la lavorazione. La maggior parte delle emissioni deriva dalla biologia \u2014 non solo dagli input energetici.",
    ex_oil_insight: "Impatto significativo sul prezzo \u2014 ma i costi si diluiscono quando il petrolio viene distribuito su migliaia di prodotti derivati. L\u2019impatto maggiore ricade sui processi concentrati ad alte emissioni come l\u2019allevamento, non solo sugli input industriali.",
    questions_label: "04 \u2014 Nodi aperti",
    questions_title: "Domande aperte",
    questions_desc: "Non pretendiamo di avere tutte le risposte. Questi sono i problemi complessi che richiedono intelligenza collettiva.",
    q1: "Quale prezzo esatto del carbonio \u00e8 necessario per modificare in modo significativo il comportamento di consumatori e industria senza provocare uno shock economico?",
    q2: "Come garantire una contabilit\u00e0 accurata del ciclo di vita a livello globale, quando le catene di fornitura attraversano decine di paesi con standard diversi?",
    q3: "Come gestire le importazioni da paesi non conformi? I meccanismi di adeguamento del carbonio alle frontiere sono promettenti ma politicamente e logisticamente complessi.",
    q4: "Qual \u00e8 il percorso realistico verso la fattibilit\u00e0 politica all\u2019interno delle strutture dell\u2019UE \u2014 e come costruiamo la coalizione necessaria?",
    q5: "Quanto velocemente possiamo effettuare la transizione senza destabilizzare i mezzi di sussistenza? Qual \u00e8 il giusto equilibrio tra urgenza e stabilit\u00e0 sociale?",
    join_label: "05 \u2014 Agire",
    join_title: "Unisciti al movimento",
    join_desc: "Questa idea ha bisogno di economisti, decisori politici, attivisti e cittadini convinti che sia il prezzo \u2014 non il senso di colpa \u2014 a cambiare il mondo. Fai sentire la tua voce.",
    join_placeholder: "tua@email.com",
    join_btn: "Iscriviti",
    join_btn_done: "Aggiunto \u2713",
    join_note: "Niente spam. Aggiornamenti sui progressi politici, la ricerca e le azioni che puoi intraprendere.",
    footer_mechanism: "Meccanismo",
    footer_data: "Dati",
    calc_label: "03.5 \u2014 Provalo tu stesso",
    calc_title: "Calcola il danno",
    calc_desc: "Scopri quanto costerebbero davvero i prodotti di tutti i giorni se il danno ambientale fosse incluso nel prezzo.",
    calc_cat_label: "Categoria",
    calc_prod_label: "Prodotto",
    calc_qty_label: "Quantit\u00e0",
    calc_unit_label: "Unit\u00e0",
    calc_price_label: "Prezzo del carbonio",
    calc_cat_food: "Cibo e bevande",
    calc_cat_clothing: "Abbigliamento (per materiale)",
    calc_cat_electronics: "Elettronica (per dimensione)",
    calc_cat_travel: "Trasporti",
    calc_cat_fuel: "Combustibili",
    calc_price_50: "$50 / ton",
    calc_price_100: "$100 / ton",
    calc_price_150: "$150 / ton",
    calc_price_200: "$200 / ton",
    calc_eco_label: "Ecocertificato / fonte biologica (riduce la stima del ~15\u00a0%)",
    calc_result_label: "Impronta di CO\u2082",
    calc_sources: "Fonti: Poore & Nemecek (2018), <a href=\"https://doi.org/10.1126/science.aaq0216\" target=\"_blank\" rel=\"noopener\"><em>Science</em> 360:987</a> (alimenti) \u00b7 <a href=\"https://www.gov.uk/government/collections/government-conversion-factors-for-company-reporting\" target=\"_blank\" rel=\"noopener\">UK DEFRA 2023</a> (combustibili/voli) \u00b7 Apple/Levi\u2019s Product Environmental Reports (elettronica/abbigliamento)",
    calc_damage_cost: "costo del danno",
    calc_eco_note: "(ecocertificato: \u221215\u00a0%)",
    calc_prod_beef: "Manzo",
    calc_prod_chicken: "Pollo",
    calc_prod_cheese: "Formaggio",
    calc_prod_milk: "Latte (vacca)",
    calc_prod_rice: "Riso",
    calc_prod_coffee: "Caff\u00e8 (tostato)",
    calc_prod_chocolate: "Cioccolato fondente",
    calc_prod_tomatoes: "Pomodori",
    calc_prod_potatoes: "Patate",
    calc_prod_eggs: "Uova",
    calc_prod_bread: "Pane (frumento)",
    calc_prod_cotton_tshirt: "Cotone \u2014 T-shirt (250\u00a0g)",
    calc_prod_cotton_jeans: "Cotone \u2014 Jeans (denim)",
    calc_prod_polyester_shirt: "Poliestere \u2014 Camicia",
    calc_prod_polyester_jacket: "Poliestere \u2014 Giacca",
    calc_prod_wool_sweater: "Lana \u2014 Maglione",
    calc_prod_wool_coat: "Lana \u2014 Cappotto",
    calc_prod_leather_shoes: "Pelle \u2014 Scarpe",
    calc_prod_nylon_sneakers: "Nylon/Misto \u2014 Sneaker",
    calc_prod_smartphone: "Formato telefono (smartphone)",
    calc_prod_tablet: "Formato tablet (10\u2033)",
    calc_prod_laptop: "Formato laptop (13\u201316\u2033)",
    calc_prod_monitor: "Formato monitor (24\u201327\u2033)",
    calc_prod_tv: "Formato TV (50\u201365\u2033)",
    calc_prod_desktop: "PC desktop (tower)",
    calc_prod_flight_short: "Volo \u2014 breve raggio (<3\u00a0h)",
    calc_prod_flight_long: "Volo \u2014 lungo raggio (>6\u00a0h)",
    calc_prod_car_petrol: "Auto \u2014 benzina (media)",
    calc_prod_car_diesel: "Auto \u2014 diesel (media)",
    calc_prod_train: "Treno (rete nazionale)",
    calc_prod_bus: "Autobus (lunga percorrenza)",
    calc_prod_petrol: "Benzina",
    calc_prod_diesel: "Diesel",
    calc_prod_natural_gas: "Gas naturale (riscaldamento)",
    calc_prod_electricity_eu: "Elettricit\u00e0 (media UE)",
    calc_note_beef: "LCA mediana globale; intervallo 20\u2013105\u00a0kg CO\u2082e/kg",
    calc_note_chicken: "Include uso del suolo, mangimi, lavorazione",
    calc_note_cheese: "~10\u00a0litri di latte per kg di formaggio",
    calc_note_milk: "Include fermentazione enterica e uso del suolo",
    calc_note_rice: "Domina il metano dalle risaie allagate",
    calc_note_coffee: "Intervallo 3,5\u201328,5; fortemente dipendente dall\u2019uso del suolo",
    calc_note_chocolate: "Elevata componente di deforestazione nella filiera del cacao",
    calc_note_tomatoes: "Valore in campo aperto; serra riscaldata ~2,1",
    calc_note_potatoes: "Uno degli amidacei a minori emissioni",
    calc_note_eggs: "~12\u00a0uova per kg",
    calc_note_bread: "Pane di frumento standard",
    calc_note_cotton_tshirt: "La coltivazione del cotone rappresenta ~la met\u00e0 dell\u2019impronta",
    calc_note_cotton_jeans: "Ciclo di vita completo: dalla coltivazione al fine vita",
    calc_note_polyester_shirt: "Fibra derivata da combustibili fossili",
    calc_note_polyester_jacket: "Imbottitura sintetica + guscio a base di petrolio",
    calc_note_wool_sweater: "Metano degli ovini + lavorazione",
    calc_note_wool_coat: "Lana pesante; elevato impatto metano + tintura",
    calc_note_leather_shoes: "Allevamento bovino + sostanze chimiche per la concia",
    calc_note_nylon_sneakers: "Materiali misti; dominato dalla manifattura",
    calc_note_smartphone: "La produzione rappresenta ~80\u00a0% dell\u2019impronta; vita utile 3\u00a0anni",
    calc_note_tablet: "Impatto intermedio tra telefono e laptop",
    calc_note_laptop: "Intervallo 150\u2013400\u00a0kg; dipende dai componenti",
    calc_note_monitor: "Produzione del display + uso pluriennale",
    calc_note_tv: "Grande display + elettricit\u00e0 della fase d\u2019uso per 7\u00a0anni",
    calc_note_desktop: "Consumo energetico pi\u00f9 elevato; vita dei componenti pi\u00f9 lunga",
    calc_note_flight_short: "Per passeggero, economy; include il forzante radiativo",
    calc_note_flight_long: "Pi\u00f9 efficiente per km sulle lunghe distanze",
    calc_note_car_petrol: "Auto a benzina europea media ~210\u00a0g CO\u2082/km",
    calc_note_car_diesel: "Leggermente meno CO\u2082 per km rispetto alla benzina",
    calc_note_train: "Varia enormemente in base al mix elettrico; media UE",
    calc_note_bus: "Per passeggero; alta occupazione ipotizzata",
    calc_note_petrol: "Dal pozzo alla ruota, inclusa estrazione a monte",
    calc_note_diesel: "Leggermente superiore per litro rispetto alla benzina",
    calc_note_natural_gas: "Combustione + perdite di metano a monte",
    calc_note_electricity_eu: "Media della rete UE; varia per paese",
  },

  pt: {
    nav_logo: "Precificar o Dano",
    nav_how: "Como Funciona",
    nav_principles: "Princ\u00edpios",
    nav_examples: "Exemplos",
    nav_questions: "Quest\u00f5es em Aberto",
    nav_join: "Aderir",
    hero_label: "Um quadro pol\u00edtico para a crise clim\u00e1tica",
    hero_title: "Tornar a polui\u00e7\u00e3o<br><em>cara</em>.",
    hero_subtitle: "Cada produto acarreta um custo ambiental oculto. Propomos uma taxa de equivalente de CO\u2082 ao longo de toda a cadeia de abastecimento \u2014 transformando o dano ecol\u00f3gico em press\u00e3o econ\u00f3mica, ao mesmo tempo que se redistribuem as receitas para proteger as pessoas.",
    hero_btn_primary: "Veja como funciona \u2193",
    hero_btn_secondary: "Junte-se ao movimento",
    how_label: "01 \u2014 Mecanismo",
    how_title: "Uma taxa em cada etapa",
    how_desc: "Taxas de equivalente de CO\u2082 s\u00e3o aplicadas a montante em cada ponto da cadeia de abastecimento. O custo total acumula-se no pre\u00e7o final \u2014 tornando os produtos de elevadas emiss\u00f5es naturalmente mais caros.",
    stage1_title: "Extra\u00e7\u00e3o",
    stage1_desc: "Extra\u00e7\u00e3o mineira, perfura\u00e7\u00e3o petrol\u00edfera, colheita",
    stage2_title: "Produ\u00e7\u00e3o",
    stage2_desc: "Fabrico, refina\u00e7\u00e3o, processamento",
    stage3_title: "Transporte",
    stage3_desc: "Expedi\u00e7\u00e3o, carga, log\u00edstica",
    stage4_title: "Com\u00e9rcio &amp; utiliza\u00e7\u00e3o",
    stage4_desc: "Distribui\u00e7\u00e3o, fase de utiliza\u00e7\u00e3o pelo consumidor",
    stage5_title: "Elimina\u00e7\u00e3o",
    stage5_desc: "Fim de vida atrav\u00e9s da responsabilidade alargada do produtor",
    stage_fee: "+ taxa CO\u2082",
    pipeline_result: "Os dados j\u00e1 existem. As <strong>an\u00e1lises de ciclo de vida (ACV)</strong> e as pegadas de carbono dos produtos cobrem toda a cadeia \u2014 da extra\u00e7\u00e3o \u00e0 elimina\u00e7\u00e3o. N\u00e3o precisamos de nova ci\u00eancia. Precisamos de vontade pol\u00edtica.",
    manifesto: "Transformar o impacto ambiental em <em>press\u00e3o econ\u00f3mica inevit\u00e1vel</em>, e depois redistribuir o dinheiro para manter a estabilidade social enquanto se obriga o mercado a <em>descarbonizar-se</em>.",
    principles_label: "02 \u2014 Princ\u00edpios",
    principles_title: "O que defendemos",
    principles_desc: "N\u00e3o se trata de campanhas de sensibiliza\u00e7\u00e3o ou compromissos volunt\u00e1rios. Trata-se de redesenhar os incentivos econ\u00f3micos desde a base.",
    p1_title: "Pre\u00e7o, n\u00e3o sensibiliza\u00e7\u00e3o",
    p1_text: "D\u00e9cadas de campanhas de sensibiliza\u00e7\u00e3o n\u00e3o dobraram a curva das emiss\u00f5es. Os sinais de pre\u00e7o alteram comportamentos em grande escala \u2014 de forma autom\u00e1tica, universal e imediata.",
    p2_title: "Proteger as pessoas, n\u00e3o os poluidores",
    p2_text: "As receitas destinam-se a bens p\u00fablicos e a um rendimento m\u00ednimo para compensar o aumento dos pre\u00e7os. Sem subs\u00eddios para que as empresas \u00abse tornem verdes\u00bb. Se polui, paga. O dinheiro protege os cidad\u00e3os.",
    p3_title: "Custo social do carbono",
    p3_text: "A taxa por tonelada baseia-se no dano real causado pelo CO\u2082. Um pre\u00e7o mais elevado gera uma mudan\u00e7a de comportamento mais forte \u2014 mas tamb\u00e9m exige uma redistribui\u00e7\u00e3o social mais robusta para garantir a equidade.",
    p4_title: "Implementa\u00e7\u00e3o \u00e0 escala europeia",
    p4_text: "Uma implementa\u00e7\u00e3o exclusivamente nacional distorce o com\u00e9rcio no mercado \u00fanico. \u00c9 necess\u00e1ria uma coordena\u00e7\u00e3o \u00e0 escala da UE \u2014 ou impostos nacionais cuidadosamente concebidos que n\u00e3o criem vantagens desleais.",
    examples_label: "03 \u2014 N\u00fameros reais",
    examples_title: "Como \u00e9 que isto se traduz?",
    examples_desc: "Utilizando dados existentes de an\u00e1lise de ciclo de vida e um pre\u00e7o do carbono de $100 por tonelada de equivalente de CO\u2082.",
    ex_case: "Estudo de caso",
    ex_beef: "Carne de bovino",
    ex_oil: "Petr\u00f3leo bruto",
    ex_lifecycle: "Emiss\u00f5es do ciclo de vida",
    ex_carbon_price: "Pre\u00e7o do carbono aplicado",
    ex_additional_kg: "Custo adicional por kg",
    ex_additional_barrel: "Custo adicional por barril",
    ex_beef_insight: "Inclui a produ\u00e7\u00e3o de ra\u00e7\u00e3o (fertilizantes de base petrol\u00edfera), o metano do gado, a mudan\u00e7a de uso do solo e o processamento. A maioria das emiss\u00f5es prov\u00e9m da biologia \u2014 n\u00e3o apenas dos insumos energ\u00e9ticos.",
    ex_oil_insight: "Impacto significativo no pre\u00e7o \u2014 mas os custos diluem-se quando o petr\u00f3leo \u00e9 distribu\u00eddo por milhares de produtos derivados. O maior impacto recai sobre processos concentrados de elevadas emiss\u00f5es como a pecu\u00e1ria, n\u00e3o apenas sobre os insumos industriais.",
    questions_label: "04 \u2014 Lacunas honestas",
    questions_title: "Quest\u00f5es em aberto",
    questions_desc: "N\u00e3o pretendemos ter todas as respostas. Estes s\u00e3o os problemas dif\u00edceis que exigem intelig\u00eancia coletiva.",
    q1: "Qual o pre\u00e7o exato do carbono necess\u00e1rio para alterar significativamente o comportamento de consumidores e da ind\u00fastria sem provocar um choque econ\u00f3mico?",
    q2: "Como garantir uma contabiliza\u00e7\u00e3o precisa do ciclo de vida a n\u00edvel global, quando as cadeias de abastecimento atravessam dezenas de pa\u00edses com padr\u00f5es diferentes?",
    q3: "Como devem ser tratadas as importa\u00e7\u00f5es de pa\u00edses n\u00e3o conformes? Os ajustes de carbono na fronteira s\u00e3o promissores, mas politica e logisticamente complexos.",
    q4: "Qual \u00e9 o caminho realista para a viabilidade pol\u00edtica dentro das estruturas da UE \u2014 e como constru\u00edmos a coaliz\u00e3o necess\u00e1ria?",
    q5: "Com que rapidez podemos fazer a transi\u00e7\u00e3o sem desestabilizar os meios de subsist\u00eancia? Qual \u00e9 o equil\u00edbrio adequado entre urg\u00eancia e estabilidade social?",
    join_label: "05 \u2014 Agir",
    join_title: "Junte-se ao movimento",
    join_desc: "Esta ideia precisa de economistas, decisores pol\u00edticos, ativistas e cidad\u00e3os que acreditem que \u00e9 o pre\u00e7o \u2014 e n\u00e3o a culpa \u2014 que muda o mundo. Fa\u00e7a ouvir a sua voz.",
    join_placeholder: "seu@email.com",
    join_btn: "Inscrever-se",
    join_btn_done: "Adicionado \u2713",
    join_note: "Sem spam. Atualiza\u00e7\u00f5es sobre avan\u00e7os pol\u00edticos, investiga\u00e7\u00e3o e a\u00e7\u00f5es que pode empreender.",
    footer_mechanism: "Mecanismo",
    footer_data: "Dados",
    calc_label: "03.5 \u2014 Experimente voc\u00ea mesmo",
    calc_title: "Calcule o dano",
    calc_desc: "Veja quanto custariam realmente os produtos do dia a dia se os danos ambientais estivessem inclu\u00eddos no pre\u00e7o.",
    calc_cat_label: "Categoria",
    calc_prod_label: "Produto",
    calc_qty_label: "Quantidade",
    calc_unit_label: "Unidade",
    calc_price_label: "Pre\u00e7o do carbono",
    calc_cat_food: "Alimenta\u00e7\u00e3o e bebidas",
    calc_cat_clothing: "Vestu\u00e1rio (por material)",
    calc_cat_electronics: "Eletr\u00f3nicos (por tamanho)",
    calc_cat_travel: "Transportes",
    calc_cat_fuel: "Combust\u00edveis",
    calc_price_50: "$50 / ton",
    calc_price_100: "$100 / ton",
    calc_price_150: "$150 / ton",
    calc_price_200: "$200 / ton",
    calc_eco_label: "Ecocertificado / fonte org\u00e2nica (reduz a estimativa em ~15\u00a0%)",
    calc_result_label: "Pegada de CO\u2082",
    calc_sources: "Fontes: Poore & Nemecek (2018), <a href=\"https://doi.org/10.1126/science.aaq0216\" target=\"_blank\" rel=\"noopener\"><em>Science</em> 360:987</a> (alimenta\u00e7\u00e3o) \u00b7 <a href=\"https://www.gov.uk/government/collections/government-conversion-factors-for-company-reporting\" target=\"_blank\" rel=\"noopener\">UK DEFRA 2023</a> (combust\u00edveis/voos) \u00b7 Apple/Levi\u2019s Product Environmental Reports (eletr\u00f3nicos/vestu\u00e1rio)",
    calc_damage_cost: "custo do dano",
    calc_eco_note: "(ecocertificado: \u221215\u00a0%)",
    calc_prod_beef: "Carne de bovino",
    calc_prod_chicken: "Frango",
    calc_prod_cheese: "Queijo",
    calc_prod_milk: "Leite (vaca)",
    calc_prod_rice: "Arroz",
    calc_prod_coffee: "Caf\u00e9 (torrado)",
    calc_prod_chocolate: "Chocolate negro",
    calc_prod_tomatoes: "Tomates",
    calc_prod_potatoes: "Batatas",
    calc_prod_eggs: "Ovos",
    calc_prod_bread: "P\u00e3o (trigo)",
    calc_prod_cotton_tshirt: "Algod\u00e3o \u2014 T-shirt (250\u00a0g)",
    calc_prod_cotton_jeans: "Algod\u00e3o \u2014 Jeans (ganga)",
    calc_prod_polyester_shirt: "Poli\u00e9ster \u2014 Camisa",
    calc_prod_polyester_jacket: "Poli\u00e9ster \u2014 Casaco",
    calc_prod_wool_sweater: "L\u00e3 \u2014 Camisola",
    calc_prod_wool_coat: "L\u00e3 \u2014 Casac\u00e3o",
    calc_prod_leather_shoes: "Couro \u2014 Sapatos",
    calc_prod_nylon_sneakers: "Nylon/Misto \u2014 T\u00e9nis",
    calc_prod_smartphone: "Formato telem\u00f3vel (smartphone)",
    calc_prod_tablet: "Formato tablet (10\u2033)",
    calc_prod_laptop: "Formato port\u00e1til (13\u201316\u2033)",
    calc_prod_monitor: "Formato monitor (24\u201327\u2033)",
    calc_prod_tv: "Formato TV (50\u201365\u2033)",
    calc_prod_desktop: "PC de secret\u00e1ria (torre)",
    calc_prod_flight_short: "Voo \u2014 curta dist\u00e2ncia (<3\u00a0h)",
    calc_prod_flight_long: "Voo \u2014 longa dist\u00e2ncia (>6\u00a0h)",
    calc_prod_car_petrol: "Carro \u2014 gasolina (m\u00e9dia)",
    calc_prod_car_diesel: "Carro \u2014 di\u00e9sel (m\u00e9dia)",
    calc_prod_train: "Comboio (rede nacional)",
    calc_prod_bus: "Autocarro (longa dist\u00e2ncia)",
    calc_prod_petrol: "Gasolina",
    calc_prod_diesel: "Di\u00e9sel",
    calc_prod_natural_gas: "G\u00e1s natural (aquecimento)",
    calc_prod_electricity_eu: "Eletricidade (m\u00e9dia UE)",
    calc_note_beef: "ACV mediana global; intervalo 20\u2013105\u00a0kg CO\u2082e/kg",
    calc_note_chicken: "Inclui uso do solo, ra\u00e7\u00e3o, processamento",
    calc_note_cheese: "~10\u00a0litros de leite por kg de queijo",
    calc_note_milk: "Inclui fermenta\u00e7\u00e3o ent\u00e9rica e uso do solo",
    calc_note_rice: "Domina o metano dos arrozais inundados",
    calc_note_coffee: "Intervalo 3,5\u201328,5; fortemente dependente do uso do solo",
    calc_note_chocolate: "Elevada componente de desfloresta\u00e7\u00e3o na cadeia de abastecimento do cacau",
    calc_note_tomatoes: "Valor em campo aberto; estufa aquecida ~2,1",
    calc_note_potatoes: "Um dos amidos com menores emiss\u00f5es",
    calc_note_eggs: "~12\u00a0ovos por kg",
    calc_note_bread: "P\u00e3o de trigo padr\u00e3o",
    calc_note_cotton_tshirt: "O cultivo do algod\u00e3o representa ~metade da pegada",
    calc_note_cotton_jeans: "Ciclo de vida completo: do cultivo ao fim de vida",
    calc_note_polyester_shirt: "Fibra derivada de combust\u00edveis f\u00f3sseis",
    calc_note_polyester_jacket: "Enchimento sint\u00e9tico + exterior \u00e0 base de petr\u00f3leo",
    calc_note_wool_sweater: "Metano dos ovinos + processamento",
    calc_note_wool_coat: "L\u00e3 pesada; elevado impacto de metano + tingimento",
    calc_note_leather_shoes: "Pecu\u00e1ria bovina + qu\u00edmicos de curtimenta",
    calc_note_nylon_sneakers: "Materiais mistos; dominado pela fabrica\u00e7\u00e3o",
    calc_note_smartphone: "A fabrica\u00e7\u00e3o representa ~80\u00a0% da pegada; vida \u00fatil de 3\u00a0anos",
    calc_note_tablet: "Impacto entre o telem\u00f3vel e o port\u00e1til",
    calc_note_laptop: "Intervalo 150\u2013400\u00a0kg; depende dos componentes",
    calc_note_monitor: "Fabrica\u00e7\u00e3o do ecr\u00e3 + utiliza\u00e7\u00e3o plurianual",
    calc_note_tv: "Ecr\u00e3 grande + eletricidade da fase de utiliza\u00e7\u00e3o durante 7\u00a0anos",
    calc_note_desktop: "Maior consumo energ\u00e9tico; maior vida \u00fatil dos componentes",
    calc_note_flight_short: "Por passageiro, classe econ\u00f3mica; inclui for\u00e7amento radiativo",
    calc_note_flight_long: "Mais eficiente por km em longas dist\u00e2ncias",
    calc_note_car_petrol: "Carro a gasolina europeu m\u00e9dio ~210\u00a0g CO\u2082/km",
    calc_note_car_diesel: "Ligeiramente menos CO\u2082 por km do que a gasolina",
    calc_note_train: "Varia enormemente conforme a rede el\u00e9trica; m\u00e9dia UE",
    calc_note_bus: "Por passageiro; alta ocupa\u00e7\u00e3o assumida",
    calc_note_petrol: "Do po\u00e7o \u00e0 roda, incluindo extra\u00e7\u00e3o a montante",
    calc_note_diesel: "Ligeiramente superior por litro do que a gasolina",
    calc_note_natural_gas: "Combust\u00e3o + fugas de metano a montante",
    calc_note_electricity_eu: "M\u00e9dia da rede UE; varia por pa\u00eds",
  },

  nl: {
    nav_logo: "Prijs de Schade",
    nav_how: "Hoe het werkt",
    nav_principles: "Principes",
    nav_examples: "Voorbeelden",
    nav_questions: "Open vragen",
    nav_join: "Meedoen",
    hero_label: "Een beleidskader voor de klimaatcrisis",
    hero_title: "Maak vervuiling<br><em>duur</em>.",
    hero_subtitle: "Elk product brengt verborgen milieukosten met zich mee. Wij stellen een CO\u2082-equivalentheffing voor over de gehele toeleveringsketen \u2014 ecologische schade wordt omgezet in economische druk, terwijl de opbrengsten worden herverdeeld om burgers te beschermen.",
    hero_btn_primary: "Bekijk hoe het werkt \u2193",
    hero_btn_secondary: "Doe mee met de beweging",
    how_label: "01 \u2014 Mechanisme",
    how_title: "Een heffing in elke fase",
    how_desc: "CO\u2082-equivalentheffingen worden stroomopwaarts toegepast op elk punt in de toeleveringsketen. De totale kosten accumuleren in de eindprijs \u2014 waardoor producten met hoge emissies vanzelf duurder worden.",
    stage1_title: "Winning",
    stage1_desc: "Grondstoffenwinning, olieboring, oogst",
    stage2_title: "Productie",
    stage2_desc: "Fabricage, raffinage, verwerking",
    stage3_title: "Transport",
    stage3_desc: "Verzending, vrachtvervoer, logistiek",
    stage4_title: "Handel &amp; gebruik",
    stage4_desc: "Distributie, gebruiksfase door de consument",
    stage5_title: "Verwerking",
    stage5_desc: "Einde levensduur via uitgebreide producentenverantwoordelijkheid",
    stage_fee: "+ CO\u2082-heffing",
    pipeline_result: "De data bestaan al. <strong>Levenscyclusanalyses (LCA\u2019s)</strong> en productgerelateerde CO\u2082-voetafdrukken bestrijken de gehele keten \u2014 van winning tot verwerking. We hebben geen nieuwe wetenschap nodig. We hebben politieke wil nodig.",
    manifesto: "Milieu-impact omzetten in <em>onvermijdelijke economische druk</em>, vervolgens het geld herverdelen om de samenleving stabiel te houden en de markt te dwingen tot <em>decarbonisatie</em>.",
    principles_label: "02 \u2014 Principes",
    principles_title: "Waar wij voor staan",
    principles_desc: "Dit gaat niet over bewustwordingscampagnes of vrijwillige beloften. Het gaat over het herontwerpen van economische prikkels vanaf de basis.",
    p1_title: "Prijs, geen bewustwording",
    p1_text: "Decennia van bewustwordingscampagnes hebben de emissiecurve niet omgebogen. Prijssignalen veranderen gedrag op grote schaal \u2014 automatisch, universeel en onmiddellijk.",
    p2_title: "Mensen beschermen, niet vervuilers",
    p2_text: "De opbrengsten gaan naar publieke voorzieningen en een minimuminkomen om hogere prijzen te compenseren. Geen subsidies voor bedrijven om \u201egroen te worden\u201d. Wie vervuilt, betaalt. Het geld beschermt de burgers.",
    p3_title: "Maatschappelijke kosten van koolstof",
    p3_text: "De heffing per ton is gebaseerd op de werkelijke schade die CO\u2082 veroorzaakt. Een hogere prijs leidt tot sterkere gedragsverandering \u2014 maar vereist ook een sterkere sociale herverdeling om eerlijk te blijven.",
    p4_title: "EU-brede implementatie",
    p4_text: "Een uitsluitend nationale implementatie verstoort de handel binnen de interne markt. Dit vereist EU-brede co\u00f6rdinatie \u2014 of zorgvuldig ontworpen nationale belastingen die geen oneerlijke voordelen cre\u00ebren.",
    examples_label: "03 \u2014 Concrete cijfers",
    examples_title: "Hoe ziet dit eruit?",
    examples_desc: "Op basis van bestaande levenscyclusanalysegegevens en een koolstofprijs van $100 per ton CO\u2082-equivalent.",
    ex_case: "Casus",
    ex_beef: "Rundvlees",
    ex_oil: "Ruwe aardolie",
    ex_lifecycle: "Levenscyclusemissies",
    ex_carbon_price: "Toegepaste koolstofprijs",
    ex_additional_kg: "Meerkosten per kg",
    ex_additional_barrel: "Meerkosten per vat",
    ex_beef_insight: "Omvat de productie van veevoer (op aardolie gebaseerde meststoffen), methaan van vee, verandering in landgebruik en verwerking. Het grootste deel van de emissies komt voort uit biologische processen \u2014 niet alleen uit energie-inputs.",
    ex_oil_insight: "Aanzienlijk prijseffect \u2014 maar de kosten verdunnen wanneer olie wordt verdeeld over duizenden afgeleide producten. De grootste impact treft geconcentreerde emisie-intensieve processen zoals veeteelt, niet alleen industri\u00eble inputs.",
    questions_label: "04 \u2014 Eerlijke hiaten",
    questions_title: "Open vragen",
    questions_desc: "We pretenderen niet alle antwoorden te hebben. Dit zijn de moeilijke problemen waarvoor we collectieve intelligentie nodig hebben.",
    q1: "Welke exacte koolstofprijs is nodig om het gedrag van consumenten en industrie wezenlijk te veranderen zonder een economische schok te veroorzaken?",
    q2: "Hoe handhaven we nauwkeurige levenscyclusboekhouding op wereldschaal, wanneer toeleveringsketens tientallen landen met verschillende normen omvatten?",
    q3: "Hoe moeten we omgaan met import uit niet-conforme landen? Koolstofgrenscorrecties zijn veelbelovend, maar politiek en logistiek complex.",
    q4: "Wat is het realistische pad naar politieke haalbaarheid binnen de EU-structuren \u2014 en hoe bouwen we de benodigde coalitie op?",
    q5: "Hoe snel kunnen we de transitie doorvoeren zonder bestaansmiddelen te destabiliseren? Hoe ziet de juiste balans tussen urgentie en sociale stabiliteit eruit?",
    join_label: "05 \u2014 Actie ondernemen",
    join_title: "Doe mee met de beweging",
    join_desc: "Dit idee heeft economen, beleidsmakers, activisten en burgers nodig die geloven dat de prijs \u2014 niet schuldgevoel \u2014 de wereld verandert. Laat uw stem horen.",
    join_placeholder: "uw@email.com",
    join_btn: "Aanmelden",
    join_btn_done: "Toegevoegd \u2713",
    join_note: "Geen spam. Updates over beleidsvoortgang, onderzoek en acties die u kunt ondernemen.",
    footer_mechanism: "Mechanisme",
    footer_data: "Data",
    calc_label: "03.5 \u2014 Probeer het zelf",
    calc_title: "Bereken de schade",
    calc_desc: "Ontdek wat alledaagse producten werkelijk zouden kosten als milieuschade in de prijs was inbegrepen.",
    calc_cat_label: "Categorie",
    calc_prod_label: "Product",
    calc_qty_label: "Hoeveelheid",
    calc_unit_label: "Eenheid",
    calc_price_label: "Koolstofprijs",
    calc_cat_food: "Voeding & dranken",
    calc_cat_clothing: "Kleding (naar materiaal)",
    calc_cat_electronics: "Elektronica (naar grootte)",
    calc_cat_travel: "Reizen",
    calc_cat_fuel: "Brandstoffen",
    calc_price_50: "$50 / ton",
    calc_price_100: "$100 / ton",
    calc_price_150: "$150 / ton",
    calc_price_200: "$200 / ton",
    calc_eco_label: "Ecogecerti\ufb01ceerd / biologische bron (vermindert de schatting met ~15\u00a0%)",
    calc_result_label: "CO\u2082-voetafdruk",
    calc_sources: "Bronnen: Poore & Nemecek (2018), <a href=\"https://doi.org/10.1126/science.aaq0216\" target=\"_blank\" rel=\"noopener\"><em>Science</em> 360:987</a> (voeding) \u00b7 <a href=\"https://www.gov.uk/government/collections/government-conversion-factors-for-company-reporting\" target=\"_blank\" rel=\"noopener\">UK DEFRA 2023</a> (brandstoffen/vluchten) \u00b7 Apple/Levi\u2019s Product Environmental Reports (elektronica/kleding)",
    calc_damage_cost: "schadekosten",
    calc_eco_note: "(ecogecerti\ufb01ceerd: \u221215\u00a0%)",
    calc_prod_beef: "Rundvlees",
    calc_prod_chicken: "Kip",
    calc_prod_cheese: "Kaas",
    calc_prod_milk: "Melk (koe)",
    calc_prod_rice: "Rijst",
    calc_prod_coffee: "Koffie (gebrand)",
    calc_prod_chocolate: "Pure chocolade",
    calc_prod_tomatoes: "Tomaten",
    calc_prod_potatoes: "Aardappelen",
    calc_prod_eggs: "Eieren",
    calc_prod_bread: "Brood (tarwe)",
    calc_prod_cotton_tshirt: "Katoen \u2014 T-shirt (250\u00a0g)",
    calc_prod_cotton_jeans: "Katoen \u2014 Jeans (denim)",
    calc_prod_polyester_shirt: "Polyester \u2014 Overhemd",
    calc_prod_polyester_jacket: "Polyester \u2014 Jas",
    calc_prod_wool_sweater: "Wol \u2014 Trui",
    calc_prod_wool_coat: "Wol \u2014 Jas",
    calc_prod_leather_shoes: "Leer \u2014 Schoenen",
    calc_prod_nylon_sneakers: "Nylon/Gemengd \u2014 Sneakers",
    calc_prod_smartphone: "Telefoonformaat (smartphone)",
    calc_prod_tablet: "Tabletformaat (10\u2033)",
    calc_prod_laptop: "Laptopformaat (13\u201316\u2033)",
    calc_prod_monitor: "Monitorformaat (24\u201327\u2033)",
    calc_prod_tv: "TV-formaat (50\u201365\u2033)",
    calc_prod_desktop: "Desktop-PC (tower)",
    calc_prod_flight_short: "Vlucht \u2014 korte afstand (<3\u00a0u)",
    calc_prod_flight_long: "Vlucht \u2014 lange afstand (>6\u00a0u)",
    calc_prod_car_petrol: "Auto \u2014 benzine (gem.)",
    calc_prod_car_diesel: "Auto \u2014 diesel (gem.)",
    calc_prod_train: "Trein (nationaal spoor)",
    calc_prod_bus: "Bus (lange afstand)",
    calc_prod_petrol: "Benzine",
    calc_prod_diesel: "Diesel",
    calc_prod_natural_gas: "Aardgas (verwarming)",
    calc_prod_electricity_eu: "Elektriciteit (EU-gem.)",
    calc_note_beef: "Wereldwijde LCA-mediaan; bereik 20\u2013105\u00a0kg CO\u2082e/kg",
    calc_note_chicken: "Inclusief landgebruik, veevoer, verwerking",
    calc_note_cheese: "~10\u00a0liter melk per kg kaas",
    calc_note_milk: "Inclusief enterische fermentatie en landgebruik",
    calc_note_rice: "Methaan uit ondergelopen rijstvelden domineert",
    calc_note_coffee: "Bereik 3,5\u201328,5; sterk afhankelijk van landgebruik",
    calc_note_chocolate: "Hoog ontbossingsaandeel in de cacaotoeleveringsketen",
    calc_note_tomatoes: "Vollegrondwaarde; verwarmde kas ~2,1",
    calc_note_potatoes: "Een van de zetmeelgewassen met de laagste uitstoot",
    calc_note_eggs: "~12\u00a0eieren per kg",
    calc_note_bread: "Standaard tarwebrood",
    calc_note_cotton_tshirt: "Katoenteelt is ~de helft van de voetafdruk",
    calc_note_cotton_jeans: "Volledige levenscyclus: van teelt tot einde levensduur",
    calc_note_polyester_shirt: "Vezel op basis van fossiele brandstoffen",
    calc_note_polyester_jacket: "Synthetische vulling + schil op aardoliebasis",
    calc_note_wool_sweater: "Methaan van schapen + verwerking",
    calc_note_wool_coat: "Zware wol; hoog methaan- + verfimpact",
    calc_note_leather_shoes: "Rundveehouderij + looichemicali\u00ebn",
    calc_note_nylon_sneakers: "Gemengde materialen; gedomineerd door productie",
    calc_note_smartphone: "Productie ~80\u00a0% van de voetafdruk; levensduur 3\u00a0jaar",
    calc_note_tablet: "Impact tussen telefoon en laptop",
    calc_note_laptop: "Bereik 150\u2013400\u00a0kg; afhankelijk van componenten",
    calc_note_monitor: "Displayproductie + meerjarig gebruik",
    calc_note_tv: "Groot display + 7\u00a0jaar elektriciteitsverbruik in gebruiksfase",
    calc_note_desktop: "Hoger stroomverbruik; langere levensduur componenten",
    calc_note_flight_short: "Per passagier, economy; inclusief stralingsforcering",
    calc_note_flight_long: "Effici\u00ebnter per km op langere afstanden",
    calc_note_car_petrol: "Gemiddelde Europese benzineauto ~210\u00a0g CO\u2082/km",
    calc_note_car_diesel: "Iets minder CO\u2082 per km dan benzine",
    calc_note_train: "Varieert sterk per elektriciteitsnet; EU-gemiddelde",
    calc_note_bus: "Per passagier; hoge bezettingsgraad aangenomen",
    calc_note_petrol: "Well-to-wheel inclusief upstream winning",
    calc_note_diesel: "Iets hoger per liter dan benzine",
    calc_note_natural_gas: "Verbranding + upstream methaanlekkage",
    calc_note_electricity_eu: "EU-netgemiddelde; varieert per land",
  },
};
