const TRANS_NORDIC = {
  da: {
    nav_logo: "Prissæt skaden",
    nav_how: "Sådan virker det",
    nav_principles: "Principper",
    nav_examples: "Eksempler",
    nav_questions: "Åbne spørgsmål",
    nav_join: "Deltag",
    hero_label: "En politisk ramme for klimakrisen",
    hero_title: "Gør forurening<br><em>dyrt</em>.",
    hero_subtitle: "Ethvert produkt bærer en skjult miljøomkostning. Vi foreslår en CO₂-ækvivalent afgift gennem hele forsyningskæden — der omsætter økologisk skade til økonomisk pres, mens indtægterne omfordeles for at beskytte mennesker.",
    hero_btn_primary: "Se hvordan det virker ↓",
    hero_btn_secondary: "Deltag i bevægelsen",
    how_label: "01 — Mekanisme",
    how_title: "En afgift på hvert trin",
    how_desc: "CO₂-ækvivalente afgifter pålægges opstrøms på hvert punkt i forsyningskæden. De samlede omkostninger akkumuleres i den endelige pris — hvilket naturligt gør højemissionsprodukter dyrere.",
    stage1_title: "Udvinding",
    stage1_desc: "Råstofudvinding, olieboring, høst",
    stage2_title: "Produktion",
    stage2_desc: "Fremstilling, raffinering, forarbejdning",
    stage3_title: "Transport",
    stage3_desc: "Fragt, godstransport, logistik",
    stage4_title: "Detail &amp; forbrug",
    stage4_desc: "Distribution, forbrugsfase",
    stage5_title: "Bortskaffelse",
    stage5_desc: "Slutfase via udvidet producentansvar",
    stage_fee: "+ CO₂-afgift",
    pipeline_result: "Dataene findes allerede. <strong>Livscyklusvurderinger (LCA)</strong> og produkters CO₂-fodaftryk dækker hele kæden — fra udvinding til bortskaffelse. Vi behøver ikke ny videnskab. Vi behøver politisk vilje.",
    manifesto: "Omsæt miljøpåvirkning til <em>uundgåeligt økonomisk pres</em>, og omfordel derefter pengene for at holde samfundet stabilt, mens markedet tvinges til at <em>dekarbonisere</em>.",
    principles_label: "02 — Principper",
    principles_title: "Hvad vi står for",
    principles_desc: "Det handler ikke om oplysningskampagner eller frivillige løfter. Det handler om at redesigne økonomiske incitamenter fra bunden.",
    p1_title: "Pris, ikke oplysning",
    p1_text: "Årtiers oplysningskampagner har ikke bøjet udledningskurven. Prissignaler ændrer adfærd i stor skala — automatisk, universelt og øjeblikkeligt.",
    p2_title: "Beskyt mennesker, ikke forurenere",
    p2_text: "Indtægterne går til offentlige goder og minimumsindkomst for at kompensere for højere priser. Ingen subsidier til virksomheder for at \"blive grønne\". Hvis du forurener, betaler du. Pengene beskytter borgerne.",
    p3_title: "Samfundsomkostningen ved CO₂",
    p3_text: "Afgiften per ton er baseret på den reelle skade, CO₂ forårsager. Højere pris betyder stærkere adfærdsændring — men kræver også stærkere social omfordeling for at holde det retfærdigt.",
    p4_title: "EU-dækkende implementering",
    p4_text: "Kun national implementering forvrider handelen inden for det indre marked. Det kræver EU-dækkende koordinering — eller omhyggeligt designede nationale afgifter, der ikke skaber uretfærdige fordele.",
    examples_label: "03 — Konkrete tal",
    examples_title: "Hvordan ser det ud?",
    examples_desc: "Baseret på eksisterende livscyklusvurderinger og en CO₂-pris på $100 per ton CO₂-ækvivalent.",
    ex_case: "Case-studie",
    ex_beef: "Oksekød",
    ex_oil: "Råolie",
    ex_lifecycle: "Livscyklusudledninger",
    ex_carbon_price: "Anvendt CO₂-pris",
    ex_additional_kg: "Meromkostning per kg",
    ex_additional_barrel: "Meromkostning per tønde",
    ex_beef_insight: "Inkluderer foderproduktion (oliebaseret gødning), metan fra kvæg, ændret arealanvendelse og forarbejdning. De fleste udledninger kommer fra biologi — ikke kun energi-input.",
    ex_oil_insight: "Betydelig prispåvirkning — men omkostningerne fortyndes, når olie fordeles på tusindvis af downstream-produkter. Den største påvirkning rammer koncentrerede højemissionsprocesser som husdyrbrug, ikke blot industrielle input.",
    questions_label: "04 — Ærlige huller",
    questions_title: "Åbne spørgsmål",
    questions_desc: "Vi påstår ikke at have alle svar. Dette er de svære problemer, vi har brug for kollektiv intelligens til at løse.",
    q1: "Hvilken præcis CO₂-pris er nødvendig for meningsfuldt at ændre forbruger- og industriadfærd uden at forårsage økonomisk chok?",
    q2: "Hvordan håndhæver vi nøjagtig livscyklusregnskab globalt, når forsyningskæder spænder over snesevis af lande med forskellige standarder?",
    q3: "Hvordan bør vi håndtere import fra ikke-kompatible lande? CO₂-grænsetilpasninger er lovende, men politisk og logistisk komplekse.",
    q4: "Hvad er den realistiske vej til politisk gennemførlighed inden for EU's strukturer — og hvordan opbygger vi koalitionen til at nå dertil?",
    q5: "Hvor hurtigt kan vi omstille uden at destabilisere levebrød? Hvordan ser den rette balance mellem hastværk og social stabilitet ud?",
    join_label: "05 — Handling",
    join_title: "Deltag i bevægelsen",
    join_desc: "Denne idé har brug for økonomer, politiske beslutningstagere, aktivister og borgere, der tror på, at pris — ikke skyld — er det, der ændrer verden. Giv din stemme.",
    join_placeholder: "din@email.dk",
    join_btn: "Tilmeld dig",
    join_btn_done: "Tilføjet ✓",
    join_note: "Ingen spam. Opdateringer om politiske fremskridt, forskning og handlinger du kan tage.",
    footer_mechanism: "Mekanisme",
    footer_data: "Data",
    calc_label: "03.5 \u2014 Pr\u00f8v det selv",
    calc_title: "Priss\u00e6t skaden",
    calc_desc: "Se hvad hverdagsprodukter virkelig ville koste, hvis milj\u00f8skader var inkluderet i prisen.",
    calc_cat_label: "Kategori",
    calc_prod_label: "Produkt",
    calc_qty_label: "Antal",
    calc_unit_label: "Enhed",
    calc_price_label: "CO\u2082-pris",
    calc_cat_food: "Mad & drikke",
    calc_cat_clothing: "T\u00f8j (efter materiale)",
    calc_cat_electronics: "Elektronik (efter st\u00f8rrelse)",
    calc_cat_travel: "Rejser",
    calc_cat_fuel: "Br\u00e6ndstof",
    calc_price_50: "$50 / ton",
    calc_price_100: "$100 / ton",
    calc_price_150: "$150 / ton",
    calc_price_200: "$200 / ton",
    calc_eco_label: "\u00d8kocertificeret / \u00f8kologisk kilde (reducerer estimat med ~15%)",
    calc_result_label: "CO\u2082-fodaftryk",
    calc_sources: "Kilder: Poore & Nemecek (2018), <a href=\"https://doi.org/10.1126/science.aaq0216\" target=\"_blank\" rel=\"noopener\"><em>Science</em> 360:987</a> (mad) \u00b7 <a href=\"https://www.gov.uk/government/collections/government-conversion-factors-for-company-reporting\" target=\"_blank\" rel=\"noopener\">UK DEFRA 2023</a> (br\u00e6ndstof/flyrejser) \u00b7 Apple/Levi\u2019s Product Environmental Reports (elektronik/t\u00f8j)",
    calc_damage_cost: "skadeomkostning",
    calc_eco_note: "(\u00f8kocertificeret: \u221215%)",
    calc_prod_beef: "Oksek\u00f8d",
    calc_prod_chicken: "Kylling",
    calc_prod_cheese: "Ost",
    calc_prod_milk: "M\u00e6lk (ko)",
    calc_prod_rice: "Ris",
    calc_prod_coffee: "Kaffe (ristet)",
    calc_prod_chocolate: "M\u00f8rk chokolade",
    calc_prod_tomatoes: "Tomater",
    calc_prod_potatoes: "Kartofler",
    calc_prod_eggs: "\u00c6g",
    calc_prod_bread: "Br\u00f8d (hvede)",
    calc_prod_cotton_tshirt: "Bomuld \u2014 T-shirt (250g)",
    calc_prod_cotton_jeans: "Bomuld \u2014 Jeans (denim)",
    calc_prod_polyester_shirt: "Polyester \u2014 Skjorte",
    calc_prod_polyester_jacket: "Polyester \u2014 Jakke",
    calc_prod_wool_sweater: "Uld \u2014 Sweater",
    calc_prod_wool_coat: "Uld \u2014 Frakke",
    calc_prod_leather_shoes: "L\u00e6der \u2014 Sko",
    calc_prod_nylon_sneakers: "Nylon/Blandet \u2014 Sneakers",
    calc_prod_smartphone: "Telefonst\u00f8rrelse (smartphone)",
    calc_prod_tablet: "Tabletst\u00f8rrelse (10\u2033)",
    calc_prod_laptop: "Laptopst\u00f8rrelse (13\u201316\u2033)",
    calc_prod_monitor: "Sk\u00e6rmst\u00f8rrelse (24\u201327\u2033)",
    calc_prod_tv: "TV-st\u00f8rrelse (50\u201365\u2033)",
    calc_prod_desktop: "Stationær PC (tower)",
    calc_prod_flight_short: "Fly \u2014 kortdistance (<3t)",
    calc_prod_flight_long: "Fly \u2014 langdistance (>6t)",
    calc_prod_car_petrol: "Bil \u2014 benzin (gns.)",
    calc_prod_car_diesel: "Bil \u2014 diesel (gns.)",
    calc_prod_train: "Tog (nationalt)",
    calc_prod_bus: "Bus (langdistance)",
    calc_prod_petrol: "Benzin",
    calc_prod_diesel: "Diesel",
    calc_prod_natural_gas: "Naturgas (opvarmning)",
    calc_prod_electricity_eu: "Elektricitet (EU-gns.)",
    calc_note_beef: "Median global LCA; interval 20\u2013105 kg CO\u2082e/kg",
    calc_note_chicken: "Inkluderer arealanvendelse, foder, forarbejdning",
    calc_note_cheese: "~10 liter m\u00e6lk per kg ost",
    calc_note_milk: "Inkluderer enterisk fermentering og arealanvendelse",
    calc_note_rice: "Metan fra oversv\u00f8mmede marker dominerer",
    calc_note_coffee: "Interval 3,5\u201328,5; st\u00e6rkt afh\u00e6ngig af arealanvendelse",
    calc_note_chocolate: "H\u00f8j skovrydningskomponent i kakaos forsyningsk\u00e6de",
    calc_note_tomatoes: "Frilandsv\u00e6rdi; opvarmet drivhus ~2,1",
    calc_note_potatoes: "En af de laveste udlednings-stivelsesholdige f\u00f8devarer",
    calc_note_eggs: "~12 \u00e6g per kg",
    calc_note_bread: "Standard hvedebr\u00f8d",
    calc_note_cotton_tshirt: "Bomuldsdyrkning ~halvdelen af fodaftrykket",
    calc_note_cotton_jeans: "Fuld livscyklus: dyrkning til bortskaffelse",
    calc_note_polyester_shirt: "Fossilt br\u00e6ndstof-baseret fiber",
    calc_note_polyester_jacket: "Syntetisk fyld + oliebaseret ydre",
    calc_note_wool_sweater: "F\u00e5remetan + forarbejdning",
    calc_note_wool_coat: "Tung uld; h\u00f8j metan + farvningseffekt",
    calc_note_leather_shoes: "Kvæghold + garvekemikalier",
    calc_note_nylon_sneakers: "Blandede materialer; fremstillingsdomineret",
    calc_note_smartphone: "Fremstilling ~80% af fodaftrykket; 3 \u00e5rs levetid",
    calc_note_tablet: "Mellem telefon og laptop i p\u00e5virkning",
    calc_note_laptop: "Interval 150\u2013400 kg; afh\u00e6nger af komponenter",
    calc_note_monitor: "Sk\u00e6rmfremstilling + fler\u00e5rig brug",
    calc_note_tv: "Stor sk\u00e6rm + 7 \u00e5rs brugsfase-elektricitet",
    calc_note_desktop: "H\u00f8jere str\u00f8mforbrug; l\u00e6ngere komponentlevetid",
    calc_note_flight_short: "Per passager, \u00f8konomi; inkluderer str\u00e5lingsp\u00e5virkning",
    calc_note_flight_long: "Mere effektiv per km ved l\u00e6ngere afstande",
    calc_note_car_petrol: "Gennemsnitlig europ\u00e6isk benzinbil ~210g CO\u2082/km",
    calc_note_car_diesel: "Lidt lavere CO\u2082 per km end benzin",
    calc_note_train: "Varierer kraftigt efter elnet; EU-gennemsnit",
    calc_note_bus: "Per passager; h\u00f8j bel\u00e6gning antaget",
    calc_note_petrol: "Well-to-wheel inklusive opstr\u00f8ms udvinding",
    calc_note_diesel: "Lidt h\u00f8jere per liter end benzin",
    calc_note_natural_gas: "Forbr\u00e6nding + opstr\u00f8ms metanl\u00e6kage",
    calc_note_electricity_eu: "EU-elnetgennemsnit; varierer efter land",
  },
  sv: {
    nav_logo: "Prissätt skadan",
    nav_how: "Så fungerar det",
    nav_principles: "Principer",
    nav_examples: "Exempel",
    nav_questions: "Öppna frågor",
    nav_join: "Gå med",
    hero_label: "Ett politiskt ramverk för klimatkrisen",
    hero_title: "Gör föroreningar<br><em>dyra</em>.",
    hero_subtitle: "Varje produkt bär en dold miljökostnad. Vi föreslår en CO₂-ekvivalent avgift genom hela leveranskedjan — som omvandlar ekologisk skada till ekonomiskt tryck, samtidigt som intäkterna omfördelas för att skydda människor.",
    hero_btn_primary: "Se hur det fungerar ↓",
    hero_btn_secondary: "Gå med i rörelsen",
    how_label: "01 — Mekanism",
    how_title: "En avgift i varje steg",
    how_desc: "CO₂-ekvivalenta avgifter tillämpas uppströms vid varje punkt i leveranskedjan. Den totala kostnaden ackumuleras i slutpriset — vilket naturligt gör högutsläppsprodukter dyrare.",
    stage1_title: "Utvinning",
    stage1_desc: "Råvarubrytning, oljeborrning, skörd",
    stage2_title: "Produktion",
    stage2_desc: "Tillverkning, raffinering, bearbetning",
    stage3_title: "Transport",
    stage3_desc: "Sjöfrakt, godstransport, logistik",
    stage4_title: "Detaljhandel &amp; användning",
    stage4_desc: "Distribution, konsumentanvändningsfas",
    stage5_title: "Avfallshantering",
    stage5_desc: "Slutskede via utökat producentansvar",
    stage_fee: "+ CO₂-avgift",
    pipeline_result: "Datan finns redan. <strong>Livscykelanalyser (LCA)</strong> och produkters koldioxidavtryck täcker hela kedjan — från utvinning till avfallshantering. Vi behöver inte ny vetenskap. Vi behöver politisk vilja.",
    manifesto: "Omvandla miljöpåverkan till <em>oundvikligt ekonomiskt tryck</em> och omfördela sedan pengarna för att hålla samhället stabilt medan marknaden tvingas <em>avkarbonisera</em>.",
    principles_label: "02 — Principer",
    principles_title: "Vad vi står för",
    principles_desc: "Det handlar inte om informationskampanjer eller frivilliga löften. Det handlar om att omforma ekonomiska incitament från grunden.",
    p1_title: "Pris, inte medvetenhet",
    p1_text: "Årtionden av informationskampanjer har inte böjt utsläppskurvan. Prissignaler förändrar beteende i stor skala — automatiskt, universellt och omedelbart.",
    p2_title: "Skydda människor, inte förorenare",
    p2_text: "Intäkterna går till offentliga nyttigheter och minimiinkomst för att kompensera högre priser. Inga subventioner till företag för att \"bli gröna\". Förorenar du, betalar du. Pengarna skyddar medborgarna.",
    p3_title: "Samhällskostnaden för CO₂",
    p3_text: "Avgiften per ton baseras på den verkliga skada CO₂ orsakar. Högre pris innebär starkare beteendeförändring — men kräver också starkare social omfördelning för att hålla det rättvist.",
    p4_title: "EU-omfattande implementering",
    p4_text: "Enbart nationell implementering snedvrider handeln inom den inre marknaden. Det krävs EU-omfattande samordning — eller noggrant utformade nationella skatter som inte skapar orättvisa fördelar.",
    examples_label: "03 — Verkliga siffror",
    examples_title: "Hur ser det ut?",
    examples_desc: "Baserat på befintliga livscykelanalyser och ett koldioxidpris på $100 per ton CO₂-ekvivalent.",
    ex_case: "Fallstudie",
    ex_beef: "Nötkött",
    ex_oil: "Råolja",
    ex_lifecycle: "Livscykelutsläpp",
    ex_carbon_price: "Tillämpad koldioxidpris",
    ex_additional_kg: "Merkostnad per kg",
    ex_additional_barrel: "Merkostnad per fat",
    ex_beef_insight: "Inkluderar foderproduktion (oljebaserade gödselmedel), metan från nötkreatur, förändrad markanvändning och bearbetning. De flesta utsläppen kommer från biologi — inte bara energiinsatser.",
    ex_oil_insight: "Betydande prispåverkan — men kostnaderna späds ut när olja fördelas på tusentals nedströmsprodukter. Den största påverkan drabbar koncentrerade högutsläppsprocesser som djurhållning, inte bara industriella insatsvaror.",
    questions_label: "04 — Ärliga luckor",
    questions_title: "Öppna frågor",
    questions_desc: "Vi påstår inte att vi har alla svar. Det här är de svåra problemen som kräver kollektiv intelligens att lösa.",
    q1: "Vilket exakt koldioxidpris behövs för att meningsfullt förändra konsument- och industribeteende utan att orsaka ekonomisk chock?",
    q2: "Hur säkerställer vi korrekt livscykelredovisning globalt, när leveranskedjor spänner över dussintals länder med olika standarder?",
    q3: "Hur bör vi hantera import från icke-kompatibla länder? Koldioxidgränsjusteringar är lovande men politiskt och logistiskt komplexa.",
    q4: "Vad är den realistiska vägen till politisk genomförbarhet inom EU:s strukturer — och hur bygger vi koalitionen för att nå dit?",
    q5: "Hur snabbt kan vi ställa om utan att destabilisera försörjningsmöjligheter? Hur ser den rätta balansen mellan brådska och social stabilitet ut?",
    join_label: "05 — Agera",
    join_title: "Gå med i rörelsen",
    join_desc: "Denna idé behöver ekonomer, beslutsfattare, aktivister och medborgare som tror att pris — inte skuld — är det som förändrar världen. Lägg till din röst.",
    join_placeholder: "din@epost.se",
    join_btn: "Anmäl dig",
    join_btn_done: "Tillagd ✓",
    join_note: "Ingen spam. Uppdateringar om politiska framsteg, forskning och åtgärder du kan vidta.",
    footer_mechanism: "Mekanism",
    footer_data: "Data",
    calc_label: "03.5 \u2014 Pr\u00f6va sj\u00e4lv",
    calc_title: "Priss\u00e4tt skadan",
    calc_desc: "Se vad vardagsprodukter verkligen skulle kosta om milj\u00f6skador inkluderades i priset.",
    calc_cat_label: "Kategori",
    calc_prod_label: "Produkt",
    calc_qty_label: "Antal",
    calc_unit_label: "Enhet",
    calc_price_label: "Koldioxidpris",
    calc_cat_food: "Mat & dryck",
    calc_cat_clothing: "Kl\u00e4der (efter material)",
    calc_cat_electronics: "Elektronik (efter storlek)",
    calc_cat_travel: "Resor",
    calc_cat_fuel: "Br\u00e4nsle",
    calc_price_50: "$50 / ton",
    calc_price_100: "$100 / ton",
    calc_price_150: "$150 / ton",
    calc_price_200: "$200 / ton",
    calc_eco_label: "Ekocertifierad / ekologisk k\u00e4lla (minskar uppskattningen med ~15%)",
    calc_result_label: "CO\u2082-avtryck",
    calc_sources: "K\u00e4llor: Poore & Nemecek (2018), <a href=\"https://doi.org/10.1126/science.aaq0216\" target=\"_blank\" rel=\"noopener\"><em>Science</em> 360:987</a> (mat) \u00b7 <a href=\"https://www.gov.uk/government/collections/government-conversion-factors-for-company-reporting\" target=\"_blank\" rel=\"noopener\">UK DEFRA 2023</a> (br\u00e4nsle/flygresor) \u00b7 Apple/Levi\u2019s Product Environmental Reports (elektronik/kl\u00e4der)",
    calc_damage_cost: "skadekostnad",
    calc_eco_note: "(ekocertifierad: \u221215%)",
    calc_prod_beef: "N\u00f6tk\u00f6tt",
    calc_prod_chicken: "Kyckling",
    calc_prod_cheese: "Ost",
    calc_prod_milk: "Mj\u00f6lk (ko)",
    calc_prod_rice: "Ris",
    calc_prod_coffee: "Kaffe (rostat)",
    calc_prod_chocolate: "M\u00f6rk choklad",
    calc_prod_tomatoes: "Tomater",
    calc_prod_potatoes: "Potatis",
    calc_prod_eggs: "\u00c4gg",
    calc_prod_bread: "Br\u00f6d (vete)",
    calc_prod_cotton_tshirt: "Bomull \u2014 T-shirt (250g)",
    calc_prod_cotton_jeans: "Bomull \u2014 Jeans (denim)",
    calc_prod_polyester_shirt: "Polyester \u2014 Skjorta",
    calc_prod_polyester_jacket: "Polyester \u2014 Jacka",
    calc_prod_wool_sweater: "Ull \u2014 Tr\u00f6ja",
    calc_prod_wool_coat: "Ull \u2014 Kappa",
    calc_prod_leather_shoes: "L\u00e4der \u2014 Skor",
    calc_prod_nylon_sneakers: "Nylon/Blandat \u2014 Sneakers",
    calc_prod_smartphone: "Telefonstorlek (smartphone)",
    calc_prod_tablet: "Plattstorlek (10\u2033)",
    calc_prod_laptop: "Laptopstorlek (13\u201316\u2033)",
    calc_prod_monitor: "Sk\u00e4rmstorlek (24\u201327\u2033)",
    calc_prod_tv: "TV-storlek (50\u201365\u2033)",
    calc_prod_desktop: "Station\u00e4r PC (tower)",
    calc_prod_flight_short: "Flyg \u2014 kortdistans (<3h)",
    calc_prod_flight_long: "Flyg \u2014 l\u00e5ngdistans (>6h)",
    calc_prod_car_petrol: "Bil \u2014 bensin (snitt)",
    calc_prod_car_diesel: "Bil \u2014 diesel (snitt)",
    calc_prod_train: "T\u00e5g (nationellt)",
    calc_prod_bus: "Buss (l\u00e5ngdistans)",
    calc_prod_petrol: "Bensin",
    calc_prod_diesel: "Diesel",
    calc_prod_natural_gas: "Naturgas (uppv\u00e4rmning)",
    calc_prod_electricity_eu: "Elektricitet (EU-snitt)",
    calc_note_beef: "Median global LCA; intervall 20\u2013105 kg CO\u2082e/kg",
    calc_note_chicken: "Inkluderar markanv\u00e4ndning, foder, bearbetning",
    calc_note_cheese: "~10 liter mj\u00f6lk per kg ost",
    calc_note_milk: "Inkluderar enterisk fermentation och markanv\u00e4ndning",
    calc_note_rice: "Metan fr\u00e5n \u00f6versv\u00e4mmade f\u00e4lt dominerar",
    calc_note_coffee: "Intervall 3,5\u201328,5; starkt beroende av markanv\u00e4ndning",
    calc_note_chocolate: "H\u00f6g avskogningskomponent i kakaokedjan",
    calc_note_tomatoes: "Frilandsv\u00e4rde; uppv\u00e4rmt v\u00e4xthus ~2,1",
    calc_note_potatoes: "En av de l\u00e4gsta utsl\u00e4ppens stärkelserika livsmedel",
    calc_note_eggs: "~12 \u00e4gg per kg",
    calc_note_bread: "Standardvetebr\u00f6d",
    calc_note_cotton_tshirt: "Bomullsodling ~h\u00e4lften av avtrycket",
    calc_note_cotton_jeans: "Full livscykel: odling till avfallshantering",
    calc_note_polyester_shirt: "Fossilbr\u00e4nslebaserad fiber",
    calc_note_polyester_jacket: "Syntetisk fyllning + petroleumbaserat skal",
    calc_note_wool_sweater: "F\u00e5rmetan + bearbetning",
    calc_note_wool_coat: "Tung ull; h\u00f6g metan + f\u00e4rgningseffekt",
    calc_note_leather_shoes: "N\u00f6tkreatursh\u00e5llning + garvningskemikalier",
    calc_note_nylon_sneakers: "Blandade material; tillverkningsdominerat",
    calc_note_smartphone: "Tillverkning ~80% av avtrycket; 3 \u00e5rs livsl\u00e4ngd",
    calc_note_tablet: "Mellan telefon och laptop i p\u00e5verkan",
    calc_note_laptop: "Intervall 150\u2013400 kg; beror p\u00e5 komponenter",
    calc_note_monitor: "Sk\u00e4rmtillverkning + fler\u00e5rig anv\u00e4ndning",
    calc_note_tv: "Stor sk\u00e4rm + 7 \u00e5rs anv\u00e4ndningsfas-el",
    calc_note_desktop: "H\u00f6gre str\u00f6mf\u00f6rbrukning; l\u00e4ngre komponentlivsl\u00e4ngd",
    calc_note_flight_short: "Per passagerare, ekonomi; inkluderar str\u00e5lningsp\u00e5verkan",
    calc_note_flight_long: "Effektivare per km vid l\u00e4ngre avst\u00e5nd",
    calc_note_car_petrol: "Genomsnittlig europeisk bensinbil ~210g CO\u2082/km",
    calc_note_car_diesel: "N\u00e5got l\u00e4gre CO\u2082 per km \u00e4n bensin",
    calc_note_train: "Varierar kraftigt beroende p\u00e5 eln\u00e4t; EU-genomsnitt",
    calc_note_bus: "Per passagerare; h\u00f6g bel\u00e4ggning antagen",
    calc_note_petrol: "Well-to-wheel inklusive uppstr\u00f6ms utvinning",
    calc_note_diesel: "N\u00e5got h\u00f6gre per liter \u00e4n bensin",
    calc_note_natural_gas: "F\u00f6rbr\u00e4nning + uppstr\u00f6ms metanl\u00e4ckage",
    calc_note_electricity_eu: "EU-eln\u00e4tsgenomsnitt; varierar per land",
  },
  fi: {
    nav_logo: "Hinnoittele vahinko",
    nav_how: "Näin se toimii",
    nav_principles: "Periaatteet",
    nav_examples: "Esimerkit",
    nav_questions: "Avoimet kysymykset",
    nav_join: "Liity",
    hero_label: "Poliittinen viitekehys ilmastokriisille",
    hero_title: "Tee saastuttamisesta<br><em>kallista</em>.",
    hero_subtitle: "Jokaisella tuotteella on piilotettu ympäristökustannus. Ehdotamme CO₂-ekvivalenttimaksua koko toimitusketjuun — muuntaen ekologisen vahingon taloudelliseksi paineeksi ja jakaen tulot uudelleen ihmisten suojelemiseksi.",
    hero_btn_primary: "Katso miten se toimii ↓",
    hero_btn_secondary: "Liity liikkeeseen",
    how_label: "01 — Mekanismi",
    how_title: "Maksu jokaisessa vaiheessa",
    how_desc: "CO₂-ekvivalenttimaksut peritään alkupäässä jokaisessa toimitusketjun vaiheessa. Kokonaiskustannus kertyy lopulliseen hintaan — tehden korkean päästötason tuotteista luonnollisesti kalliimpia.",
    stage1_title: "Louhinta",
    stage1_desc: "Raaka-aineiden louhinta, öljynporaus, korjuu",
    stage2_title: "Tuotanto",
    stage2_desc: "Valmistus, jalostus, prosessointi",
    stage3_title: "Kuljetus",
    stage3_desc: "Laivaus, rahti, logistiikka",
    stage4_title: "Vähittäiskauppa &amp; käyttö",
    stage4_desc: "Jakelu, kuluttajan käyttövaihe",
    stage5_title: "Hävittäminen",
    stage5_desc: "Elinkaaren loppu laajennetun tuottajavastuun kautta",
    stage_fee: "+ CO₂-maksu",
    pipeline_result: "Data on jo olemassa. <strong>Elinkaariarvioinnit (LCA)</strong> ja tuotteiden hiilijalanjäljet kattavat koko ketjun — louhinnasta hävittämiseen. Emme tarvitse uutta tiedettä. Tarvitsemme poliittista tahtoa.",
    manifesto: "Muunna ympäristövaikutus <em>väistämättömäksi taloudelliseksi paineeksi</em> ja jaa sitten rahat uudelleen pitääksesi yhteiskunnan vakaana samalla kun markkinat pakotetaan <em>irtautumaan hiilestä</em>.",
    principles_label: "02 — Periaatteet",
    principles_title: "Mitä kannatamme",
    principles_desc: "Kyse ei ole tiedotuskampanjoista tai vapaaehtoisista lupauksista. Kyse on taloudellisten kannustimien uudelleensuunnittelusta perustasolta lähtien.",
    p1_title: "Hinta, ei tietoisuus",
    p1_text: "Vuosikymmenten tiedotuskampanjat eivät ole taivuttaneet päästökäyrää. Hintasignaalit muuttavat käyttäytymistä laajassa mittakaavassa — automaattisesti, yleismaailmallisesti ja välittömästi.",
    p2_title: "Suojele ihmisiä, älä saastuttajia",
    p2_text: "Tulot ohjataan julkisiin palveluihin ja vähimmäistuloon korkeampien hintojen kompensoimiseksi. Ei tukia yrityksille \"vihertyäkseen\". Jos saastutat, maksat. Rahat suojaavat kansalaisia.",
    p3_title: "CO₂:n yhteiskunnallinen kustannus",
    p3_text: "Maksu per tonni perustuu CO₂:n todelliseen aiheuttamaan vahinkoon. Korkeampi hinta tarkoittaa voimakkaampaa käyttäytymisen muutosta — mutta vaatii myös vahvempaa sosiaalista uudelleenjakoa oikeudenmukaisuuden säilyttämiseksi.",
    p4_title: "EU:n laajuinen toteutus",
    p4_text: "Pelkästään kansallinen toteutus vääristää kauppaa sisämarkkinoilla. Tämä vaatii EU:n laajuista koordinointia — tai huolellisesti suunniteltuja kansallisia veroja, jotka eivät luo epäreiluja etuja.",
    examples_label: "03 — Todelliset luvut",
    examples_title: "Miltä tämä näyttää?",
    examples_desc: "Olemassa olevien elinkaariarviointien ja $100 per tonni CO₂-ekvivalentti -hiilihinnan perusteella.",
    ex_case: "Tapaustutkimus",
    ex_beef: "Naudanliha",
    ex_oil: "Raakaöljy",
    ex_lifecycle: "Elinkaaren päästöt",
    ex_carbon_price: "Sovellettu hiilihinta",
    ex_additional_kg: "Lisäkustannus per kg",
    ex_additional_barrel: "Lisäkustannus per tynnyri",
    ex_beef_insight: "Sisältää rehuntuotannon (öljypohjaiset lannoitteet), karjan metaanipäästöt, maankäytön muutoksen ja prosessoinnin. Suurin osa päästöistä tulee biologiasta — ei pelkästään energiapanoksista.",
    ex_oil_insight: "Merkittävä hintavaikutus — mutta kustannukset laimeutuvat, kun öljy jakautuu tuhansiin jatkotuotteisiin. Suurin vaikutus kohdistuu keskittyneisiin korkeiden päästöjen prosesseihin kuten karjankasvatukseen, ei pelkästään teollisiin panoksiin.",
    questions_label: "04 — Avoimet aukot",
    questions_title: "Avoimet kysymykset",
    questions_desc: "Emme väitä, että meillä on kaikki vastaukset. Nämä ovat vaikeita ongelmia, joiden ratkaiseminen vaatii yhteistä älykkyyttä.",
    q1: "Mikä tarkka hiilihinta tarvitaan kuluttaja- ja teollisuuskäyttäytymisen merkitykselliseen muuttamiseen aiheuttamatta taloudellista sokkia?",
    q2: "Miten valvomme tarkkaa elinkaarikirjanpitoa maailmanlaajuisesti, kun toimitusketjut ulottuvat kymmeniin maihin, joilla on erilaiset standardit?",
    q3: "Miten meidän tulisi käsitellä tuontia sääntöjä noudattamattomista maista? Hiilirajamekanismit ovat lupaavia, mutta poliittisesti ja logistisesti monimutkaisia.",
    q4: "Mikä on realistinen polku poliittiseen toteutettavuuteen EU:n rakenteiden puitteissa — ja miten rakennamme koalition sen saavuttamiseksi?",
    q5: "Kuinka nopeasti voimme siirtyä horjuttamatta elinkeinoja? Miltä oikea tasapaino kiireellisyyden ja sosiaalisen vakauden välillä näyttää?",
    join_label: "05 — Toimi",
    join_title: "Liity liikkeeseen",
    join_desc: "Tämä idea tarvitsee ekonomisteja, päätöksentekijöitä, aktivisteja ja kansalaisia, jotka uskovat, että hinta — ei syyllisyys — muuttaa maailman. Lisää äänesi.",
    join_placeholder: "sinun@sahkoposti.fi",
    join_btn: "Rekisteröidy",
    join_btn_done: "Lisätty ✓",
    join_note: "Ei roskapostia. Päivityksiä politiikan edistymisestä, tutkimuksesta ja toimista, joihin voit ryhtyä.",
    footer_mechanism: "Mekanismi",
    footer_data: "Data",
    calc_label: "03.5 \u2014 Kokeile itse",
    calc_title: "Hinnoittele vahinko",
    calc_desc: "Katso mit\u00e4 arkituotteet todella maksaisivat, jos ymp\u00e4rist\u00f6vahingot sis\u00e4ltyisiv\u00e4t hintaan.",
    calc_cat_label: "Kategoria",
    calc_prod_label: "Tuote",
    calc_qty_label: "M\u00e4\u00e4r\u00e4",
    calc_unit_label: "Yksikk\u00f6",
    calc_price_label: "Hiilihinta",
    calc_cat_food: "Ruoka & juoma",
    calc_cat_clothing: "Vaatteet (materiaalin mukaan)",
    calc_cat_electronics: "Elektroniikka (koon mukaan)",
    calc_cat_travel: "Matkustaminen",
    calc_cat_fuel: "Polttoaine",
    calc_price_50: "$50 / tonni",
    calc_price_100: "$100 / tonni",
    calc_price_150: "$150 / tonni",
    calc_price_200: "$200 / tonni",
    calc_eco_label: "Ekosertifioitu / luomul\u00e4hde (v\u00e4hent\u00e4\u00e4 arviota ~15%)",
    calc_result_label: "CO\u2082-jalanj\u00e4lki",
    calc_sources: "L\u00e4hteet: Poore & Nemecek (2018), <a href=\"https://doi.org/10.1126/science.aaq0216\" target=\"_blank\" rel=\"noopener\"><em>Science</em> 360:987</a> (ruoka) \u00b7 <a href=\"https://www.gov.uk/government/collections/government-conversion-factors-for-company-reporting\" target=\"_blank\" rel=\"noopener\">UK DEFRA 2023</a> (polttoaine/lennot) \u00b7 Apple/Levi\u2019s Product Environmental Reports (elektroniikka/vaatteet)",
    calc_damage_cost: "vahinkokustannus",
    calc_eco_note: "(ekosertifioitu: \u221215%)",
    calc_prod_beef: "Naudanliha",
    calc_prod_chicken: "Kana",
    calc_prod_cheese: "Juusto",
    calc_prod_milk: "Maito (lehm\u00e4)",
    calc_prod_rice: "Riisi",
    calc_prod_coffee: "Kahvi (paahdettu)",
    calc_prod_chocolate: "Tumma suklaa",
    calc_prod_tomatoes: "Tomaatit",
    calc_prod_potatoes: "Perunat",
    calc_prod_eggs: "Kananmunat",
    calc_prod_bread: "Leip\u00e4 (vehn\u00e4)",
    calc_prod_cotton_tshirt: "Puuvilla \u2014 T-paita (250g)",
    calc_prod_cotton_jeans: "Puuvilla \u2014 Farkut (denim)",
    calc_prod_polyester_shirt: "Polyesteri \u2014 Paita",
    calc_prod_polyester_jacket: "Polyesteri \u2014 Takki",
    calc_prod_wool_sweater: "Villa \u2014 Villapaita",
    calc_prod_wool_coat: "Villa \u2014 Takki",
    calc_prod_leather_shoes: "Nahka \u2014 Keng\u00e4t",
    calc_prod_nylon_sneakers: "Nylon/Sekoite \u2014 Lenkkarit",
    calc_prod_smartphone: "Puhelinkoko (\u00e4lypuhelin)",
    calc_prod_tablet: "Tablettikoko (10\u2033)",
    calc_prod_laptop: "Kannettavan koko (13\u201316\u2033)",
    calc_prod_monitor: "N\u00e4yt\u00f6n koko (24\u201327\u2033)",
    calc_prod_tv: "TV:n koko (50\u201365\u2033)",
    calc_prod_desktop: "P\u00f6yt\u00e4kone (torni)",
    calc_prod_flight_short: "Lento \u2014 lyhyt matka (<3h)",
    calc_prod_flight_long: "Lento \u2014 pitk\u00e4 matka (>6h)",
    calc_prod_car_petrol: "Auto \u2014 bensiini (keskim.)",
    calc_prod_car_diesel: "Auto \u2014 diesel (keskim.)",
    calc_prod_train: "Juna (kotimainen)",
    calc_prod_bus: "Bussi (kaukoliikenne)",
    calc_prod_petrol: "Bensiini",
    calc_prod_diesel: "Diesel",
    calc_prod_natural_gas: "Maakaasu (l\u00e4mmitys)",
    calc_prod_electricity_eu: "S\u00e4hk\u00f6 (EU-keskim.)",
    calc_note_beef: "Mediaani globaali LCA; vaihteluv\u00e4li 20\u2013105 kg CO\u2082e/kg",
    calc_note_chicken: "Sis\u00e4lt\u00e4\u00e4 maank\u00e4yt\u00f6n, rehun, jalostuksen",
    calc_note_cheese: "~10 litraa maitoa per kg juustoa",
    calc_note_milk: "Sis\u00e4lt\u00e4\u00e4 enterisen fermentaation ja maank\u00e4yt\u00f6n",
    calc_note_rice: "Tulvitettujen peltojen metaani hallitsee",
    calc_note_coffee: "Vaihteluv\u00e4li 3,5\u201328,5; voimakkaasti maank\u00e4yt\u00f6st\u00e4 riippuvainen",
    calc_note_chocolate: "Korkea mets\u00e4katokomponentti kaakaon toimitusketjussa",
    calc_note_tomatoes: "Avomaaarvo; l\u00e4mmitetty kasvihuone ~2,1",
    calc_note_potatoes: "Yksi matalap\u00e4\u00e4st\u00f6isimmist\u00e4 t\u00e4rkkelysruuista",
    calc_note_eggs: "~12 kananmunaa per kg",
    calc_note_bread: "Tavallinen vehn\u00e4leip\u00e4",
    calc_note_cotton_tshirt: "Puuvillanviljely ~puolet jalanj\u00e4ljest\u00e4",
    calc_note_cotton_jeans: "Koko elinkaari: viljelyst\u00e4 h\u00e4vitt\u00e4miseen",
    calc_note_polyester_shirt: "Fossiilisista polttoaineista johdettu kuitu",
    calc_note_polyester_jacket: "Synteettinen t\u00e4yte + \u00f6ljypohjainen kuori",
    calc_note_wool_sweater: "Lampaiden metaani + jalostus",
    calc_note_wool_coat: "Raskas villa; korkea metaani + v\u00e4rj\u00e4ysvaikutus",
    calc_note_leather_shoes: "Karjankasvatus + parkituskemikaalit",
    calc_note_nylon_sneakers: "Sekamateriaalit; valmistusvaltainen",
    calc_note_smartphone: "Valmistus ~80% jalanj\u00e4ljest\u00e4; 3 vuoden k\u00e4ytt\u00f6ik\u00e4",
    calc_note_tablet: "Puhelimen ja kannettavan v\u00e4liss\u00e4 vaikutukseltaan",
    calc_note_laptop: "Vaihteluv\u00e4li 150\u2013400 kg; riippuu komponenteista",
    calc_note_monitor: "N\u00e4yt\u00f6n valmistus + monivuotinen k\u00e4ytt\u00f6",
    calc_note_tv: "Suuri n\u00e4ytt\u00f6 + 7 vuoden k\u00e4ytt\u00f6vaiheen s\u00e4hk\u00f6",
    calc_note_desktop: "Suurempi tehonkulutus; pidempi komponenttien k\u00e4ytt\u00f6ik\u00e4",
    calc_note_flight_short: "Per matkustaja, economy; sis\u00e4lt\u00e4\u00e4 s\u00e4teilyvaikutuksen",
    calc_note_flight_long: "Tehokkaampi per km pidemmill\u00e4 matkoilla",
    calc_note_car_petrol: "Keskim\u00e4\u00e4r\u00e4inen eurooppalainen bensiiniauto ~210g CO\u2082/km",
    calc_note_car_diesel: "Hieman alempi CO\u2082 per km kuin bensiini",
    calc_note_train: "Vaihtelee suuresti s\u00e4hk\u00f6verkon mukaan; EU-keskiarvo",
    calc_note_bus: "Per matkustaja; korkea k\u00e4ytt\u00f6aste oletettu",
    calc_note_petrol: "Well-to-wheel sis\u00e4lt\u00e4en alkup\u00e4\u00e4n louhinnan",
    calc_note_diesel: "Hieman korkeampi per litra kuin bensiini",
    calc_note_natural_gas: "Palaminen + alkup\u00e4\u00e4n metaanivuodot",
    calc_note_electricity_eu: "EU:n s\u00e4hk\u00f6verkon keskiarvo; vaihtelee maittain",
  },
  et: {
    nav_logo: "Hinnasta kahju",
    nav_how: "Kuidas see toimib",
    nav_principles: "Põhimõtted",
    nav_examples: "Näited",
    nav_questions: "Avatud küsimused",
    nav_join: "Liitu",
    hero_label: "Poliitiline raamistik kliimakriisile",
    hero_title: "Muuda saastamine<br><em>kulukaks</em>.",
    hero_subtitle: "Igal tootel on varjatud keskkonnamaksumus. Me pakume CO₂-ekvivalentset tasu kogu tarneahela ulatuses — muutes ökoloogiline kahju majanduslikuks surveks, samal ajal jaotades tulu ümber inimeste kaitseks.",
    hero_btn_primary: "Vaata, kuidas see toimib ↓",
    hero_btn_secondary: "Liitu liikumisega",
    how_label: "01 — Mehhanism",
    how_title: "Tasu igal etapil",
    how_desc: "CO₂-ekvivalentsed tasud rakendatakse tarneahela igal punktil ülesvoolu. Kogumaksumus koguneb lõpphinda — muutes suure heitega tooted loomulikult kallimaks.",
    stage1_title: "Kaevandamine",
    stage1_desc: "Toorainete kaevandamine, nafta puurimine, koristamine",
    stage2_title: "Tootmine",
    stage2_desc: "Valmistamine, rafineerimine, töötlemine",
    stage3_title: "Transport",
    stage3_desc: "Laevandus, kaubavedu, logistika",
    stage4_title: "Jaemüük &amp; kasutamine",
    stage4_desc: "Jaotamine, tarbija kasutamisfaas",
    stage5_title: "Kõrvaldamine",
    stage5_desc: "Elutsükli lõpp laiendatud tootjavastutuse kaudu",
    stage_fee: "+ CO₂-tasu",
    pipeline_result: "Andmed on juba olemas. <strong>Olelusringi hindamised (LCA)</strong> ja toodete süsiniku jalajäljed katavad kogu ahela — kaevandamisest kõrvaldamiseni. Me ei vaja uut teadust. Me vajame poliitilist tahet.",
    manifesto: "Muuda keskkonnamõju <em>vältimatuks majanduslikuks surveks</em>, seejärel jaota raha ümber, et hoida ühiskonda stabiilsena, sundides turgu samal ajal <em>dekarboniseeruma</em>.",
    principles_label: "02 — Põhimõtted",
    principles_title: "Mille eest me seisame",
    principles_desc: "See ei puuduta teadlikkuse kampaaniaid ega vabatahtlikke lubadusi. See puudutab majanduslike stiimulite ümberkujundamist nullist.",
    p1_title: "Hind, mitte teadlikkus",
    p1_text: "Aastakümnete pikkused teadlikkuse kampaaniad pole heitkõverat painutanud. Hinnasignaalid muudavad käitumist laiaulatuslikult — automaatselt, universaalselt ja kohe.",
    p2_title: "Kaitse inimesi, mitte saastajaid",
    p2_text: "Tulu läheb avalikele hüvedele ja miinimumsissetulekule kõrgemate hindade kompenseerimiseks. Ei mingeid toetusi ettevõtetele, et \"muutuda roheliseks\". Kui saastad, maksad. Raha kaitseb kodanikke.",
    p3_title: "CO₂ sotsiaalne maksumus",
    p3_text: "Tasu tonni kohta põhineb CO₂ tegelikul kahjul. Kõrgem hind tähendab tugevamat käitumismuutust — kuid nõuab ka tugevamat sotsiaalset ümberjaotust, et hoida see õiglasena.",
    p4_title: "EL-ülene rakendamine",
    p4_text: "Ainult riiklik rakendamine moonutab kaubandust ühisturul. See vajab EL-ülest koordineerimist — või hoolikalt kavandatud riiklikke makse, mis ei loo ebaõiglasi eeliseid.",
    examples_label: "03 — Tegelikud arvud",
    examples_title: "Kuidas see välja näeb?",
    examples_desc: "Olemasolevate olelusringi hindamiste ja $100 tonni CO₂-ekvivalendi kohta süsinikuhinna põhjal.",
    ex_case: "Juhtumiuuring",
    ex_beef: "Veiseliha",
    ex_oil: "Toornafta",
    ex_lifecycle: "Olelusringi heited",
    ex_carbon_price: "Rakendatud süsinikuhind",
    ex_additional_kg: "Lisakulu kg kohta",
    ex_additional_barrel: "Lisakulu barreli kohta",
    ex_beef_insight: "Hõlmab söödatootmist (naftapõhised väetised), veiste metaani, maakasutuse muutust ja töötlemist. Enamik heiteid tuleb bioloogiast — mitte ainult energiasisenditest.",
    ex_oil_insight: "Märkimisväärne hinnmõju — kuid kulud hajuvad, kuna nafta jaotub tuhandete järeltoodete vahel. Suurim mõju langeb kontsentreeritud suure heitega protsessidele nagu loomakasvatus, mitte ainult tööstuslikele sisenditele.",
    questions_label: "04 — Ausad lüngad",
    questions_title: "Avatud küsimused",
    questions_desc: "Me ei teeskle, et meil on kõik vastused. Need on rasked probleemid, mille lahendamiseks vajame kollektiivset intelligentsi.",
    q1: "Milline täpne süsinikuhind on vajalik tarbija- ja tööstuskäitumise sisukaks muutmiseks ilma majandusliku šoki tekitamiseta?",
    q2: "Kuidas tagame täpse olelusringi arvestuse globaalselt, kui tarneahelad ulatuvad kümnetesse riikidesse erinevate standarditega?",
    q3: "Kuidas peaksime käsitlema importi mittevastavatelt riikidelt? Süsiniku piirimeetmed on paljulubavad, kuid poliitiliselt ja logistiliselt keerukad.",
    q4: "Milline on realistlik tee poliitilise teostatavuseni EL-i struktuurides — ja kuidas ehitame koalitsiooni selle saavutamiseks?",
    q5: "Kui kiiresti saame üle minna elatusallikaid destabiliseerimata? Milline näeb välja õige tasakaal kiireloomulisuse ja sotsiaalse stabiilsuse vahel?",
    join_label: "05 — Tegutse",
    join_title: "Liitu liikumisega",
    join_desc: "See idee vajab majandusteadlasi, poliitikakujundajaid, aktiviste ja kodanikke, kes usuvad, et hind — mitte süütunne — on see, mis muudab maailma. Lisa oma hääl.",
    join_placeholder: "sinu@email.ee",
    join_btn: "Registreeru",
    join_btn_done: "Lisatud ✓",
    join_note: "Ei rämpsposti. Uuendused poliitika edenemise, uuringute ja tegevuste kohta, mida saad ette võtta.",
    footer_mechanism: "Mehhanism",
    footer_data: "Andmed",
    calc_label: "03.5 \u2014 Proovi ise",
    calc_title: "Hinnasta kahju",
    calc_desc: "Vaata, mida igap\u00e4evatooted tegelikult maksaksid, kui keskkonnakahju oleks hinna sisse arvestatud.",
    calc_cat_label: "Kategooria",
    calc_prod_label: "Toode",
    calc_qty_label: "Kogus",
    calc_unit_label: "\u00dchik",
    calc_price_label: "S\u00fcsinikuhind",
    calc_cat_food: "Toit ja jook",
    calc_cat_clothing: "R\u00f5ivad (materjali j\u00e4rgi)",
    calc_cat_electronics: "Elektroonika (suuruse j\u00e4rgi)",
    calc_cat_travel: "Reisimine",
    calc_cat_fuel: "K\u00fctus",
    calc_price_50: "$50 / tonn",
    calc_price_100: "$100 / tonn",
    calc_price_150: "$150 / tonn",
    calc_price_200: "$200 / tonn",
    calc_eco_label: "\u00d6kosertifitseeritud / mahe allikas (v\u00e4hendab hinnangut ~15%)",
    calc_result_label: "CO\u2082 jalaj\u00e4lg",
    calc_sources: "Allikad: Poore & Nemecek (2018), <a href=\"https://doi.org/10.1126/science.aaq0216\" target=\"_blank\" rel=\"noopener\"><em>Science</em> 360:987</a> (toit) \u00b7 <a href=\"https://www.gov.uk/government/collections/government-conversion-factors-for-company-reporting\" target=\"_blank\" rel=\"noopener\">UK DEFRA 2023</a> (k\u00fctus/lennud) \u00b7 Apple/Levi\u2019s Product Environmental Reports (elektroonika/r\u00f5ivad)",
    calc_damage_cost: "kahjukulu",
    calc_eco_note: "(\u00f6kosertifitseeritud: \u221215%)",
    calc_prod_beef: "Veiseliha",
    calc_prod_chicken: "Kanaliha",
    calc_prod_cheese: "Juust",
    calc_prod_milk: "Piim (lehm)",
    calc_prod_rice: "Riis",
    calc_prod_coffee: "Kohv (r\u00f6stitud)",
    calc_prod_chocolate: "Tume \u0161okolaad",
    calc_prod_tomatoes: "Tomatid",
    calc_prod_potatoes: "Kartulid",
    calc_prod_eggs: "Munad",
    calc_prod_bread: "Leib (nisu)",
    calc_prod_cotton_tshirt: "Puuvill \u2014 T-s\u00e4rk (250g)",
    calc_prod_cotton_jeans: "Puuvill \u2014 T\u00e4ksad (denim)",
    calc_prod_polyester_shirt: "Pol\u00fcester \u2014 S\u00e4rk",
    calc_prod_polyester_jacket: "Pol\u00fcester \u2014 Jakk",
    calc_prod_wool_sweater: "Vill \u2014 Kampsun",
    calc_prod_wool_coat: "Vill \u2014 Mantel",
    calc_prod_leather_shoes: "Nahk \u2014 Kingad",
    calc_prod_nylon_sneakers: "N\u00fclon/Sega \u2014 Tossud",
    calc_prod_smartphone: "Telefonisuurune (nutitelefon)",
    calc_prod_tablet: "Tahvlisuurune (10\u2033)",
    calc_prod_laptop: "S\u00fclearvutisuurune (13\u201316\u2033)",
    calc_prod_monitor: "Monitorisuurune (24\u201327\u2033)",
    calc_prod_tv: "Telerisuurune (50\u201365\u2033)",
    calc_prod_desktop: "Lauaarvuti (torn)",
    calc_prod_flight_short: "Lend \u2014 l\u00fchimaa (<3h)",
    calc_prod_flight_long: "Lend \u2014 kaugmaa (>6h)",
    calc_prod_car_petrol: "Auto \u2014 bensiin (kesk.)",
    calc_prod_car_diesel: "Auto \u2014 diisel (kesk.)",
    calc_prod_train: "Rong (riigisisene)",
    calc_prod_bus: "Buss (kaugliini)",
    calc_prod_petrol: "Bensiin",
    calc_prod_diesel: "Diisel",
    calc_prod_natural_gas: "Maagaas (k\u00fcte)",
    calc_prod_electricity_eu: "Elekter (EL-i kesk.)",
    calc_note_beef: "Mediaanv\u00e4\u00e4rtus globaalne LCA; vahemik 20\u2013105 kg CO\u2082e/kg",
    calc_note_chicken: "H\u00f5lmab maakasutust, s\u00f6\u00f6ta, t\u00f6\u00f6tlemist",
    calc_note_cheese: "~10 liitrit piima kg juustu kohta",
    calc_note_milk: "H\u00f5lmab enteraalset fermentatsiooni ja maakasutust",
    calc_note_rice: "Metaan \u00fcleujutatud p\u00f5ldudelt domineerib",
    calc_note_coffee: "Vahemik 3,5\u201328,5; tugevalt maakasutusest s\u00f5ltuv",
    calc_note_chocolate: "K\u00f5rge raadamiskomponent kakao tarneahelas",
    calc_note_tomatoes: "Avamaa v\u00e4\u00e4rtus; k\u00f6etav kasvuhoone ~2,1",
    calc_note_potatoes: "\u00dcks madalaima heitega t\u00e4rkliserikastest toiduainetest",
    calc_note_eggs: "~12 muna kg kohta",
    calc_note_bread: "Tavap\u00e4rane nisuleib",
    calc_note_cotton_tshirt: "Puuvilla kasvatamine ~pool jalaj\u00e4ljest",
    calc_note_cotton_jeans: "T\u00e4is elutsukkel: kasvatamisest k\u00f5rvaldamiseni",
    calc_note_polyester_shirt: "Fossiilk\u00fctusep\u00f5hine kiud",
    calc_note_polyester_jacket: "S\u00fcnteetiline t\u00e4idis + naftap\u00f5hine v\u00e4liskest",
    calc_note_wool_sweater: "Lammaste metaan + t\u00f6\u00f6tlemine",
    calc_note_wool_coat: "Raske vill; k\u00f5rge metaani + v\u00e4rvimise m\u00f5ju",
    calc_note_leather_shoes: "Veisekasvatus + parkimiskemikaalid",
    calc_note_nylon_sneakers: "Segamaterjalid; tootmisdomineeritud",
    calc_note_smartphone: "Tootmine ~80% jalaj\u00e4ljest; 3-aastane eluiga",
    calc_note_tablet: "Telefoni ja s\u00fclearvuti vahel m\u00f5ju poolest",
    calc_note_laptop: "Vahemik 150\u2013400 kg; s\u00f5ltub komponentidest",
    calc_note_monitor: "Ekraanitootmine + mitmeaastane kasutamine",
    calc_note_tv: "Suur ekraan + 7-aastane kasutusfaasi elekter",
    calc_note_desktop: "K\u00f5rgem energiatarve; pikem komponentide eluiga",
    calc_note_flight_short: "Reisija kohta, s\u00e4\u00e4stuklass; h\u00f5lmab kiirgusm\u00f5ju",
    calc_note_flight_long: "T\u00f5husam km kohta pikemate vahemaade puhul",
    calc_note_car_petrol: "Keskmine Euroopa bensiiniauto ~210g CO\u2082/km",
    calc_note_car_diesel: "Pisut madalam CO\u2082 km kohta kui bensiin",
    calc_note_train: "Varieerub tugevalt elektriv\u00f5rgu j\u00e4rgi; EL-i keskmine",
    calc_note_bus: "Reisija kohta; k\u00f5rge t\u00e4ituvus eeldatud",
    calc_note_petrol: "Well-to-wheel kaasa arvatud \u00fclesvoolu kaevandamine",
    calc_note_diesel: "Pisut k\u00f5rgem liitri kohta kui bensiin",
    calc_note_natural_gas: "P\u00f5lemine + \u00fclesvoolu metaanileke",
    calc_note_electricity_eu: "EL-i elektriv\u00f5rgu keskmine; varieerub riigiti",
  },
  lv: {
    nav_logo: "Novērtē kaitējumu",
    nav_how: "Kā tas darbojas",
    nav_principles: "Principi",
    nav_examples: "Piemēri",
    nav_questions: "Atklāti jautājumi",
    nav_join: "Pievienojies",
    hero_label: "Politikas ietvars klimata krīzei",
    hero_title: "Padari piesārņošanu<br><em>dārgu</em>.",
    hero_subtitle: "Katram produktam ir slēptas vides izmaksas. Mēs piedāvājam CO₂-ekvivalenta maksu visā piegādes ķēdē — pārvēršot ekoloģisko kaitējumu ekonomiskā spiedienā, vienlaikus pārdalot ieņēmumus cilvēku aizsardzībai.",
    hero_btn_primary: "Uzzini, kā tas darbojas ↓",
    hero_btn_secondary: "Pievienojies kustībai",
    how_label: "01 — Mehānisms",
    how_title: "Maksa katrā posmā",
    how_desc: "CO₂-ekvivalenta maksas tiek piemērotas augšpus katrā piegādes ķēdes punktā. Kopējās izmaksas uzkrājas gala cenā — dabiski padarot augstu emisiju produktus dārgākus.",
    stage1_title: "Ieguve",
    stage1_desc: "Izejvielu ieguve, naftas urbšana, ievākšana",
    stage2_title: "Ražošana",
    stage2_desc: "Rūpnieciskā ražošana, rafinēšana, apstrāde",
    stage3_title: "Transports",
    stage3_desc: "Kuģošana, kravas pārvadājumi, loģistika",
    stage4_title: "Mazumtirdzniecība &amp; lietošana",
    stage4_desc: "Izplatīšana, patērētāja lietošanas fāze",
    stage5_title: "Utilizācija",
    stage5_desc: "Dzīves cikla beigas ar paplašinātu ražotāja atbildību",
    stage_fee: "+ CO₂ maksa",
    pipeline_result: "Dati jau pastāv. <strong>Dzīves cikla novērtējumi (LCA)</strong> un produktu oglekļa pēdas nospiedumi aptver visu ķēdi — no ieguves līdz utilizācijai. Mums nav vajadzīga jauna zinātne. Mums ir vajadzīga politiskā griba.",
    manifesto: "Pārvērt vides ietekmi <em>neizbēgamā ekonomiskā spiedienā</em>, pēc tam pārdali naudu, lai uzturētu sabiedrību stabilu, kamēr tirgus tiek spiests <em>dekarbonizēties</em>.",
    principles_label: "02 — Principi",
    principles_title: "Par ko mēs iestājamies",
    principles_desc: "Runa nav par informēšanas kampaņām vai brīvprātīgiem solījumiem. Runa ir par ekonomisko stimulu pārveidošanu no pamatiem.",
    p1_title: "Cena, nevis informētība",
    p1_text: "Gadu desmitiem ilgas informēšanas kampaņas nav liektušas emisiju līkni. Cenu signāli maina uzvedību plašā mērogā — automātiski, universāli un nekavējoties.",
    p2_title: "Aizsargā cilvēkus, nevis piesārņotājus",
    p2_text: "Ieņēmumi tiek novirzīti sabiedriskiem labumiem un minimālajiem ienākumiem, lai kompensētu augstākas cenas. Nekādu subsidiju uzņēmumiem, lai \"kļūtu zaļi\". Ja piesārņo — maksā. Nauda aizsargā iedzīvotājus.",
    p3_title: "CO₂ sociālās izmaksas",
    p3_text: "Maksa par tonnu ir balstīta uz reālo kaitējumu, ko rada CO₂. Augstāka cena nozīmē spēcīgāku uzvedības maiņu — bet prasa arī spēcīgāku sociālo pārdali, lai saglabātu taisnīgumu.",
    p4_title: "ES mēroga ieviešana",
    p4_text: "Tikai valsts līmeņa ieviešana kropļo tirdzniecību vienotajā tirgū. Tam nepieciešama ES mēroga koordinācija — vai rūpīgi izstrādāti valsts nodokļi, kas nerada negodīgas priekšrocības.",
    examples_label: "03 — Reāli skaitļi",
    examples_title: "Kā tas izskatās?",
    examples_desc: "Izmantojot esošos dzīves cikla novērtējumus un oglekļa cenu $100 par tonnu CO₂-ekvivalenta.",
    ex_case: "Gadījuma izpēte",
    ex_beef: "Liellopu gaļa",
    ex_oil: "Jēlnafta",
    ex_lifecycle: "Dzīves cikla emisijas",
    ex_carbon_price: "Piemērotā oglekļa cena",
    ex_additional_kg: "Papildu izmaksas par kg",
    ex_additional_barrel: "Papildu izmaksas par barelu",
    ex_beef_insight: "Ietver barības ražošanu (naftas bāzes mēslojumi), liellopu metānu, zemes izmantošanas maiņu un apstrādi. Lielākā daļa emisiju nāk no bioloģijas — ne tikai enerģijas ieguldījumiem.",
    ex_oil_insight: "Būtiska ietekme uz cenu — taču izmaksas izšķīst, kad nafta sadalās tūkstošiem pakārtotu produktu. Lielākā ietekme skar koncentrētus augstu emisiju procesus kā lopkopību, ne tikai rūpnieciskos ieguldījumus.",
    questions_label: "04 — Godīgas nepilnības",
    questions_title: "Atklāti jautājumi",
    questions_desc: "Mēs neizliekamies, ka mums ir visas atbildes. Šīs ir grūtās problēmas, kuru risināšanai nepieciešams kolektīvais intelekts.",
    q1: "Kāda precīza oglekļa cena ir nepieciešama, lai jēgpilni mainītu patērētāju un rūpniecības uzvedību, neizraisot ekonomisku šoku?",
    q2: "Kā mēs nodrošinām precīzu dzīves cikla uzskaiti globālā mērogā, ja piegādes ķēdes aptver desmitiem valstu ar dažādiem standartiem?",
    q3: "Kā mums būtu jārīkojas ar importu no neatbilstošām valstīm? Oglekļa robežkorekcijas ir daudzsološas, bet politiski un loģistiski sarežģītas.",
    q4: "Kāds ir reālistisks ceļš uz politisko īstenojamību ES struktūrās — un kā mēs veidojam koalīciju, lai to sasniegtu?",
    q5: "Cik ātri mēs varam pāriet, nedestabilizējot iztiku? Kā izskatās pareizais līdzsvars starp steidzamību un sociālo stabilitāti?",
    join_label: "05 — Rīkojies",
    join_title: "Pievienojies kustībai",
    join_desc: "Šai idejai ir nepieciešami ekonomisti, politikas veidotāji, aktīvisti un pilsoņi, kas tic, ka cena — nevis vainas apziņa — ir tas, kas maina pasauli. Pievieno savu balsi.",
    join_placeholder: "tavs@epasts.lv",
    join_btn: "Reģistrēties",
    join_btn_done: "Pievienots ✓",
    join_note: "Nekāda surogātpasta. Jaunumi par politikas virzību, pētījumiem un darbībām, ko vari veikt.",
    footer_mechanism: "Meh\u0101nisms",
    footer_data: "Dati",
    calc_label: "03.5 \u2014 Izm\u0113\u0123ini pats",
    calc_title: "Nov\u0113rt\u0113 kait\u0113jumu",
    calc_desc: "Uzzini, cik ikdienas produkti paties\u012bb\u0101 maks\u0101tu, ja vides kait\u0113jums b\u016btu iek\u013cauts cen\u0101.",
    calc_cat_label: "Kategorija",
    calc_prod_label: "Produkts",
    calc_qty_label: "Daudzums",
    calc_unit_label: "Vien\u012bba",
    calc_price_label: "Oglek\u013ca cena",
    calc_cat_food: "\u0112diens un dz\u0113riens",
    calc_cat_clothing: "Ap\u0123\u0113rbs (p\u0113c materi\u0101la)",
    calc_cat_electronics: "Elektronika (p\u0113c izm\u0113ra)",
    calc_cat_travel: "Ce\u013co\u0161ana",
    calc_cat_fuel: "Degviela",
    calc_price_50: "$50 / tonna",
    calc_price_100: "$100 / tonna",
    calc_price_150: "$150 / tonna",
    calc_price_200: "$200 / tonna",
    calc_eco_label: "Ekosertific\u0113ts / biolo\u0123isks avots (samazina apl\u0113si par ~15%)",
    calc_result_label: "CO\u2082 p\u0113das nospiedums",
    calc_sources: "Avoti: Poore & Nemecek (2018), <a href=\"https://doi.org/10.1126/science.aaq0216\" target=\"_blank\" rel=\"noopener\"><em>Science</em> 360:987</a> (\u0113diens) \u00b7 <a href=\"https://www.gov.uk/government/collections/government-conversion-factors-for-company-reporting\" target=\"_blank\" rel=\"noopener\">UK DEFRA 2023</a> (degviela/lidojumi) \u00b7 Apple/Levi\u2019s Product Environmental Reports (elektronika/ap\u0123\u0113rbs)",
    calc_damage_cost: "kait\u0113juma izmaksas",
    calc_eco_note: "(ekosertific\u0113ts: \u221215%)",
    calc_prod_beef: "Liellopu ga\u013ca",
    calc_prod_chicken: "Vista",
    calc_prod_cheese: "Siers",
    calc_prod_milk: "Piens (govs)",
    calc_prod_rice: "R\u012bsi",
    calc_prod_coffee: "Kafija (grauzdēta)",
    calc_prod_chocolate: "Tumšā šokolāde",
    calc_prod_tomatoes: "Tomāti",
    calc_prod_potatoes: "Kartupeļi",
    calc_prod_eggs: "Olas",
    calc_prod_bread: "Maize (kviešu)",
    calc_prod_cotton_tshirt: "Kokvilna \u2014 T-krekls (250g)",
    calc_prod_cotton_jeans: "Kokvilna \u2014 D\u017einsi (denim)",
    calc_prod_polyester_shirt: "Poliesters \u2014 Krekls",
    calc_prod_polyester_jacket: "Poliesters \u2014 Jaka",
    calc_prod_wool_sweater: "Vilna \u2014 Džemperis",
    calc_prod_wool_coat: "Vilna \u2014 M\u0113telis",
    calc_prod_leather_shoes: "\u0100da \u2014 Kurpes",
    calc_prod_nylon_sneakers: "Neilons/Mais\u012bjums \u2014 Kedas",
    calc_prod_smartphone: "Telefona izm\u0113rs (viedtelefons)",
    calc_prod_tablet: "Plan\u0161etes izm\u0113rs (10\u2033)",
    calc_prod_laptop: "Portat\u012bv\u0101 datora izm\u0113rs (13\u201316\u2033)",
    calc_prod_monitor: "Monitora izm\u0113rs (24\u201327\u2033)",
    calc_prod_tv: "TV izm\u0113rs (50\u201365\u2033)",
    calc_prod_desktop: "Galddators (tornis)",
    calc_prod_flight_short: "Lidojums \u2014 \u012bsa distance (<3h)",
    calc_prod_flight_long: "Lidojums \u2014 gara distance (>6h)",
    calc_prod_car_petrol: "Auto \u2014 benz\u012bns (vid.)",
    calc_prod_car_diesel: "Auto \u2014 d\u012bze\u013ca (vid.)",
    calc_prod_train: "Vilciens (iek\u0161zemes)",
    calc_prod_bus: "Autobuss (t\u0101lsatiksmes)",
    calc_prod_petrol: "Benz\u012bns",
    calc_prod_diesel: "D\u012bze\u013cdegviela",
    calc_prod_natural_gas: "Dabas g\u0101ze (apkure)",
    calc_prod_electricity_eu: "Elektr\u012bba (ES vid.)",
    calc_note_beef: "Medi\u0101na glob\u0101l\u0101 LCA; diapazons 20\u2013105 kg CO\u2082e/kg",
    calc_note_chicken: "Ietver zemes izmanto\u0161anu, bar\u012bbu, p\u0101rstr\u0101di",
    calc_note_cheese: "~10 litri piena uz kg siera",
    calc_note_milk: "Ietver enterisko ferment\u0101ciju un zemes izmanto\u0161anu",
    calc_note_rice: "Met\u0101ns no appl\u016bdin\u0101tiem laukiem domin\u0113",
    calc_note_coffee: "Diapazons 3,5\u201328,5; sp\u0113c\u012bgi atkar\u012bgs no zemes izmanto\u0161anas",
    calc_note_chocolate: "Augsts me\u017eu izciršanas komponents kakao pieg\u0101des \u0137\u0113d\u0113",
    calc_note_tomatoes: "Atkl\u0101ta lauka v\u0113rt\u012bba; apkurināma siltumn\u012bca ~2,1",
    calc_note_potatoes: "Viens no zem\u0101ko emisiju cietes\u012bgo p\u0101rtikas produktiem",
    calc_note_eggs: "~12 olas uz kg",
    calc_note_bread: "Standarta kviešu maize",
    calc_note_cotton_tshirt: "Kokvilnas audz\u0113\u0161ana ~puse no p\u0113das nospieduma",
    calc_note_cotton_jeans: "Pilns dz\u012bves cikls: no audz\u0113\u0161anas l\u012bdz utiliz\u0101cijai",
    calc_note_polyester_shirt: "No fosil\u0101 kurin\u0101m\u0101 ieg\u016bta \u0161\u0137iedra",
    calc_note_polyester_jacket: "Sint\u0113tisks pild\u012bjums + naftas b\u0101zes apvalks",
    calc_note_wool_sweater: "Aitu met\u0101ns + p\u0101rstr\u0101de",
    calc_note_wool_coat: "Smaga vilna; augsts met\u0101ns + kr\u0101so\u0161anas ietekme",
    calc_note_leather_shoes: "Liellopu audz\u0113\u0161ana + miec\u0113\u0161anas \u0137\u012bmikas",
    calc_note_nylon_sneakers: "Jaukti materi\u0101li; ra\u017eo\u0161anas domin\u0113ts",
    calc_note_smartphone: "Ra\u017eo\u0161ana ~80% no p\u0113das nospieduma; 3 gadu kalpo\u0161anas laiks",
    calc_note_tablet: "Starp telefonu un portat\u012bvo datoru ietekmes zi\u0146\u0101",
    calc_note_laptop: "Diapazons 150\u2013400 kg; atkar\u012bgs no komponentiem",
    calc_note_monitor: "Displeja ra\u017eo\u0161ana + daudzgadu lieto\u0161ana",
    calc_note_tv: "Liels displejs + 7 gadu lieto\u0161anas f\u0101zes elektr\u012bba",
    calc_note_desktop: "Augst\u0101ks ener\u0123ijas pat\u0113ri\u0146\u0161; ilg\u0101ks komponentu kalpo\u0161anas laiks",
    calc_note_flight_short: "Uz pasažieri, ekonomisk\u0101; ietver radi\u0101cijas ietekmi",
    calc_note_flight_long: "Efekt\u012bv\u0101ks uz km liel\u0101kos att\u0101lumos",
    calc_note_car_petrol: "Vid\u0113j\u0101 Eiropas benz\u012bna auto ~210g CO\u2082/km",
    calc_note_car_diesel: "Nedaudz zem\u0101ks CO\u2082 uz km nek\u0101 benz\u012bns",
    calc_note_train: "B\u016btiski at\u0161\u0137iras p\u0113c elektrot\u012bkla; ES vid\u0113jais",
    calc_note_bus: "Uz pasažieri; augsta noslogot\u012bba pie\u0146emta",
    calc_note_petrol: "Well-to-wheel ieskaitot augšup\u0113j\u0101s ieguvi",
    calc_note_diesel: "Nedaudz augst\u0101ks uz litru nek\u0101 benz\u012bns",
    calc_note_natural_gas: "Sadeg\u0161ana + augšup\u0113j\u0101s met\u0101na nopl\u016bde",
    calc_note_electricity_eu: "ES elektrot\u012bkla vid\u0113jais; at\u0161\u0137iras p\u0113c valsts",
  },
  lt: {
    nav_logo: "Įkainok žalą",
    nav_how: "Kaip tai veikia",
    nav_principles: "Principai",
    nav_examples: "Pavyzdžiai",
    nav_questions: "Atviri klausimai",
    nav_join: "Prisijunk",
    hero_label: "Politikos sistema klimato krizei",
    hero_title: "Padaryk taršą<br><em>brangią</em>.",
    hero_subtitle: "Kiekvienas produktas turi paslėptą aplinkosauginę kainą. Siūlome CO₂-ekvivalento mokestį visoje tiekimo grandinėje — paverčiant ekologinę žalą ekonominiu spaudimu ir perskirstant pajamas žmonių apsaugai.",
    hero_btn_primary: "Sužinok, kaip tai veikia ↓",
    hero_btn_secondary: "Prisijunk prie judėjimo",
    how_label: "01 — Mechanizmas",
    how_title: "Mokestis kiekviename etape",
    how_desc: "CO₂-ekvivalento mokesčiai taikomi prieš srovę kiekviename tiekimo grandinės taške. Bendra kaina kaupiasi galutinėje kainoje — natūraliai brangindama didelių išmetimų produktus.",
    stage1_title: "Gavyba",
    stage1_desc: "Žaliavų kasimas, naftos gręžimas, derliaus nuėmimas",
    stage2_title: "Gamyba",
    stage2_desc: "Pramoninė gamyba, rafinavimas, apdorojimas",
    stage3_title: "Transportas",
    stage3_desc: "Laivyba, krovinių pervežimas, logistika",
    stage4_title: "Mažmeninė prekyba &amp; naudojimas",
    stage4_desc: "Platinimas, vartotojo naudojimo fazė",
    stage5_title: "Šalinimas",
    stage5_desc: "Gyvavimo ciklo pabaiga pagal išplėstinę gamintojo atsakomybę",
    stage_fee: "+ CO₂ mokestis",
    pipeline_result: "Duomenys jau egzistuoja. <strong>Gyvavimo ciklo vertinimai (LCA)</strong> ir produktų anglies pėdsakai apima visą grandinę — nuo gavybos iki šalinimo. Mums nereikia naujo mokslo. Mums reikia politinės valios.",
    manifesto: "Paverskite aplinkos poveikį <em>neišvengiamu ekonominiu spaudimu</em>, tada perskirstykite pinigus, kad visuomenė išliktų stabili, kol rinka priverčiama <em>dekarbonizuotis</em>.",
    principles_label: "02 — Principai",
    principles_title: "Už ką mes pasisakome",
    principles_desc: "Tai ne apie informavimo kampanijas ar savanoriškus įsipareigojimus. Tai apie ekonominių paskatų pertvarkymą iš pagrindų.",
    p1_title: "Kaina, ne sąmoningumas",
    p1_text: "Dešimtmečiai informavimo kampanijų nepalenkė išmetimų kreivės. Kainų signalai keičia elgesį dideliu mastu — automatiškai, universaliai ir nedelsiant.",
    p2_title: "Saugok žmones, ne teršėjus",
    p2_text: "Pajamos skiriamos viešosioms gėrybėms ir minimalioms pajamoms, kad kompensuotų aukštesnes kainas. Jokių subsidijų įmonėms \"tapti žaliomis\". Jei terši — moki. Pinigai saugo piliečius.",
    p3_title: "Socialinė CO₂ kaina",
    p3_text: "Mokestis už toną grindžiamas realia CO₂ daroma žala. Aukštesnė kaina reiškia stipresnį elgesio pokytį — bet taip pat reikalauja stipresnio socialinio perskirstymo, kad tai būtų teisinga.",
    p4_title: "ES masto įgyvendinimas",
    p4_text: "Vien tik nacionalinis įgyvendinimas iškraipo prekybą bendrojoje rinkoje. Tam reikia ES masto koordinavimo — arba kruopščiai suprojektuotų nacionalinių mokesčių, kurie nesukuria nesąžiningų pranašumų.",
    examples_label: "03 — Tikri skaičiai",
    examples_title: "Kaip tai atrodo?",
    examples_desc: "Remiantis esamais gyvavimo ciklo vertinimais ir $100 už toną CO₂-ekvivalento anglies kaina.",
    ex_case: "Atvejo analizė",
    ex_beef: "Jautiena",
    ex_oil: "Žaliavinė nafta",
    ex_lifecycle: "Gyvavimo ciklo išmetimai",
    ex_carbon_price: "Taikoma anglies kaina",
    ex_additional_kg: "Papildoma kaina už kg",
    ex_additional_barrel: "Papildoma kaina už barelį",
    ex_beef_insight: "Apima pašarų gamybą (naftos pagrindu pagamintų trąšų), galvijų metaną, žemės naudojimo pokytį ir perdirbimą. Dauguma išmetimų kyla iš biologijos — ne vien iš energijos sąnaudų.",
    ex_oil_insight: "Reikšmingas poveikis kainai — tačiau išlaidos praskiedžiamos, kai nafta pasiskirsto tarp tūkstančių tolesnių produktų. Didžiausias poveikis tenka koncentruotiems didelių išmetimų procesams, tokiems kaip gyvulininkystė, o ne vien pramoninėms žaliavoms.",
    questions_label: "04 — Sąžiningos spragos",
    questions_title: "Atviri klausimai",
    questions_desc: "Mes neapsimetame, kad turime visus atsakymus. Tai sudėtingos problemos, kurioms spręsti reikia kolektyvinio intelekto.",
    q1: "Kokia tiksli anglies kaina reikalinga, kad prasmingai pakeistų vartotojų ir pramonės elgesį nesukeliant ekonominio šoko?",
    q2: "Kaip užtikrinsime tikslią gyvavimo ciklo apskaitą globaliai, kai tiekimo grandinės apima dešimtis šalių su skirtingais standartais?",
    q3: "Kaip turėtume elgtis su importu iš neatitinkančių šalių? Anglies pasienio koregavimai yra perspektyvūs, bet politiškai ir logistiškai sudėtingi.",
    q4: "Koks yra realistinis kelias į politinį įgyvendinamumą ES struktūrose — ir kaip suformuosime koaliciją tam pasiekti?",
    q5: "Kaip greitai galime pereiti nedestabilizuodami pragyvenimo šaltinių? Kaip atrodo tinkama pusiausvyra tarp skubos ir socialinio stabilumo?",
    join_label: "05 — Veik",
    join_title: "Prisijunk prie judėjimo",
    join_desc: "Šiai idėjai reikia ekonomistų, politikos formuotojų, aktyvistų ir piliečių, kurie tiki, kad kaina — ne kaltė — yra tai, kas keičia pasaulį. Pridėk savo balsą.",
    join_placeholder: "tavo@elpastas.lt",
    join_btn: "Registruotis",
    join_btn_done: "Pridėta ✓",
    join_note: "Jokio brukalų. Naujienos apie politikos pažangą, tyrimus ir veiksmus, kurių galite imtis.",
    footer_mechanism: "Mechanizmas",
    footer_data: "Duomenys",
    calc_label: "03.5 \u2014 Išbandyk pats",
    calc_title: "Įkainok žalą",
    calc_desc: "Pažiūrėk, kiek kasdieniai produktai iš tikrųjų kainuotų, jei aplinkos žala būtų įskaičiuota į kainą.",
    calc_cat_label: "Kategorija",
    calc_prod_label: "Produktas",
    calc_qty_label: "Kiekis",
    calc_unit_label: "Vienetas",
    calc_price_label: "Anglies kaina",
    calc_cat_food: "Maistas ir g\u0117rimai",
    calc_cat_clothing: "Drabu\u017eiai (pagal med\u017eiag\u0105)",
    calc_cat_electronics: "Elektronika (pagal dyd\u012f)",
    calc_cat_travel: "Kelion\u0117s",
    calc_cat_fuel: "Kuras",
    calc_price_50: "$50 / tona",
    calc_price_100: "$100 / tona",
    calc_price_150: "$150 / tona",
    calc_price_200: "$200 / tona",
    calc_eco_label: "Ekosertifikuotas / ekologi\u0161kas \u0161altinis (suma\u017eina \u012fvert\u012f ~15%)",
    calc_result_label: "CO\u2082 p\u0117dsakas",
    calc_sources: "\u0160altiniai: Poore & Nemecek (2018), <a href=\"https://doi.org/10.1126/science.aaq0216\" target=\"_blank\" rel=\"noopener\"><em>Science</em> 360:987</a> (maistas) \u00b7 <a href=\"https://www.gov.uk/government/collections/government-conversion-factors-for-company-reporting\" target=\"_blank\" rel=\"noopener\">UK DEFRA 2023</a> (kuras/skryd\u017eiai) \u00b7 Apple/Levi\u2019s Product Environmental Reports (elektronika/drabu\u017eiai)",
    calc_damage_cost: "\u017ealos kaina",
    calc_eco_note: "(ekosertifikuotas: \u221215%)",
    calc_prod_beef: "Jautiena",
    calc_prod_chicken: "Vi\u0161tiena",
    calc_prod_cheese: "S\u016bris",
    calc_prod_milk: "Pienas (karv\u0117s)",
    calc_prod_rice: "Ry\u017eiai",
    calc_prod_coffee: "Kava (skrudinta)",
    calc_prod_chocolate: "Juodasis \u0161okoladas",
    calc_prod_tomatoes: "Pomidorai",
    calc_prod_potatoes: "Bulv\u0117s",
    calc_prod_eggs: "Kiau\u0161iniai",
    calc_prod_bread: "Duona (kvietin\u0117)",
    calc_prod_cotton_tshirt: "Medviln\u0117 \u2014 Mar\u0161kin\u0117liai (250g)",
    calc_prod_cotton_jeans: "Medviln\u0117 \u2014 D\u017einsai (denim)",
    calc_prod_polyester_shirt: "Poliesteris \u2014 Mar\u0161kiniai",
    calc_prod_polyester_jacket: "Poliesteris \u2014 Striuk\u0117",
    calc_prod_wool_sweater: "Vilna \u2014 Megztinis",
    calc_prod_wool_coat: "Vilna \u2014 Paltas",
    calc_prod_leather_shoes: "Oda \u2014 Batai",
    calc_prod_nylon_sneakers: "Nailonas/Mi\u0161inys \u2014 Sportbačiai",
    calc_prod_smartphone: "Telefono dydis (i\u0161manusis telefonas)",
    calc_prod_tablet: "Plan\u0161et\u0117s dydis (10\u2033)",
    calc_prod_laptop: "Ne\u0161iojamojo dydis (13\u201316\u2033)",
    calc_prod_monitor: "Monitoriaus dydis (24\u201327\u2033)",
    calc_prod_tv: "TV dydis (50\u201365\u2033)",
    calc_prod_desktop: "Stalinis kompiuteris (boksas)",
    calc_prod_flight_short: "Skrydis \u2014 trumpas atstumas (<3val.)",
    calc_prod_flight_long: "Skrydis \u2014 ilgas atstumas (>6val.)",
    calc_prod_car_petrol: "Automobilis \u2014 benzinas (vid.)",
    calc_prod_car_diesel: "Automobilis \u2014 dyzelinas (vid.)",
    calc_prod_train: "Traukinys (\u0161alies viduje)",
    calc_prod_bus: "Autobusas (tolimojo eismo)",
    calc_prod_petrol: "Benzinas",
    calc_prod_diesel: "Dyzelinas",
    calc_prod_natural_gas: "Gamtin\u0117s dujos (\u0161ildymas)",
    calc_prod_electricity_eu: "Elektra (ES vid.)",
    calc_note_beef: "Medianos global\u0117 LCA; diapazonas 20\u2013105 kg CO\u2082e/kg",
    calc_note_chicken: "Apima \u017eem\u0117s naudojim\u0105, pa\u0161arus, perdirbim\u0105",
    calc_note_cheese: "~10 litr\u0173 pieno kg s\u016brio",
    calc_note_milk: "Apima enterin\u0119 fermentacij\u0105 ir \u017eem\u0117s naudojim\u0105",
    calc_note_rice: "Metanas i\u0161 u\u017etvindyt\u0173 lauk\u0173 dominuoja",
    calc_note_coffee: "Diapazonas 3,5\u201328,5; stipriai priklauso nuo \u017eem\u0117s naudojimo",
    calc_note_chocolate: "Auk\u0161tas mi\u0161k\u0173 kirtimo komponentas kakavos tiekimo grandin\u0117je",
    calc_note_tomatoes: "Atviro lauko vert\u0117; \u0161ildomas \u0161iltnamis ~2,1",
    calc_note_potatoes: "Vienas ma\u017eiausiai i\u0161metim\u0173 turintis krakmolingas maistas",
    calc_note_eggs: "~12 kiau\u0161ini\u0173 kg",
    calc_note_bread: "Standartin\u0117 kvietin\u0117 duona",
    calc_note_cotton_tshirt: "Medviln\u0117s auginimas ~pus\u0117 p\u0117dsako",
    calc_note_cotton_jeans: "Visas gyvavimo ciklas: nuo auginimo iki \u0161alinimo",
    calc_note_polyester_shirt: "I\u0161 i\u0161kastinio kuro pagaminta pluo\u0161tas",
    calc_note_polyester_jacket: "Sintetinis u\u017epildas + naftos pagrindu pagamintas apvalkalas",
    calc_note_wool_sweater: "Avi\u0173 metanas + perdirbimas",
    calc_note_wool_coat: "Sunki vilna; auk\u0161tas metanas + da\u017eymo poveikis",
    calc_note_leather_shoes: "Galvij\u0173 auginimas + raugimo chemikalai",
    calc_note_nylon_sneakers: "Mi\u0161rios med\u017eiagos; gamybos dominuojamas",
    calc_note_smartphone: "Gamyba ~80% p\u0117dsako; 3 met\u0173 tarnavimo laikas",
    calc_note_tablet: "Tarp telefono ir ne\u0161iojamojo pagal poveik\u012f",
    calc_note_laptop: "Diapazonas 150\u2013400 kg; priklauso nuo komponent\u0173",
    calc_note_monitor: "Ekrano gamyba + daugiame\u010di\u0173 naudojimas",
    calc_note_tv: "Didelis ekranas + 7 met\u0173 naudojimo faz\u0117s elektra",
    calc_note_desktop: "Didesnis energijos suvartojimas; ilgesnis komponent\u0173 tarnavimo laikas",
    calc_note_flight_short: "Vienam keleiviui, ekonomin\u0117; \u012fskaitant spinduliuot\u0117s poveik\u012f",
    calc_note_flight_long: "Efektyvesnis km ilgesniuose atstumuose",
    calc_note_car_petrol: "Vidutinis Europos bensininis automobilis ~210g CO\u2082/km",
    calc_note_car_diesel: "Šiek tiek mažesnis CO\u2082 km nei benzinas",
    calc_note_train: "Labai skiriasi pagal elektros tinkl\u0105; ES vidurkis",
    calc_note_bus: "Vienam keleiviui; didelis u\u017epildymas numatytas",
    calc_note_petrol: "Well-to-wheel \u012fskaitant prie\u0161srovin\u0119 gavyb\u0105",
    calc_note_diesel: "\u0160iek tiek auk\u0161tesnis litrui nei benzinas",
    calc_note_natural_gas: "Degimas + prie\u0161srovin\u0117 metano nuot\u0117kis",
    calc_note_electricity_eu: "ES elektros tinklo vidurkis; skiriasi pagal \u0161al\u012f",
  },
};
