const TRANS_EAST = {
  pl: {
    nav_logo: "Wyceniaj Szkody",
    nav_how: "Jak to działa",
    nav_principles: "Zasady",
    nav_examples: "Przykłady",
    nav_questions: "Otwarte pytania",
    nav_join: "Dołącz",
    hero_label: "Ramy polityczne dla kryzysu klimatycznego",
    hero_title: "Niech zanieczyszczanie<br><em>kosztuje</em>.",
    hero_subtitle: "Każdy produkt niesie ze sobą ukryty koszt środowiskowy. Proponujemy opłatę za ekwiwalent CO₂ na każdym etapie łańcucha dostaw — przekształcając szkody ekologiczne w presję ekonomiczną i jednocześnie redystrybuując przychody, aby chronić ludzi.",
    hero_btn_primary: "Zobacz, jak to działa ↓",
    hero_btn_secondary: "Dołącz do ruchu",
    how_label: "01 — Mechanizm",
    how_title: "Opłata na każdym etapie",
    how_desc: "Opłaty za ekwiwalent CO₂ są naliczane na każdym etapie łańcucha dostaw. Całkowity koszt kumuluje się w cenie końcowej — sprawiając, że produkty o wysokiej emisji są naturalnie droższe.",
    stage1_title: "Wydobycie",
    stage1_desc: "Wydobycie surowców, odwierty naftowe, pozyskiwanie zasobów",
    stage2_title: "Produkcja",
    stage2_desc: "Wytwarzanie, rafinacja, przetwarzanie",
    stage3_title: "Transport",
    stage3_desc: "Żegluga, fracht, logistyka",
    stage4_title: "Handel i&nbsp;użytkowanie",
    stage4_desc: "Dystrybucja, faza użytkowania przez konsumenta",
    stage5_title: "Utylizacja",
    stage5_desc: "Koniec cyklu życia w ramach rozszerzonej odpowiedzialności producenta",
    stage_fee: "+ opłata CO₂",
    pipeline_result: "Dane już istnieją. <strong>Oceny cyklu życia (LCA)</strong> i ślady węglowe produktów obejmują cały łańcuch — od wydobycia po utylizację. Nie potrzebujemy nowej nauki. Potrzebujemy woli politycznej.",
    manifesto: "Przekształć wpływ na środowisko w <em>nieuniknioną presję ekonomiczną</em>, a następnie redystrybuuj pieniądze, aby utrzymać stabilność społeczną, zmuszając jednocześnie rynek do <em>dekarbonizacji</em>.",
    principles_label: "02 — Zasady",
    principles_title: "Za czym się opowiadamy",
    principles_desc: "Nie chodzi o kampanie uświadamiające ani dobrowolne zobowiązania. Chodzi o przebudowę bodźców ekonomicznych od podstaw.",
    p1_title: "Cena, nie świadomość",
    p1_text: "Dziesięciolecia kampanii uświadamiających nie zmieniły krzywej emisji. Sygnały cenowe zmieniają zachowania na masową skalę — automatycznie, powszechnie i natychmiast.",
    p2_title: "Chrońmy ludzi, nie trucicieli",
    p2_text: "Przychody trafiają na dobra publiczne i dochód minimalny, aby zrekompensować wyższe ceny. Żadnych dotacji dla firm na „zazielenianie się". Jeśli zanieczyszczasz, płacisz. Pieniądze chronią obywateli.",
    p3_title: "Społeczny koszt węgla",
    p3_text: "Opłata za tonę opiera się na rzeczywistych szkodach powodowanych przez CO₂. Wyższa cena oznacza silniejszą zmianę zachowań — ale wymaga też silniejszej redystrybucji społecznej, aby zachować sprawiedliwość.",
    p4_title: "Wdrożenie na poziomie UE",
    p4_text: "Wdrożenie wyłącznie na poziomie krajowym zakłóca handel na jednolitym rynku. Potrzebna jest koordynacja na szczeblu UE — lub starannie zaprojektowane podatki krajowe, które nie tworzą nieuczciwej przewagi.",
    examples_label: "03 — Konkretne liczby",
    examples_title: "Jak to wygląda w praktyce?",
    examples_desc: "Na podstawie istniejących danych z ocen cyklu życia i ceny węgla wynoszącej $100 / ton ekwiwalentu CO₂.",
    ex_case: "Studium przypadku",
    ex_beef: "Wołowina",
    ex_oil: "Ropa naftowa",
    ex_lifecycle: "Emisje w cyklu życia",
    ex_carbon_price: "Zastosowana cena węgla",
    ex_additional_kg: "Dodatkowy koszt za kg",
    ex_additional_barrel: "Dodatkowy koszt za baryłkę",
    ex_beef_insight: "Obejmuje produkcję pasz (nawozy na bazie ropy), metan od bydła, zmianę użytkowania gruntów i przetwórstwo. Większość emisji pochodzi z biologii — nie tylko z nakładów energetycznych.",
    ex_oil_insight: "Znaczący wpływ na cenę — ale koszty rozkładają się, gdy ropa jest dystrybuowana na tysiące produktów pochodnych. Największy wpływ dotyczy skoncentrowanych procesów o wysokiej emisji, jak hodowla zwierząt, a nie samych surowców przemysłowych.",
    questions_label: "04 — Uczciwe luki",
    questions_title: "Otwarte pytania",
    questions_desc: "Nie udajemy, że mamy odpowiedzi na wszystko. Oto trudne problemy, które wymagają zbiorowej inteligencji.",
    q1: "Jaka dokładna cena węgla jest potrzebna, aby w sposób znaczący zmienić zachowania konsumentów i przemysłu, nie wywołując szoku gospodarczego?",
    q2: "Jak egzekwować dokładne rozliczanie cyklu życia na skalę globalną, skoro łańcuchy dostaw obejmują dziesiątki krajów o różnych standardach?",
    q3: "Jak powinniśmy traktować import z krajów niestosujących się do systemu? Graniczne mechanizmy węglowe są obiecujące, ale politycznie i logistycznie złożone.",
    q4: "Jaka jest realistyczna droga do wykonalności politycznej w strukturach UE — i jak zbudować koalicję, by to osiągnąć?",
    q5: "Jak szybko możemy przeprowadzić transformację, nie destabilizując źródeł utrzymania? Jak wygląda właściwa równowaga między pilnością a stabilnością społeczną?",
    join_label: "05 — Działaj",
    join_title: "Dołącz do ruchu",
    join_desc: "Ta idea potrzebuje ekonomistów, decydentów politycznych, aktywistów i obywateli, którzy wierzą, że to cena — nie poczucie winy — zmienia świat. Dołącz swój głos.",
    join_placeholder: "twoj@email.pl",
    join_btn: "Zapisz się",
    join_btn_done: "Dodano ✓",
    join_note: "Żadnego spamu. Informacje o postępach politycznych, badaniach i działaniach, które możesz podjąć.",
    footer_mechanism: "Mechanizm",
    footer_data: "Dane",
  },
  cs: {
    nav_logo: "Oceňte škody",
    nav_how: "Jak to funguje",
    nav_principles: "Principy",
    nav_examples: "Příklady",
    nav_questions: "Otevřené otázky",
    nav_join: "Přidejte se",
    hero_label: "Politický rámec pro klimatickou krizi",
    hero_title: "Ať znečišťování<br><em>stojí</em>.",
    hero_subtitle: "Každý produkt nese skryté environmentální náklady. Navrhujeme poplatek za ekvivalent CO₂ v celém dodavatelském řetězci — přeměňující ekologické škody na ekonomický tlak a zároveň přerozdělující příjmy na ochranu lidí.",
    hero_btn_primary: "Podívejte se, jak to funguje ↓",
    hero_btn_secondary: "Přidejte se k hnutí",
    how_label: "01 — Mechanismus",
    how_title: "Poplatek v každé fázi",
    how_desc: "Poplatky za ekvivalent CO₂ se uplatňují v každém bodě dodavatelského řetězce. Celkové náklady se kumulují do konečné ceny — produkty s vysokými emisemi jsou tak přirozeně dražší.",
    stage1_title: "Těžba",
    stage1_desc: "Těžba surovin, vrtání ropy, sklizeň",
    stage2_title: "Výroba",
    stage2_desc: "Zpracování, rafinace, průmyslová výroba",
    stage3_title: "Doprava",
    stage3_desc: "Lodní přeprava, nákladní doprava, logistika",
    stage4_title: "Prodej a&nbsp;užívání",
    stage4_desc: "Distribuce, fáze spotřebitelského užívání",
    stage5_title: "Likvidace",
    stage5_desc: "Konec životního cyklu v rámci rozšířené odpovědnosti výrobce",
    stage_fee: "+ poplatek CO₂",
    pipeline_result: "Data již existují. <strong>Posouzení životního cyklu (LCA)</strong> a uhlíkové stopy produktů pokrývají celý řetězec — od těžby po likvidaci. Nepotřebujeme novou vědu. Potřebujeme politickou vůli.",
    manifesto: "Přeměňte dopad na životní prostředí v <em>nevyhnutelný ekonomický tlak</em> a poté přerozdělte peníze, aby společnost zůstala stabilní, zatímco trh bude nucen k <em>dekarbonizaci</em>.",
    principles_label: "02 — Principy",
    principles_title: "Za čím stojíme",
    principles_desc: "Nejde o osvětové kampaně ani dobrovolné závazky. Jde o přestavbu ekonomických pobídek od základů.",
    p1_title: "Cena, nikoli osvěta",
    p1_text: "Desetiletí osvětových kampaní nezměnila křivku emisí. Cenové signály mění chování ve velkém měřítku — automaticky, univerzálně a okamžitě.",
    p2_title: "Chraňme lidi, ne znečišťovatele",
    p2_text: "Příjmy směřují na veřejné statky a minimální příjem k vyrovnání vyšších cen. Žádné dotace firmám na „ekologizaci". Kdo znečišťuje, platí. Peníze chrání občany.",
    p3_title: "Společenské náklady uhlíku",
    p3_text: "Poplatek za tunu vychází ze skutečných škod způsobených CO₂. Vyšší cena znamená silnější změnu chování — ale také vyžaduje silnější sociální přerozdělování, aby to zůstalo spravedlivé.",
    p4_title: "Celoevropská implementace",
    p4_text: "Implementace pouze na národní úrovni narušuje obchod na jednotném trhu. Je zapotřebí celoevropská koordinace — nebo pečlivě navržené národní daně, které nevytvářejí nespravedlivé výhody.",
    examples_label: "03 — Reálná čísla",
    examples_title: "Jak to vypadá v praxi?",
    examples_desc: "Na základě existujících dat z posouzení životního cyklu a ceny uhlíku $100 / ton ekvivalentu CO₂.",
    ex_case: "Případová studie",
    ex_beef: "Hovězí maso",
    ex_oil: "Ropa",
    ex_lifecycle: "Emise za životní cyklus",
    ex_carbon_price: "Uplatněná cena uhlíku",
    ex_additional_kg: "Dodatečné náklady na kg",
    ex_additional_barrel: "Dodatečné náklady na barel",
    ex_beef_insight: "Zahrnuje výrobu krmiv (ropná hnojiva), metan ze skotu, změnu využití půdy a zpracování. Většina emisí pochází z biologie — nejen z energetických vstupů.",
    ex_oil_insight: "Výrazný dopad na cenu — ale náklady se rozmělňují, když se ropa distribuuje do tisíců navazujících produktů. Největší dopad dopadá na koncentrované procesy s vysokými emisemi, jako je chov dobytka, nikoli jen na průmyslové vstupy.",
    questions_label: "04 — Upřímné mezery",
    questions_title: "Otevřené otázky",
    questions_desc: "Nepředstíráme, že máme všechny odpovědi. Toto jsou obtížné problémy, které vyžadují kolektivní inteligenci.",
    q1: "Jaká přesná cena uhlíku je potřeba k významné změně spotřebitelského a průmyslového chování, aniž by způsobila ekonomický šok?",
    q2: "Jak zajistit přesné celosvětové účtování životního cyklu, když dodavatelské řetězce procházejí desítkami zemí s různými standardy?",
    q3: "Jak bychom měli zacházet s dovozem ze zemí, které systém nedodržují? Uhlíkové hraniční mechanismy jsou slibné, ale politicky a logisticky složité.",
    q4: "Jaká je realistická cesta k politické proveditelnosti v rámci struktur EU — a jak vybudovat koalici, která toho dosáhne?",
    q5: "Jak rychle můžeme provést transformaci, aniž bychom destabilizovali živobytí? Jak vypadá správná rovnováha mezi naléhavostí a společenskou stabilitou?",
    join_label: "05 — Jednejte",
    join_title: "Přidejte se k hnutí",
    join_desc: "Tato myšlenka potřebuje ekonomy, tvůrce politik, aktivisty a občany, kteří věří, že cena — nikoli pocit viny — mění svět. Přidejte svůj hlas.",
    join_placeholder: "vas@email.cz",
    join_btn: "Zaregistrovat se",
    join_btn_done: "Přidáno ✓",
    join_note: "Žádný spam. Informace o pokroku politik, výzkumu a akcích, které můžete podniknout.",
    footer_mechanism: "Mechanismus",
    footer_data: "Data",
  },
  sk: {
    nav_logo: "Oceňte škody",
    nav_how: "Ako to funguje",
    nav_principles: "Princípy",
    nav_examples: "Príklady",
    nav_questions: "Otvorené otázky",
    nav_join: "Pridajte sa",
    hero_label: "Politický rámec pre klimatickú krízu",
    hero_title: "Nech znečisťovanie<br><em>stojí</em>.",
    hero_subtitle: "Každý produkt nesie skryté environmentálne náklady. Navrhujeme poplatok za ekvivalent CO₂ v celom dodávateľskom reťazci — premieňajúc ekologické škody na ekonomický tlak a zároveň prerozdeľujúc príjmy na ochranu ľudí.",
    hero_btn_primary: "Pozrite sa, ako to funguje ↓",
    hero_btn_secondary: "Pridajte sa k hnutiu",
    how_label: "01 — Mechanizmus",
    how_title: "Poplatok v každej fáze",
    how_desc: "Poplatky za ekvivalent CO₂ sa uplatňujú v každom bode dodávateľského reťazca. Celkové náklady sa kumulujú do konečnej ceny — produkty s vysokými emisiami sú tak prirodzene drahšie.",
    stage1_title: "Ťažba",
    stage1_desc: "Ťažba surovín, vŕtanie ropy, zber",
    stage2_title: "Výroba",
    stage2_desc: "Spracovanie, rafinácia, priemyselná výroba",
    stage3_title: "Doprava",
    stage3_desc: "Lodná preprava, nákladná doprava, logistika",
    stage4_title: "Predaj a&nbsp;používanie",
    stage4_desc: "Distribúcia, fáza spotrebiteľského používania",
    stage5_title: "Likvidácia",
    stage5_desc: "Koniec životného cyklu v rámci rozšírenej zodpovednosti výrobcu",
    stage_fee: "+ poplatok CO₂",
    pipeline_result: "Údaje už existujú. <strong>Posúdenia životného cyklu (LCA)</strong> a uhlíkové stopy produktov pokrývajú celý reťazec — od ťažby po likvidáciu. Nepotrebujeme novú vedu. Potrebujeme politickú vôľu.",
    manifesto: "Premeňte vplyv na životné prostredie na <em>neodvrátiteľný ekonomický tlak</em> a potom prerozdeľte peniaze, aby spoločnosť zostala stabilná, zatiaľ čo trh bude nútený k <em>dekarbonizácii</em>.",
    principles_label: "02 — Princípy",
    principles_title: "Za čím stojíme",
    principles_desc: "Nejde o osvetové kampane ani dobrovoľné záväzky. Ide o prestavbu ekonomických stimulov od základov.",
    p1_title: "Cena, nie osveta",
    p1_text: "Desaťročia osvetových kampaní nezmenili krivku emisií. Cenové signály menia správanie vo veľkom meradle — automaticky, univerzálne a okamžite.",
    p2_title: "Chráňme ľudí, nie znečisťovateľov",
    p2_text: "Príjmy smerujú na verejné statky a minimálny príjem na kompenzáciu vyšších cien. Žiadne dotácie pre firmy na „ekologizáciu". Kto znečisťuje, platí. Peniaze chránia občanov.",
    p3_title: "Spoločenské náklady uhlíka",
    p3_text: "Poplatok za tonu vychádza zo skutočných škôd spôsobených CO₂. Vyššia cena znamená silnejšiu zmenu správania — ale vyžaduje aj silnejšie sociálne prerozdeľovanie, aby to zostalo spravodlivé.",
    p4_title: "Celoeurópska implementácia",
    p4_text: "Implementácia iba na národnej úrovni narúša obchod na jednotnom trhu. Je potrebná celoeurópska koordinácia — alebo starostlivo navrhnuté národné dane, ktoré nevytvárajú nespravodlivé výhody.",
    examples_label: "03 — Reálne čísla",
    examples_title: "Ako to vyzerá v praxi?",
    examples_desc: "Na základe existujúcich údajov z posúdení životného cyklu a ceny uhlíka $100 / ton ekvivalentu CO₂.",
    ex_case: "Prípadová štúdia",
    ex_beef: "Hovädzie mäso",
    ex_oil: "Ropa",
    ex_lifecycle: "Emisie za životný cyklus",
    ex_carbon_price: "Uplatnená cena uhlíka",
    ex_additional_kg: "Dodatočné náklady na kg",
    ex_additional_barrel: "Dodatočné náklady na barel",
    ex_beef_insight: "Zahŕňa výrobu krmív (ropné hnojivá), metán z dobytka, zmenu využívania pôdy a spracovanie. Väčšina emisií pochádza z biológie — nielen z energetických vstupov.",
    ex_oil_insight: "Výrazný vplyv na cenu — ale náklady sa rozkladajú, keď sa ropa distribuuje do tisícov nadväzujúcich produktov. Najväčší vplyv dopadá na koncentrované procesy s vysokými emisiami, ako je chov dobytka, nie len na priemyselné vstupy.",
    questions_label: "04 — Úprimné medzery",
    questions_title: "Otvorené otázky",
    questions_desc: "Nepredstierame, že máme všetky odpovede. Toto sú ťažké problémy, ktoré vyžadujú kolektívnu inteligenciu.",
    q1: "Aká presná cena uhlíka je potrebná na významnú zmenu spotrebiteľského a priemyselného správania bez vyvolania ekonomického šoku?",
    q2: "Ako presadiť presné celosvetové účtovanie životného cyklu, keď dodávateľské reťazce prechádzajú desiatkami krajín s rôznymi štandardmi?",
    q3: "Ako by sme mali zaobchádzať s dovozom z krajín, ktoré systém nedodržiavajú? Uhlíkové hraničné mechanizmy sú sľubné, ale politicky a logisticky zložité.",
    q4: "Aká je realistická cesta k politickej uskutočniteľnosti v rámci štruktúr EÚ — a ako vybudovať koalíciu, ktorá to dosiahne?",
    q5: "Ako rýchlo môžeme uskutočniť transformáciu bez destabilizácie živobytia? Ako vyzerá správna rovnováha medzi naliehavosťou a spoločenskou stabilitou?",
    join_label: "05 — Konajte",
    join_title: "Pridajte sa k hnutiu",
    join_desc: "Táto myšlienka potrebuje ekonómov, tvorcov politík, aktivistov a občanov, ktorí veria, že cena — nie pocit viny — mení svet. Pridajte svoj hlas.",
    join_placeholder: "vas@email.sk",
    join_btn: "Zaregistrovať sa",
    join_btn_done: "Pridané ✓",
    join_note: "Žiadny spam. Informácie o pokroku politík, výskume a akciách, ktoré môžete podniknúť.",
    footer_mechanism: "Mechanizmus",
    footer_data: "Údaje",
  },
  hu: {
    nav_logo: "Árazd be a kárt",
    nav_how: "Hogyan működik",
    nav_principles: "Alapelvek",
    nav_examples: "Példák",
    nav_questions: "Nyitott kérdések",
    nav_join: "Csatlakozz",
    hero_label: "Szakpolitikai keretrendszer a klímaválságra",
    hero_title: "Legyen a szennyezés<br><em>drága</em>.",
    hero_subtitle: "Minden termék rejtett környezeti költséget hordoz. CO₂-egyenérték-díjat javasolunk az ellátási lánc minden szakaszára — az ökológiai károkat gazdasági nyomássá alakítva, miközben a bevételeket az emberek védelmére osztjuk újra.",
    hero_btn_primary: "Nézd meg, hogyan működik ↓",
    hero_btn_secondary: "Csatlakozz a mozgalomhoz",
    how_label: "01 — Mechanizmus",
    how_title: "Díj minden szakaszban",
    how_desc: "A CO₂-egyenérték-díjak az ellátási lánc minden pontján érvényesülnek. Az összköltség beépül a végső árba — így a magas kibocsátású termékek természetesen drágábbak lesznek.",
    stage1_title: "Kitermelés",
    stage1_desc: "Nyersanyag-bányászat, olajfúrás, betakarítás",
    stage2_title: "Gyártás",
    stage2_desc: "Előállítás, finomítás, feldolgozás",
    stage3_title: "Szállítás",
    stage3_desc: "Hajózás, áruszállítás, logisztika",
    stage4_title: "Kereskedelem és&nbsp;használat",
    stage4_desc: "Forgalmazás, fogyasztói használati fázis",
    stage5_title: "Ártalmatlanítás",
    stage5_desc: "Életciklus vége a kiterjesztett gyártói felelősség keretében",
    stage_fee: "+ CO₂-díj",
    pipeline_result: "Az adatok már rendelkezésre állnak. Az <strong>életciklus-értékelések (LCA)</strong> és a termékek szénlábnyomai lefedik a teljes láncot — a kitermeléstől az ártalmatlanításig. Nem új tudományra van szükségünk. Politikai akaratra van szükségünk.",
    manifesto: "Alakítsd a környezeti hatást <em>elkerülhetetlen gazdasági nyomássá</em>, majd oszd újra a pénzt, hogy a társadalom stabil maradjon, miközben a piacot <em>dekarbonizációra</em> kényszeríted.",
    principles_label: "02 — Alapelvek",
    principles_title: "Amiért kiállunk",
    principles_desc: "Ez nem tudatosságnövelő kampányokról vagy önkéntes vállalásokról szól. A gazdasági ösztönzők alapjainak újratervezéséről van szó.",
    p1_title: "Ár, nem tudatosság",
    p1_text: "Évtizedes tudatosságnövelő kampányok sem változtatták meg a kibocsátási görbét. Az árjelzések nagy léptékben változtatnak viselkedést — automatikusan, egyetemlegesen és azonnal.",
    p2_title: "Védjük az embereket, ne a szennyezőket",
    p2_text: "A bevételek közjavakra és minimáljövedelemre fordítódnak a magasabb árak kompenzálására. Nincs szubvenció vállalatoknak a „zöldülésre". Ha szennyezel, fizetsz. A pénz az állampolgárokat védi.",
    p3_title: "A szén társadalmi költsége",
    p3_text: "A tonnánkénti díj a CO₂ által okozott valós káron alapul. A magasabb ár erősebb viselkedésváltozást jelent — de erősebb társadalmi újraelosztást is megkövetel a méltányosság érdekében.",
    p4_title: "EU-szintű bevezetés",
    p4_text: "A kizárólag nemzeti szintű bevezetés torzítja a kereskedelmet az egységes piacon. EU-szintű koordinációra van szükség — vagy gondosan megtervezett nemzeti adókra, amelyek nem teremtenek tisztességtelen előnyt.",
    examples_label: "03 — Valós számok",
    examples_title: "Hogyan néz ez ki a gyakorlatban?",
    examples_desc: "Meglévő életciklus-értékelési adatok és $100 / ton CO₂-egyenérték szénár alapján.",
    ex_case: "Esettanulmány",
    ex_beef: "Marhahús",
    ex_oil: "Nyersolaj",
    ex_lifecycle: "Életciklus-kibocsátás",
    ex_carbon_price: "Alkalmazott szénár",
    ex_additional_kg: "Többletköltség kg-onként",
    ex_additional_barrel: "Többletköltség hordónként",
    ex_beef_insight: "Tartalmazza a takarmánytermelést (kőolaj alapú műtrágyák), a szarvasmarhák metánkibocsátását, a földhasználat-változást és a feldolgozást. A kibocsátás nagy része biológiai eredetű — nem csupán energetikai.",
    ex_oil_insight: "Jelentős hatás az árra — de a költségek eloszlanak, ahogy az olaj ezer és ezer továbbfeldolgozott termékbe kerül. A legnagyobb hatás a koncentrált, magas kibocsátású folyamatokra, például az állattenyésztésre esik, nem csupán az ipari alapanyagokra.",
    questions_label: "04 — Őszinte hiányosságok",
    questions_title: "Nyitott kérdések",
    questions_desc: "Nem teszünk úgy, mintha minden válasszal rendelkeznénk. Ezek azok a nehéz problémák, amelyek megoldásához kollektív intelligenciára van szükség.",
    q1: "Pontosan mekkora szénár szükséges ahhoz, hogy érdemben megváltoztassa a fogyasztói és ipari viselkedést gazdasági sokk kiváltása nélkül?",
    q2: "Hogyan kényszeríthetjük ki a pontos életciklus-elszámolást globálisan, amikor az ellátási láncok különböző szabványokkal rendelkező tucatnyi országon átívelnek?",
    q3: "Hogyan kezeljük a nem megfelelő országokból származó importot? A szénhatár-kiigazítások ígéretesek, de politikailag és logisztikailag összetettek.",
    q4: "Mi a realista út a politikai megvalósíthatósághoz az EU struktúráin belül — és hogyan építjük ki az ehhez szükséges koalíciót?",
    q5: "Milyen gyorsan hajthatjuk végre az átmenetet a megélhetések destabilizálása nélkül? Hogyan néz ki a helyes egyensúly a sürgősség és a társadalmi stabilitás között?",
    join_label: "05 — Cselekedj",
    join_title: "Csatlakozz a mozgalomhoz",
    join_desc: "Ennek az ötletnek közgazdászokra, döntéshozókra, aktivistákra és állampolgárokra van szüksége, akik hisznek abban, hogy az ár — nem a bűntudat — változtatja meg a világot. Add hozzá a hangodat.",
    join_placeholder: "neved@email.hu",
    join_btn: "Feliratkozás",
    join_btn_done: "Hozzáadva ✓",
    join_note: "Nincs spam. Tájékoztatás a szakpolitikai haladásról, kutatásokról és a lehetséges lépésekről.",
    footer_mechanism: "Mechanizmus",
    footer_data: "Adatok",
  },
  ro: {
    nav_logo: "Prețul pagubelor",
    nav_how: "Cum funcționează",
    nav_principles: "Principii",
    nav_examples: "Exemple",
    nav_questions: "Întrebări deschise",
    nav_join: "Alătură-te",
    hero_label: "Un cadru politic pentru criza climatică",
    hero_title: "Fă poluarea<br><em>costisitoare</em>.",
    hero_subtitle: "Fiecare produs poartă un cost de mediu ascuns. Propunem o taxă pe echivalentul CO₂ de-a lungul întregului lanț de aprovizionare — transformând daunele ecologice în presiune economică și redistribuind veniturile pentru a proteja oamenii.",
    hero_btn_primary: "Vezi cum funcționează ↓",
    hero_btn_secondary: "Alătură-te mișcării",
    how_label: "01 — Mecanism",
    how_title: "O taxă în fiecare etapă",
    how_desc: "Taxele pe echivalentul CO₂ se aplică în fiecare punct al lanțului de aprovizionare. Costul total se acumulează în prețul final — făcând produsele cu emisii ridicate în mod natural mai scumpe.",
    stage1_title: "Extracție",
    stage1_desc: "Extragerea materiilor prime, forarea petrolului, recoltarea",
    stage2_title: "Producție",
    stage2_desc: "Fabricare, rafinare, prelucrare",
    stage3_title: "Transport",
    stage3_desc: "Expediție, transport de marfă, logistică",
    stage4_title: "Comerț și&nbsp;utilizare",
    stage4_desc: "Distribuție, faza de utilizare de către consumator",
    stage5_title: "Eliminare",
    stage5_desc: "Sfârșitul ciclului de viață prin responsabilitatea extinsă a producătorului",
    stage_fee: "+ taxă CO₂",
    pipeline_result: "Datele există deja. <strong>Evaluările ciclului de viață (LCA)</strong> și amprentele de carbon ale produselor acoperă întregul lanț — de la extracție până la eliminare. Nu avem nevoie de știință nouă. Avem nevoie de voință politică.",
    manifesto: "Transformă impactul asupra mediului în <em>presiune economică inevitabilă</em>, apoi redistribuie banii pentru a menține societatea stabilă, forțând totodată piața să se <em>decarbonizeze</em>.",
    principles_label: "02 — Principii",
    principles_title: "Ce susținem",
    principles_desc: "Nu este vorba despre campanii de conștientizare sau angajamente voluntare. Este vorba despre reproiectarea stimulentelor economice de la zero.",
    p1_title: "Preț, nu conștientizare",
    p1_text: "Decenii de campanii de conștientizare nu au modificat curba emisiilor. Semnalele de preț schimbă comportamentul la scară largă — automat, universal și imediat.",
    p2_title: "Protejăm oamenii, nu poluatorii",
    p2_text: "Veniturile sunt direcționate către bunuri publice și un venit minim pentru a compensa prețurile mai mari. Nicio subvenție pentru companii să „devină verzi". Dacă poluezi, plătești. Banii îi protejează pe cetățeni.",
    p3_title: "Costul social al carbonului",
    p3_text: "Taxa pe tonă se bazează pe daunele reale cauzate de CO₂. Un preț mai mare înseamnă o schimbare comportamentală mai puternică — dar necesită și o redistribuire socială mai puternică pentru a rămâne echitabil.",
    p4_title: "Implementare la nivel european",
    p4_text: "Implementarea doar la nivel național distorsionează comerțul pe piața unică. Este nevoie de coordonare la nivelul UE — sau de taxe naționale concepute cu grijă care să nu creeze avantaje neloiale.",
    examples_label: "03 — Cifre reale",
    examples_title: "Cum arată în practică?",
    examples_desc: "Pe baza datelor existente din evaluările ciclului de viață și a unui preț al carbonului de $100 / ton de echivalent CO₂.",
    ex_case: "Studiu de caz",
    ex_beef: "Carne de vită",
    ex_oil: "Petrol brut",
    ex_lifecycle: "Emisii pe ciclul de viață",
    ex_carbon_price: "Preț de carbon aplicat",
    ex_additional_kg: "Cost suplimentar per kg",
    ex_additional_barrel: "Cost suplimentar per baril",
    ex_beef_insight: "Include producția de furaje (îngrășăminte pe bază de petrol), metanul de la bovine, schimbarea utilizării terenurilor și prelucrarea. Majoritatea emisiilor provin din biologie — nu doar din inputuri energetice.",
    ex_oil_insight: "Impact semnificativ asupra prețului — dar costurile se diluează pe măsură ce petrolul este distribuit în mii de produse derivate. Cel mai mare impact cade asupra proceselor concentrate cu emisii ridicate, precum creșterea animalelor, nu doar asupra inputurilor industriale.",
    questions_label: "04 — Lacune oneste",
    questions_title: "Întrebări deschise",
    questions_desc: "Nu pretindem că avem toate răspunsurile. Acestea sunt problemele dificile care necesită inteligență colectivă.",
    q1: "Ce preț exact al carbonului este necesar pentru a schimba semnificativ comportamentul consumatorilor și al industriei fără a provoca un șoc economic?",
    q2: "Cum impunem o contabilizare precisă a ciclului de viață la nivel global, când lanțurile de aprovizionare traversează zeci de țări cu standarde diferite?",
    q3: "Cum ar trebui să gestionăm importurile din țări care nu respectă sistemul? Ajustările de frontieră pentru carbon sunt promițătoare, dar complexe din punct de vedere politic și logistic.",
    q4: "Care este calea realistă către fezabilitatea politică în cadrul structurilor UE — și cum construim coaliția necesară?",
    q5: "Cât de repede putem realiza tranziția fără a destabiliza mijloacele de trai? Cum arată echilibrul corect între urgență și stabilitate socială?",
    join_label: "05 — Acționează",
    join_title: "Alătură-te mișcării",
    join_desc: "Această idee are nevoie de economiști, factori de decizie, activiști și cetățeni care cred că prețul — nu vinovăția — schimbă lumea. Adaugă-ți vocea.",
    join_placeholder: "adresa@email.ro",
    join_btn: "Înscrie-te",
    join_btn_done: "Adăugat ✓",
    join_note: "Fără spam. Actualizări despre progresul politicilor, cercetare și acțiuni pe care le poți întreprinde.",
    footer_mechanism: "Mecanism",
    footer_data: "Date",
  },
  sl: {
    nav_logo: "Določi ceno škode",
    nav_how: "Kako deluje",
    nav_principles: "Načela",
    nav_examples: "Primeri",
    nav_questions: "Odprta vprašanja",
    nav_join: "Pridruži se",
    hero_label: "Politični okvir za podnebno krizo",
    hero_title: "Naj onesnaževanje<br><em>stane</em>.",
    hero_subtitle: "Vsak izdelek nosi skrite okoljske stroške. Predlagamo dajatev na ekvivalent CO₂ vzdolž celotne dobavne verige — ekološko škodo spreminjamo v gospodarski pritisk, hkrati pa prihodke prerazporejamo za zaščito ljudi.",
    hero_btn_primary: "Poglej, kako deluje ↓",
    hero_btn_secondary: "Pridruži se gibanju",
    how_label: "01 — Mehanizem",
    how_title: "Dajatev na vsaki stopnji",
    how_desc: "Dajatve na ekvivalent CO₂ se zaračunavajo na vsaki točki dobavne verige. Skupni strošek se kopiči v končni ceni — izdelki z visokimi izpusti so tako naravno dražji.",
    stage1_title: "Pridobivanje",
    stage1_desc: "Rudarjenje surovin, črpanje nafte, žetev",
    stage2_title: "Proizvodnja",
    stage2_desc: "Izdelava, rafiniranje, predelava",
    stage3_title: "Prevoz",
    stage3_desc: "Ladijski prevoz, tovorni promet, logistika",
    stage4_title: "Prodaja in&nbsp;uporaba",
    stage4_desc: "Distribucija, faza potrošniške uporabe",
    stage5_title: "Odstranjevanje",
    stage5_desc: "Konec življenjskega cikla v okviru razširjene odgovornosti proizvajalca",
    stage_fee: "+ dajatev CO₂",
    pipeline_result: "Podatki že obstajajo. <strong>Ocene življenjskega cikla (LCA)</strong> in ogljični odtisi izdelkov pokrivajo celotno verigo — od pridobivanja do odstranjevanja. Ne potrebujemo nove znanosti. Potrebujemo politično voljo.",
    manifesto: "Pretvori okoljski vpliv v <em>neizogiben gospodarski pritisk</em>, nato prerazdeli denar, da bo družba ostala stabilna, medtem ko trg prisiljen v <em>dekarbonizacijo</em>.",
    principles_label: "02 — Načela",
    principles_title: "Za kaj se zavzemamo",
    principles_desc: "Ne gre za ozaveščevalne kampanje ali prostovoljne zaveze. Gre za preoblikovanje gospodarskih spodbud od temeljev.",
    p1_title: "Cena, ne ozaveščanje",
    p1_text: "Desetletja ozaveščevalnih kampanj niso spremenila krivulje izpustov. Cenovni signali spreminjajo vedenje v velikem obsegu — samodejno, univerzalno in takoj.",
    p2_title: "Zaščitimo ljudi, ne onesnaževalce",
    p2_text: "Prihodki se namenijo javnim dobrinam in minimalnemu dohodku za izravnavo višjih cen. Brez subvencij podjetjem za „ozelenitev". Kdor onesnažuje, plača. Denar ščiti državljane.",
    p3_title: "Družbeni stroški ogljika",
    p3_text: "Dajatev na tono temelji na dejanski škodi, ki jo povzroča CO₂. Višja cena pomeni močnejšo spremembo vedenja — a zahteva tudi močnejšo družbeno prerazporeditev, da ostane pravična.",
    p4_title: "Uvedba na ravni EU",
    p4_text: "Zgolj nacionalna uvedba izkrivlja trgovino na enotnem trgu. Potrebna je koordinacija na ravni EU — ali skrbno zasnovani nacionalni davki, ki ne ustvarjajo nepoštene prednosti.",
    examples_label: "03 — Dejanske številke",
    examples_title: "Kako to izgleda v praksi?",
    examples_desc: "Na podlagi obstoječih podatkov iz ocen življenjskega cikla in cene ogljika $100 / ton ekvivalenta CO₂.",
    ex_case: "Študija primera",
    ex_beef: "Goveje meso",
    ex_oil: "Surova nafta",
    ex_lifecycle: "Izpusti v življenjskem ciklu",
    ex_carbon_price: "Upoštevana cena ogljika",
    ex_additional_kg: "Dodatni strošek na kg",
    ex_additional_barrel: "Dodatni strošek na sodček",
    ex_beef_insight: "Vključuje pridelavo krme (gnojila na osnovi nafte), metan goveda, spremembo rabe zemljišč in predelavo. Večina izpustov izvira iz biologije — ne le iz energetskih vnosov.",
    ex_oil_insight: "Znaten vpliv na ceno — a stroški se razpršijo, ko se nafta razdeli na tisoče nadaljnjih izdelkov. Največji vpliv pade na koncentrirane procese z visokimi izpusti, kot je živinoreja, ne le na industrijske vhodne surovine.",
    questions_label: "04 — Iskrene vrzeli",
    questions_title: "Odprta vprašanja",
    questions_desc: "Ne pretvarjamo se, da imamo vse odgovore. To so težki problemi, ki zahtevajo kolektivno inteligenco.",
    q1: "Kakšna natančna cena ogljika je potrebna, da smiselno spremeni vedenje potrošnikov in industrije brez povzročanja gospodarskega šoka?",
    q2: "Kako uveljaviti natančno globalno obračunavanje življenjskega cikla, ko dobavne verige segajo čez desetine držav z različnimi standardi?",
    q3: "Kako naj obravnavamo uvoz iz držav, ki sistema ne spoštujejo? Ogljične mejne prilagoditve so obetavne, a politično in logistično zapletene.",
    q4: "Kakšna je realistična pot do politične izvedljivosti znotraj struktur EU — in kako zgraditi koalicijo za to?",
    q5: "Kako hitro lahko izvedemo prehod, ne da bi destabilizirali preživetje? Kako izgleda pravo ravnovesje med nujnostjo in družbeno stabilnostjo?",
    join_label: "05 — Ukrepaj",
    join_title: "Pridruži se gibanju",
    join_desc: "Ta ideja potrebuje ekonomiste, oblikovalce politik, aktiviste in državljane, ki verjamejo, da cena — ne krivda — spreminja svet. Dodaj svoj glas.",
    join_placeholder: "tvoj@email.si",
    join_btn: "Prijavi se",
    join_btn_done: "Dodano ✓",
    join_note: "Brez neželene pošte. Obvestila o napredku politik, raziskavah in ukrepih, ki jih lahko izvedeš.",
    footer_mechanism: "Mehanizem",
    footer_data: "Podatki",
  },
  hr: {
    nav_logo: "Odredi cijenu štete",
    nav_how: "Kako funkcionira",
    nav_principles: "Načela",
    nav_examples: "Primjeri",
    nav_questions: "Otvorena pitanja",
    nav_join: "Pridruži se",
    hero_label: "Politički okvir za klimatsku krizu",
    hero_title: "Neka zagađivanje<br><em>košta</em>.",
    hero_subtitle: "Svaki proizvod nosi skriveni okolišni trošak. Predlažemo naknadu za ekvivalent CO₂ duž cijelog opskrbnog lanca — pretvarajući ekološku štetu u ekonomski pritisak, uz preraspodjelu prihoda radi zaštite ljudi.",
    hero_btn_primary: "Pogledaj kako funkcionira ↓",
    hero_btn_secondary: "Pridruži se pokretu",
    how_label: "01 — Mehanizam",
    how_title: "Naknada u svakoj fazi",
    how_desc: "Naknade za ekvivalent CO₂ primjenjuju se u svakoj točki opskrbnog lanca. Ukupni trošak se akumulira u konačnoj cijeni — čineći proizvode s visokim emisijama prirodno skupljima.",
    stage1_title: "Vađenje",
    stage1_desc: "Rudarenje sirovina, bušenje nafte, žetva",
    stage2_title: "Proizvodnja",
    stage2_desc: "Prerađivanje, rafiniranje, obrada",
    stage3_title: "Prijevoz",
    stage3_desc: "Brodski prijevoz, teretni promet, logistika",
    stage4_title: "Prodaja i&nbsp;korištenje",
    stage4_desc: "Distribucija, faza potrošačkog korištenja",
    stage5_title: "Zbrinjavanje",
    stage5_desc: "Kraj životnog ciklusa u okviru proširene odgovornosti proizvođača",
    stage_fee: "+ naknada CO₂",
    pipeline_result: "Podaci već postoje. <strong>Procjene životnog ciklusa (LCA)</strong> i ugljični otisci proizvoda pokrivaju cijeli lanac — od vađenja do zbrinjavanja. Ne trebamo novu znanost. Trebamo političku volju.",
    manifesto: "Pretvori utjecaj na okoliš u <em>neizbježan ekonomski pritisak</em>, zatim preraspodjeli novac kako bi društvo ostalo stabilno dok se tržište prisiljava na <em>dekarbonizaciju</em>.",
    principles_label: "02 — Načela",
    principles_title: "Za što se zalažemo",
    principles_desc: "Ovo nije o kampanjama podizanja svijesti niti o dobrovoljnim obvezama. Radi se o preoblikovanju ekonomskih poticaja iz temelja.",
    p1_title: "Cijena, ne svijest",
    p1_text: "Desetljeća kampanja podizanja svijesti nisu promijenila krivulju emisija. Cjenovni signali mijenjaju ponašanje na velikoj razini — automatski, univerzalno i odmah.",
    p2_title: "Zaštitimo ljude, ne zagađivače",
    p2_text: "Prihodi idu za javna dobra i minimalni dohodak radi kompenzacije viših cijena. Nema subvencija za tvrtke da „postanu zelene". Tko zagađuje, plaća. Novac štiti građane.",
    p3_title: "Društveni trošak ugljika",
    p3_text: "Naknada po toni temelji se na stvarnoj šteti koju uzrokuje CO₂. Viša cijena znači snažniju promjenu ponašanja — ali zahtijeva i snažniju socijalnu preraspodjelu kako bi sustav ostao pravedan.",
    p4_title: "Provedba na razini EU",
    p4_text: "Provedba samo na nacionalnoj razini iskrivljuje trgovinu na jedinstvenom tržištu. Potrebna je koordinacija na razini EU — ili pažljivo osmišljeni nacionalni porezi koji ne stvaraju nepoštene prednosti.",
    examples_label: "03 — Stvarni brojevi",
    examples_title: "Kako to izgleda u praksi?",
    examples_desc: "Na temelju postojećih podataka iz procjena životnog ciklusa i cijene ugljika od $100 / ton ekvivalenta CO₂.",
    ex_case: "Studija slučaja",
    ex_beef: "Govedina",
    ex_oil: "Sirova nafta",
    ex_lifecycle: "Emisije u životnom ciklusu",
    ex_carbon_price: "Primijenjena cijena ugljika",
    ex_additional_kg: "Dodatni trošak po kg",
    ex_additional_barrel: "Dodatni trošak po barelu",
    ex_beef_insight: "Uključuje proizvodnju stočne hrane (gnojiva na bazi nafte), metan goveda, promjenu korištenja zemljišta i preradu. Većina emisija potječe iz biologije — ne samo iz energetskih inputa.",
    ex_oil_insight: "Značajan utjecaj na cijenu — ali troškovi se razrjeđuju kad se nafta distribuira u tisuće nizvodnih proizvoda. Najveći utjecaj pada na koncentrirane procese s visokim emisijama poput stočarstva, a ne samo na industrijske inpute.",
    questions_label: "04 — Iskrene praznine",
    questions_title: "Otvorena pitanja",
    questions_desc: "Ne pretvaramo se da imamo sve odgovore. Ovo su teški problemi koji zahtijevaju kolektivnu inteligenciju.",
    q1: "Koja je točna cijena ugljika potrebna za značajnu promjenu ponašanja potrošača i industrije bez izazivanja gospodarskog šoka?",
    q2: "Kako osigurati točno globalno praćenje životnog ciklusa kad opskrbni lanci prolaze kroz desetke zemalja s različitim standardima?",
    q3: "Kako bismo trebali postupati s uvozom iz zemalja koje ne poštuju sustav? Ugljične granične prilagodbe su obećavajuće, ali politički i logistički složene.",
    q4: "Koji je realan put do političke izvedivosti unutar struktura EU — i kako izgraditi koaliciju koja će to postići?",
    q5: "Koliko brzo možemo provesti tranziciju bez destabilizacije sredstava za život? Kako izgleda prava ravnoteža između hitnosti i društvene stabilnosti?",
    join_label: "05 — Djeluj",
    join_title: "Pridruži se pokretu",
    join_desc: "Ova ideja treba ekonomiste, kreatore politika, aktiviste i građane koji vjeruju da cijena — ne krivnja — mijenja svijet. Dodaj svoj glas.",
    join_placeholder: "tvoj@email.hr",
    join_btn: "Prijavi se",
    join_btn_done: "Dodano ✓",
    join_note: "Bez neželjene pošte. Obavijesti o napretku politika, istraživanjima i akcijama koje možeš poduzeti.",
    footer_mechanism: "Mehanizam",
    footer_data: "Podaci",
  },
};
