const TRANS_SOUTH = {
  bg: {
    nav_logo: "Оцени щетите",
    nav_how: "Как работи",
    nav_principles: "Принципи",
    nav_examples: "Примери",
    nav_questions: "Отворени въпроси",
    nav_join: "Присъедини се",
    hero_label: "Политическа рамка за климатичната криза",
    hero_title: "Направи замърсяването<br><em>скъпо</em>.",
    hero_subtitle: "Всеки продукт носи скрита екологична цена. Ние предлагаме такса за CO₂-еквивалент по цялата верига на доставки — превръщайки екологичните щети в икономически натиск, като същевременно преразпределяме приходите за защита на хората.",
    hero_btn_primary: "Вижте как работи ↓",
    hero_btn_secondary: "Присъединете се към движението",
    how_label: "01 — Механизъм",
    how_title: "Такса на всеки етап",
    how_desc: "Таксите за CO₂-еквивалент се прилагат нагоре по веригата, на всяка точка от веригата на доставки. Общата стойност се натрупва в крайната цена — правейки продуктите с високи емисии естествено по-скъпи.",
    stage1_title: "Добив",
    stage1_desc: "Добив на суровини, нефтен добив, прибиране на реколта",
    stage2_title: "Производство",
    stage2_desc: "Преработка, рафиниране, обработка",
    stage3_title: "Транспорт",
    stage3_desc: "Корабоплаване, товарен превоз, логистика",
    stage4_title: "Търговия &amp; Употреба",
    stage4_desc: "Дистрибуция, фаза на потребителска употреба",
    stage5_title: "Обезвреждане",
    stage5_desc: "Край на жизнения цикъл чрез разширена отговорност на производителя",
    stage_fee: "+ CO₂ такса",
    pipeline_result: "Данните вече съществуват. <strong>Оценките на жизнения цикъл (LCA)</strong> и въглеродните отпечатъци на продуктите обхващат цялата верига — от добива до обезвреждането. Не се нуждаем от нова наука. Нуждаем се от политическа воля.",
    manifesto: "Превърнете въздействието върху околната среда в <em>неизбежен икономически натиск</em>, след което преразпределете средствата, за да поддържате обществото стабилно, докато принуждавате пазара да се <em>декарбонизира</em>.",
    principles_label: "02 — Принципи",
    principles_title: "За какво се борим",
    principles_desc: "Тук не става дума за кампании за осведоменост или доброволни ангажименти. Става дума за преосмисляне на икономическите стимули от основата.",
    p1_title: "Цена, не осведоменост",
    p1_text: "Десетилетия кампании за осведоменост не успяха да обърнат кривата на емисиите. Ценовите сигнали променят поведението в мащаб — автоматично, универсално и незабавно.",
    p2_title: "Защита на хората, не на замърсителите",
    p2_text: "Приходите отиват за обществени блага и минимален доход, за да компенсират по-високите цени. Никакви субсидии за компании да „позеленеят". Който замърсява — плаща. Парите защитават гражданите.",
    p3_title: "Социална цена на въглерода",
    p3_text: "Таксата на тон се основава на реалните щети, причинени от CO₂. По-високата цена означава по-силна промяна в поведението — но също така изисква по-силно социално преразпределение, за да остане справедливо.",
    p4_title: "Прилагане в целия ЕС",
    p4_text: "Прилагането само на национално ниво изкривява търговията в рамките на единния пазар. Необходима е координация на ниво ЕС — или внимателно проектирани национални данъци, които не създават нелоялни предимства.",
    examples_label: "03 — Реални числа",
    examples_title: "Как изглежда на практика?",
    examples_desc: "На базата на съществуващи данни от оценки на жизнения цикъл и цена на въглерода от $100 / ton CO₂-еквивалент.",
    ex_case: "Казус",
    ex_beef: "Говеждо месо",
    ex_oil: "Суров петрол",
    ex_lifecycle: "Емисии през жизнения цикъл",
    ex_carbon_price: "Приложена цена на въглерода",
    ex_additional_kg: "Допълнителна цена на kg",
    ex_additional_barrel: "Допълнителна цена на барел",
    ex_beef_insight: "Включва производство на фуражи (торове на основата на нефт), метан от добитъка, промяна на земеползването и преработка. Повечето емисии идват от биологията — не само от енергийните суровини.",
    ex_oil_insight: "Значително въздействие върху цената — но разходите се разпределят, когато нефтът се разпространява в хиляди последващи продукти. Най-голямото въздействие е върху концентрирани процеси с високи емисии като животновъдството, а не само върху промишлените суровини.",
    questions_label: "04 — Открити пропуски",
    questions_title: "Отворени въпроси",
    questions_desc: "Не претендираме, че имаме всички отговори. Това са трудните проблеми, за които се нуждаем от колективен интелект.",
    q1: "Каква точно цена на въглерода е необходима, за да промени съществено потребителското и промишленото поведение, без да причини икономически шок?",
    q2: "Как да наложим точно отчитане на жизнения цикъл в глобален мащаб, когато веригите на доставки обхващат десетки държави с различни стандарти?",
    q3: "Как трябва да третираме вноса от страни, които не спазват правилата? Граничните корекции за въглерод са обещаващи, но политически и логистично сложни.",
    q4: "Какъв е реалистичният път към политическа осъществимост в рамките на структурите на ЕС — и как да изградим коалицията, за да стигнем дотам?",
    q5: "Колко бързо можем да осъществим прехода, без да дестабилизираме поминъците? Как изглежда правилният баланс между неотложност и социална стабилност?",
    join_label: "05 — Действай",
    join_title: "Присъединете се към движението",
    join_desc: "Тази идея се нуждае от икономисти, политици, активисти и граждани, които вярват, че цената — а не чувството за вина — е това, което променя света. Добавете вашия глас.",
    join_placeholder: "вашият@email.com",
    join_btn: "Запишете се",
    join_btn_done: "Добавен ✓",
    join_note: "Без спам. Актуализации за напредъка на политиките, изследвания и действия, които можете да предприемете.",
    footer_mechanism: "Механизъм",
    footer_data: "Данни",
    calc_label: "03.5 \u2014 Опитайте сами",
    calc_title: "Остойностете щетите",
    calc_desc: "Вижте колко наистина биха стрували ежедневните продукти, ако екологичните щети бяха включени в цената.",
    calc_cat_label: "Категория",
    calc_prod_label: "Продукт",
    calc_qty_label: "Количество",
    calc_unit_label: "Единица",
    calc_price_label: "Цена на въглерода",
    calc_cat_food: "Храна и напитки",
    calc_cat_clothing: "Облекло (по материал)",
    calc_cat_electronics: "Електроника (по размер)",
    calc_cat_travel: "Пътуване",
    calc_cat_fuel: "Гориво",
    calc_price_50: "$50 / ton",
    calc_price_100: "$100 / ton",
    calc_price_150: "$150 / ton",
    calc_price_200: "$200 / ton",
    calc_eco_label: "Еко-сертифициран / органичен източник (намалява оценката с ~15%)",
    calc_result_label: "CO\u2082 отпечатък",
    calc_sources: "Източници: Poore & Nemecek (2018), <a href=\"https://doi.org/10.1126/science.aaq0216\" target=\"_blank\" rel=\"noopener\"><em>Science</em> 360:987</a> (храна) \u00b7 <a href=\"https://www.gov.uk/government/collections/government-conversion-factors-for-company-reporting\" target=\"_blank\" rel=\"noopener\">UK DEFRA 2023</a> (горива/полети) \u00b7 Apple/Levi\u2019s Product Environmental Reports (електроника/облекло)",
    calc_damage_cost: "цена на щетите",
    calc_eco_note: "(еко-сертифициран: \u221215%)",
    calc_prod_beef: "Говеждо",
    calc_prod_chicken: "Пиле",
    calc_prod_cheese: "Сирене",
    calc_prod_milk: "Мляко (краве)",
    calc_prod_rice: "Ориз",
    calc_prod_coffee: "Кафе (печено)",
    calc_prod_chocolate: "Тъмен шоколад",
    calc_prod_tomatoes: "Домати",
    calc_prod_potatoes: "Картофи",
    calc_prod_eggs: "Яйца",
    calc_prod_bread: "Хляб (пшеничен)",
    calc_prod_cotton_tshirt: "Памук \u2014 Тениска (250g)",
    calc_prod_cotton_jeans: "Памук \u2014 Дънки",
    calc_prod_polyester_shirt: "Полиестер \u2014 Риза",
    calc_prod_polyester_jacket: "Полиестер \u2014 Яке",
    calc_prod_wool_sweater: "Вълна \u2014 Пуловер",
    calc_prod_wool_coat: "Вълна \u2014 Палто",
    calc_prod_leather_shoes: "Кожа \u2014 Обувки",
    calc_prod_nylon_sneakers: "Найлон/Смесени \u2014 Маратонки",
    calc_prod_smartphone: "Размер телефон (смартфон)",
    calc_prod_tablet: "Размер таблет (10\u2033)",
    calc_prod_laptop: "Размер лаптоп (13\u201316\u2033)",
    calc_prod_monitor: "Размер монитор (24\u201327\u2033)",
    calc_prod_tv: "Размер телевизор (50\u201365\u2033)",
    calc_prod_desktop: "Настолен компютър (кутия)",
    calc_prod_flight_short: "Полет \u2014 къс (< 3 ч.)",
    calc_prod_flight_long: "Полет \u2014 дълъг (> 6 ч.)",
    calc_prod_car_petrol: "Кола \u2014 бензин (средно)",
    calc_prod_car_diesel: "Кола \u2014 дизел (средно)",
    calc_prod_train: "Влак (национален)",
    calc_prod_bus: "Автобус (междуградски)",
    calc_prod_petrol: "Бензин",
    calc_prod_diesel: "Дизел",
    calc_prod_natural_gas: "Природен газ (отопление)",
    calc_prod_electricity_eu: "Електричество (средно ЕС)",
    calc_note_beef: "Медиана на глобален LCA; диапазон 20\u2013105 kg CO\u2082e/kg",
    calc_note_chicken: "Включва земеползване, фуражи, преработка",
    calc_note_cheese: "~10 литра мляко за kg сирене",
    calc_note_milk: "Включва ентерична ферментация и земеползване",
    calc_note_rice: "Метанът от наводнени оризища доминира",
    calc_note_coffee: "Диапазон 3.5\u201328.5; силно зависи от земеползването",
    calc_note_chocolate: "Висок компонент на обезлесяване във веригата на доставки на какао",
    calc_note_tomatoes: "Стойност на открито поле; отопляема оранжерия ~2.1",
    calc_note_potatoes: "Една от храните с най-ниски емисии сред нишестените",
    calc_note_eggs: "~12 яйца на kg",
    calc_note_bread: "Стандартен пшеничен хляб",
    calc_note_cotton_tshirt: "Памучното земеделие ~половината от отпечатъка",
    calc_note_cotton_jeans: "Пълен жизнен цикъл: от земеделие до край на живота",
    calc_note_polyester_shirt: "Влакно, получено от изкопаеми горива",
    calc_note_polyester_jacket: "Синтетичен пълнеж + обвивка на нефтена основа",
    calc_note_wool_sweater: "Метан от овце + обработка",
    calc_note_wool_coat: "Тежка вълна; висок метан + въздействие от боядисване",
    calc_note_leather_shoes: "Животновъдство + химикали за дъбене",
    calc_note_nylon_sneakers: "Смесени материали; доминирано от производство",
    calc_note_smartphone: "Производството ~80% от отпечатъка; 3-годишен живот",
    calc_note_tablet: "Между телефон и лаптоп по въздействие",
    calc_note_laptop: "Диапазон 150\u2013400 kg; зависи от компонентите",
    calc_note_monitor: "Производство на дисплей + многогодишна употреба",
    calc_note_tv: "Голям дисплей + 7-годишна фаза на потребление на електричество",
    calc_note_desktop: "По-висока консумация; по-дълъг живот на компонентите",
    calc_note_flight_short: "На пътник, икономична класа; включва радиативен форсинг",
    calc_note_flight_long: "По-ефективен на km при по-дълги разстояния",
    calc_note_car_petrol: "Средноевропейска бензинова кола ~210g CO\u2082/km",
    calc_note_car_diesel: "Малко по-нисък CO\u2082 на km от бензин",
    calc_note_train: "Варира силно според електрическата мрежа; средно за ЕС",
    calc_note_bus: "На пътник; предполага се висока заетост",
    calc_note_petrol: "От кладенец до колело, включително добив нагоре по веригата",
    calc_note_diesel: "Малко по-висок на литър от бензин",
    calc_note_natural_gas: "Горене + изтичане на метан нагоре по веригата",
    calc_note_electricity_eu: "Средно за ЕС мрежата; варира по държави",
  },

  el: {
    nav_logo: "Κοστολόγησε τη Ζημιά",
    nav_how: "Πώς Λειτουργεί",
    nav_principles: "Αρχές",
    nav_examples: "Παραδείγματα",
    nav_questions: "Ανοιχτά Ερωτήματα",
    nav_join: "Συμμετοχή",
    hero_label: "Ένα πλαίσιο πολιτικής για την κλιματική κρίση",
    hero_title: "Κάνε τη ρύπανση<br><em>ακριβή</em>.",
    hero_subtitle: "Κάθε προϊόν κρύβει ένα περιβαλλοντικό κόστος. Προτείνουμε ένα τέλος ισοδυνάμου CO₂ σε ολόκληρη την αλυσίδα εφοδιασμού — μετατρέποντας την οικολογική ζημιά σε οικονομική πίεση, ενώ παράλληλα αναδιανέμουμε τα έσοδα για την προστασία των πολιτών.",
    hero_btn_primary: "Δείτε Πώς Λειτουργεί ↓",
    hero_btn_secondary: "Γίνετε Μέλος του Κινήματος",
    how_label: "01 — Μηχανισμός",
    how_title: "Ένα τέλος σε κάθε στάδιο",
    how_desc: "Τα τέλη ισοδυνάμου CO₂ εφαρμόζονται ανοδικά σε κάθε σημείο της αλυσίδας εφοδιασμού. Το συνολικό κόστος συσσωρεύεται στην τελική τιμή — καθιστώντας τα προϊόντα υψηλών εκπομπών φυσικά ακριβότερα.",
    stage1_title: "Εξόρυξη",
    stage1_desc: "Εξόρυξη πρώτων υλών, άντληση πετρελαίου, συγκομιδή",
    stage2_title: "Παραγωγή",
    stage2_desc: "Βιομηχανοποίηση, διύλιση, επεξεργασία",
    stage3_title: "Μεταφορά",
    stage3_desc: "Ναυτιλία, εμπορευματικές μεταφορές, εφοδιαστική",
    stage4_title: "Λιανική &amp; Χρήση",
    stage4_desc: "Διανομή, φάση χρήσης από τον καταναλωτή",
    stage5_title: "Απόρριψη",
    stage5_desc: "Τέλος κύκλου ζωής μέσω διευρυμένης ευθύνης του παραγωγού",
    stage_fee: "+ τέλος CO₂",
    pipeline_result: "Τα δεδομένα υπάρχουν ήδη. Οι <strong>αξιολογήσεις κύκλου ζωής (LCA)</strong> και τα αποτυπώματα άνθρακα προϊόντων καλύπτουν ολόκληρη την αλυσίδα — από την εξόρυξη έως την απόρριψη. Δεν χρειαζόμαστε νέα επιστήμη. Χρειαζόμαστε πολιτική βούληση.",
    manifesto: "Μετατρέψτε τον περιβαλλοντικό αντίκτυπο σε <em>αναπόφευκτη οικονομική πίεση</em> και στη συνέχεια αναδιανείμετε τα χρήματα για να διατηρήσετε την κοινωνία σταθερή, ενώ αναγκάζετε την αγορά να <em>απανθρακοποιηθεί</em>.",
    principles_label: "02 — Αρχές",
    principles_title: "Τι υποστηρίζουμε",
    principles_desc: "Δεν πρόκειται για εκστρατείες ευαισθητοποίησης ή εθελοντικές δεσμεύσεις. Πρόκειται για τον επανασχεδιασμό των οικονομικών κινήτρων από τη βάση.",
    p1_title: "Τιμή, όχι ευαισθητοποίηση",
    p1_text: "Δεκαετίες εκστρατειών ευαισθητοποίησης δεν κατάφεραν να κάμψουν την καμπύλη εκπομπών. Τα σήματα τιμών αλλάζουν τη συμπεριφορά σε κλίμακα — αυτόματα, καθολικά και άμεσα.",
    p2_title: "Προστασία των πολιτών, όχι των ρυπαντών",
    p2_text: "Τα έσοδα κατευθύνονται σε δημόσια αγαθά και ελάχιστο εισόδημα για την αντιστάθμιση των υψηλότερων τιμών. Καμία επιδότηση σε εταιρείες για να «πρασινίσουν». Αν ρυπαίνεις, πληρώνεις. Τα χρήματα προστατεύουν τους πολίτες.",
    p3_title: "Κοινωνικό κόστος του άνθρακα",
    p3_text: "Το τέλος ανά τόνο βασίζεται στην πραγματική ζημιά που προκαλεί το CO₂. Υψηλότερη τιμή σημαίνει ισχυρότερη αλλαγή συμπεριφοράς — αλλά απαιτεί επίσης ισχυρότερη κοινωνική αναδιανομή για να παραμείνει δίκαιη.",
    p4_title: "Εφαρμογή σε επίπεδο ΕΕ",
    p4_text: "Η εφαρμογή μόνο σε εθνικό επίπεδο στρεβλώνει το εμπόριο εντός της ενιαίας αγοράς. Απαιτείται συντονισμός σε επίπεδο ΕΕ — ή προσεκτικά σχεδιασμένοι εθνικοί φόροι που δεν δημιουργούν αθέμιτα πλεονεκτήματα.",
    examples_label: "03 — Πραγματικοί Αριθμοί",
    examples_title: "Πώς φαίνεται στην πράξη;",
    examples_desc: "Με βάση υπάρχοντα δεδομένα αξιολογήσεων κύκλου ζωής και τιμή άνθρακα $100 / ton ισοδυνάμου CO₂.",
    ex_case: "Μελέτη Περίπτωσης",
    ex_beef: "Βοδινό κρέας",
    ex_oil: "Αργό πετρέλαιο",
    ex_lifecycle: "Εκπομπές κύκλου ζωής",
    ex_carbon_price: "Εφαρμοζόμενη τιμή άνθρακα",
    ex_additional_kg: "Πρόσθετο κόστος ανά kg",
    ex_additional_barrel: "Πρόσθετο κόστος ανά βαρέλι",
    ex_beef_insight: "Περιλαμβάνει παραγωγή ζωοτροφών (λιπάσματα με βάση το πετρέλαιο), μεθάνιο από τα βοοειδή, αλλαγή χρήσης γης και επεξεργασία. Οι περισσότερες εκπομπές προέρχονται από τη βιολογία — όχι μόνο από τις ενεργειακές εισροές.",
    ex_oil_insight: "Σημαντική επίπτωση στην τιμή — αλλά τα κόστη αραιώνουν καθώς το πετρέλαιο διανέμεται σε χιλιάδες προϊόντα κατάντη. Η μεγαλύτερη επίπτωση πέφτει σε συγκεντρωμένες διεργασίες υψηλών εκπομπών όπως η κτηνοτροφία, όχι μόνο στις βιομηχανικές εισροές.",
    questions_label: "04 — Ειλικρινή Κενά",
    questions_title: "Ανοιχτά ερωτήματα",
    questions_desc: "Δεν ισχυριζόμαστε ότι έχουμε κάθε απάντηση. Αυτά είναι τα δύσκολα προβλήματα που χρειάζονται συλλογική νοημοσύνη για να λυθούν.",
    q1: "Ποια ακριβής τιμή άνθρακα απαιτείται ώστε να μεταβάλει ουσιαστικά τη συμπεριφορά καταναλωτών και βιομηχανίας χωρίς να προκαλέσει οικονομικό σοκ;",
    q2: "Πώς θα επιβάλουμε ακριβή λογιστική κύκλου ζωής παγκοσμίως, όταν οι αλυσίδες εφοδιασμού εκτείνονται σε δεκάδες χώρες με διαφορετικά πρότυπα;",
    q3: "Πώς πρέπει να αντιμετωπίζουμε τις εισαγωγές από μη συμμορφούμενες χώρες; Οι συνοριακές προσαρμογές άνθρακα είναι πολλά υποσχόμενες αλλά πολιτικά και υλικοτεχνικά σύνθετες.",
    q4: "Ποιος είναι ο ρεαλιστικός δρόμος προς την πολιτική εφικτότητα εντός των δομών της ΕΕ — και πώς θα οικοδομήσουμε τον συνασπισμό για να φτάσουμε εκεί;",
    q5: "Πόσο γρήγορα μπορούμε να πραγματοποιήσουμε τη μετάβαση χωρίς να αποσταθεροποιήσουμε τα μέσα βιοπορισμού; Πώς μοιάζει η σωστή ισορροπία μεταξύ επείγοντος και κοινωνικής σταθερότητας;",
    join_label: "05 — Δράση",
    join_title: "Γίνετε μέλος του κινήματος",
    join_desc: "Αυτή η ιδέα χρειάζεται οικονομολόγους, πολιτικούς, ακτιβιστές και πολίτες που πιστεύουν ότι η τιμή — όχι η ενοχή — είναι αυτό που αλλάζει τον κόσμο. Προσθέστε τη φωνή σας.",
    join_placeholder: "to@email.σας",
    join_btn: "Εγγραφή",
    join_btn_done: "Προστέθηκε ✓",
    join_note: "Χωρίς spam. Ενημερώσεις για την πρόοδο πολιτικών, έρευνα και δράσεις που μπορείτε να αναλάβετε.",
    footer_mechanism: "Μηχανισμός",
    footer_data: "Δεδομένα",
    calc_label: "03.5 \u2014 Δοκιμάστε το Μόνοι σας",
    calc_title: "Κοστολογήστε τη ζημιά",
    calc_desc: "Δείτε πόσο θα κόστιζαν πραγματικά τα καθημερινά προϊόντα αν η περιβαλλοντική ζημιά περιλαμβανόταν στην τιμή.",
    calc_cat_label: "Κατηγορία",
    calc_prod_label: "Προϊόν",
    calc_qty_label: "Ποσότητα",
    calc_unit_label: "Μονάδα",
    calc_price_label: "Τιμή άνθρακα",
    calc_cat_food: "Τρόφιμα & Ποτά",
    calc_cat_clothing: "Ρουχισμός (ανά υλικό)",
    calc_cat_electronics: "Ηλεκτρονικά (ανά μέγεθος)",
    calc_cat_travel: "Μεταφορές",
    calc_cat_fuel: "Καύσιμα",
    calc_price_50: "$50 / ton",
    calc_price_100: "$100 / ton",
    calc_price_150: "$150 / ton",
    calc_price_200: "$200 / ton",
    calc_eco_label: "Οικο-πιστοποιημένο / βιολογική προέλευση (μειώνει την εκτίμηση κατά ~15%)",
    calc_result_label: "Αποτύπωμα CO\u2082",
    calc_sources: "Πηγές: Poore & Nemecek (2018), <a href=\"https://doi.org/10.1126/science.aaq0216\" target=\"_blank\" rel=\"noopener\"><em>Science</em> 360:987</a> (τρόφιμα) \u00b7 <a href=\"https://www.gov.uk/government/collections/government-conversion-factors-for-company-reporting\" target=\"_blank\" rel=\"noopener\">UK DEFRA 2023</a> (καύσιμα/πτήσεις) \u00b7 Apple/Levi\u2019s Product Environmental Reports (ηλεκτρονικά/ρουχισμός)",
    calc_damage_cost: "κόστος ζημιάς",
    calc_eco_note: "(οικο-πιστοποιημένο: \u221215%)",
    calc_prod_beef: "Βοδινό",
    calc_prod_chicken: "Κοτόπουλο",
    calc_prod_cheese: "Τυρί",
    calc_prod_milk: "Γάλα (αγελάδας)",
    calc_prod_rice: "Ρύζι",
    calc_prod_coffee: "Καφές (καβουρδισμένος)",
    calc_prod_chocolate: "Μαύρη σοκολάτα",
    calc_prod_tomatoes: "Ντομάτες",
    calc_prod_potatoes: "Πατάτες",
    calc_prod_eggs: "Αυγά",
    calc_prod_bread: "Ψωμί (σιταρένιο)",
    calc_prod_cotton_tshirt: "Βαμβάκι \u2014 Μπλουζάκι (250g)",
    calc_prod_cotton_jeans: "Βαμβάκι \u2014 Τζιν",
    calc_prod_polyester_shirt: "Πολυεστέρας \u2014 Πουκάμισο",
    calc_prod_polyester_jacket: "Πολυεστέρας \u2014 Μπουφάν",
    calc_prod_wool_sweater: "Μαλλί \u2014 Πουλόβερ",
    calc_prod_wool_coat: "Μαλλί \u2014 Παλτό",
    calc_prod_leather_shoes: "Δέρμα \u2014 Παπούτσια",
    calc_prod_nylon_sneakers: "Νάιλον/Μικτά \u2014 Αθλητικά",
    calc_prod_smartphone: "Μέγεθος τηλεφώνου (smartphone)",
    calc_prod_tablet: "Μέγεθος tablet (10\u2033)",
    calc_prod_laptop: "Μέγεθος laptop (13\u201316\u2033)",
    calc_prod_monitor: "Μέγεθος οθόνης (24\u201327\u2033)",
    calc_prod_tv: "Μέγεθος τηλεόρασης (50\u201365\u2033)",
    calc_prod_desktop: "Επιτραπέζιος Η/Υ (πύργος)",
    calc_prod_flight_short: "Πτήση \u2014 μικρής απόστασης (<3 ώ.)",
    calc_prod_flight_long: "Πτήση \u2014 μεγάλης απόστασης (>6 ώ.)",
    calc_prod_car_petrol: "Αυτοκίνητο \u2014 βενζίνη (μέσος όρος)",
    calc_prod_car_diesel: "Αυτοκίνητο \u2014 ντίζελ (μέσος όρος)",
    calc_prod_train: "Τρένο (εθνικό δίκτυο)",
    calc_prod_bus: "Λεωφορείο (υπεραστικό)",
    calc_prod_petrol: "Βενζίνη",
    calc_prod_diesel: "Ντίζελ",
    calc_prod_natural_gas: "Φυσικό αέριο (θέρμανση)",
    calc_prod_electricity_eu: "Ηλεκτρισμός (μέσος όρος ΕΕ)",
    calc_note_beef: "Διάμεσος παγκόσμιου LCA\u00b7 εύρος 20\u2013105 kg CO\u2082e/kg",
    calc_note_chicken: "Περιλαμβάνει χρήση γης, ζωοτροφές, επεξεργασία",
    calc_note_cheese: "~10 λίτρα γάλα ανά kg τυρί",
    calc_note_milk: "Περιλαμβάνει εντερική ζύμωση και χρήση γης",
    calc_note_rice: "Κυριαρχεί το μεθάνιο από πλημμυρισμένους ορυζώνες",
    calc_note_coffee: "Εύρος 3.5\u201328.5\u00b7 εξαρτάται έντονα από τη χρήση γης",
    calc_note_chocolate: "Υψηλό στοιχείο αποψίλωσης στην αλυσίδα εφοδιασμού κακάο",
    calc_note_tomatoes: "Τιμή ανοιχτού αγρού\u00b7 θερμαινόμενο θερμοκήπιο ~2.1",
    calc_note_potatoes: "Μία από τις τροφές με τις χαμηλότερες εκπομπές σε αμυλούχες τροφές",
    calc_note_eggs: "~12 αυγά ανά kg",
    calc_note_bread: "Τυπικό σιταρένιο ψωμί",
    calc_note_cotton_tshirt: "Η καλλιέργεια βαμβακιού ~το μισό αποτύπωμα",
    calc_note_cotton_jeans: "Πλήρης κύκλος ζωής: από καλλιέργεια έως τέλος ζωής",
    calc_note_polyester_shirt: "Ίνα παράγωγο ορυκτών καυσίμων",
    calc_note_polyester_jacket: "Συνθετική γέμιση + κέλυφος με βάση το πετρέλαιο",
    calc_note_wool_sweater: "Μεθάνιο προβάτων + επεξεργασία",
    calc_note_wool_coat: "Βαρύ μαλλί\u00b7 υψηλό μεθάνιο + επίδραση βαφής",
    calc_note_leather_shoes: "Κτηνοτροφία + χημικά δέψης",
    calc_note_nylon_sneakers: "Μικτά υλικά\u00b7 κυριαρχεί η κατασκευή",
    calc_note_smartphone: "Η κατασκευή ~80% του αποτυπώματος\u00b7 3-ετής ζωή",
    calc_note_tablet: "Μεταξύ τηλεφώνου και laptop σε επίδραση",
    calc_note_laptop: "Εύρος 150\u2013400 kg\u00b7 εξαρτάται από τα εξαρτήματα",
    calc_note_monitor: "Κατασκευή οθόνης + πολυετής χρήση",
    calc_note_tv: "Μεγάλη οθόνη + 7-ετής φάση κατανάλωσης ρεύματος",
    calc_note_desktop: "Υψηλότερη κατανάλωση ενέργειας\u00b7 μεγαλύτερη ζωή εξαρτημάτων",
    calc_note_flight_short: "Ανά επιβάτη, οικονομική θέση\u00b7 περιλαμβάνει ακτινοβολητικό εξαναγκασμό",
    calc_note_flight_long: "Αποδοτικότερο ανά km σε μεγαλύτερες αποστάσεις",
    calc_note_car_petrol: "Μέσο ευρωπαϊκό αυτοκίνητο βενζίνης ~210g CO\u2082/km",
    calc_note_car_diesel: "Ελαφρώς χαμηλότερο CO\u2082 ανά km από βενζίνη",
    calc_note_train: "Ποικίλλει πολύ ανάλογα με το δίκτυο ηλεκτρισμού\u00b7 μέσος όρος ΕΕ",
    calc_note_bus: "Ανά επιβάτη\u00b7 υψηλή πληρότητα υποτίθεται",
    calc_note_petrol: "Από πηγάδι σε τροχό, συμπεριλαμβανομένης εξόρυξης ανάντη",
    calc_note_diesel: "Ελαφρώς υψηλότερο ανά λίτρο από βενζίνη",
    calc_note_natural_gas: "Καύση + διαρροή μεθανίου ανάντη",
    calc_note_electricity_eu: "Μέσος όρος δικτύου ΕΕ\u00b7 ποικίλλει ανά χώρα",
  },

  mt: {
    nav_logo: "Agħti Prezz lid-Danni",
    nav_how: "Kif Taħdem",
    nav_principles: "Prinċipji",
    nav_examples: "Eżempji",
    nav_questions: "Mistoqsijiet Miftuħa",
    nav_join: "Ingħaqad",
    hero_label: "Qafas ta' politika għall-kriżi klimatika",
    hero_title: "Agħmel it-tniġġis<br><em>għali</em>.",
    hero_subtitle: "Kull prodott iġorr spiża ambjentali moħbija. Nipproponu tariffa ta' ekwivalent CO₂ tul il-katina tal-provvista kollha — nibdlu l-ħsara ekoloġika f'pressjoni ekonomika, filwaqt li nqassmu mill-ġdid id-dħul biex nipproteġu lin-nies.",
    hero_btn_primary: "Ara Kif Taħdem ↓",
    hero_btn_secondary: "Ingħaqad mal-Moviment",
    how_label: "01 — Mekkaniżmu",
    how_title: "Tariffa f'kull stadju",
    how_desc: "It-tariffi ta' ekwivalent CO₂ jiġu applikati 'l fuq f'kull punt tal-katina tal-provvista. L-ispiża totali takkumula fil-prezz finali — li tagħmel il-prodotti b'emissjonijiet għoljin naturalment aktar għoljin fil-prezz.",
    stage1_title: "Estrazzjoni",
    stage1_desc: "Tħaffir ta' materja prima, tħaffir taż-żejt, ħsad",
    stage2_title: "Produzzjoni",
    stage2_desc: "Manifattura, raffinar, ipproċessar",
    stage3_title: "Trasport",
    stage3_desc: "Tbaħħir, merkanzija, loġistika",
    stage4_title: "Bejgħ &amp; Użu",
    stage4_desc: "Distribuzzjoni, fażi tal-użu mill-konsumatur",
    stage5_title: "Rimi",
    stage5_desc: "Tmiem il-ħajja permezz ta' responsabbiltà estiża tal-produttur",
    stage_fee: "+ tariffa CO₂",
    pipeline_result: "Id-data diġà teżisti. <strong>Il-valutazzjonijiet taċ-ċiklu tal-ħajja (LCA)</strong> u l-impronta tal-karbonju tal-prodotti jkopru l-katina kollha — mill-estrazzjoni sal-irimi. M'għandniex bżonn xjenza ġdida. Għandna bżonn rieda politika.",
    manifesto: "Ibdel l-impatt ambjentali f'<em>pressjoni ekonomika inevitabbli</em>, imbagħad qassam il-flus mill-ġdid biex iżżomm is-soċjetà stabbli filwaqt li ġġiegħel is-suq <em>jiddekarbonizza</em>.",
    principles_label: "02 — Prinċipji",
    principles_title: "Għalxiex nieqfu",
    principles_desc: "Din m'hijiex dwar kampanji ta' sensibilizzazzjoni jew wegħdiet volontarji. Hija dwar li nerġgħu nfasslu l-inċentivi ekonomiċi mill-pedamenti.",
    p1_title: "Prezz, mhux sensibilizzazzjoni",
    p1_text: "Għexieren ta' snin ta' kampanji ta' sensibilizzazzjoni ma rnexxilhomx ibiddlu l-kurva tal-emissjonijiet. Is-sinjali tal-prezzijiet ibiddlu l-imġiba fuq skala wiesgħa — awtomatikament, universalment, u minnufih.",
    p2_title: "Ipproteġi lin-nies, mhux lil-min iniġġeż",
    p2_text: "Id-dħul imur għal oġġetti pubbliċi u dħul minimu biex jikkumpensa l-prezzijiet ogħla. L-ebda sussidji għal kumpaniji biex \"isiru ekoloġiċi\". Jekk tniġġeż, tħallas. Il-flus jipproteġu liċ-ċittadini.",
    p3_title: "Spiża soċjali tal-karbonju",
    p3_text: "It-tariffa għal kull tunnellata hija bbażata fuq il-ħsara reali li jikkawża l-CO₂. Prezz ogħla jfisser bidla aktar qawwija fl-imġiba — iżda jitlob ukoll ridistribuzzjoni soċjali aktar qawwija biex tibqa' ġusta.",
    p4_title: "Implimentazzjoni mal-UE kollha",
    p4_text: "Implimentazzjoni nazzjonali biss tfixkel il-kummerċ fis-suq uniku. Din teħtieġ koordinazzjoni mal-UE kollha — jew taxxi nazzjonali mfassla b'attenzjoni li ma joħolqux vantaġġi inġusti.",
    examples_label: "03 — Numri Reali",
    examples_title: "Kif tidher fil-prattika?",
    examples_desc: "Bl-użu ta' data eżistenti ta' valutazzjonijiet taċ-ċiklu tal-ħajja u prezz tal-karbonju ta' $100 / ton ta' ekwivalent CO₂.",
    ex_case: "Studju ta' Każ",
    ex_beef: "Ċanga",
    ex_oil: "Żejt Mhux Raffinat",
    ex_lifecycle: "Emissjonijiet taċ-ċiklu tal-ħajja",
    ex_carbon_price: "Prezz tal-karbonju applikat",
    ex_additional_kg: "Spiża addizzjonali għal kull kg",
    ex_additional_barrel: "Spiża addizzjonali għal kull barmil",
    ex_beef_insight: "Jinkludi produzzjoni tal-għalf (fertilizzanti bbażati fuq iż-żejt), metan mill-baqar, bidla fl-użu tal-art, u pproċessar. Il-biċċa l-kbira tal-emissjonijiet ġejjin mill-bijoloġija — mhux biss mill-inputs tal-enerġija.",
    ex_oil_insight: "Impatt sinifikanti fuq il-prezz — iżda l-ispejjeż jiddilwew hekk kif iż-żejt jiġi distribwit f'eluf ta' prodotti 'l isfel. L-akbar impatt jaqa' fuq proċessi kkonċentrati b'emissjonijiet għoljin bħat-trobbija tal-bhejjem, mhux biss fuq inputs industrijali.",
    questions_label: "04 — Lakuni Onesti",
    questions_title: "Mistoqsijiet miftuħa",
    questions_desc: "Ma nippretendu xejn li għandna kull tweġiba. Dawn huma l-problemi diffiċli li għalihom neħtieġu intelliġenza kollettiva.",
    q1: "Liema prezz eżatt tal-karbonju huwa meħtieġ biex ibiddel b'mod sinifikanti l-imġiba tal-konsumaturi u tal-industrija mingħajr ma jikkawża xokk ekonomiku?",
    q2: "Kif ninfurzaw kontabbiltà preċiża taċ-ċiklu tal-ħajja globalment, meta l-ktajjen tal-provvista jinfirxu f'għexieren ta' pajjiżi b'standards differenti?",
    q3: "Kif għandna nittrattaw l-importazzjonijiet minn pajjiżi mhux konformi? L-aġġustamenti tal-karbonju fil-fruntieri huma promettenti iżda politikament u loġistikament kumplessi.",
    q4: "Liema huwa t-triq realistiku lejn il-fattibbiltà politika fi ħdan l-istrutturi tal-UE — u kif nibnu l-koalizzjoni biex naslu hemm?",
    q5: "Kemm nistgħu nagħmlu t-tranżizzjoni malajr mingħajr ma niddestabilizzaw il-għajxien? Kif tidher il-bilanċ it-tajba bejn l-urġenza u l-istabbiltà soċjali?",
    join_label: "05 — Ħu Azzjoni",
    join_title: "Ingħaqad mal-moviment",
    join_desc: "Din l-idea teħtieġ ekonomisti, leġiżlaturi, attivisti, u ċittadini li jemmnu li l-prezz — mhux il-ħtija — huwa dak li jibdel id-dinja. Żid il-vuċi tiegħek.",
    join_placeholder: "tiegħek@email.com",
    join_btn: "Irreġistra",
    join_btn_done: "Miżjud ✓",
    join_note: "L-ebda spam. Aġġornamenti dwar il-progress fil-politika, riċerka, u azzjonijiet li tista' tieħu.",
    footer_mechanism: "Mekkaniżmu",
    footer_data: "Data",
    calc_label: "03.5 \u2014 Ipprova Int",
    calc_title: "Agħti prezz lid-danni",
    calc_desc: "Ara kemm ikunu jiswew tassew il-prodotti ta' kuljum kieku l-ħsara ambjentali kienet inkluża fil-prezz.",
    calc_cat_label: "Kategorija",
    calc_prod_label: "Prodott",
    calc_qty_label: "Kwantità",
    calc_unit_label: "Unità",
    calc_price_label: "Prezz tal-karbonju",
    calc_cat_food: "Ikel u Xorb",
    calc_cat_clothing: "Ħwejjeġ (skont il-materjal)",
    calc_cat_electronics: "Elettronika (skont id-daqs)",
    calc_cat_travel: "Vjaġġar",
    calc_cat_fuel: "Fjuwil",
    calc_price_50: "$50 / ton",
    calc_price_100: "$100 / ton",
    calc_price_150: "$150 / ton",
    calc_price_200: "$200 / ton",
    calc_eco_label: "Eko-ċertifikat / sors organiku (inaqqas l-istima b'~15%)",
    calc_result_label: "Impronta CO\u2082",
    calc_sources: "Sorsi: Poore & Nemecek (2018), <a href=\"https://doi.org/10.1126/science.aaq0216\" target=\"_blank\" rel=\"noopener\"><em>Science</em> 360:987</a> (ikel) \u00b7 <a href=\"https://www.gov.uk/government/collections/government-conversion-factors-for-company-reporting\" target=\"_blank\" rel=\"noopener\">UK DEFRA 2023</a> (fjuwil/titjiriet) \u00b7 Apple/Levi\u2019s Product Environmental Reports (elettronika/ħwejjeġ)",
    calc_damage_cost: "spiża tad-danni",
    calc_eco_note: "(eko-ċertifikat: \u221215%)",
    calc_prod_beef: "Ċanga",
    calc_prod_chicken: "Tiġieġa",
    calc_prod_cheese: "Ġobon",
    calc_prod_milk: "Ħalib (tal-baqra)",
    calc_prod_rice: "Ross",
    calc_prod_coffee: "Kafè (inkaljat)",
    calc_prod_chocolate: "Ċikkulata skura",
    calc_prod_tomatoes: "Tadam",
    calc_prod_potatoes: "Patata",
    calc_prod_eggs: "Bajd",
    calc_prod_bread: "Ħobż (tal-qamħ)",
    calc_prod_cotton_tshirt: "Qoton \u2014 T-shirt (250g)",
    calc_prod_cotton_jeans: "Qoton \u2014 Jeans (denim)",
    calc_prod_polyester_shirt: "Polyester \u2014 Qmis",
    calc_prod_polyester_jacket: "Polyester \u2014 Ġakketta",
    calc_prod_wool_sweater: "Suf \u2014 Sweater",
    calc_prod_wool_coat: "Suf \u2014 Kowt",
    calc_prod_leather_shoes: "Ġilda \u2014 Żraben",
    calc_prod_nylon_sneakers: "Najlon/Imħallat \u2014 Sneakers",
    calc_prod_smartphone: "Daqs ta' telefon (smartphone)",
    calc_prod_tablet: "Daqs ta' tablet (10\u2033)",
    calc_prod_laptop: "Daqs ta' laptop (13\u201316\u2033)",
    calc_prod_monitor: "Daqs ta' monitor (24\u201327\u2033)",
    calc_prod_tv: "Daqs ta' TV (50\u201365\u2033)",
    calc_prod_desktop: "Desktop PC (torri)",
    calc_prod_flight_short: "Titjira \u2014 qasira (<3 sig.)",
    calc_prod_flight_long: "Titjira \u2014 twila (>6 sig.)",
    calc_prod_car_petrol: "Karozza \u2014 petrol (medja)",
    calc_prod_car_diesel: "Karozza \u2014 diesel (medja)",
    calc_prod_train: "Ferrovija (nazzjonali)",
    calc_prod_bus: "Xarabank (distanza twila)",
    calc_prod_petrol: "Petrol / Gasoline",
    calc_prod_diesel: "Diesel",
    calc_prod_natural_gas: "Gass naturali (tisħin)",
    calc_prod_electricity_eu: "Elettriku (medja UE)",
    calc_note_beef: "Medjana ta' LCA globali; firxa 20\u2013105 kg CO\u2082e/kg",
    calc_note_chicken: "Jinkludi użu tal-art, għalf, ipproċessar",
    calc_note_cheese: "~10 litri ħalib għal kull kg ġobon",
    calc_note_milk: "Jinkludi fermentazzjoni enterika u użu tal-art",
    calc_note_rice: "Il-metan minn għelieqi mgħarrqa jiddomina",
    calc_note_coffee: "Firxa 3.5\u201328.5; jiddependi ħafna fuq l-użu tal-art",
    calc_note_chocolate: "Komponent għoli ta' deforestazzjoni fil-katina tal-provvista tal-kakaw",
    calc_note_tomatoes: "Valur ta' għalqa miftuħa; serra msaħħna ~2.1",
    calc_note_potatoes: "Waħda mill-ikel bl-inqas emissjonijiet fost l-ikel starchy",
    calc_note_eggs: "~12-il bajda għal kull kg",
    calc_note_bread: "Ħobż tal-qamħ standard",
    calc_note_cotton_tshirt: "Il-biedja tal-qoton ~nofs l-impronta",
    calc_note_cotton_jeans: "Ċiklu tal-ħajja sħiħ: mill-biedja sat-tmiem",
    calc_note_polyester_shirt: "Fibra derivata minn fjuwils fossili",
    calc_note_polyester_jacket: "Mili sintetiku + qoxra bbażata fuq iż-żejt",
    calc_note_wool_sweater: "Metan min-nagħaġ + ipproċessar",
    calc_note_wool_coat: "Suf tqil; metan għoli + impatt tad-dyeing",
    calc_note_leather_shoes: "Trobbija tal-bhejjem + kimiċi tad-debbaħ",
    calc_note_nylon_sneakers: "Materjali mħallta; iddominata mill-manifattura",
    calc_note_smartphone: "Il-manifattura ~80% tal-impronta; ħajja ta' 3 snin",
    calc_note_tablet: "Bejn telefon u laptop fl-impatt",
    calc_note_laptop: "Firxa 150\u2013400 kg; jiddependi fuq il-komponenti",
    calc_note_monitor: "Manifattura tad-display + użu ta' bosta snin",
    calc_note_tv: "Display kbir + fażi ta' 7 snin ta' konsum tal-elettriku",
    calc_note_desktop: "Konsum ogħla tal-enerġija; ħajja itwal tal-komponenti",
    calc_note_flight_short: "Għal kull passiġġier, economy; jinkludi forcing radjattiv",
    calc_note_flight_long: "Aktar effiċjenti għal kull km f'distanzi itwal",
    calc_note_car_petrol: "Karozza Ewropea medja tal-petrol ~210g CO\u2082/km",
    calc_note_car_diesel: "Ftit inqas CO\u2082 għal kull km mill-petrol",
    calc_note_train: "Ivarja ħafna skont il-grilja tal-elettriku; medja tal-UE",
    calc_note_bus: "Għal kull passiġġier; okkupanza għolja preżunta",
    calc_note_petrol: "Mill-bir sal-rota inkluż estrazzjoni upstream",
    calc_note_diesel: "Ftit ogħla għal kull litru mill-petrol",
    calc_note_natural_gas: "Kombustjoni + tnixxija tal-metan upstream",
    calc_note_electricity_eu: "Medja tal-grilja tal-UE; ivarja skont il-pajjiż",
  },

  ga: {
    nav_logo: "Cuir Praghas ar an Damáiste",
    nav_how: "Conas a Oibríonn Sé",
    nav_principles: "Prionsabail",
    nav_examples: "Samplaí",
    nav_questions: "Ceisteanna Oscailte",
    nav_join: "Glac Páirt",
    hero_label: "Creat beartais don ghéarchéim aeráide",
    hero_title: "Déan an truailliú<br><em>costasach</em>.",
    hero_subtitle: "Tá costas comhshaoil folaithe ag gach táirge. Molaimid táille choibhéis CO₂ ar fud an tslabhra soláthair ar fad — ag tiontú damáiste éiceolaíoch ina bhrú eacnamaíoch, agus ioncam á athdháileadh chun daoine a chosaint.",
    hero_btn_primary: "Féach Conas a Oibríonn Sé ↓",
    hero_btn_secondary: "Glac Páirt sa Ghluaiseacht",
    how_label: "01 — Meicníocht",
    how_title: "Táille ag gach céim",
    how_desc: "Cuirtear táillí coibhéis CO₂ i bhfeidhm in aghaidh an tsrutha ag gach pointe sa slabhra soláthair. Carntar an costas iomlán sa phraghas deiridh — rud a fhágann go mbíonn táirgí ardastutha go nádúrtha níos costasaí.",
    stage1_title: "Eastóscadh",
    stage1_desc: "Mianadóireacht amhábhar, druileáil ola, fómhar",
    stage2_title: "Táirgeadh",
    stage2_desc: "Monaraíocht, scagadh, próiseáil",
    stage3_title: "Iompar",
    stage3_desc: "Loingseoireacht, lasta, lóistíocht",
    stage4_title: "Miondíol &amp; Úsáid",
    stage4_desc: "Dáileadh, céim úsáide an tomhaltóra",
    stage5_title: "Diúscairt",
    stage5_desc: "Deireadh saoil trí fhreagracht leathnaithe an táirgeora",
    stage_fee: "+ táille CO₂",
    pipeline_result: "Tá na sonraí ann cheana féin. Clúdaíonn <strong>measúnachtaí saolré (LCA)</strong> agus lorg carbóin táirgí an slabhra iomlán — ón eastóscadh go dtí an diúscairt. Ní eolaíocht nua atá de dhíth orainn. Is toil pholaitiúil atá de dhíth orainn.",
    manifesto: "Athraigh tionchar comhshaoil ina <em>bhrú eacnamaíoch dosheachanta</em>, ansin athdháil an t-airgead chun an tsochaí a choinneáil cobhsaí agus an margadh á iallach <em>dícharbónú</em>.",
    principles_label: "02 — Prionsabail",
    principles_title: "Cad a sheasaimid ar a shon",
    principles_desc: "Ní faoi fheachtais feasachta ná gealltanais dheonacha atá sé seo. Is faoi dhreasachtaí eacnamaíocha a athdhearadh ón mbun aníos atá sé.",
    p1_title: "Praghas, ní feasacht",
    p1_text: "Níor éirigh le blianta fada d'fheachtais feasachta cuar na n-astuithe a chasadh. Athraíonn comharthaí praghais iompar ar scála — go huathoibríoch, go huilíoch, agus láithreach.",
    p2_title: "Cosain daoine, ní truaillitheoirí",
    p2_text: "Téann an t-ioncam chuig earraí poiblí agus íosioncam chun praghsanna níos airde a fhritháireamh. Gan fóirdheontais do chuideachtaí chun \"éirí glas\". Má thruaillíonn tú, íocann tú. Cosnaíonn an t-airgead na saoránaigh.",
    p3_title: "Costas sóisialta an charbóin",
    p3_text: "Tá an táille in aghaidh an tona bunaithe ar an damáiste iarbhír a dhéanann CO₂. Ciallaíonn praghas níos airde athrú iompair níos láidre — ach éilíonn sé freisin athdháileadh sóisialta níos láidre chun é a choinneáil cothrom.",
    p4_title: "Cur i bhfeidhm ar fud an AE",
    p4_text: "Déanann cur i bhfeidhm náisiúnta amháin an trádáil a shaobhadh laistigh den mhargadh aonair. Teastaíonn comhordú ar fud an AE — nó cánacha náisiúnta a dheartar go cúramach nach gcruthaíonn buntáistí éagóracha.",
    examples_label: "03 — Fíoruimhreacha",
    examples_title: "Conas a fhéachann sé seo?",
    examples_desc: "Ag úsáid sonraí reatha measúnachta saolré agus praghas carbóin de $100 / ton de choibhéis CO₂.",
    ex_case: "Cás-Staidéar",
    ex_beef: "Mairteoil",
    ex_oil: "Amhola",
    ex_lifecycle: "Astuithe saolré",
    ex_carbon_price: "Praghas carbóin curtha i bhfeidhm",
    ex_additional_kg: "Costas breise in aghaidh an kg",
    ex_additional_barrel: "Costas breise in aghaidh an bhairille",
    ex_beef_insight: "Áirítear táirgeadh beatha (leasacháin bunaithe ar ola), meatán ó eallaí, athrú ar úsáid talún, agus próiseáil. Tagann formhór na n-astuithe ón mbitheolaíocht — ní ó ionchuir fuinnimh amháin.",
    ex_oil_insight: "Tionchar suntasach ar phraghas — ach caolítear na costais de réir mar a dháiltear an ola thar na mílte táirgí iartheachtacha. Is ar phróisis chomhchruinnithe ardastuthe ar nós tréadchur beostoic is mó a thiteann an tionchar, ní ar ionchuir thionsclaíocha amháin.",
    questions_label: "04 — Bearnaí Macánta",
    questions_title: "Ceisteanna oscailte",
    questions_desc: "Ní ligimid orainn go bhfuil gach freagra againn. Seo iad na fadhbanna deacra a dteastaíonn intleacht chomhchoiteann chun iad a réiteach.",
    q1: "Cén praghas carbóin beacht atá ag teastáil chun iompar tomhaltóirí agus tionsclaíochta a athrú go suntasach gan suaitheadh eacnamaíoch a chruthú?",
    q2: "Conas a fhorfheidhmímid cuntasaíocht bheacht saolré ar fud an domhain, nuair a shíneann slabhraí soláthair thar na scórtha tíortha le caighdeáin éagsúla?",
    q3: "Conas ba cheart dúinn déileáil le hallmhairí ó thíortha neamhchomhlíontacha? Tá coigeartuithe carbóin teorann gealltanach ach casta go polaitiúil agus go lóistíochtúil.",
    q4: "Cad é an cosán réalaíoch chuig indéantacht pholaitiúil laistigh de struchtúir an AE — agus conas a thógaimid an comhghuaillíocht chun é sin a bhaint amach?",
    q5: "Cé chomh tapa is féidir linn aistriú gan slite beatha a dhíchobhsú? Cén chuma atá ar an gcothromaíocht cheart idir práinn agus cobhsaíocht shóisialta?",
    join_label: "05 — Glac Beart",
    join_title: "Glac páirt sa ghluaiseacht",
    join_desc: "Teastaíonn eacnamaithe, lucht déanta beartas, gníomhaithe, agus saoránaigh ón smaoineamh seo — daoine a chreideann gurb é an praghas — ní an chiontacht — a athraíonn an domhan. Cuir do ghuth leis.",
    join_placeholder: "do@ríomhphost.com",
    join_btn: "Cláraigh",
    join_btn_done: "Curtha leis ✓",
    join_note: "Gan turscar. Nuashonruithe ar dhul chun cinn beartais, taighde, agus gníomhartha is féidir leat a dhéanamh.",
    footer_mechanism: "Meicníocht",
    footer_data: "Sonraí",
    calc_label: "03.5 \u2014 Triail \u00c9 T\u00fa F\u00e9in",
    calc_title: "Cuir praghas ar an dam\u00e1iste",
    calc_desc: "F\u00e9ach c\u00e9n costas a bheadh ar th\u00e1irg\u00ed laethúla dá mbeadh an dam\u00e1iste comhshaoil san \u00e1ireamh sa phraghas.",
    calc_cat_label: "Catag\u00f3ir",
    calc_prod_label: "T\u00e1irge",
    calc_qty_label: "Cainníocht",
    calc_unit_label: "Aonad",
    calc_price_label: "Praghas carb\u00f3in",
    calc_cat_food: "Bia & Deoch",
    calc_cat_clothing: "\u00c9ada\u00ed (de r\u00e9ir \u00e1bhair)",
    calc_cat_electronics: "Leictreonaic (de r\u00e9ir m\u00e9ide)",
    calc_cat_travel: "Taisteal",
    calc_cat_fuel: "Breosla",
    calc_price_50: "$50 / ton",
    calc_price_100: "$100 / ton",
    calc_price_150: "$150 / ton",
    calc_price_200: "$200 / ton",
    calc_eco_label: "\u00c9icidheimhnithe / foinse orgánach (laghdaíonn an meastach\u00e1n faoi ~15%)",
    calc_result_label: "Lorg CO\u2082",
    calc_sources: "Foinsí: Poore & Nemecek (2018), <a href=\"https://doi.org/10.1126/science.aaq0216\" target=\"_blank\" rel=\"noopener\"><em>Science</em> 360:987</a> (bia) \u00b7 <a href=\"https://www.gov.uk/government/collections/government-conversion-factors-for-company-reporting\" target=\"_blank\" rel=\"noopener\">UK DEFRA 2023</a> (breosla/eitilt\u00ed) \u00b7 Apple/Levi\u2019s Product Environmental Reports (leictreonaic/\u00e9ada\u00ed)",
    calc_damage_cost: "costas dam\u00e1iste",
    calc_eco_note: "(\u00e9icidheimhnithe: \u221215%)",
    calc_prod_beef: "Mairteoil",
    calc_prod_chicken: "Sicín",
    calc_prod_cheese: "C\u00e1is",
    calc_prod_milk: "Bainne (b\u00f3)",
    calc_prod_rice: "Rís",
    calc_prod_coffee: "Caife (r\u00f3sta)",
    calc_prod_chocolate: "Seacl\u00e1id dhorcha",
    calc_prod_tomatoes: "Tr\u00e1ta\u00ed",
    calc_prod_potatoes: "Pr\u00e1ta\u00ed",
    calc_prod_eggs: "Uibheacha",
    calc_prod_bread: "Ar\u00e1n (cruithneachta)",
    calc_prod_cotton_tshirt: "Cadás \u2014 T-l\u00e9ine (250g)",
    calc_prod_cotton_jeans: "Cadás \u2014 Jeans (d\u00eanam)",
    calc_prod_polyester_shirt: "Poileist\u00e9ar \u2014 L\u00e9ine",
    calc_prod_polyester_jacket: "Poileist\u00e9ar \u2014 Seaic\u00e9ad",
    calc_prod_wool_sweater: "Olann \u2014 Geansaí",
    calc_prod_wool_coat: "Olann \u2014 C\u00f3ta",
    calc_prod_leather_shoes: "Leathar \u2014 Br\u00f3ga",
    calc_prod_nylon_sneakers: "N\u00edol\u00f3n/Measctha \u2014 Br\u00f3ga reatha",
    calc_prod_smartphone: "M\u00e9id fón (smartphone)",
    calc_prod_tablet: "M\u00e9id t\u00e1ibléid (10\u2033)",
    calc_prod_laptop: "M\u00e9id ríomhaire glúine (13\u201316\u2033)",
    calc_prod_monitor: "M\u00e9id monat\u00f3ra (24\u201327\u2033)",
    calc_prod_tv: "M\u00e9id teilifíse (50\u201365\u2033)",
    calc_prod_desktop: "Ríomhaire deisce (túr)",
    calc_prod_flight_short: "Eitilt \u2014 gearraistear (<3 u.)",
    calc_prod_flight_long: "Eitilt \u2014 fadaistear (>6 u.)",
    calc_prod_car_petrol: "Carr \u2014 peitreal (meánach)",
    calc_prod_car_diesel: "Carr \u2014 d\u00edosal (meánach)",
    calc_prod_train: "Traein (n\u00e1isiúnta)",
    calc_prod_bus: "Bus (fadaistir)",
    calc_prod_petrol: "Peitreal / G\u00e1sal\u00edn",
    calc_prod_diesel: "D\u00edosal",
    calc_prod_natural_gas: "G\u00e1s n\u00e1dúrtha (t\u00e9amh)",
    calc_prod_electricity_eu: "Leictreachas (meán an AE)",
    calc_note_beef: "Meánach LCA domhanda; raon 20\u2013105 kg CO\u2082e/kg",
    calc_note_chicken: "Áirítear úsáid tal\u00fan, beatha, pr\u00f3ise\u00e1il",
    calc_note_cheese: "~10 lítear bainne in aghaidh an kg c\u00e1ise",
    calc_note_milk: "Áirítear coire\u00e1il intreach agus \u00fas\u00e1id tal\u00fan",
    calc_note_rice: "Is \u00e9 an meát\u00e1n \u00f3 ghoirt t\u00fa tuile is m\u00f3 at\u00e1 i gceist",
    calc_note_coffee: "Raon 3.5\u201328.5; ag brath go m\u00f3r ar \u00fas\u00e1id tal\u00fan",
    calc_note_chocolate: "Comhph\u00e1irt ard d\u00edthreoithe sa slabhra sol\u00e1thair c\u00f3c\u00f3",
    calc_note_tomatoes: "Luach machaire oscailte; teach gloine t\u00e9ite ~2.1",
    calc_note_potatoes: "Ceann de na bia\u00ed staitsigh is ísle ast\u00fa",
    calc_note_eggs: "~12 ubh in aghaidh an kg",
    calc_note_bread: "Ar\u00e1n cruithneachta caighde\u00e1nach",
    calc_note_cotton_tshirt: "Feirmeoire\u00e1cht chadáis ~leath den lorg",
    calc_note_cotton_jeans: "Saolré ioml\u00e1n: \u00f3n bhfeirmeoire\u00e1cht go deireadh saoil",
    calc_note_polyester_shirt: "Sn\u00e1ithín \u00f3 bhreoslaí iontaise",
    calc_note_polyester_jacket: "Líonadh sint\u00e9iseach + blaosc pheitrile\u00e9am-bhunaithe",
    calc_note_wool_sweater: "Meát\u00e1n caorach + pr\u00f3ise\u00e1il",
    calc_note_wool_coat: "Olann throm; meát\u00e1n ard + tionchar d\u00e1ite",
    calc_note_leather_shoes: "Feirmeoireacht eallaí + ceimice\u00e1in s\u00fadaire\u00e1chta",
    calc_note_nylon_sneakers: "Ábhair mheasctha; monar\u00fa is m\u00f3 at\u00e1 i gceist",
    calc_note_smartphone: "Monar\u00fa ~80% den lorg; saol 3 bliana",
    calc_note_tablet: "Idir f\u00f3n agus ríomhaire glúine i dtionchar",
    calc_note_laptop: "Raon 150\u2013400 kg; ag brath ar na comhph\u00e1irteanna",
    calc_note_monitor: "Monar\u00fa taispe\u00e1na + \u00fas\u00e1id ilbhliant\u00fail",
    calc_note_tv: "Taispe\u00e1int mh\u00f3r + c\u00e9im 7 mbliana de thomhalt\u00fa leictreachais",
    calc_note_desktop: "Tarraing\u00edt cumhachta n\u00edos airde; saol n\u00edos faide comhph\u00e1irteanna",
    calc_note_flight_short: "In aghaidh an phaisi\u00e9ara, eacnamaíocht; áirítear f\u00f3rsáil raidíochta",
    calc_note_flight_long: "N\u00edos \u00e9ifeachta\u00ed in aghaidh an km ar achair n\u00edos faide",
    calc_note_car_petrol: "Meáncharr Eorpach peitril ~210g CO\u2082/km",
    calc_note_car_diesel: "CO\u2082 beag\u00e1n n\u00edos ísle in aghaidh an km n\u00e1 peitreal",
    calc_note_train: "Ath\u00edra\u00edonn go m\u00f3r de r\u00e9ir greille leictreachais; me\u00e1n an AE",
    calc_note_bus: "In aghaidh an phaisin\u00e9ara; áitíocht ard glactha",
    calc_note_petrol: "Ón tobar go dtí an roth lena n-áirítear eastóscadh in aghaidh an tsrutha",
    calc_note_diesel: "Beag\u00e1n n\u00edos airde in aghaidh an l\u00edtir n\u00e1 peitreal",
    calc_note_natural_gas: "D\u00f3ch\u00e1n + sceitheadh meát\u00e1in in aghaidh an tsrutha",
    calc_note_electricity_eu: "Me\u00e1n greille an AE; ath\u00edra\u00edonn de r\u00e9ir tíre",
  },
};
