const TRANS_SOUTH = {
  bg: {
    nav_logo: "Оцени щетите",
    nav_how: "Как работи",
    nav_principles: "Принципи",
    nav_examples: "Примери",
    nav_questions: "Отворени въпроси",
    nav_join: "Присъедини се",
    hero_label: "Политическа рамка за климатичната криза",
    hero_title: "Направи замърсяването<br><em>скъпо</em>.",
    hero_subtitle: "Всеки продукт носи скрита екологична цена. Ние предлагаме такса за CO₂-еквивалент по цялата верига на доставки — превръщайки екологичните щети в икономически натиск, като същевременно преразпределяме приходите за защита на хората.",
    hero_btn_primary: "Вижте как работи ↓",
    hero_btn_secondary: "Присъединете се към движението",
    how_label: "01 — Механизъм",
    how_title: "Такса на всеки етап",
    how_desc: "Таксите за CO₂-еквивалент се прилагат нагоре по веригата, на всяка точка от веригата на доставки. Общата стойност се натрупва в крайната цена — правейки продуктите с високи емисии естествено по-скъпи.",
    stage1_title: "Добив",
    stage1_desc: "Добив на суровини, нефтен добив, прибиране на реколта",
    stage2_title: "Производство",
    stage2_desc: "Преработка, рафиниране, обработка",
    stage3_title: "Транспорт",
    stage3_desc: "Корабоплаване, товарен превоз, логистика",
    stage4_title: "Търговия &amp; Употреба",
    stage4_desc: "Дистрибуция, фаза на потребителска употреба",
    stage5_title: "Обезвреждане",
    stage5_desc: "Край на жизнения цикъл чрез разширена отговорност на производителя",
    stage_fee: "+ CO₂ такса",
    pipeline_result: "Данните вече съществуват. <strong>Оценките на жизнения цикъл (LCA)</strong> и въглеродните отпечатъци на продуктите обхващат цялата верига — от добива до обезвреждането. Не се нуждаем от нова наука. Нуждаем се от политическа воля.",
    manifesto: "Превърнете въздействието върху околната среда в <em>неизбежен икономически натиск</em>, след което преразпределете средствата, за да поддържате обществото стабилно, докато принуждавате пазара да се <em>декарбонизира</em>.",
    principles_label: "02 — Принципи",
    principles_title: "За какво се борим",
    principles_desc: "Тук не става дума за кампании за осведоменост или доброволни ангажименти. Става дума за преосмисляне на икономическите стимули от основата.",
    p1_title: "Цена, не осведоменост",
    p1_text: "Десетилетия кампании за осведоменост не успяха да обърнат кривата на емисиите. Ценовите сигнали променят поведението в мащаб — автоматично, универсално и незабавно.",
    p2_title: "Защита на хората, не на замърсителите",
    p2_text: "Приходите отиват за обществени блага и минимален доход, за да компенсират по-високите цени. Никакви субсидии за компании да „позеленеят". Който замърсява — плаща. Парите защитават гражданите.",
    p3_title: "Социална цена на въглерода",
    p3_text: "Таксата на тон се основава на реалните щети, причинени от CO₂. По-високата цена означава по-силна промяна в поведението — но също така изисква по-силно социално преразпределение, за да остане справедливо.",
    p4_title: "Прилагане в целия ЕС",
    p4_text: "Прилагането само на национално ниво изкривява търговията в рамките на единния пазар. Необходима е координация на ниво ЕС — или внимателно проектирани национални данъци, които не създават нелоялни предимства.",
    examples_label: "03 — Реални числа",
    examples_title: "Как изглежда на практика?",
    examples_desc: "На базата на съществуващи данни от оценки на жизнения цикъл и цена на въглерода от $100 / ton CO₂-еквивалент.",
    ex_case: "Казус",
    ex_beef: "Говеждо месо",
    ex_oil: "Суров петрол",
    ex_lifecycle: "Емисии през жизнения цикъл",
    ex_carbon_price: "Приложена цена на въглерода",
    ex_additional_kg: "Допълнителна цена на kg",
    ex_additional_barrel: "Допълнителна цена на барел",
    ex_beef_insight: "Включва производство на фуражи (торове на основата на нефт), метан от добитъка, промяна на земеползването и преработка. Повечето емисии идват от биологията — не само от енергийните суровини.",
    ex_oil_insight: "Значително въздействие върху цената — но разходите се разпределят, когато нефтът се разпространява в хиляди последващи продукти. Най-голямото въздействие е върху концентрирани процеси с високи емисии като животновъдството, а не само върху промишлените суровини.",
    questions_label: "04 — Открити пропуски",
    questions_title: "Отворени въпроси",
    questions_desc: "Не претендираме, че имаме всички отговори. Това са трудните проблеми, за които се нуждаем от колективен интелект.",
    q1: "Каква точно цена на въглерода е необходима, за да промени съществено потребителското и промишленото поведение, без да причини икономически шок?",
    q2: "Как да наложим точно отчитане на жизнения цикъл в глобален мащаб, когато веригите на доставки обхващат десетки държави с различни стандарти?",
    q3: "Как трябва да третираме вноса от страни, които не спазват правилата? Граничните корекции за въглерод са обещаващи, но политически и логистично сложни.",
    q4: "Какъв е реалистичният път към политическа осъществимост в рамките на структурите на ЕС — и как да изградим коалицията, за да стигнем дотам?",
    q5: "Колко бързо можем да осъществим прехода, без да дестабилизираме поминъците? Как изглежда правилният баланс между неотложност и социална стабилност?",
    join_label: "05 — Действай",
    join_title: "Присъединете се към движението",
    join_desc: "Тази идея се нуждае от икономисти, политици, активисти и граждани, които вярват, че цената — а не чувството за вина — е това, което променя света. Добавете вашия глас.",
    join_placeholder: "вашият@email.com",
    join_btn: "Запишете се",
    join_btn_done: "Добавен ✓",
    join_note: "Без спам. Актуализации за напредъка на политиките, изследвания и действия, които можете да предприемете.",
    footer_mechanism: "Механизъм",
    footer_data: "Данни",
  },

  el: {
    nav_logo: "Κοστολόγησε τη Ζημιά",
    nav_how: "Πώς Λειτουργεί",
    nav_principles: "Αρχές",
    nav_examples: "Παραδείγματα",
    nav_questions: "Ανοιχτά Ερωτήματα",
    nav_join: "Συμμετοχή",
    hero_label: "Ένα πλαίσιο πολιτικής για την κλιματική κρίση",
    hero_title: "Κάνε τη ρύπανση<br><em>ακριβή</em>.",
    hero_subtitle: "Κάθε προϊόν κρύβει ένα περιβαλλοντικό κόστος. Προτείνουμε ένα τέλος ισοδυνάμου CO₂ σε ολόκληρη την αλυσίδα εφοδιασμού — μετατρέποντας την οικολογική ζημιά σε οικονομική πίεση, ενώ παράλληλα αναδιανέμουμε τα έσοδα για την προστασία των πολιτών.",
    hero_btn_primary: "Δείτε Πώς Λειτουργεί ↓",
    hero_btn_secondary: "Γίνετε Μέλος του Κινήματος",
    how_label: "01 — Μηχανισμός",
    how_title: "Ένα τέλος σε κάθε στάδιο",
    how_desc: "Τα τέλη ισοδυνάμου CO₂ εφαρμόζονται ανοδικά σε κάθε σημείο της αλυσίδας εφοδιασμού. Το συνολικό κόστος συσσωρεύεται στην τελική τιμή — καθιστώντας τα προϊόντα υψηλών εκπομπών φυσικά ακριβότερα.",
    stage1_title: "Εξόρυξη",
    stage1_desc: "Εξόρυξη πρώτων υλών, άντληση πετρελαίου, συγκομιδή",
    stage2_title: "Παραγωγή",
    stage2_desc: "Βιομηχανοποίηση, διύλιση, επεξεργασία",
    stage3_title: "Μεταφορά",
    stage3_desc: "Ναυτιλία, εμπορευματικές μεταφορές, εφοδιαστική",
    stage4_title: "Λιανική &amp; Χρήση",
    stage4_desc: "Διανομή, φάση χρήσης από τον καταναλωτή",
    stage5_title: "Απόρριψη",
    stage5_desc: "Τέλος κύκλου ζωής μέσω διευρυμένης ευθύνης του παραγωγού",
    stage_fee: "+ τέλος CO₂",
    pipeline_result: "Τα δεδομένα υπάρχουν ήδη. Οι <strong>αξιολογήσεις κύκλου ζωής (LCA)</strong> και τα αποτυπώματα άνθρακα προϊόντων καλύπτουν ολόκληρη την αλυσίδα — από την εξόρυξη έως την απόρριψη. Δεν χρειαζόμαστε νέα επιστήμη. Χρειαζόμαστε πολιτική βούληση.",
    manifesto: "Μετατρέψτε τον περιβαλλοντικό αντίκτυπο σε <em>αναπόφευκτη οικονομική πίεση</em> και στη συνέχεια αναδιανείμετε τα χρήματα για να διατηρήσετε την κοινωνία σταθερή, ενώ αναγκάζετε την αγορά να <em>απανθρακοποιηθεί</em>.",
    principles_label: "02 — Αρχές",
    principles_title: "Τι υποστηρίζουμε",
    principles_desc: "Δεν πρόκειται για εκστρατείες ευαισθητοποίησης ή εθελοντικές δεσμεύσεις. Πρόκειται για τον επανασχεδιασμό των οικονομικών κινήτρων από τη βάση.",
    p1_title: "Τιμή, όχι ευαισθητοποίηση",
    p1_text: "Δεκαετίες εκστρατειών ευαισθητοποίησης δεν κατάφεραν να κάμψουν την καμπύλη εκπομπών. Τα σήματα τιμών αλλάζουν τη συμπεριφορά σε κλίμακα — αυτόματα, καθολικά και άμεσα.",
    p2_title: "Προστασία των πολιτών, όχι των ρυπαντών",
    p2_text: "Τα έσοδα κατευθύνονται σε δημόσια αγαθά και ελάχιστο εισόδημα για την αντιστάθμιση των υψηλότερων τιμών. Καμία επιδότηση σε εταιρείες για να «πρασινίσουν». Αν ρυπαίνεις, πληρώνεις. Τα χρήματα προστατεύουν τους πολίτες.",
    p3_title: "Κοινωνικό κόστος του άνθρακα",
    p3_text: "Το τέλος ανά τόνο βασίζεται στην πραγματική ζημιά που προκαλεί το CO₂. Υψηλότερη τιμή σημαίνει ισχυρότερη αλλαγή συμπεριφοράς — αλλά απαιτεί επίσης ισχυρότερη κοινωνική αναδιανομή για να παραμείνει δίκαιη.",
    p4_title: "Εφαρμογή σε επίπεδο ΕΕ",
    p4_text: "Η εφαρμογή μόνο σε εθνικό επίπεδο στρεβλώνει το εμπόριο εντός της ενιαίας αγοράς. Απαιτείται συντονισμός σε επίπεδο ΕΕ — ή προσεκτικά σχεδιασμένοι εθνικοί φόροι που δεν δημιουργούν αθέμιτα πλεονεκτήματα.",
    examples_label: "03 — Πραγματικοί Αριθμοί",
    examples_title: "Πώς φαίνεται στην πράξη;",
    examples_desc: "Με βάση υπάρχοντα δεδομένα αξιολογήσεων κύκλου ζωής και τιμή άνθρακα $100 / ton ισοδυνάμου CO₂.",
    ex_case: "Μελέτη Περίπτωσης",
    ex_beef: "Βοδινό κρέας",
    ex_oil: "Αργό πετρέλαιο",
    ex_lifecycle: "Εκπομπές κύκλου ζωής",
    ex_carbon_price: "Εφαρμοζόμενη τιμή άνθρακα",
    ex_additional_kg: "Πρόσθετο κόστος ανά kg",
    ex_additional_barrel: "Πρόσθετο κόστος ανά βαρέλι",
    ex_beef_insight: "Περιλαμβάνει παραγωγή ζωοτροφών (λιπάσματα με βάση το πετρέλαιο), μεθάνιο από τα βοοειδή, αλλαγή χρήσης γης και επεξεργασία. Οι περισσότερες εκπομπές προέρχονται από τη βιολογία — όχι μόνο από τις ενεργειακές εισροές.",
    ex_oil_insight: "Σημαντική επίπτωση στην τιμή — αλλά τα κόστη αραιώνουν καθώς το πετρέλαιο διανέμεται σε χιλιάδες προϊόντα κατάντη. Η μεγαλύτερη επίπτωση πέφτει σε συγκεντρωμένες διεργασίες υψηλών εκπομπών όπως η κτηνοτροφία, όχι μόνο στις βιομηχανικές εισροές.",
    questions_label: "04 — Ειλικρινή Κενά",
    questions_title: "Ανοιχτά ερωτήματα",
    questions_desc: "Δεν ισχυριζόμαστε ότι έχουμε κάθε απάντηση. Αυτά είναι τα δύσκολα προβλήματα που χρειάζονται συλλογική νοημοσύνη για να λυθούν.",
    q1: "Ποια ακριβής τιμή άνθρακα απαιτείται ώστε να μεταβάλει ουσιαστικά τη συμπεριφορά καταναλωτών και βιομηχανίας χωρίς να προκαλέσει οικονομικό σοκ;",
    q2: "Πώς θα επιβάλουμε ακριβή λογιστική κύκλου ζωής παγκοσμίως, όταν οι αλυσίδες εφοδιασμού εκτείνονται σε δεκάδες χώρες με διαφορετικά πρότυπα;",
    q3: "Πώς πρέπει να αντιμετωπίζουμε τις εισαγωγές από μη συμμορφούμενες χώρες; Οι συνοριακές προσαρμογές άνθρακα είναι πολλά υποσχόμενες αλλά πολιτικά και υλικοτεχνικά σύνθετες.",
    q4: "Ποιος είναι ο ρεαλιστικός δρόμος προς την πολιτική εφικτότητα εντός των δομών της ΕΕ — και πώς θα οικοδομήσουμε τον συνασπισμό για να φτάσουμε εκεί;",
    q5: "Πόσο γρήγορα μπορούμε να πραγματοποιήσουμε τη μετάβαση χωρίς να αποσταθεροποιήσουμε τα μέσα βιοπορισμού; Πώς μοιάζει η σωστή ισορροπία μεταξύ επείγοντος και κοινωνικής σταθερότητας;",
    join_label: "05 — Δράση",
    join_title: "Γίνετε μέλος του κινήματος",
    join_desc: "Αυτή η ιδέα χρειάζεται οικονομολόγους, πολιτικούς, ακτιβιστές και πολίτες που πιστεύουν ότι η τιμή — όχι η ενοχή — είναι αυτό που αλλάζει τον κόσμο. Προσθέστε τη φωνή σας.",
    join_placeholder: "to@email.σας",
    join_btn: "Εγγραφή",
    join_btn_done: "Προστέθηκε ✓",
    join_note: "Χωρίς spam. Ενημερώσεις για την πρόοδο πολιτικών, έρευνα και δράσεις που μπορείτε να αναλάβετε.",
    footer_mechanism: "Μηχανισμός",
    footer_data: "Δεδομένα",
  },

  mt: {
    nav_logo: "Agħti Prezz lid-Danni",
    nav_how: "Kif Taħdem",
    nav_principles: "Prinċipji",
    nav_examples: "Eżempji",
    nav_questions: "Mistoqsijiet Miftuħa",
    nav_join: "Ingħaqad",
    hero_label: "Qafas ta' politika għall-kriżi klimatika",
    hero_title: "Agħmel it-tniġġis<br><em>għali</em>.",
    hero_subtitle: "Kull prodott iġorr spiża ambjentali moħbija. Nipproponu tariffa ta' ekwivalent CO₂ tul il-katina tal-provvista kollha — nibdlu l-ħsara ekoloġika f'pressjoni ekonomika, filwaqt li nqassmu mill-ġdid id-dħul biex nipproteġu lin-nies.",
    hero_btn_primary: "Ara Kif Taħdem ↓",
    hero_btn_secondary: "Ingħaqad mal-Moviment",
    how_label: "01 — Mekkaniżmu",
    how_title: "Tariffa f'kull stadju",
    how_desc: "It-tariffi ta' ekwivalent CO₂ jiġu applikati 'l fuq f'kull punt tal-katina tal-provvista. L-ispiża totali takkumula fil-prezz finali — li tagħmel il-prodotti b'emissjonijiet għoljin naturalment aktar għoljin fil-prezz.",
    stage1_title: "Estrazzjoni",
    stage1_desc: "Tħaffir ta' materja prima, tħaffir taż-żejt, ħsad",
    stage2_title: "Produzzjoni",
    stage2_desc: "Manifattura, raffinar, ipproċessar",
    stage3_title: "Trasport",
    stage3_desc: "Tbaħħir, merkanzija, loġistika",
    stage4_title: "Bejgħ &amp; Użu",
    stage4_desc: "Distribuzzjoni, fażi tal-użu mill-konsumatur",
    stage5_title: "Rimi",
    stage5_desc: "Tmiem il-ħajja permezz ta' responsabbiltà estiża tal-produttur",
    stage_fee: "+ tariffa CO₂",
    pipeline_result: "Id-data diġà teżisti. <strong>Il-valutazzjonijiet taċ-ċiklu tal-ħajja (LCA)</strong> u l-impronta tal-karbonju tal-prodotti jkopru l-katina kollha — mill-estrazzjoni sal-irimi. M'għandniex bżonn xjenza ġdida. Għandna bżonn rieda politika.",
    manifesto: "Ibdel l-impatt ambjentali f'<em>pressjoni ekonomika inevitabbli</em>, imbagħad qassam il-flus mill-ġdid biex iżżomm is-soċjetà stabbli filwaqt li ġġiegħel is-suq <em>jiddekarbonizza</em>.",
    principles_label: "02 — Prinċipji",
    principles_title: "Għalxiex nieqfu",
    principles_desc: "Din m'hijiex dwar kampanji ta' sensibilizzazzjoni jew wegħdiet volontarji. Hija dwar li nerġgħu nfasslu l-inċentivi ekonomiċi mill-pedamenti.",
    p1_title: "Prezz, mhux sensibilizzazzjoni",
    p1_text: "Għexieren ta' snin ta' kampanji ta' sensibilizzazzjoni ma rnexxilhomx ibiddlu l-kurva tal-emissjonijiet. Is-sinjali tal-prezzijiet ibiddlu l-imġiba fuq skala wiesgħa — awtomatikament, universalment, u minnufih.",
    p2_title: "Ipproteġi lin-nies, mhux lil-min iniġġeż",
    p2_text: "Id-dħul imur għal oġġetti pubbliċi u dħul minimu biex jikkumpensa l-prezzijiet ogħla. L-ebda sussidji għal kumpaniji biex \"isiru ekoloġiċi\". Jekk tniġġeż, tħallas. Il-flus jipproteġu liċ-ċittadini.",
    p3_title: "Spiża soċjali tal-karbonju",
    p3_text: "It-tariffa għal kull tunnellata hija bbażata fuq il-ħsara reali li jikkawża l-CO₂. Prezz ogħla jfisser bidla aktar qawwija fl-imġiba — iżda jitlob ukoll ridistribuzzjoni soċjali aktar qawwija biex tibqa' ġusta.",
    p4_title: "Implimentazzjoni mal-UE kollha",
    p4_text: "Implimentazzjoni nazzjonali biss tfixkel il-kummerċ fis-suq uniku. Din teħtieġ koordinazzjoni mal-UE kollha — jew taxxi nazzjonali mfassla b'attenzjoni li ma joħolqux vantaġġi inġusti.",
    examples_label: "03 — Numri Reali",
    examples_title: "Kif tidher fil-prattika?",
    examples_desc: "Bl-użu ta' data eżistenti ta' valutazzjonijiet taċ-ċiklu tal-ħajja u prezz tal-karbonju ta' $100 / ton ta' ekwivalent CO₂.",
    ex_case: "Studju ta' Każ",
    ex_beef: "Ċanga",
    ex_oil: "Żejt Mhux Raffinat",
    ex_lifecycle: "Emissjonijiet taċ-ċiklu tal-ħajja",
    ex_carbon_price: "Prezz tal-karbonju applikat",
    ex_additional_kg: "Spiża addizzjonali għal kull kg",
    ex_additional_barrel: "Spiża addizzjonali għal kull barmil",
    ex_beef_insight: "Jinkludi produzzjoni tal-għalf (fertilizzanti bbażati fuq iż-żejt), metan mill-baqar, bidla fl-użu tal-art, u pproċessar. Il-biċċa l-kbira tal-emissjonijiet ġejjin mill-bijoloġija — mhux biss mill-inputs tal-enerġija.",
    ex_oil_insight: "Impatt sinifikanti fuq il-prezz — iżda l-ispejjeż jiddilwew hekk kif iż-żejt jiġi distribwit f'eluf ta' prodotti 'l isfel. L-akbar impatt jaqa' fuq proċessi kkonċentrati b'emissjonijiet għoljin bħat-trobbija tal-bhejjem, mhux biss fuq inputs industrijali.",
    questions_label: "04 — Lakuni Onesti",
    questions_title: "Mistoqsijiet miftuħa",
    questions_desc: "Ma nippretendu xejn li għandna kull tweġiba. Dawn huma l-problemi diffiċli li għalihom neħtieġu intelliġenza kollettiva.",
    q1: "Liema prezz eżatt tal-karbonju huwa meħtieġ biex ibiddel b'mod sinifikanti l-imġiba tal-konsumaturi u tal-industrija mingħajr ma jikkawża xokk ekonomiku?",
    q2: "Kif ninfurzaw kontabbiltà preċiża taċ-ċiklu tal-ħajja globalment, meta l-ktajjen tal-provvista jinfirxu f'għexieren ta' pajjiżi b'standards differenti?",
    q3: "Kif għandna nittrattaw l-importazzjonijiet minn pajjiżi mhux konformi? L-aġġustamenti tal-karbonju fil-fruntieri huma promettenti iżda politikament u loġistikament kumplessi.",
    q4: "Liema huwa t-triq realistiku lejn il-fattibbiltà politika fi ħdan l-istrutturi tal-UE — u kif nibnu l-koalizzjoni biex naslu hemm?",
    q5: "Kemm nistgħu nagħmlu t-tranżizzjoni malajr mingħajr ma niddestabilizzaw il-għajxien? Kif tidher il-bilanċ it-tajba bejn l-urġenza u l-istabbiltà soċjali?",
    join_label: "05 — Ħu Azzjoni",
    join_title: "Ingħaqad mal-moviment",
    join_desc: "Din l-idea teħtieġ ekonomisti, leġiżlaturi, attivisti, u ċittadini li jemmnu li l-prezz — mhux il-ħtija — huwa dak li jibdel id-dinja. Żid il-vuċi tiegħek.",
    join_placeholder: "tiegħek@email.com",
    join_btn: "Irreġistra",
    join_btn_done: "Miżjud ✓",
    join_note: "L-ebda spam. Aġġornamenti dwar il-progress fil-politika, riċerka, u azzjonijiet li tista' tieħu.",
    footer_mechanism: "Mekkaniżmu",
    footer_data: "Data",
  },

  ga: {
    nav_logo: "Cuir Praghas ar an Damáiste",
    nav_how: "Conas a Oibríonn Sé",
    nav_principles: "Prionsabail",
    nav_examples: "Samplaí",
    nav_questions: "Ceisteanna Oscailte",
    nav_join: "Glac Páirt",
    hero_label: "Creat beartais don ghéarchéim aeráide",
    hero_title: "Déan an truailliú<br><em>costasach</em>.",
    hero_subtitle: "Tá costas comhshaoil folaithe ag gach táirge. Molaimid táille choibhéis CO₂ ar fud an tslabhra soláthair ar fad — ag tiontú damáiste éiceolaíoch ina bhrú eacnamaíoch, agus ioncam á athdháileadh chun daoine a chosaint.",
    hero_btn_primary: "Féach Conas a Oibríonn Sé ↓",
    hero_btn_secondary: "Glac Páirt sa Ghluaiseacht",
    how_label: "01 — Meicníocht",
    how_title: "Táille ag gach céim",
    how_desc: "Cuirtear táillí coibhéis CO₂ i bhfeidhm in aghaidh an tsrutha ag gach pointe sa slabhra soláthair. Carntar an costas iomlán sa phraghas deiridh — rud a fhágann go mbíonn táirgí ardastutha go nádúrtha níos costasaí.",
    stage1_title: "Eastóscadh",
    stage1_desc: "Mianadóireacht amhábhar, druileáil ola, fómhar",
    stage2_title: "Táirgeadh",
    stage2_desc: "Monaraíocht, scagadh, próiseáil",
    stage3_title: "Iompar",
    stage3_desc: "Loingseoireacht, lasta, lóistíocht",
    stage4_title: "Miondíol &amp; Úsáid",
    stage4_desc: "Dáileadh, céim úsáide an tomhaltóra",
    stage5_title: "Diúscairt",
    stage5_desc: "Deireadh saoil trí fhreagracht leathnaithe an táirgeora",
    stage_fee: "+ táille CO₂",
    pipeline_result: "Tá na sonraí ann cheana féin. Clúdaíonn <strong>measúnachtaí saolré (LCA)</strong> agus lorg carbóin táirgí an slabhra iomlán — ón eastóscadh go dtí an diúscairt. Ní eolaíocht nua atá de dhíth orainn. Is toil pholaitiúil atá de dhíth orainn.",
    manifesto: "Athraigh tionchar comhshaoil ina <em>bhrú eacnamaíoch dosheachanta</em>, ansin athdháil an t-airgead chun an tsochaí a choinneáil cobhsaí agus an margadh á iallach <em>dícharbónú</em>.",
    principles_label: "02 — Prionsabail",
    principles_title: "Cad a sheasaimid ar a shon",
    principles_desc: "Ní faoi fheachtais feasachta ná gealltanais dheonacha atá sé seo. Is faoi dhreasachtaí eacnamaíocha a athdhearadh ón mbun aníos atá sé.",
    p1_title: "Praghas, ní feasacht",
    p1_text: "Níor éirigh le blianta fada d'fheachtais feasachta cuar na n-astuithe a chasadh. Athraíonn comharthaí praghais iompar ar scála — go huathoibríoch, go huilíoch, agus láithreach.",
    p2_title: "Cosain daoine, ní truaillitheoirí",
    p2_text: "Téann an t-ioncam chuig earraí poiblí agus íosioncam chun praghsanna níos airde a fhritháireamh. Gan fóirdheontais do chuideachtaí chun \"éirí glas\". Má thruaillíonn tú, íocann tú. Cosnaíonn an t-airgead na saoránaigh.",
    p3_title: "Costas sóisialta an charbóin",
    p3_text: "Tá an táille in aghaidh an tona bunaithe ar an damáiste iarbhír a dhéanann CO₂. Ciallaíonn praghas níos airde athrú iompair níos láidre — ach éilíonn sé freisin athdháileadh sóisialta níos láidre chun é a choinneáil cothrom.",
    p4_title: "Cur i bhfeidhm ar fud an AE",
    p4_text: "Déanann cur i bhfeidhm náisiúnta amháin an trádáil a shaobhadh laistigh den mhargadh aonair. Teastaíonn comhordú ar fud an AE — nó cánacha náisiúnta a dheartar go cúramach nach gcruthaíonn buntáistí éagóracha.",
    examples_label: "03 — Fíoruimhreacha",
    examples_title: "Conas a fhéachann sé seo?",
    examples_desc: "Ag úsáid sonraí reatha measúnachta saolré agus praghas carbóin de $100 / ton de choibhéis CO₂.",
    ex_case: "Cás-Staidéar",
    ex_beef: "Mairteoil",
    ex_oil: "Amhola",
    ex_lifecycle: "Astuithe saolré",
    ex_carbon_price: "Praghas carbóin curtha i bhfeidhm",
    ex_additional_kg: "Costas breise in aghaidh an kg",
    ex_additional_barrel: "Costas breise in aghaidh an bhairille",
    ex_beef_insight: "Áirítear táirgeadh beatha (leasacháin bunaithe ar ola), meatán ó eallaí, athrú ar úsáid talún, agus próiseáil. Tagann formhór na n-astuithe ón mbitheolaíocht — ní ó ionchuir fuinnimh amháin.",
    ex_oil_insight: "Tionchar suntasach ar phraghas — ach caolítear na costais de réir mar a dháiltear an ola thar na mílte táirgí iartheachtacha. Is ar phróisis chomhchruinnithe ardastuthe ar nós tréadchur beostoic is mó a thiteann an tionchar, ní ar ionchuir thionsclaíocha amháin.",
    questions_label: "04 — Bearnaí Macánta",
    questions_title: "Ceisteanna oscailte",
    questions_desc: "Ní ligimid orainn go bhfuil gach freagra againn. Seo iad na fadhbanna deacra a dteastaíonn intleacht chomhchoiteann chun iad a réiteach.",
    q1: "Cén praghas carbóin beacht atá ag teastáil chun iompar tomhaltóirí agus tionsclaíochta a athrú go suntasach gan suaitheadh eacnamaíoch a chruthú?",
    q2: "Conas a fhorfheidhmímid cuntasaíocht bheacht saolré ar fud an domhain, nuair a shíneann slabhraí soláthair thar na scórtha tíortha le caighdeáin éagsúla?",
    q3: "Conas ba cheart dúinn déileáil le hallmhairí ó thíortha neamhchomhlíontacha? Tá coigeartuithe carbóin teorann gealltanach ach casta go polaitiúil agus go lóistíochtúil.",
    q4: "Cad é an cosán réalaíoch chuig indéantacht pholaitiúil laistigh de struchtúir an AE — agus conas a thógaimid an comhghuaillíocht chun é sin a bhaint amach?",
    q5: "Cé chomh tapa is féidir linn aistriú gan slite beatha a dhíchobhsú? Cén chuma atá ar an gcothromaíocht cheart idir práinn agus cobhsaíocht shóisialta?",
    join_label: "05 — Glac Beart",
    join_title: "Glac páirt sa ghluaiseacht",
    join_desc: "Teastaíonn eacnamaithe, lucht déanta beartas, gníomhaithe, agus saoránaigh ón smaoineamh seo — daoine a chreideann gurb é an praghas — ní an chiontacht — a athraíonn an domhan. Cuir do ghuth leis.",
    join_placeholder: "do@ríomhphost.com",
    join_btn: "Cláraigh",
    join_btn_done: "Curtha leis ✓",
    join_note: "Gan turscar. Nuashonruithe ar dhul chun cinn beartais, taighde, agus gníomhartha is féidir leat a dhéanamh.",
    footer_mechanism: "Meicníocht",
    footer_data: "Sonraí",
  },
};
