const TRANS_EAST = {
  pl: {
    nav_logo: "Wyceniaj Szkody",
    nav_how: "Jak to działa",
    nav_principles: "Zasady",
    nav_examples: "Przykłady",
    nav_questions: "Otwarte pytania",
    nav_join: "Dołącz",
    hero_label: "Ramy polityczne dla kryzysu klimatycznego",
    hero_title: "Niech zanieczyszczanie<br><em>kosztuje</em>.",
    hero_subtitle: "Każdy produkt niesie ze sobą ukryty koszt środowiskowy. Proponujemy opłatę za ekwiwalent CO₂ na każdym etapie łańcucha dostaw — przekształcając szkody ekologiczne w presję ekonomiczną i jednocześnie redystrybuując przychody, aby chronić ludzi.",
    hero_btn_primary: "Zobacz, jak to działa ↓",
    hero_btn_secondary: "Dołącz do ruchu",
    how_label: "01 — Mechanizm",
    how_title: "Opłata na każdym etapie",
    how_desc: "Opłaty za ekwiwalent CO₂ są naliczane na każdym etapie łańcucha dostaw. Całkowity koszt kumuluje się w cenie końcowej — sprawiając, że produkty o wysokiej emisji są naturalnie droższe.",
    stage1_title: "Wydobycie",
    stage1_desc: "Wydobycie surowców, odwierty naftowe, pozyskiwanie zasobów",
    stage2_title: "Produkcja",
    stage2_desc: "Wytwarzanie, rafinacja, przetwarzanie",
    stage3_title: "Transport",
    stage3_desc: "Żegluga, fracht, logistyka",
    stage4_title: "Handel i&nbsp;użytkowanie",
    stage4_desc: "Dystrybucja, faza użytkowania przez konsumenta",
    stage5_title: "Utylizacja",
    stage5_desc: "Koniec cyklu życia w ramach rozszerzonej odpowiedzialności producenta",
    stage_fee: "+ opłata CO₂",
    pipeline_result: "Dane już istnieją. <strong>Oceny cyklu życia (LCA)</strong> i ślady węglowe produktów obejmują cały łańcuch — od wydobycia po utylizację. Nie potrzebujemy nowej nauki. Potrzebujemy woli politycznej.",
    manifesto: "Przekształć wpływ na środowisko w <em>nieuniknioną presję ekonomiczną</em>, a następnie redystrybuuj pieniądze, aby utrzymać stabilność społeczną, zmuszając jednocześnie rynek do <em>dekarbonizacji</em>.",
    principles_label: "02 — Zasady",
    principles_title: "Za czym się opowiadamy",
    principles_desc: "Nie chodzi o kampanie uświadamiające ani dobrowolne zobowiązania. Chodzi o przebudowę bodźców ekonomicznych od podstaw.",
    p1_title: "Cena, nie świadomość",
    p1_text: "Dziesięciolecia kampanii uświadamiających nie zmieniły krzywej emisji. Sygnały cenowe zmieniają zachowania na masową skalę — automatycznie, powszechnie i natychmiast.",
    p2_title: "Chrońmy ludzi, nie trucicieli",
    p2_text: "Przychody trafiają na dobra publiczne i dochód minimalny, aby zrekompensować wyższe ceny. Żadnych dotacji dla firm na „zazielenianie się". Jeśli zanieczyszczasz, płacisz. Pieniądze chronią obywateli.",
    p3_title: "Społeczny koszt węgla",
    p3_text: "Opłata za tonę opiera się na rzeczywistych szkodach powodowanych przez CO₂. Wyższa cena oznacza silniejszą zmianę zachowań — ale wymaga też silniejszej redystrybucji społecznej, aby zachować sprawiedliwość.",
    p4_title: "Wdrożenie na poziomie UE",
    p4_text: "Wdrożenie wyłącznie na poziomie krajowym zakłóca handel na jednolitym rynku. Potrzebna jest koordynacja na szczeblu UE — lub starannie zaprojektowane podatki krajowe, które nie tworzą nieuczciwej przewagi.",
    examples_label: "03 — Konkretne liczby",
    examples_title: "Jak to wygląda w praktyce?",
    examples_desc: "Na podstawie istniejących danych z ocen cyklu życia i ceny węgla wynoszącej $100 / ton ekwiwalentu CO₂.",
    ex_case: "Studium przypadku",
    ex_beef: "Wołowina",
    ex_oil: "Ropa naftowa",
    ex_lifecycle: "Emisje w cyklu życia",
    ex_carbon_price: "Zastosowana cena węgla",
    ex_additional_kg: "Dodatkowy koszt za kg",
    ex_additional_barrel: "Dodatkowy koszt za baryłkę",
    ex_beef_insight: "Obejmuje produkcję pasz (nawozy na bazie ropy), metan od bydła, zmianę użytkowania gruntów i przetwórstwo. Większość emisji pochodzi z biologii — nie tylko z nakładów energetycznych.",
    ex_oil_insight: "Znaczący wpływ na cenę — ale koszty rozkładają się, gdy ropa jest dystrybuowana na tysiące produktów pochodnych. Największy wpływ dotyczy skoncentrowanych procesów o wysokiej emisji, jak hodowla zwierząt, a nie samych surowców przemysłowych.",
    questions_label: "04 — Uczciwe luki",
    questions_title: "Otwarte pytania",
    questions_desc: "Nie udajemy, że mamy odpowiedzi na wszystko. Oto trudne problemy, które wymagają zbiorowej inteligencji.",
    q1: "Jaka dokładna cena węgla jest potrzebna, aby w sposób znaczący zmienić zachowania konsumentów i przemysłu, nie wywołując szoku gospodarczego?",
    q2: "Jak egzekwować dokładne rozliczanie cyklu życia na skalę globalną, skoro łańcuchy dostaw obejmują dziesiątki krajów o różnych standardach?",
    q3: "Jak powinniśmy traktować import z krajów niestosujących się do systemu? Graniczne mechanizmy węglowe są obiecujące, ale politycznie i logistycznie złożone.",
    q4: "Jaka jest realistyczna droga do wykonalności politycznej w strukturach UE — i jak zbudować koalicję, by to osiągnąć?",
    q5: "Jak szybko możemy przeprowadzić transformację, nie destabilizując źródeł utrzymania? Jak wygląda właściwa równowaga między pilnością a stabilnością społeczną?",
    join_label: "05 — Działaj",
    join_title: "Dołącz do ruchu",
    join_desc: "Ta idea potrzebuje ekonomistów, decydentów politycznych, aktywistów i obywateli, którzy wierzą, że to cena — nie poczucie winy — zmienia świat. Dołącz swój głos.",
    join_placeholder: "twoj@email.pl",
    join_btn: "Zapisz się",
    join_btn_done: "Dodano ✓",
    join_note: "Żadnego spamu. Informacje o postępach politycznych, badaniach i działaniach, które możesz podjąć.",
    footer_mechanism: "Mechanizm",
    footer_data: "Dane",
    calc_label: "03.5 \u2014 Spr\u00f3buj sam",
    calc_title: "Wyce\u0144 szkody",
    calc_desc: "Zobacz, ile naprawd\u0119 kosztowa\u0142yby codzienne produkty, gdyby szkody \u015brodowiskowe by\u0142y wliczone w cen\u0119.",
    calc_cat_label: "Kategoria",
    calc_prod_label: "Produkt",
    calc_qty_label: "Ilo\u015b\u0107",
    calc_unit_label: "Jednostka",
    calc_price_label: "Cena w\u0119gla",
    calc_cat_food: "\u017bywno\u015b\u0107 i napoje",
    calc_cat_clothing: "Odzie\u017c (wg materia\u0142u)",
    calc_cat_electronics: "Elektronika (wg rozmiaru)",
    calc_cat_travel: "Podr\u00f3\u017ce",
    calc_cat_fuel: "Paliwo",
    calc_price_50: "$50 / ton",
    calc_price_100: "$100 / ton",
    calc_price_150: "$150 / ton",
    calc_price_200: "$200 / ton",
    calc_eco_label: "Certyfikat ekologiczny / \u017ar\u00f3d\u0142o organiczne (zmniejsza szacunek o ~15%)",
    calc_result_label: "\u015alad CO\u2082",
    calc_sources: "\u0179r\u00f3d\u0142a: Poore & Nemecek (2018), <a href=\"https://doi.org/10.1126/science.aaq0216\" target=\"_blank\" rel=\"noopener\"><em>Science</em> 360:987</a> (\u017cywno\u015b\u0107) \u00b7 <a href=\"https://www.gov.uk/government/collections/government-conversion-factors-for-company-reporting\" target=\"_blank\" rel=\"noopener\">UK DEFRA 2023</a> (paliwo/loty) \u00b7 Apple/Levi\u2019s Product Environmental Reports (elektronika/odzie\u017c)",
    calc_damage_cost: "koszt szk\u00f3d",
    calc_eco_note: "(eko-certyfikat: \u221215%)",
    calc_prod_beef: "Wo\u0142owina",
    calc_prod_chicken: "Kurczak",
    calc_prod_cheese: "Ser",
    calc_prod_milk: "Mleko (krowie)",
    calc_prod_rice: "Ry\u017c",
    calc_prod_coffee: "Kawa (palona)",
    calc_prod_chocolate: "Ciemna czekolada",
    calc_prod_tomatoes: "Pomidory",
    calc_prod_potatoes: "Ziemniaki",
    calc_prod_eggs: "Jajka",
    calc_prod_bread: "Chleb (pszenny)",
    calc_prod_cotton_tshirt: "Bawe\u0142na \u2014 T-shirt (250g)",
    calc_prod_cotton_jeans: "Bawe\u0142na \u2014 D\u017cinsy (denim)",
    calc_prod_polyester_shirt: "Poliester \u2014 Koszula",
    calc_prod_polyester_jacket: "Poliester \u2014 Kurtka",
    calc_prod_wool_sweater: "We\u0142na \u2014 Sweter",
    calc_prod_wool_coat: "We\u0142na \u2014 P\u0142aszcz",
    calc_prod_leather_shoes: "Sk\u00f3ra \u2014 Buty",
    calc_prod_nylon_sneakers: "Nylon/Mix \u2014 Trampki",
    calc_prod_smartphone: "Rozmiar telefonu (smartfon)",
    calc_prod_tablet: "Rozmiar tabletu (10\u2033)",
    calc_prod_laptop: "Rozmiar laptopa (13\u201316\u2033)",
    calc_prod_monitor: "Rozmiar monitora (24\u201327\u2033)",
    calc_prod_tv: "Rozmiar telewizora (50\u201365\u2033)",
    calc_prod_desktop: "Komputer stacjonarny (wie\u017ca)",
    calc_prod_flight_short: "Lot \u2014 kr\u00f3tkodystansowy (<3h)",
    calc_prod_flight_long: "Lot \u2014 d\u0142ugodystansowy (>6h)",
    calc_prod_car_petrol: "Samoch\u00f3d \u2014 benzyna (\u015br.)",
    calc_prod_car_diesel: "Samoch\u00f3d \u2014 diesel (\u015br.)",
    calc_prod_train: "Poci\u0105g (kolej krajowa)",
    calc_prod_bus: "Autobus (dalekob.)",
    calc_prod_petrol: "Benzyna",
    calc_prod_diesel: "Olej nap\u0119dowy",
    calc_prod_natural_gas: "Gaz ziemny (ogrzewanie)",
    calc_prod_electricity_eu: "Energia elektryczna (\u015br. UE)",
    calc_note_beef: "Mediana globalnego LCA; zakres 20\u2013105 kg CO\u2082e/kg",
    calc_note_chicken: "Obejmuje u\u017cytkowanie grunt\u00f3w, pasz\u0119, przetw\u00f3rstwo",
    calc_note_cheese: "~10 litr\u00f3w mleka na kg sera",
    calc_note_milk: "Obejmuje fermentacj\u0119 jelitow\u0105 i u\u017cytkowanie grunt\u00f3w",
    calc_note_rice: "Dominuje metan z zalanych p\u00f3l ry\u017cowych",
    calc_note_coffee: "Zakres 3,5\u201328,5; silnie zale\u017cne od u\u017cytkowania grunt\u00f3w",
    calc_note_chocolate: "Wysoki udzia\u0142 wylesiania w \u0142a\u0144cuchu dostaw kakao",
    calc_note_tomatoes: "Uprawa polowa; ogrzewana szklarnia ~2,1",
    calc_note_potatoes: "Jeden z produkt\u00f3w skrobiowych o najni\u017cszej emisji",
    calc_note_eggs: "~12 jajek na kg",
    calc_note_bread: "Standardowy chleb pszenny",
    calc_note_cotton_tshirt: "Uprawa bawe\u0142ny to ~po\u0142owa \u015bladu",
    calc_note_cotton_jeans: "Pe\u0142ny cykl \u017cycia: od uprawy po utylizacj\u0119",
    calc_note_polyester_shirt: "W\u0142\u00f3kno pochodz\u0105ce z paliw kopalnych",
    calc_note_polyester_jacket: "Syntetyczne wype\u0142nienie + pow\u0142oka na bazie ropy",
    calc_note_wool_sweater: "Metan od owiec + przetw\u00f3rstwo",
    calc_note_wool_coat: "Ci\u0119\u017cka we\u0142na; wysoki wp\u0142yw metanu + barwienia",
    calc_note_leather_shoes: "Hodowla byd\u0142a + chemikalia garbarskie",
    calc_note_nylon_sneakers: "Mieszane materia\u0142y; dominuje produkcja",
    calc_note_smartphone: "Produkcja to ~80% \u015bladu; 3-letni cykl \u017cycia",
    calc_note_tablet: "Mi\u0119dzy telefonem a laptopem pod wzgl\u0119dem wp\u0142ywu",
    calc_note_laptop: "Zakres 150\u2013400 kg; zale\u017cy od komponent\u00f3w",
    calc_note_monitor: "Produkcja wy\u015bwietlacza + wieloletnie u\u017cytkowanie",
    calc_note_tv: "Du\u017cy wy\u015bwietlacz + 7-letnie zu\u017cycie energii",
    calc_note_desktop: "Wy\u017csze zu\u017cycie energii; d\u0142u\u017csza \u017cywotno\u015b\u0107 komponent\u00f3w",
    calc_note_flight_short: "Na pasa\u017cera, klasa ekonomiczna; uwzgl\u0119dnia wymuszenie radiacyjne",
    calc_note_flight_long: "Wydajniejszy na km przy d\u0142u\u017cszych dystansach",
    calc_note_car_petrol: "\u015aredni europejski samoch\u00f3d benzynowy ~210g CO\u2082/km",
    calc_note_car_diesel: "Nieco ni\u017csze CO\u2082 na km ni\u017c benzyna",
    calc_note_train: "Znacznie si\u0119 r\u00f3\u017cni w zale\u017cno\u015bci od sieci elektr.; \u015br. UE",
    calc_note_bus: "Na pasa\u017cera; za\u0142o\u017cone wysokie obci\u0105\u017cenie",
    calc_note_petrol: "Od szybu do ko\u0142a, w tym wydobycie",
    calc_note_diesel: "Nieco wi\u0119cej na litr ni\u017c benzyna",
    calc_note_natural_gas: "Spalanie + wycieki metanu na etapie wydobycia",
    calc_note_electricity_eu: "\u015arednia sieci UE; r\u00f3\u017cni si\u0119 w zale\u017cno\u015bci od kraju",
  },
  cs: {
    nav_logo: "Oceňte škody",
    nav_how: "Jak to funguje",
    nav_principles: "Principy",
    nav_examples: "Příklady",
    nav_questions: "Otevřené otázky",
    nav_join: "Přidejte se",
    hero_label: "Politický rámec pro klimatickou krizi",
    hero_title: "Ať znečišťování<br><em>stojí</em>.",
    hero_subtitle: "Každý produkt nese skryté environmentální náklady. Navrhujeme poplatek za ekvivalent CO₂ v celém dodavatelském řetězci — přeměňující ekologické škody na ekonomický tlak a zároveň přerozdělující příjmy na ochranu lidí.",
    hero_btn_primary: "Podívejte se, jak to funguje ↓",
    hero_btn_secondary: "Přidejte se k hnutí",
    how_label: "01 — Mechanismus",
    how_title: "Poplatek v každé fázi",
    how_desc: "Poplatky za ekvivalent CO₂ se uplatňují v každém bodě dodavatelského řetězce. Celkové náklady se kumulují do konečné ceny — produkty s vysokými emisemi jsou tak přirozeně dražší.",
    stage1_title: "Těžba",
    stage1_desc: "Těžba surovin, vrtání ropy, sklizeň",
    stage2_title: "Výroba",
    stage2_desc: "Zpracování, rafinace, průmyslová výroba",
    stage3_title: "Doprava",
    stage3_desc: "Lodní přeprava, nákladní doprava, logistika",
    stage4_title: "Prodej a&nbsp;užívání",
    stage4_desc: "Distribuce, fáze spotřebitelského užívání",
    stage5_title: "Likvidace",
    stage5_desc: "Konec životního cyklu v rámci rozšířené odpovědnosti výrobce",
    stage_fee: "+ poplatek CO₂",
    pipeline_result: "Data již existují. <strong>Posouzení životního cyklu (LCA)</strong> a uhlíkové stopy produktů pokrývají celý řetězec — od těžby po likvidaci. Nepotřebujeme novou vědu. Potřebujeme politickou vůli.",
    manifesto: "Přeměňte dopad na životní prostředí v <em>nevyhnutelný ekonomický tlak</em> a poté přerozdělte peníze, aby společnost zůstala stabilní, zatímco trh bude nucen k <em>dekarbonizaci</em>.",
    principles_label: "02 — Principy",
    principles_title: "Za čím stojíme",
    principles_desc: "Nejde o osvětové kampaně ani dobrovolné závazky. Jde o přestavbu ekonomických pobídek od základů.",
    p1_title: "Cena, nikoli osvěta",
    p1_text: "Desetiletí osvětových kampaní nezměnila křivku emisí. Cenové signály mění chování ve velkém měřítku — automaticky, univerzálně a okamžitě.",
    p2_title: "Chraňme lidi, ne znečišťovatele",
    p2_text: "Příjmy směřují na veřejné statky a minimální příjem k vyrovnání vyšších cen. Žádné dotace firmám na „ekologizaci". Kdo znečišťuje, platí. Peníze chrání občany.",
    p3_title: "Společenské náklady uhlíku",
    p3_text: "Poplatek za tunu vychází ze skutečných škod způsobených CO₂. Vyšší cena znamená silnější změnu chování — ale také vyžaduje silnější sociální přerozdělování, aby to zůstalo spravedlivé.",
    p4_title: "Celoevropská implementace",
    p4_text: "Implementace pouze na národní úrovni narušuje obchod na jednotném trhu. Je zapotřebí celoevropská koordinace — nebo pečlivě navržené národní daně, které nevytvářejí nespravedlivé výhody.",
    examples_label: "03 — Reálná čísla",
    examples_title: "Jak to vypadá v praxi?",
    examples_desc: "Na základě existujících dat z posouzení životního cyklu a ceny uhlíku $100 / ton ekvivalentu CO₂.",
    ex_case: "Případová studie",
    ex_beef: "Hovězí maso",
    ex_oil: "Ropa",
    ex_lifecycle: "Emise za životní cyklus",
    ex_carbon_price: "Uplatněná cena uhlíku",
    ex_additional_kg: "Dodatečné náklady na kg",
    ex_additional_barrel: "Dodatečné náklady na barel",
    ex_beef_insight: "Zahrnuje výrobu krmiv (ropná hnojiva), metan ze skotu, změnu využití půdy a zpracování. Většina emisí pochází z biologie — nejen z energetických vstupů.",
    ex_oil_insight: "Výrazný dopad na cenu — ale náklady se rozmělňují, když se ropa distribuuje do tisíců navazujících produktů. Největší dopad dopadá na koncentrované procesy s vysokými emisemi, jako je chov dobytka, nikoli jen na průmyslové vstupy.",
    questions_label: "04 — Upřímné mezery",
    questions_title: "Otevřené otázky",
    questions_desc: "Nepředstíráme, že máme všechny odpovědi. Toto jsou obtížné problémy, které vyžadují kolektivní inteligenci.",
    q1: "Jaká přesná cena uhlíku je potřeba k významné změně spotřebitelského a průmyslového chování, aniž by způsobila ekonomický šok?",
    q2: "Jak zajistit přesné celosvětové účtování životního cyklu, když dodavatelské řetězce procházejí desítkami zemí s různými standardy?",
    q3: "Jak bychom měli zacházet s dovozem ze zemí, které systém nedodržují? Uhlíkové hraniční mechanismy jsou slibné, ale politicky a logisticky složité.",
    q4: "Jaká je realistická cesta k politické proveditelnosti v rámci struktur EU — a jak vybudovat koalici, která toho dosáhne?",
    q5: "Jak rychle můžeme provést transformaci, aniž bychom destabilizovali živobytí? Jak vypadá správná rovnováha mezi naléhavostí a společenskou stabilitou?",
    join_label: "05 — Jednejte",
    join_title: "Přidejte se k hnutí",
    join_desc: "Tato myšlenka potřebuje ekonomy, tvůrce politik, aktivisty a občany, kteří věří, že cena — nikoli pocit viny — mění svět. Přidejte svůj hlas.",
    join_placeholder: "vas@email.cz",
    join_btn: "Zaregistrovat se",
    join_btn_done: "Přidáno ✓",
    join_note: "Žádný spam. Informace o pokroku politik, výzkumu a akcích, které můžete podniknout.",
    footer_mechanism: "Mechanismus",
    footer_data: "Data",
    calc_label: "03.5 \u2014 Vyzkou\u0161ejte sami",
    calc_title: "Oce\u0148te \u0161kody",
    calc_desc: "Pod\u00edvejte se, kolik by ka\u017edodenn\u00ed produkty skute\u010dn\u011b st\u00e1ly, kdyby \u0161kody na \u017eivotn\u00edm prost\u0159ed\u00ed byly zahrnuty v cen\u011b.",
    calc_cat_label: "Kategorie",
    calc_prod_label: "Produkt",
    calc_qty_label: "Mno\u017estv\u00ed",
    calc_unit_label: "Jednotka",
    calc_price_label: "Cena uhl\u00edku",
    calc_cat_food: "Potraviny a n\u00e1poje",
    calc_cat_clothing: "Od\u011bvy (podle materi\u00e1lu)",
    calc_cat_electronics: "Elektronika (podle velikosti)",
    calc_cat_travel: "Cestov\u00e1n\u00ed",
    calc_cat_fuel: "Palivo",
    calc_price_50: "$50 / ton",
    calc_price_100: "$100 / ton",
    calc_price_150: "$150 / ton",
    calc_price_200: "$200 / ton",
    calc_eco_label: "Ekologicky certifikovan\u00fd / organick\u00fd zdroj (sni\u017euje odhad o ~15 %)",
    calc_result_label: "Uhl\u00edkov\u00e1 stopa CO\u2082",
    calc_sources: "Zdroje: Poore & Nemecek (2018), <a href=\"https://doi.org/10.1126/science.aaq0216\" target=\"_blank\" rel=\"noopener\"><em>Science</em> 360:987</a> (potraviny) \u00b7 <a href=\"https://www.gov.uk/government/collections/government-conversion-factors-for-company-reporting\" target=\"_blank\" rel=\"noopener\">UK DEFRA 2023</a> (palivo/lety) \u00b7 Apple/Levi\u2019s Product Environmental Reports (elektronika/od\u011bvy)",
    calc_damage_cost: "n\u00e1klady na \u0161kody",
    calc_eco_note: "(eko-certifikov\u00e1no: \u221215 %)",
    calc_prod_beef: "Hov\u011bz\u00ed maso",
    calc_prod_chicken: "Ku\u0159ec\u00ed maso",
    calc_prod_cheese: "S\u00fdr",
    calc_prod_milk: "Ml\u00e9ko (kravsk\u00e9)",
    calc_prod_rice: "R\u00fd\u017ee",
    calc_prod_coffee: "K\u00e1va (pra\u017een\u00e1)",
    calc_prod_chocolate: "Tmav\u00e1 \u010dokol\u00e1da",
    calc_prod_tomatoes: "Raj\u010data",
    calc_prod_potatoes: "Brambory",
    calc_prod_eggs: "Vejce",
    calc_prod_bread: "Chl\u00e9b (p\u0161eni\u010dn\u00fd)",
    calc_prod_cotton_tshirt: "Bavlna \u2014 Tri\u010dko (250g)",
    calc_prod_cotton_jeans: "Bavlna \u2014 D\u017e\u00edny (denim)",
    calc_prod_polyester_shirt: "Polyester \u2014 Ko\u0161ile",
    calc_prod_polyester_jacket: "Polyester \u2014 Bunda",
    calc_prod_wool_sweater: "Vlna \u2014 Sveter",
    calc_prod_wool_coat: "Vlna \u2014 Kab\u00e1t",
    calc_prod_leather_shoes: "K\u016f\u017ee \u2014 Boty",
    calc_prod_nylon_sneakers: "Nylon/Mix \u2014 Tenisky",
    calc_prod_smartphone: "Velikost telefonu (smartphone)",
    calc_prod_tablet: "Velikost tabletu (10\u2033)",
    calc_prod_laptop: "Velikost notebooku (13\u201316\u2033)",
    calc_prod_monitor: "Velikost monitoru (24\u201327\u2033)",
    calc_prod_tv: "Velikost televizoru (50\u201365\u2033)",
    calc_prod_desktop: "Stoln\u00ed po\u010d\u00edta\u010d (v\u011b\u017e)",
    calc_prod_flight_short: "Let \u2014 kr\u00e1tk\u00fd (<3h)",
    calc_prod_flight_long: "Let \u2014 dlouh\u00fd (>6h)",
    calc_prod_car_petrol: "Auto \u2014 benz\u00edn (pr\u016fm.)",
    calc_prod_car_diesel: "Auto \u2014 nafta (pr\u016fm.)",
    calc_prod_train: "Vlak (vnitrost\u00e1tn\u00ed)",
    calc_prod_bus: "Autobus (d\u00e1lkov\u00fd)",
    calc_prod_petrol: "Benz\u00edn",
    calc_prod_diesel: "Nafta",
    calc_prod_natural_gas: "Zemn\u00ed plyn (vyt\u00e1p\u011bn\u00ed)",
    calc_prod_electricity_eu: "Elekt\u0159ina (pr\u016fm. EU)",
    calc_note_beef: "Medi\u00e1n glob\u00e1ln\u00edho LCA; rozsah 20\u2013105 kg CO\u2082e/kg",
    calc_note_chicken: "Zahrnuje vyu\u017eit\u00ed p\u016fdy, krmivo, zpracov\u00e1n\u00ed",
    calc_note_cheese: "~10 litr\u016f ml\u00e9ka na kg s\u00fdra",
    calc_note_milk: "Zahrnuje enter\u00e1ln\u00ed fermentaci a vyu\u017eit\u00ed p\u016fdy",
    calc_note_rice: "Dominuje metan ze zaplavovan\u00fdch pol\u00ed",
    calc_note_coffee: "Rozsah 3,5\u201328,5; siln\u011b z\u00e1visl\u00e9 na vyu\u017eit\u00ed p\u016fdy",
    calc_note_chocolate: "Vysok\u00fd pod\u00edl odlesn\u011bn\u00ed v dodavatelsk\u00e9m \u0159et\u011bzci kakaa",
    calc_note_tomatoes: "Polní p\u011bstov\u00e1n\u00ed; vyt\u00e1p\u011bn\u00fd sklen\u00edk ~2,1",
    calc_note_potatoes: "Jedna z \u0161krob. potravin s nejni\u017e\u0161\u00edmi emisemi",
    calc_note_eggs: "~12 vajec na kg",
    calc_note_bread: "Standardn\u00ed p\u0161eni\u010dn\u00fd chl\u00e9b",
    calc_note_cotton_tshirt: "P\u011bstov\u00e1n\u00ed bavlny tvo\u0159\u00ed ~polovinu stopy",
    calc_note_cotton_jeans: "Cel\u00fd \u017eivotn\u00ed cyklus: od p\u011bstov\u00e1n\u00ed po likvidaci",
    calc_note_polyester_shirt: "Vl\u00e1kno z fosiln\u00edch paliv",
    calc_note_polyester_jacket: "Syntetick\u00e1 v\u00fdpl\u0148 + pl\u00e1\u0161\u0165 na b\u00e1zi ropy",
    calc_note_wool_sweater: "Metan z ovc\u00ed + zpracov\u00e1n\u00ed",
    calc_note_wool_coat: "T\u011b\u017ek\u00e1 vlna; vysok\u00fd dopad metanu + barven\u00ed",
    calc_note_leather_shoes: "Chov skotu + \u010dinic\u00ed chemik\u00e1lie",
    calc_note_nylon_sneakers: "Sm\u00ed\u0161en\u00e9 materi\u00e1ly; dominuje v\u00fdroba",
    calc_note_smartphone: "V\u00fdroba tvo\u0159\u00ed ~80 % stopy; 3let\u00e1 \u017eivotnost",
    calc_note_tablet: "Mezi telefonem a notebookem co do dopadu",
    calc_note_laptop: "Rozsah 150\u2013400 kg; z\u00e1vis\u00ed na komponentech",
    calc_note_monitor: "V\u00fdroba displeje + v\u00edcelet\u00e9 u\u017e\u00edv\u00e1n\u00ed",
    calc_note_tv: "Velk\u00fd displej + 7let\u00e1 spot\u0159eba elekt\u0159iny",
    calc_note_desktop: "Vy\u0161\u0161\u00ed spot\u0159eba; del\u0161\u00ed \u017eivotnost komponent\u016f",
    calc_note_flight_short: "Na cestuj\u00edc\u00edho, ekonomick\u00e1 t\u0159\u00edda; zahrnuje radia\u010dn\u00ed p\u016fsoben\u00ed",
    calc_note_flight_long: "\u00da\u010dinn\u011bj\u0161\u00ed na km p\u0159i del\u0161\u00edch vzd\u00e1lenostech",
    calc_note_car_petrol: "Pr\u016fm\u011brn\u00e9 evropsk\u00e9 benz\u00ednov\u00e9 auto ~210g CO\u2082/km",
    calc_note_car_diesel: "M\u00edrn\u011b ni\u017e\u0161\u00ed CO\u2082 na km ne\u017e benz\u00edn",
    calc_note_train: "Velmi se li\u0161\u00ed podle elektrick\u00e9 s\u00edt\u011b; pr\u016fm\u011br EU",
    calc_note_bus: "Na cestuj\u00edc\u00edho; p\u0159edpokl\u00e1d\u00e1 se vysok\u00e9 obsazen\u00ed",
    calc_note_petrol: "Od vrtu po kolo v\u010detn\u011b t\u011b\u017eby",
    calc_note_diesel: "M\u00edrn\u011b v\u00edce na litr ne\u017e benz\u00edn",
    calc_note_natural_gas: "Spalov\u00e1n\u00ed + \u00faniky metanu p\u0159i t\u011b\u017eb\u011b",
    calc_note_electricity_eu: "Pr\u016fm\u011br s\u00edt\u011b EU; li\u0161\u00ed se podle zem\u011b",
  },
  sk: {
    nav_logo: "Oceňte škody",
    nav_how: "Ako to funguje",
    nav_principles: "Princípy",
    nav_examples: "Príklady",
    nav_questions: "Otvorené otázky",
    nav_join: "Pridajte sa",
    hero_label: "Politický rámec pre klimatickú krízu",
    hero_title: "Nech znečisťovanie<br><em>stojí</em>.",
    hero_subtitle: "Každý produkt nesie skryté environmentálne náklady. Navrhujeme poplatok za ekvivalent CO₂ v celom dodávateľskom reťazci — premieňajúc ekologické škody na ekonomický tlak a zároveň prerozdeľujúc príjmy na ochranu ľudí.",
    hero_btn_primary: "Pozrite sa, ako to funguje ↓",
    hero_btn_secondary: "Pridajte sa k hnutiu",
    how_label: "01 — Mechanizmus",
    how_title: "Poplatok v každej fáze",
    how_desc: "Poplatky za ekvivalent CO₂ sa uplatňujú v každom bode dodávateľského reťazca. Celkové náklady sa kumulujú do konečnej ceny — produkty s vysokými emisiami sú tak prirodzene drahšie.",
    stage1_title: "Ťažba",
    stage1_desc: "Ťažba surovín, vŕtanie ropy, zber",
    stage2_title: "Výroba",
    stage2_desc: "Spracovanie, rafinácia, priemyselná výroba",
    stage3_title: "Doprava",
    stage3_desc: "Lodná preprava, nákladná doprava, logistika",
    stage4_title: "Predaj a&nbsp;používanie",
    stage4_desc: "Distribúcia, fáza spotrebiteľského používania",
    stage5_title: "Likvidácia",
    stage5_desc: "Koniec životného cyklu v rámci rozšírenej zodpovednosti výrobcu",
    stage_fee: "+ poplatok CO₂",
    pipeline_result: "Údaje už existujú. <strong>Posúdenia životného cyklu (LCA)</strong> a uhlíkové stopy produktov pokrývajú celý reťazec — od ťažby po likvidáciu. Nepotrebujeme novú vedu. Potrebujeme politickú vôľu.",
    manifesto: "Premeňte vplyv na životné prostredie na <em>neodvrátiteľný ekonomický tlak</em> a potom prerozdeľte peniaze, aby spoločnosť zostala stabilná, zatiaľ čo trh bude nútený k <em>dekarbonizácii</em>.",
    principles_label: "02 — Princípy",
    principles_title: "Za čím stojíme",
    principles_desc: "Nejde o osvetové kampane ani dobrovoľné záväzky. Ide o prestavbu ekonomických stimulov od základov.",
    p1_title: "Cena, nie osveta",
    p1_text: "Desaťročia osvetových kampaní nezmenili krivku emisií. Cenové signály menia správanie vo veľkom meradle — automaticky, univerzálne a okamžite.",
    p2_title: "Chráňme ľudí, nie znečisťovateľov",
    p2_text: "Príjmy smerujú na verejné statky a minimálny príjem na kompenzáciu vyšších cien. Žiadne dotácie pre firmy na „ekologizáciu". Kto znečisťuje, platí. Peniaze chránia občanov.",
    p3_title: "Spoločenské náklady uhlíka",
    p3_text: "Poplatok za tonu vychádza zo skutočných škôd spôsobených CO₂. Vyššia cena znamená silnejšiu zmenu správania — ale vyžaduje aj silnejšie sociálne prerozdeľovanie, aby to zostalo spravodlivé.",
    p4_title: "Celoeurópska implementácia",
    p4_text: "Implementácia iba na národnej úrovni narúša obchod na jednotnom trhu. Je potrebná celoeurópska koordinácia — alebo starostlivo navrhnuté národné dane, ktoré nevytvárajú nespravodlivé výhody.",
    examples_label: "03 — Reálne čísla",
    examples_title: "Ako to vyzerá v praxi?",
    examples_desc: "Na základe existujúcich údajov z posúdení životného cyklu a ceny uhlíka $100 / ton ekvivalentu CO₂.",
    ex_case: "Prípadová štúdia",
    ex_beef: "Hovädzie mäso",
    ex_oil: "Ropa",
    ex_lifecycle: "Emisie za životný cyklus",
    ex_carbon_price: "Uplatnená cena uhlíka",
    ex_additional_kg: "Dodatočné náklady na kg",
    ex_additional_barrel: "Dodatočné náklady na barel",
    ex_beef_insight: "Zahŕňa výrobu krmív (ropné hnojivá), metán z dobytka, zmenu využívania pôdy a spracovanie. Väčšina emisií pochádza z biológie — nielen z energetických vstupov.",
    ex_oil_insight: "Výrazný vplyv na cenu — ale náklady sa rozkladajú, keď sa ropa distribuuje do tisícov nadväzujúcich produktov. Najväčší vplyv dopadá na koncentrované procesy s vysokými emisiami, ako je chov dobytka, nie len na priemyselné vstupy.",
    questions_label: "04 — Úprimné medzery",
    questions_title: "Otvorené otázky",
    questions_desc: "Nepredstierame, že máme všetky odpovede. Toto sú ťažké problémy, ktoré vyžadujú kolektívnu inteligenciu.",
    q1: "Aká presná cena uhlíka je potrebná na významnú zmenu spotrebiteľského a priemyselného správania bez vyvolania ekonomického šoku?",
    q2: "Ako presadiť presné celosvetové účtovanie životného cyklu, keď dodávateľské reťazce prechádzajú desiatkami krajín s rôznymi štandardmi?",
    q3: "Ako by sme mali zaobchádzať s dovozom z krajín, ktoré systém nedodržiavajú? Uhlíkové hraničné mechanizmy sú sľubné, ale politicky a logisticky zložité.",
    q4: "Aká je realistická cesta k politickej uskutočniteľnosti v rámci štruktúr EÚ — a ako vybudovať koalíciu, ktorá to dosiahne?",
    q5: "Ako rýchlo môžeme uskutočniť transformáciu bez destabilizácie živobytia? Ako vyzerá správna rovnováha medzi naliehavosťou a spoločenskou stabilitou?",
    join_label: "05 — Konajte",
    join_title: "Pridajte sa k hnutiu",
    join_desc: "Táto myšlienka potrebuje ekonómov, tvorcov politík, aktivistov a občanov, ktorí veria, že cena — nie pocit viny — mení svet. Pridajte svoj hlas.",
    join_placeholder: "vas@email.sk",
    join_btn: "Zaregistrovať sa",
    join_btn_done: "Pridané ✓",
    join_note: "Žiadny spam. Informácie o pokroku politík, výskume a akciách, ktoré môžete podniknúť.",
    footer_mechanism: "Mechanizmus",
    footer_data: "Údaje",
    calc_label: "03.5 \u2014 Vysk\u00fa\u0161ajte sami",
    calc_title: "Oce\u0148te \u0161kody",
    calc_desc: "Pozrite sa, ko\u013eko by ka\u017edodenn\u00e9 produkty skuto\u010dne st\u00e1li, keby boli \u0161kody na \u017eivotnom prostred\u00ed zahrnut\u00e9 v cene.",
    calc_cat_label: "Kateg\u00f3ria",
    calc_prod_label: "Produkt",
    calc_qty_label: "Mno\u017estvo",
    calc_unit_label: "Jednotka",
    calc_price_label: "Cena uhl\u00edka",
    calc_cat_food: "Potraviny a n\u00e1poje",
    calc_cat_clothing: "Odev (pod\u013ea materi\u00e1lu)",
    calc_cat_electronics: "Elektronika (pod\u013ea ve\u013ekosti)",
    calc_cat_travel: "Cestovanie",
    calc_cat_fuel: "Palivo",
    calc_price_50: "$50 / ton",
    calc_price_100: "$100 / ton",
    calc_price_150: "$150 / ton",
    calc_price_200: "$200 / ton",
    calc_eco_label: "Ekologicky certifikovan\u00fd / organick\u00fd zdroj (zni\u017euje odhad o ~15 %)",
    calc_result_label: "Uhl\u00edkov\u00e1 stopa CO\u2082",
    calc_sources: "Zdroje: Poore & Nemecek (2018), <a href=\"https://doi.org/10.1126/science.aaq0216\" target=\"_blank\" rel=\"noopener\"><em>Science</em> 360:987</a> (potraviny) \u00b7 <a href=\"https://www.gov.uk/government/collections/government-conversion-factors-for-company-reporting\" target=\"_blank\" rel=\"noopener\">UK DEFRA 2023</a> (palivo/lety) \u00b7 Apple/Levi\u2019s Product Environmental Reports (elektronika/odev)",
    calc_damage_cost: "n\u00e1klady na \u0161kody",
    calc_eco_note: "(eko-certifikovan\u00e9: \u221215 %)",
    calc_prod_beef: "Hov\u00e4dzie m\u00e4so",
    calc_prod_chicken: "Kuracie m\u00e4so",
    calc_prod_cheese: "Syr",
    calc_prod_milk: "Mlieko (kravsk\u00e9)",
    calc_prod_rice: "Ry\u017ea",
    calc_prod_coffee: "K\u00e1va (pra\u017een\u00e1)",
    calc_prod_chocolate: "Tmav\u00e1 \u010dokol\u00e1da",
    calc_prod_tomatoes: "Paradajky",
    calc_prod_potatoes: "Zemiaky",
    calc_prod_eggs: "Vajcia",
    calc_prod_bread: "Chlieb (p\u0161eni\u010dn\u00fd)",
    calc_prod_cotton_tshirt: "Bavlna \u2014 Tri\u010dko (250g)",
    calc_prod_cotton_jeans: "Bavlna \u2014 D\u017e\u00ednsy (denim)",
    calc_prod_polyester_shirt: "Polyester \u2014 Ko\u0161e\u013ea",
    calc_prod_polyester_jacket: "Polyester \u2014 Bunda",
    calc_prod_wool_sweater: "Vlna \u2014 Sveter",
    calc_prod_wool_coat: "Vlna \u2014 Kab\u00e1t",
    calc_prod_leather_shoes: "Ko\u017ea \u2014 Top\u00e1nky",
    calc_prod_nylon_sneakers: "Nylon/Mix \u2014 Tenisky",
    calc_prod_smartphone: "Ve\u013ekos\u0165 telef\u00f3nu (smartf\u00f3n)",
    calc_prod_tablet: "Ve\u013ekos\u0165 tabletu (10\u2033)",
    calc_prod_laptop: "Ve\u013ekos\u0165 notebooku (13\u201316\u2033)",
    calc_prod_monitor: "Ve\u013ekos\u0165 monitora (24\u201327\u2033)",
    calc_prod_tv: "Ve\u013ekos\u0165 telev\u00edzora (50\u201365\u2033)",
    calc_prod_desktop: "Stolov\u00fd po\u010d\u00edta\u010d (ve\u017ea)",
    calc_prod_flight_short: "Let \u2014 kr\u00e1tky (<3h)",
    calc_prod_flight_long: "Let \u2014 dlh\u00fd (>6h)",
    calc_prod_car_petrol: "Auto \u2014 benz\u00edn (priemer)",
    calc_prod_car_diesel: "Auto \u2014 nafta (priemer)",
    calc_prod_train: "Vlak (vn\u00fatro\u0161t\u00e1tny)",
    calc_prod_bus: "Autobus (dia\u013ekov\u00fd)",
    calc_prod_petrol: "Benz\u00edn",
    calc_prod_diesel: "Nafta",
    calc_prod_natural_gas: "Zemn\u00fd plyn (k\u00farenie)",
    calc_prod_electricity_eu: "Elektrina (priemer E\u00da)",
    calc_note_beef: "Medi\u00e1n glob\u00e1lneho LCA; rozsah 20\u2013105 kg CO\u2082e/kg",
    calc_note_chicken: "Zah\u0155\u0148a vyu\u017e\u00edvanie p\u00f4dy, krmivo, spracovanie",
    calc_note_cheese: "~10 litrov mlieka na kg syra",
    calc_note_milk: "Zah\u0155\u0148a enter\u00e1lnu ferment\u00e1ciu a vyu\u017e\u00edvanie p\u00f4dy",
    calc_note_rice: "Dominuje met\u00e1n zo zaplavovan\u00fdch pol\u00ed",
    calc_note_coffee: "Rozsah 3,5\u201328,5; silne z\u00e1visl\u00e9 od vyu\u017e\u00edvania p\u00f4dy",
    calc_note_chocolate: "Vysok\u00fd podiel odlesnenia v dodávate\u013eskom re\u0165azci kakaa",
    calc_note_tomatoes: "Po\u013en\u00e9 pestovanie; vyhrievan\u00fd sklen\u00edk ~2,1",
    calc_note_potatoes: "Jedna z \u0161krobov\u00fdch potrav\u00edn s najni\u017e\u0161\u00edmi emisiami",
    calc_note_eggs: "~12 vajec na kg",
    calc_note_bread: "\u0160tandardn\u00fd p\u0161eni\u010dn\u00fd chlieb",
    calc_note_cotton_tshirt: "Pestovanie bavlny tvor\u00ed ~polovicu stopy",
    calc_note_cotton_jeans: "Cel\u00fd \u017eivotn\u00fd cyklus: od pestovania po likvid\u00e1ciu",
    calc_note_polyester_shirt: "Vl\u00e1kno z fos\u00edlnych pal\u00edv",
    calc_note_polyester_jacket: "Syntetick\u00e1 v\u00fdpl\u0148 + pl\u00e1\u0161\u0165 na b\u00e1ze ropy",
    calc_note_wool_sweater: "Met\u00e1n z oviec + spracovanie",
    calc_note_wool_coat: "\u0164a\u017ek\u00e1 vlna; vysok\u00fd vplyv met\u00e1nu + farbenia",
    calc_note_leather_shoes: "Chov dobytka + garbiarske chemik\u00e1lie",
    calc_note_nylon_sneakers: "Zmie\u0161an\u00e9 materi\u00e1ly; dominuje v\u00fdroba",
    calc_note_smartphone: "V\u00fdroba tvor\u00ed ~80 % stopy; 3-ro\u010dn\u00e1 \u017eivotnos\u0165",
    calc_note_tablet: "Medzi telef\u00f3nom a notebookom \u010do do vplyvu",
    calc_note_laptop: "Rozsah 150\u2013400 kg; z\u00e1vis\u00ed od komponentov",
    calc_note_monitor: "V\u00fdroba displeja + viacro\u010dn\u00e9 pou\u017e\u00edvanie",
    calc_note_tv: "Ve\u013ek\u00fd displej + 7-ro\u010dn\u00e1 spotreba elektriny",
    calc_note_desktop: "Vy\u0161\u0161ia spotreba energie; dlh\u0161ia \u017eivotnos\u0165 komponentov",
    calc_note_flight_short: "Na cestuj\u00faceho, ekonomick\u00e1 trieda; zah\u0155\u0148a radia\u010dn\u00e9 p\u00f4sobenie",
    calc_note_flight_long: "\u00da\u010dinnej\u0161\u00ed na km pri dlh\u0161\u00edch vzdialenos\u0165iach",
    calc_note_car_petrol: "Priemern\u00e9 eur\u00f3pske benz\u00ednov\u00e9 auto ~210g CO\u2082/km",
    calc_note_car_diesel: "Mierne ni\u017e\u0161ie CO\u2082 na km ako benz\u00edn",
    calc_note_train: "Ve\u013emi sa l\u00ed\u0161i pod\u013ea elektrickej siete; priemer E\u00da",
    calc_note_bus: "Na cestuj\u00faceho; predpokladan\u00e9 vysok\u00e9 obsadenie",
    calc_note_petrol: "Od vrtu po koleso vr\u00e1tane \u0165a\u017eby",
    calc_note_diesel: "Mierne viac na liter ako benz\u00edn",
    calc_note_natural_gas: "Spa\u013eovanie + \u00faniky met\u00e1nu pri \u0165a\u017ebe",
    calc_note_electricity_eu: "Priemer siete E\u00da; l\u00ed\u0161i sa pod\u013ea krajiny",
  },
  hu: {
    nav_logo: "Árazd be a kárt",
    nav_how: "Hogyan működik",
    nav_principles: "Alapelvek",
    nav_examples: "Példák",
    nav_questions: "Nyitott kérdések",
    nav_join: "Csatlakozz",
    hero_label: "Szakpolitikai keretrendszer a klímaválságra",
    hero_title: "Legyen a szennyezés<br><em>drága</em>.",
    hero_subtitle: "Minden termék rejtett környezeti költséget hordoz. CO₂-egyenérték-díjat javasolunk az ellátási lánc minden szakaszára — az ökológiai károkat gazdasági nyomássá alakítva, miközben a bevételeket az emberek védelmére osztjuk újra.",
    hero_btn_primary: "Nézd meg, hogyan működik ↓",
    hero_btn_secondary: "Csatlakozz a mozgalomhoz",
    how_label: "01 — Mechanizmus",
    how_title: "Díj minden szakaszban",
    how_desc: "A CO₂-egyenérték-díjak az ellátási lánc minden pontján érvényesülnek. Az összköltség beépül a végső árba — így a magas kibocsátású termékek természetesen drágábbak lesznek.",
    stage1_title: "Kitermelés",
    stage1_desc: "Nyersanyag-bányászat, olajfúrás, betakarítás",
    stage2_title: "Gyártás",
    stage2_desc: "Előállítás, finomítás, feldolgozás",
    stage3_title: "Szállítás",
    stage3_desc: "Hajózás, áruszállítás, logisztika",
    stage4_title: "Kereskedelem és&nbsp;használat",
    stage4_desc: "Forgalmazás, fogyasztói használati fázis",
    stage5_title: "Ártalmatlanítás",
    stage5_desc: "Életciklus vége a kiterjesztett gyártói felelősség keretében",
    stage_fee: "+ CO₂-díj",
    pipeline_result: "Az adatok már rendelkezésre állnak. Az <strong>életciklus-értékelések (LCA)</strong> és a termékek szénlábnyomai lefedik a teljes láncot — a kitermeléstől az ártalmatlanításig. Nem új tudományra van szükségünk. Politikai akaratra van szükségünk.",
    manifesto: "Alakítsd a környezeti hatást <em>elkerülhetetlen gazdasági nyomássá</em>, majd oszd újra a pénzt, hogy a társadalom stabil maradjon, miközben a piacot <em>dekarbonizációra</em> kényszeríted.",
    principles_label: "02 — Alapelvek",
    principles_title: "Amiért kiállunk",
    principles_desc: "Ez nem tudatosságnövelő kampányokról vagy önkéntes vállalásokról szól. A gazdasági ösztönzők alapjainak újratervezéséről van szó.",
    p1_title: "Ár, nem tudatosság",
    p1_text: "Évtizedes tudatosságnövelő kampányok sem változtatták meg a kibocsátási görbét. Az árjelzések nagy léptékben változtatnak viselkedést — automatikusan, egyetemlegesen és azonnal.",
    p2_title: "Védjük az embereket, ne a szennyezőket",
    p2_text: "A bevételek közjavakra és minimáljövedelemre fordítódnak a magasabb árak kompenzálására. Nincs szubvenció vállalatoknak a „zöldülésre". Ha szennyezel, fizetsz. A pénz az állampolgárokat védi.",
    p3_title: "A szén társadalmi költsége",
    p3_text: "A tonnánkénti díj a CO₂ által okozott valós káron alapul. A magasabb ár erősebb viselkedésváltozást jelent — de erősebb társadalmi újraelosztást is megkövetel a méltányosság érdekében.",
    p4_title: "EU-szintű bevezetés",
    p4_text: "A kizárólag nemzeti szintű bevezetés torzítja a kereskedelmet az egységes piacon. EU-szintű koordinációra van szükség — vagy gondosan megtervezett nemzeti adókra, amelyek nem teremtenek tisztességtelen előnyt.",
    examples_label: "03 — Valós számok",
    examples_title: "Hogyan néz ez ki a gyakorlatban?",
    examples_desc: "Meglévő életciklus-értékelési adatok és $100 / ton CO₂-egyenérték szénár alapján.",
    ex_case: "Esettanulmány",
    ex_beef: "Marhahús",
    ex_oil: "Nyersolaj",
    ex_lifecycle: "Életciklus-kibocsátás",
    ex_carbon_price: "Alkalmazott szénár",
    ex_additional_kg: "Többletköltség kg-onként",
    ex_additional_barrel: "Többletköltség hordónként",
    ex_beef_insight: "Tartalmazza a takarmánytermelést (kőolaj alapú műtrágyák), a szarvasmarhák metánkibocsátását, a földhasználat-változást és a feldolgozást. A kibocsátás nagy része biológiai eredetű — nem csupán energetikai.",
    ex_oil_insight: "Jelentős hatás az árra — de a költségek eloszlanak, ahogy az olaj ezer és ezer továbbfeldolgozott termékbe kerül. A legnagyobb hatás a koncentrált, magas kibocsátású folyamatokra, például az állattenyésztésre esik, nem csupán az ipari alapanyagokra.",
    questions_label: "04 — Őszinte hiányosságok",
    questions_title: "Nyitott kérdések",
    questions_desc: "Nem teszünk úgy, mintha minden válasszal rendelkeznénk. Ezek azok a nehéz problémák, amelyek megoldásához kollektív intelligenciára van szükség.",
    q1: "Pontosan mekkora szénár szükséges ahhoz, hogy érdemben megváltoztassa a fogyasztói és ipari viselkedést gazdasági sokk kiváltása nélkül?",
    q2: "Hogyan kényszeríthetjük ki a pontos életciklus-elszámolást globálisan, amikor az ellátási láncok különböző szabványokkal rendelkező tucatnyi országon átívelnek?",
    q3: "Hogyan kezeljük a nem megfelelő országokból származó importot? A szénhatár-kiigazítások ígéretesek, de politikailag és logisztikailag összetettek.",
    q4: "Mi a realista út a politikai megvalósíthatósághoz az EU struktúráin belül — és hogyan építjük ki az ehhez szükséges koalíciót?",
    q5: "Milyen gyorsan hajthatjuk végre az átmenetet a megélhetések destabilizálása nélkül? Hogyan néz ki a helyes egyensúly a sürgősség és a társadalmi stabilitás között?",
    join_label: "05 — Cselekedj",
    join_title: "Csatlakozz a mozgalomhoz",
    join_desc: "Ennek az ötletnek közgazdászokra, döntéshozókra, aktivistákra és állampolgárokra van szüksége, akik hisznek abban, hogy az ár — nem a bűntudat — változtatja meg a világot. Add hozzá a hangodat.",
    join_placeholder: "neved@email.hu",
    join_btn: "Feliratkozás",
    join_btn_done: "Hozzáadva ✓",
    join_note: "Nincs spam. Tájékoztatás a szakpolitikai haladásról, kutatásokról és a lehetséges lépésekről.",
    footer_mechanism: "Mechanizmus",
    footer_data: "Adatok",
    calc_label: "03.5 \u2014 Pr\u00f3b\u00e1ld ki magad",
    calc_title: "\u00c1razd be a k\u00e1rt",
    calc_desc: "N\u00e9zd meg, mennyibe ker\u00fclne val\u00f3j\u00e1ban a mindennapi term\u00e9kek, ha a k\u00f6rnyezeti k\u00e1rok benne lenn\u00e9nek az \u00e1rban.",
    calc_cat_label: "Kateg\u00f3ria",
    calc_prod_label: "Term\u00e9k",
    calc_qty_label: "Mennyis\u00e9g",
    calc_unit_label: "Egys\u00e9g",
    calc_price_label: "Sz\u00e9n\u00e1r",
    calc_cat_food: "\u00c9tel \u00e9s ital",
    calc_cat_clothing: "Ruh\u00e1zat (anyag szerint)",
    calc_cat_electronics: "Elektronika (m\u00e9ret szerint)",
    calc_cat_travel: "Utaz\u00e1s",
    calc_cat_fuel: "\u00dczemanyag",
    calc_price_50: "$50 / ton",
    calc_price_100: "$100 / ton",
    calc_price_150: "$150 / ton",
    calc_price_200: "$200 / ton",
    calc_eco_label: "\u00d6ko-tan\u00fas\u00edtott / organikus forr\u00e1s (cs\u00f6kkenti a becsl\u00e9st ~15%-kal)",
    calc_result_label: "CO\u2082-l\u00e1bnyom",
    calc_sources: "Forr\u00e1sok: Poore & Nemecek (2018), <a href=\"https://doi.org/10.1126/science.aaq0216\" target=\"_blank\" rel=\"noopener\"><em>Science</em> 360:987</a> (\u00e9tel) \u00b7 <a href=\"https://www.gov.uk/government/collections/government-conversion-factors-for-company-reporting\" target=\"_blank\" rel=\"noopener\">UK DEFRA 2023</a> (\u00fczemanyag/rep\u00fcl\u00e9s) \u00b7 Apple/Levi\u2019s Product Environmental Reports (elektronika/ruh\u00e1zat)",
    calc_damage_cost: "k\u00e1rk\u00f6lts\u00e9g",
    calc_eco_note: "(\u00f6ko-tan\u00fas\u00edtott: \u221215%)",
    calc_prod_beef: "Marhah\u00fas",
    calc_prod_chicken: "Csirkeh\u00fas",
    calc_prod_cheese: "Sajt",
    calc_prod_milk: "Tej (teh\u00e9n)",
    calc_prod_rice: "Rizs",
    calc_prod_coffee: "K\u00e1v\u00e9 (p\u00f6rk\u00f6lt)",
    calc_prod_chocolate: "Ét\u010dokol\u00e1d\u00e9",
    calc_prod_tomatoes: "Paradicsom",
    calc_prod_potatoes: "Burgonya",
    calc_prod_eggs: "Toj\u00e1s",
    calc_prod_bread: "Keny\u00e9r (b\u00faza)",
    calc_prod_cotton_tshirt: "Pamut \u2014 P\u00f3l\u00f3 (250g)",
    calc_prod_cotton_jeans: "Pamut \u2014 Farmer (denim)",
    calc_prod_polyester_shirt: "Poli\u00e9szter \u2014 Ing",
    calc_prod_polyester_jacket: "Poli\u00e9szter \u2014 Dzseki",
    calc_prod_wool_sweater: "Gyapj\u00fa \u2014 Pulóver",
    calc_prod_wool_coat: "Gyapj\u00fa \u2014 Kab\u00e1t",
    calc_prod_leather_shoes: "B\u0151r \u2014 Cip\u0151",
    calc_prod_nylon_sneakers: "Nylon/vegyes \u2014 Sportcip\u0151",
    calc_prod_smartphone: "Telefon m\u00e9ret\u0171 (okostelefon)",
    calc_prod_tablet: "Tablet m\u00e9ret\u0171 (10\u2033)",
    calc_prod_laptop: "Laptop m\u00e9ret\u0171 (13\u201316\u2033)",
    calc_prod_monitor: "Monitor m\u00e9ret\u0171 (24\u201327\u2033)",
    calc_prod_tv: "TV m\u00e9ret\u0171 (50\u201365\u2033)",
    calc_prod_desktop: "Asztali sz\u00e1m\u00edt\u00f3g\u00e9p (torony)",
    calc_prod_flight_short: "Rep\u00fcl\u00e9s \u2014 r\u00f6vid t\u00e1v (<3\u00f3)",
    calc_prod_flight_long: "Rep\u00fcl\u00e9s \u2014 hossz\u00fa t\u00e1v (>6\u00f3)",
    calc_prod_car_petrol: "Aut\u00f3 \u2014 benzin (\u00e1tl.)",
    calc_prod_car_diesel: "Aut\u00f3 \u2014 d\u00edzel (\u00e1tl.)",
    calc_prod_train: "Vonat (belf\u00f6ldi)",
    calc_prod_bus: "Busz (t\u00e1vols\u00e1gi)",
    calc_prod_petrol: "Benzin",
    calc_prod_diesel: "D\u00edzel",
    calc_prod_natural_gas: "F\u00f6ldg\u00e1z (f\u0171t\u00e9s)",
    calc_prod_electricity_eu: "Villamos energia (EU \u00e1tl.)",
    calc_note_beef: "Glob\u00e1lis LCA medi\u00e1n; tartom\u00e1ny 20\u2013105 kg CO\u2082e/kg",
    calc_note_chicken: "Tartalmazza a f\u00f6ldhaszn\u00e1latot, takarm\u00e1nyt, feldolgoz\u00e1st",
    calc_note_cheese: "~10 liter tej kg-onk\u00e9nt sajt",
    calc_note_milk: "Tartalmazza az enter\u00e1lis ferment\u00e1ci\u00f3t \u00e9s f\u00f6ldhaszn\u00e1latot",
    calc_note_rice: "Az el\u00e1rasztott rizsf\u00f6ldek met\u00e1nja domin\u00e1l",
    calc_note_coffee: "Tartom\u00e1ny 3,5\u201328,5; er\u0151sen f\u00f6ldhaszn\u00e1lat-f\u00fcgg\u0151",
    calc_note_chocolate: "Magas erd\u0151irt\u00e1si ar\u00e1ny a kaka\u00f3-ell\u00e1t\u00e1si l\u00e1ncban",
    calc_note_tomatoes: "Szabadf\u00f6ldi \u00e9rt\u00e9k; f\u0171t\u00f6tt \u00fcvegh\u00e1z ~2,1",
    calc_note_potatoes: "Az egyik legalacsonyabb kibocs\u00e1t\u00e1s\u00fa kem\u00e9ny\u00edt\u0151s \u00e9tel",
    calc_note_eggs: "~12 toj\u00e1s per kg",
    calc_note_bread: "Standard b\u00fazakeny\u00e9r",
    calc_note_cotton_tshirt: "A pamutterm. a l\u00e1bnyom ~fele",
    calc_note_cotton_jeans: "Teljes \u00e9letciklus: termel\u00e9st\u0151l az \u00e9letciklus v\u00e9g\u00e9ig",
    calc_note_polyester_shirt: "Fosszilis t\u00fczel\u0151anyagb\u00f3l sz\u00e1rmaz\u00f3 sz\u00e1l",
    calc_note_polyester_jacket: "Szintetikus t\u00f6ltet + k\u0151olaj alap\u00fa h\u00e9j",
    calc_note_wool_sweater: "Juh met\u00e1n + feldolgoz\u00e1s",
    calc_note_wool_coat: "Neh\u00e9z gyapj\u00fa; magas met\u00e1n + fest\u00e9si hat\u00e1s",
    calc_note_leather_shoes: "Szarvasmarha-teny\u00e9szt\u00e9s + cserz\u0151 vegyszerek",
    calc_note_nylon_sneakers: "Vegyes anyagok; a gy\u00e1rt\u00e1s domin\u00e1l",
    calc_note_smartphone: "A gy\u00e1rt\u00e1s a l\u00e1bnyom ~80%-a; 3 \u00e9ves \u00e9lettartam",
    calc_note_tablet: "Telefon \u00e9s laptop k\u00f6z\u00f6tti hat\u00e1s",
    calc_note_laptop: "Tartom\u00e1ny 150\u2013400 kg; f\u00fcgg az alkatr\u00e9szekt\u0151l",
    calc_note_monitor: "Kijelz\u0151gy\u00e1rt\u00e1s + t\u00f6bb\u00e9ves haszn\u00e1lat",
    calc_note_tv: "Nagy kijelz\u0151 + 7 \u00e9ves haszn\u00e1lati f\u00e1zis villamos energia",
    calc_note_desktop: "Magasabb energiafogyaszt\u00e1s; hosszabb alkatr\u00e9sz-\u00e9lettartam",
    calc_note_flight_short: "Utasonk\u00e9nt, tur. oszt.; tartalmazza a sug\u00e1rz\u00e1si k\u00e9nyszer\u00edt\u00e9st",
    calc_note_flight_long: "Hat\u00e9konyabb km-enk\u00e9nt hosszabb t\u00e1vokon",
    calc_note_car_petrol: "\u00c1tlagos eur\u00f3pai benzines aut\u00f3 ~210g CO\u2082/km",
    calc_note_car_diesel: "Valamivel alacsonyabb CO\u2082/km, mint a benzin",
    calc_note_train: "Er\u0151sen f\u00fcgg a villamosh\u00e1l\u00f3zatt\u00f3l; EU \u00e1tlag",
    calc_note_bus: "Utasonk\u00e9nt; magas kihaszn\u00e1lts\u00e1g felt\u00e9telezve",
    calc_note_petrol: "K\u00fatt\u00f3l a ker\u00e9kig, bele\u00e9rtve a kitermel\u00e9st",
    calc_note_diesel: "Valamivel t\u00f6bb literenk\u00e9nt, mint a benzin",
    calc_note_natural_gas: "\u00c9get\u00e9s + fels\u0151 \u00e1gazati met\u00e1nsziv\u00e1rg\u00e1s",
    calc_note_electricity_eu: "EU h\u00e1l\u00f3zati \u00e1tlag; orsz\u00e1gonk\u00e9nt v\u00e1ltozik",
  },
  ro: {
    nav_logo: "Prețul pagubelor",
    nav_how: "Cum funcționează",
    nav_principles: "Principii",
    nav_examples: "Exemple",
    nav_questions: "Întrebări deschise",
    nav_join: "Alătură-te",
    hero_label: "Un cadru politic pentru criza climatică",
    hero_title: "Fă poluarea<br><em>costisitoare</em>.",
    hero_subtitle: "Fiecare produs poartă un cost de mediu ascuns. Propunem o taxă pe echivalentul CO₂ de-a lungul întregului lanț de aprovizionare — transformând daunele ecologice în presiune economică și redistribuind veniturile pentru a proteja oamenii.",
    hero_btn_primary: "Vezi cum funcționează ↓",
    hero_btn_secondary: "Alătură-te mișcării",
    how_label: "01 — Mecanism",
    how_title: "O taxă în fiecare etapă",
    how_desc: "Taxele pe echivalentul CO₂ se aplică în fiecare punct al lanțului de aprovizionare. Costul total se acumulează în prețul final — făcând produsele cu emisii ridicate în mod natural mai scumpe.",
    stage1_title: "Extracție",
    stage1_desc: "Extragerea materiilor prime, forarea petrolului, recoltarea",
    stage2_title: "Producție",
    stage2_desc: "Fabricare, rafinare, prelucrare",
    stage3_title: "Transport",
    stage3_desc: "Expediție, transport de marfă, logistică",
    stage4_title: "Comerț și&nbsp;utilizare",
    stage4_desc: "Distribuție, faza de utilizare de către consumator",
    stage5_title: "Eliminare",
    stage5_desc: "Sfârșitul ciclului de viață prin responsabilitatea extinsă a producătorului",
    stage_fee: "+ taxă CO₂",
    pipeline_result: "Datele există deja. <strong>Evaluările ciclului de viață (LCA)</strong> și amprentele de carbon ale produselor acoperă întregul lanț — de la extracție până la eliminare. Nu avem nevoie de știință nouă. Avem nevoie de voință politică.",
    manifesto: "Transformă impactul asupra mediului în <em>presiune economică inevitabilă</em>, apoi redistribuie banii pentru a menține societatea stabilă, forțând totodată piața să se <em>decarbonizeze</em>.",
    principles_label: "02 — Principii",
    principles_title: "Ce susținem",
    principles_desc: "Nu este vorba despre campanii de conștientizare sau angajamente voluntare. Este vorba despre reproiectarea stimulentelor economice de la zero.",
    p1_title: "Preț, nu conștientizare",
    p1_text: "Decenii de campanii de conștientizare nu au modificat curba emisiilor. Semnalele de preț schimbă comportamentul la scară largă — automat, universal și imediat.",
    p2_title: "Protejăm oamenii, nu poluatorii",
    p2_text: "Veniturile sunt direcționate către bunuri publice și un venit minim pentru a compensa prețurile mai mari. Nicio subvenție pentru companii să „devină verzi". Dacă poluezi, plătești. Banii îi protejează pe cetățeni.",
    p3_title: "Costul social al carbonului",
    p3_text: "Taxa pe tonă se bazează pe daunele reale cauzate de CO₂. Un preț mai mare înseamnă o schimbare comportamentală mai puternică — dar necesită și o redistribuire socială mai puternică pentru a rămâne echitabil.",
    p4_title: "Implementare la nivel european",
    p4_text: "Implementarea doar la nivel național distorsionează comerțul pe piața unică. Este nevoie de coordonare la nivelul UE — sau de taxe naționale concepute cu grijă care să nu creeze avantaje neloiale.",
    examples_label: "03 — Cifre reale",
    examples_title: "Cum arată în practică?",
    examples_desc: "Pe baza datelor existente din evaluările ciclului de viață și a unui preț al carbonului de $100 / ton de echivalent CO₂.",
    ex_case: "Studiu de caz",
    ex_beef: "Carne de vită",
    ex_oil: "Petrol brut",
    ex_lifecycle: "Emisii pe ciclul de viață",
    ex_carbon_price: "Preț de carbon aplicat",
    ex_additional_kg: "Cost suplimentar per kg",
    ex_additional_barrel: "Cost suplimentar per baril",
    ex_beef_insight: "Include producția de furaje (îngrășăminte pe bază de petrol), metanul de la bovine, schimbarea utilizării terenurilor și prelucrarea. Majoritatea emisiilor provin din biologie — nu doar din inputuri energetice.",
    ex_oil_insight: "Impact semnificativ asupra prețului — dar costurile se diluează pe măsură ce petrolul este distribuit în mii de produse derivate. Cel mai mare impact cade asupra proceselor concentrate cu emisii ridicate, precum creșterea animalelor, nu doar asupra inputurilor industriale.",
    questions_label: "04 — Lacune oneste",
    questions_title: "Întrebări deschise",
    questions_desc: "Nu pretindem că avem toate răspunsurile. Acestea sunt problemele dificile care necesită inteligență colectivă.",
    q1: "Ce preț exact al carbonului este necesar pentru a schimba semnificativ comportamentul consumatorilor și al industriei fără a provoca un șoc economic?",
    q2: "Cum impunem o contabilizare precisă a ciclului de viață la nivel global, când lanțurile de aprovizionare traversează zeci de țări cu standarde diferite?",
    q3: "Cum ar trebui să gestionăm importurile din țări care nu respectă sistemul? Ajustările de frontieră pentru carbon sunt promițătoare, dar complexe din punct de vedere politic și logistic.",
    q4: "Care este calea realistă către fezabilitatea politică în cadrul structurilor UE — și cum construim coaliția necesară?",
    q5: "Cât de repede putem realiza tranziția fără a destabiliza mijloacele de trai? Cum arată echilibrul corect între urgență și stabilitate socială?",
    join_label: "05 — Acționează",
    join_title: "Alătură-te mișcării",
    join_desc: "Această idee are nevoie de economiști, factori de decizie, activiști și cetățeni care cred că prețul — nu vinovăția — schimbă lumea. Adaugă-ți vocea.",
    join_placeholder: "adresa@email.ro",
    join_btn: "Înscrie-te",
    join_btn_done: "Adăugat ✓",
    join_note: "Fără spam. Actualizări despre progresul politicilor, cercetare și acțiuni pe care le poți întreprinde.",
    footer_mechanism: "Mecanism",
    footer_data: "Date",
    calc_label: "03.5 \u2014 \u00cencearc\u0103 singur",
    calc_title: "Pre\u021buie\u0219te pagubele",
    calc_desc: "Vezi c\u00e2t ar costa cu adev\u0103rat produsele de zi cu zi dac\u0103 daunele aduse mediului ar fi incluse \u00een pre\u021b.",
    calc_cat_label: "Categorie",
    calc_prod_label: "Produs",
    calc_qty_label: "Cantitate",
    calc_unit_label: "Unitate",
    calc_price_label: "Pre\u021bul carbonului",
    calc_cat_food: "Alimente \u0219i b\u0103uturi",
    calc_cat_clothing: "\u00cembr\u0103c\u0103minte (dup\u0103 material)",
    calc_cat_electronics: "Electronic\u0103 (dup\u0103 dimensiune)",
    calc_cat_travel: "C\u0103l\u0103torii",
    calc_cat_fuel: "Combustibil",
    calc_price_50: "$50 / ton",
    calc_price_100: "$100 / ton",
    calc_price_150: "$150 / ton",
    calc_price_200: "$200 / ton",
    calc_eco_label: "Certificat ecologic / surs\u0103 organic\u0103 (reduce estimarea cu ~15%)",
    calc_result_label: "Amprenta de CO\u2082",
    calc_sources: "Surse: Poore & Nemecek (2018), <a href=\"https://doi.org/10.1126/science.aaq0216\" target=\"_blank\" rel=\"noopener\"><em>Science</em> 360:987</a> (alimente) \u00b7 <a href=\"https://www.gov.uk/government/collections/government-conversion-factors-for-company-reporting\" target=\"_blank\" rel=\"noopener\">UK DEFRA 2023</a> (combustibil/zboruri) \u00b7 Apple/Levi\u2019s Product Environmental Reports (electronic\u0103/\u00eembr\u0103c\u0103minte)",
    calc_damage_cost: "costul daunelor",
    calc_eco_note: "(certificat ecologic: \u221215%)",
    calc_prod_beef: "Carne de vit\u0103",
    calc_prod_chicken: "Carne de pui",
    calc_prod_cheese: "Br\u00e2nz\u0103",
    calc_prod_milk: "Lapte (de vac\u0103)",
    calc_prod_rice: "Orez",
    calc_prod_coffee: "Cafea (pr\u0103jit\u0103)",
    calc_prod_chocolate: "Ciocolat\u0103 neagr\u0103",
    calc_prod_tomatoes: "Ro\u0219ii",
    calc_prod_potatoes: "Cartofi",
    calc_prod_eggs: "Ou\u0103",
    calc_prod_bread: "P\u00e2ine (de gr\u00e2u)",
    calc_prod_cotton_tshirt: "Bumbac \u2014 Tricou (250g)",
    calc_prod_cotton_jeans: "Bumbac \u2014 Blugi (denim)",
    calc_prod_polyester_shirt: "Poliester \u2014 C\u0103ma\u0219\u0103",
    calc_prod_polyester_jacket: "Poliester \u2014 Jachet\u0103",
    calc_prod_wool_sweater: "L\u00e2n\u0103 \u2014 Pulover",
    calc_prod_wool_coat: "L\u00e2n\u0103 \u2014 Palton",
    calc_prod_leather_shoes: "Piele \u2014 Pantofi",
    calc_prod_nylon_sneakers: "Nylon/Mixt \u2014 Adida\u0219i",
    calc_prod_smartphone: "Dimensiune telefon (smartphone)",
    calc_prod_tablet: "Dimensiune tablet\u0103 (10\u2033)",
    calc_prod_laptop: "Dimensiune laptop (13\u201316\u2033)",
    calc_prod_monitor: "Dimensiune monitor (24\u201327\u2033)",
    calc_prod_tv: "Dimensiune TV (50\u201365\u2033)",
    calc_prod_desktop: "PC desktop (tower)",
    calc_prod_flight_short: "Zbor \u2014 curs\u0103 scurt\u0103 (<3h)",
    calc_prod_flight_long: "Zbor \u2014 curs\u0103 lung\u0103 (>6h)",
    calc_prod_car_petrol: "Ma\u0219in\u0103 \u2014 benzin\u0103 (med.)",
    calc_prod_car_diesel: "Ma\u0219in\u0103 \u2014 motorin\u0103 (med.)",
    calc_prod_train: "Tren (na\u021bional)",
    calc_prod_bus: "Autobuz (lung\u0103 distan\u021b\u0103)",
    calc_prod_petrol: "Benzin\u0103",
    calc_prod_diesel: "Motorin\u0103",
    calc_prod_natural_gas: "Gaz natural (\u00eenc\u0103lzire)",
    calc_prod_electricity_eu: "Electricitate (med. UE)",
    calc_note_beef: "Median\u0103 global\u0103 LCA; interval 20\u2013105 kg CO\u2082e/kg",
    calc_note_chicken: "Include utilizarea terenului, furajele, procesarea",
    calc_note_cheese: "~10 litri de lapte per kg de br\u00e2nz\u0103",
    calc_note_milk: "Include fermenta\u021bia enteric\u0103 \u0219i utilizarea terenului",
    calc_note_rice: "Metanul din orez\u0103riile inundate domin\u0103",
    calc_note_coffee: "Interval 3,5\u201328,5; puternic dependent de utilizarea terenului",
    calc_note_chocolate: "Component\u0103 mare de defrișare \u00een lan\u021bul de aprovizionare cu cacao",
    calc_note_tomatoes: "Valoare \u00een c\u00e2mp deschis; ser\u0103 \u00eenc\u0103lzit\u0103 ~2,1",
    calc_note_potatoes: "Unul dintre alimentele amilacee cu cele mai mici emisii",
    calc_note_eggs: "~12 ou\u0103 per kg",
    calc_note_bread: "P\u00e2ine standard din gr\u00e2u",
    calc_note_cotton_tshirt: "Cultura bumbacului \u2014 ~jum\u0103tate din amprent\u0103",
    calc_note_cotton_jeans: "Ciclul de via\u021b\u0103 complet: de la cultur\u0103 p\u00e2n\u0103 la sf\u00e2r\u0219itul vie\u021bii",
    calc_note_polyester_shirt: "Fibr\u0103 derivat\u0103 din combustibili fosili",
    calc_note_polyester_jacket: "Umplutur\u0103 sintetic\u0103 + \u00eenveli\u0219 pe baz\u0103 de petrol",
    calc_note_wool_sweater: "Metan de la oi + procesare",
    calc_note_wool_coat: "L\u00e2n\u0103 grea; impact mare de metan + vopsire",
    calc_note_leather_shoes: "Cre\u0219terea bovinelor + substan\u021be chimice de t\u0103b\u0103cire",
    calc_note_nylon_sneakers: "Materiale mixte; dominat de fabrica\u021bie",
    calc_note_smartphone: "Fabricarea \u2014 ~80% din amprent\u0103; via\u021b\u0103 de 3 ani",
    calc_note_tablet: "\u00centre telefon \u0219i laptop ca impact",
    calc_note_laptop: "Interval 150\u2013400 kg; depinde de componente",
    calc_note_monitor: "Fabricarea ecranului + utilizare multi-anual\u0103",
    calc_note_tv: "Ecran mare + consum de electricitate pe 7 ani",
    calc_note_desktop: "Consum mai mare de energie; componente cu via\u021b\u0103 mai lung\u0103",
    calc_note_flight_short: "Per pasager, clasa economic; include for\u021bare radiativ\u0103",
    calc_note_flight_long: "Mai eficient pe km la distan\u021be mai lungi",
    calc_note_car_petrol: "Ma\u0219in\u0103 european\u0103 medie pe benzin\u0103 ~210g CO\u2082/km",
    calc_note_car_diesel: "CO\u2082 u\u0219or mai sc\u0103zut pe km dec\u00e2t benzina",
    calc_note_train: "Variaz\u0103 enorm \u00een func\u021bie de re\u021beaua electric\u0103; media UE",
    calc_note_bus: "Per pasager; se presupune grad ridicat de ocupare",
    calc_note_petrol: "De la sond\u0103 la roat\u0103, inclusiv extrac\u021bia",
    calc_note_diesel: "U\u0219or mai mult per litru dec\u00e2t benzina",
    calc_note_natural_gas: "Combustie + scurgeri de metan \u00een amonte",
    calc_note_electricity_eu: "Media re\u021belei UE; variaz\u0103 pe \u021bar\u0103",
  },
  sl: {
    nav_logo: "Določi ceno škode",
    nav_how: "Kako deluje",
    nav_principles: "Načela",
    nav_examples: "Primeri",
    nav_questions: "Odprta vprašanja",
    nav_join: "Pridruži se",
    hero_label: "Politični okvir za podnebno krizo",
    hero_title: "Naj onesnaževanje<br><em>stane</em>.",
    hero_subtitle: "Vsak izdelek nosi skrite okoljske stroške. Predlagamo dajatev na ekvivalent CO₂ vzdolž celotne dobavne verige — ekološko škodo spreminjamo v gospodarski pritisk, hkrati pa prihodke prerazporejamo za zaščito ljudi.",
    hero_btn_primary: "Poglej, kako deluje ↓",
    hero_btn_secondary: "Pridruži se gibanju",
    how_label: "01 — Mehanizem",
    how_title: "Dajatev na vsaki stopnji",
    how_desc: "Dajatve na ekvivalent CO₂ se zaračunavajo na vsaki točki dobavne verige. Skupni strošek se kopiči v končni ceni — izdelki z visokimi izpusti so tako naravno dražji.",
    stage1_title: "Pridobivanje",
    stage1_desc: "Rudarjenje surovin, črpanje nafte, žetev",
    stage2_title: "Proizvodnja",
    stage2_desc: "Izdelava, rafiniranje, predelava",
    stage3_title: "Prevoz",
    stage3_desc: "Ladijski prevoz, tovorni promet, logistika",
    stage4_title: "Prodaja in&nbsp;uporaba",
    stage4_desc: "Distribucija, faza potrošniške uporabe",
    stage5_title: "Odstranjevanje",
    stage5_desc: "Konec življenjskega cikla v okviru razširjene odgovornosti proizvajalca",
    stage_fee: "+ dajatev CO₂",
    pipeline_result: "Podatki že obstajajo. <strong>Ocene življenjskega cikla (LCA)</strong> in ogljični odtisi izdelkov pokrivajo celotno verigo — od pridobivanja do odstranjevanja. Ne potrebujemo nove znanosti. Potrebujemo politično voljo.",
    manifesto: "Pretvori okoljski vpliv v <em>neizogiben gospodarski pritisk</em>, nato prerazdeli denar, da bo družba ostala stabilna, medtem ko trg prisiljen v <em>dekarbonizacijo</em>.",
    principles_label: "02 — Načela",
    principles_title: "Za kaj se zavzemamo",
    principles_desc: "Ne gre za ozaveščevalne kampanje ali prostovoljne zaveze. Gre za preoblikovanje gospodarskih spodbud od temeljev.",
    p1_title: "Cena, ne ozaveščanje",
    p1_text: "Desetletja ozaveščevalnih kampanj niso spremenila krivulje izpustov. Cenovni signali spreminjajo vedenje v velikem obsegu — samodejno, univerzalno in takoj.",
    p2_title: "Zaščitimo ljudi, ne onesnaževalce",
    p2_text: "Prihodki se namenijo javnim dobrinam in minimalnemu dohodku za izravnavo višjih cen. Brez subvencij podjetjem za „ozelenitev". Kdor onesnažuje, plača. Denar ščiti državljane.",
    p3_title: "Družbeni stroški ogljika",
    p3_text: "Dajatev na tono temelji na dejanski škodi, ki jo povzroča CO₂. Višja cena pomeni močnejšo spremembo vedenja — a zahteva tudi močnejšo družbeno prerazporeditev, da ostane pravična.",
    p4_title: "Uvedba na ravni EU",
    p4_text: "Zgolj nacionalna uvedba izkrivlja trgovino na enotnem trgu. Potrebna je koordinacija na ravni EU — ali skrbno zasnovani nacionalni davki, ki ne ustvarjajo nepoštene prednosti.",
    examples_label: "03 — Dejanske številke",
    examples_title: "Kako to izgleda v praksi?",
    examples_desc: "Na podlagi obstoječih podatkov iz ocen življenjskega cikla in cene ogljika $100 / ton ekvivalenta CO₂.",
    ex_case: "Študija primera",
    ex_beef: "Goveje meso",
    ex_oil: "Surova nafta",
    ex_lifecycle: "Izpusti v življenjskem ciklu",
    ex_carbon_price: "Upoštevana cena ogljika",
    ex_additional_kg: "Dodatni strošek na kg",
    ex_additional_barrel: "Dodatni strošek na sodček",
    ex_beef_insight: "Vključuje pridelavo krme (gnojila na osnovi nafte), metan goveda, spremembo rabe zemljišč in predelavo. Večina izpustov izvira iz biologije — ne le iz energetskih vnosov.",
    ex_oil_insight: "Znaten vpliv na ceno — a stroški se razpršijo, ko se nafta razdeli na tisoče nadaljnjih izdelkov. Največji vpliv pade na koncentrirane procese z visokimi izpusti, kot je živinoreja, ne le na industrijske vhodne surovine.",
    questions_label: "04 — Iskrene vrzeli",
    questions_title: "Odprta vprašanja",
    questions_desc: "Ne pretvarjamo se, da imamo vse odgovore. To so težki problemi, ki zahtevajo kolektivno inteligenco.",
    q1: "Kakšna natančna cena ogljika je potrebna, da smiselno spremeni vedenje potrošnikov in industrije brez povzročanja gospodarskega šoka?",
    q2: "Kako uveljaviti natančno globalno obračunavanje življenjskega cikla, ko dobavne verige segajo čez desetine držav z različnimi standardi?",
    q3: "Kako naj obravnavamo uvoz iz držav, ki sistema ne spoštujejo? Ogljične mejne prilagoditve so obetavne, a politično in logistično zapletene.",
    q4: "Kakšna je realistična pot do politične izvedljivosti znotraj struktur EU — in kako zgraditi koalicijo za to?",
    q5: "Kako hitro lahko izvedemo prehod, ne da bi destabilizirali preživetje? Kako izgleda pravo ravnovesje med nujnostjo in družbeno stabilnostjo?",
    join_label: "05 — Ukrepaj",
    join_title: "Pridruži se gibanju",
    join_desc: "Ta ideja potrebuje ekonomiste, oblikovalce politik, aktiviste in državljane, ki verjamejo, da cena — ne krivda — spreminja svet. Dodaj svoj glas.",
    join_placeholder: "tvoj@email.si",
    join_btn: "Prijavi se",
    join_btn_done: "Dodano ✓",
    join_note: "Brez neželene pošte. Obvestila o napredku politik, raziskavah in ukrepih, ki jih lahko izvedeš.",
    footer_mechanism: "Mehanizem",
    footer_data: "Podatki",
    calc_label: "03.5 \u2014 Preizkusi sam",
    calc_title: "Dolo\u010di ceno \u0161kode",
    calc_desc: "Poglej, koliko bi vsakdanji izdelki res stali, \u010de bi bila okoljska \u0161koda vklju\u010dena v ceno.",
    calc_cat_label: "Kategorija",
    calc_prod_label: "Izdelek",
    calc_qty_label: "Koli\u010dina",
    calc_unit_label: "Enota",
    calc_price_label: "Cena ogljika",
    calc_cat_food: "Hrana in pija\u010da",
    calc_cat_clothing: "Oblačila (po materialu)",
    calc_cat_electronics: "Elektronika (po velikosti)",
    calc_cat_travel: "Potovanja",
    calc_cat_fuel: "Gorivo",
    calc_price_50: "$50 / ton",
    calc_price_100: "$100 / ton",
    calc_price_150: "$150 / ton",
    calc_price_200: "$200 / ton",
    calc_eco_label: "Ekolo\u0161ko certificiran / organski vir (zmanj\u0161a oceno za ~15 %)",
    calc_result_label: "Ogljični odtis CO\u2082",
    calc_sources: "Viri: Poore & Nemecek (2018), <a href=\"https://doi.org/10.1126/science.aaq0216\" target=\"_blank\" rel=\"noopener\"><em>Science</em> 360:987</a> (hrana) \u00b7 <a href=\"https://www.gov.uk/government/collections/government-conversion-factors-for-company-reporting\" target=\"_blank\" rel=\"noopener\">UK DEFRA 2023</a> (gorivo/leti) \u00b7 Apple/Levi\u2019s Product Environmental Reports (elektronika/obla\u010dila)",
    calc_damage_cost: "stro\u0161ek \u0161kode",
    calc_eco_note: "(eko-certificirano: \u221215 %)",
    calc_prod_beef: "Goveje meso",
    calc_prod_chicken: "Pišč\u0061nčje meso",
    calc_prod_cheese: "Sir",
    calc_prod_milk: "Mleko (kravje)",
    calc_prod_rice: "Ri\u017e",
    calc_prod_coffee: "Kava (pr\u017eena)",
    calc_prod_chocolate: "Temna \u010dokolada",
    calc_prod_tomatoes: "Paradi\u017eniki",
    calc_prod_potatoes: "Krompir",
    calc_prod_eggs: "Jajca",
    calc_prod_bread: "Kruh (p\u0161eni\u010dni)",
    calc_prod_cotton_tshirt: "Bomba\u017e \u2014 Majica (250g)",
    calc_prod_cotton_jeans: "Bomba\u017e \u2014 Kavbojke (denim)",
    calc_prod_polyester_shirt: "Poliester \u2014 Srajca",
    calc_prod_polyester_jacket: "Poliester \u2014 Jakna",
    calc_prod_wool_sweater: "Volna \u2014 Pulover",
    calc_prod_wool_coat: "Volna \u2014 Plašč",
    calc_prod_leather_shoes: "Usnje \u2014 \u010cevlji",
    calc_prod_nylon_sneakers: "Najlon/me\u0161anica \u2014 Superge",
    calc_prod_smartphone: "Velikost telefona (pametni telefon)",
    calc_prod_tablet: "Velikost tablice (10\u2033)",
    calc_prod_laptop: "Velikost prenosnika (13\u201316\u2033)",
    calc_prod_monitor: "Velikost zaslona (24\u201327\u2033)",
    calc_prod_tv: "Velikost televizorja (50\u201365\u2033)",
    calc_prod_desktop: "Namizni ra\u010dunalnik (stolp)",
    calc_prod_flight_short: "Let \u2014 kratki (<3h)",
    calc_prod_flight_long: "Let \u2014 dolgi (>6h)",
    calc_prod_car_petrol: "Avto \u2014 bencin (povpr.)",
    calc_prod_car_diesel: "Avto \u2014 dizel (povpr.)",
    calc_prod_train: "Vlak (dr\u017eavni)",
    calc_prod_bus: "Avtobus (medkrajevni)",
    calc_prod_petrol: "Bencin",
    calc_prod_diesel: "Dizel",
    calc_prod_natural_gas: "Zemeljski plin (ogrevanje)",
    calc_prod_electricity_eu: "Elektrika (povpr. EU)",
    calc_note_beef: "Mediana globalnega LCA; razpon 20\u2013105 kg CO\u2082e/kg",
    calc_note_chicken: "Vklju\u010duje rabo zemlji\u0161\u010d, krmo, predelavo",
    calc_note_cheese: "~10 litrov mleka na kg sira",
    calc_note_milk: "Vklju\u010duje enter\u010dno fermentacijo in rabo zemlji\u0161\u010d",
    calc_note_rice: "Dominira metan iz poplavljenih ri\u017eevih polj",
    calc_note_coffee: "Razpon 3,5\u201328,5; mo\u010dno odvisno od rabe zemlji\u0161\u010d",
    calc_note_chocolate: "Visok dele\u017e kr\u010denja gozdov v dobavni verigi kakava",
    calc_note_tomatoes: "Vrednost na prostem; ogrevan rastlinjak ~2,1",
    calc_note_potatoes: "Ena od \u0161krobnih \u017eivil z najni\u017ejimi izpusti",
    calc_note_eggs: "~12 jajc na kg",
    calc_note_bread: "Standardni p\u0161eni\u010dni kruh",
    calc_note_cotton_tshirt: "Pridelava bomba\u017ea \u2014 ~polovica odtisa",
    calc_note_cotton_jeans: "Celoten \u017eivljenjski cikel: od pridelave do konca \u017eivljenjske dobe",
    calc_note_polyester_shirt: "Vlakno iz fosilnih goriv",
    calc_note_polyester_jacket: "Sintetična polnitev + lupina na osnovi nafte",
    calc_note_wool_sweater: "Metan ovac + predelava",
    calc_note_wool_coat: "Te\u017eka volna; velik vpliv metana + barvanja",
    calc_note_leather_shoes: "Govedoreja + kemikalije za strojenje",
    calc_note_nylon_sneakers: "Me\u0161ani materiali; prevladuje proizvodnja",
    calc_note_smartphone: "Proizvodnja ~80 % odtisa; 3-letna \u017eivljenjska doba",
    calc_note_tablet: "Med telefonom in prenosnikom po vplivu",
    calc_note_laptop: "Razpon 150\u2013400 kg; odvisno od komponent",
    calc_note_monitor: "Proizvodnja zaslona + ve\u010dletna uporaba",
    calc_note_tv: "Velik zaslon + 7-letna poraba elektrike",
    calc_note_desktop: "Vi\u0161ja poraba energije; dalj\u0161a \u017eivljenjska doba komponent",
    calc_note_flight_short: "Na potnika, ekonomski razred; vklju\u010duje sevalno prisiljevanje",
    calc_note_flight_long: "U\u010dinkovitej\u0161i na km pri dalj\u0161ih razdaljah",
    calc_note_car_petrol: "Povpre\u010den evropski bencinski avto ~210g CO\u2082/km",
    calc_note_car_diesel: "Nekoliko ni\u017eji CO\u2082 na km kot bencin",
    calc_note_train: "Mo\u010dno se razlikuje glede na el. omre\u017eje; povpre\u010dje EU",
    calc_note_bus: "Na potnika; predpostavljena visoka zasedenost",
    calc_note_petrol: "Od vrtine do kolesa, vklju\u010dno s pridobivanjem",
    calc_note_diesel: "Nekoliko ve\u010d na liter kot bencin",
    calc_note_natural_gas: "Zgorevanje + uhajanje metana pri pridobivanju",
    calc_note_electricity_eu: "Povpre\u010dje omre\u017eja EU; razlikuje se po dr\u017eavah",
  },
  hr: {
    nav_logo: "Odredi cijenu štete",
    nav_how: "Kako funkcionira",
    nav_principles: "Načela",
    nav_examples: "Primjeri",
    nav_questions: "Otvorena pitanja",
    nav_join: "Pridruži se",
    hero_label: "Politički okvir za klimatsku krizu",
    hero_title: "Neka zagađivanje<br><em>košta</em>.",
    hero_subtitle: "Svaki proizvod nosi skriveni okolišni trošak. Predlažemo naknadu za ekvivalent CO₂ duž cijelog opskrbnog lanca — pretvarajući ekološku štetu u ekonomski pritisak, uz preraspodjelu prihoda radi zaštite ljudi.",
    hero_btn_primary: "Pogledaj kako funkcionira ↓",
    hero_btn_secondary: "Pridruži se pokretu",
    how_label: "01 — Mehanizam",
    how_title: "Naknada u svakoj fazi",
    how_desc: "Naknade za ekvivalent CO₂ primjenjuju se u svakoj točki opskrbnog lanca. Ukupni trošak se akumulira u konačnoj cijeni — čineći proizvode s visokim emisijama prirodno skupljima.",
    stage1_title: "Vađenje",
    stage1_desc: "Rudarenje sirovina, bušenje nafte, žetva",
    stage2_title: "Proizvodnja",
    stage2_desc: "Prerađivanje, rafiniranje, obrada",
    stage3_title: "Prijevoz",
    stage3_desc: "Brodski prijevoz, teretni promet, logistika",
    stage4_title: "Prodaja i&nbsp;korištenje",
    stage4_desc: "Distribucija, faza potrošačkog korištenja",
    stage5_title: "Zbrinjavanje",
    stage5_desc: "Kraj životnog ciklusa u okviru proširene odgovornosti proizvođača",
    stage_fee: "+ naknada CO₂",
    pipeline_result: "Podaci već postoje. <strong>Procjene životnog ciklusa (LCA)</strong> i ugljični otisci proizvoda pokrivaju cijeli lanac — od vađenja do zbrinjavanja. Ne trebamo novu znanost. Trebamo političku volju.",
    manifesto: "Pretvori utjecaj na okoliš u <em>neizbježan ekonomski pritisak</em>, zatim preraspodjeli novac kako bi društvo ostalo stabilno dok se tržište prisiljava na <em>dekarbonizaciju</em>.",
    principles_label: "02 — Načela",
    principles_title: "Za što se zalažemo",
    principles_desc: "Ovo nije o kampanjama podizanja svijesti niti o dobrovoljnim obvezama. Radi se o preoblikovanju ekonomskih poticaja iz temelja.",
    p1_title: "Cijena, ne svijest",
    p1_text: "Desetljeća kampanja podizanja svijesti nisu promijenila krivulju emisija. Cjenovni signali mijenjaju ponašanje na velikoj razini — automatski, univerzalno i odmah.",
    p2_title: "Zaštitimo ljude, ne zagađivače",
    p2_text: "Prihodi idu za javna dobra i minimalni dohodak radi kompenzacije viših cijena. Nema subvencija za tvrtke da „postanu zelene". Tko zagađuje, plaća. Novac štiti građane.",
    p3_title: "Društveni trošak ugljika",
    p3_text: "Naknada po toni temelji se na stvarnoj šteti koju uzrokuje CO₂. Viša cijena znači snažniju promjenu ponašanja — ali zahtijeva i snažniju socijalnu preraspodjelu kako bi sustav ostao pravedan.",
    p4_title: "Provedba na razini EU",
    p4_text: "Provedba samo na nacionalnoj razini iskrivljuje trgovinu na jedinstvenom tržištu. Potrebna je koordinacija na razini EU — ili pažljivo osmišljeni nacionalni porezi koji ne stvaraju nepoštene prednosti.",
    examples_label: "03 — Stvarni brojevi",
    examples_title: "Kako to izgleda u praksi?",
    examples_desc: "Na temelju postojećih podataka iz procjena životnog ciklusa i cijene ugljika od $100 / ton ekvivalenta CO₂.",
    ex_case: "Studija slučaja",
    ex_beef: "Govedina",
    ex_oil: "Sirova nafta",
    ex_lifecycle: "Emisije u životnom ciklusu",
    ex_carbon_price: "Primijenjena cijena ugljika",
    ex_additional_kg: "Dodatni trošak po kg",
    ex_additional_barrel: "Dodatni trošak po barelu",
    ex_beef_insight: "Uključuje proizvodnju stočne hrane (gnojiva na bazi nafte), metan goveda, promjenu korištenja zemljišta i preradu. Većina emisija potječe iz biologije — ne samo iz energetskih inputa.",
    ex_oil_insight: "Značajan utjecaj na cijenu — ali troškovi se razrjeđuju kad se nafta distribuira u tisuće nizvodnih proizvoda. Najveći utjecaj pada na koncentrirane procese s visokim emisijama poput stočarstva, a ne samo na industrijske inpute.",
    questions_label: "04 — Iskrene praznine",
    questions_title: "Otvorena pitanja",
    questions_desc: "Ne pretvaramo se da imamo sve odgovore. Ovo su teški problemi koji zahtijevaju kolektivnu inteligenciju.",
    q1: "Koja je točna cijena ugljika potrebna za značajnu promjenu ponašanja potrošača i industrije bez izazivanja gospodarskog šoka?",
    q2: "Kako osigurati točno globalno praćenje životnog ciklusa kad opskrbni lanci prolaze kroz desetke zemalja s različitim standardima?",
    q3: "Kako bismo trebali postupati s uvozom iz zemalja koje ne poštuju sustav? Ugljične granične prilagodbe su obećavajuće, ali politički i logistički složene.",
    q4: "Koji je realan put do političke izvedivosti unutar struktura EU — i kako izgraditi koaliciju koja će to postići?",
    q5: "Koliko brzo možemo provesti tranziciju bez destabilizacije sredstava za život? Kako izgleda prava ravnoteža između hitnosti i društvene stabilnosti?",
    join_label: "05 — Djeluj",
    join_title: "Pridruži se pokretu",
    join_desc: "Ova ideja treba ekonomiste, kreatore politika, aktiviste i građane koji vjeruju da cijena — ne krivnja — mijenja svijet. Dodaj svoj glas.",
    join_placeholder: "tvoj@email.hr",
    join_btn: "Prijavi se",
    join_btn_done: "Dodano ✓",
    join_note: "Bez neželjene pošte. Obavijesti o napretku politika, istraživanjima i akcijama koje možeš poduzeti.",
    footer_mechanism: "Mehanizam",
    footer_data: "Podaci",
    calc_label: "03.5 \u2014 Isprobaj sam",
    calc_title: "Odredi cijenu \u0161tete",
    calc_desc: "Pogledaj koliko bi svakodnevni proizvodi zaista ko\u0161tali da su \u0161tete za okoli\u0161 uklju\u010dene u cijenu.",
    calc_cat_label: "Kategorija",
    calc_prod_label: "Proizvod",
    calc_qty_label: "Koli\u010dina",
    calc_unit_label: "Jedinica",
    calc_price_label: "Cijena ugljika",
    calc_cat_food: "Hrana i pi\u0107e",
    calc_cat_clothing: "Odje\u0107a (prema materijalu)",
    calc_cat_electronics: "Elektronika (prema veli\u010dini)",
    calc_cat_travel: "Putovanja",
    calc_cat_fuel: "Gorivo",
    calc_price_50: "$50 / ton",
    calc_price_100: "$100 / ton",
    calc_price_150: "$150 / ton",
    calc_price_200: "$200 / ton",
    calc_eco_label: "Ekolo\u0161ki certificirano / organski izvor (smanjuje procjenu za ~15%)",
    calc_result_label: "Ugljični otisak CO\u2082",
    calc_sources: "Izvori: Poore & Nemecek (2018), <a href=\"https://doi.org/10.1126/science.aaq0216\" target=\"_blank\" rel=\"noopener\"><em>Science</em> 360:987</a> (hrana) \u00b7 <a href=\"https://www.gov.uk/government/collections/government-conversion-factors-for-company-reporting\" target=\"_blank\" rel=\"noopener\">UK DEFRA 2023</a> (gorivo/letovi) \u00b7 Apple/Levi\u2019s Product Environmental Reports (elektronika/odje\u0107a)",
    calc_damage_cost: "tro\u0161ak \u0161tete",
    calc_eco_note: "(eko-certificirano: \u221215%)",
    calc_prod_beef: "Govedina",
    calc_prod_chicken: "Piletina",
    calc_prod_cheese: "Sir",
    calc_prod_milk: "Mlijeko (kravlje)",
    calc_prod_rice: "Ri\u017ea",
    calc_prod_coffee: "Kava (pr\u017eena)",
    calc_prod_chocolate: "Tamna \u010dokolada",
    calc_prod_tomatoes: "Rajčice",
    calc_prod_potatoes: "Krumpir",
    calc_prod_eggs: "Jaja",
    calc_prod_bread: "Kruh (p\u0161eni\u010dni)",
    calc_prod_cotton_tshirt: "Pamuk \u2014 Majica (250g)",
    calc_prod_cotton_jeans: "Pamuk \u2014 Traperice (denim)",
    calc_prod_polyester_shirt: "Poliester \u2014 Ko\u0161ulja",
    calc_prod_polyester_jacket: "Poliester \u2014 Jakna",
    calc_prod_wool_sweater: "Vuna \u2014 D\u017eemper",
    calc_prod_wool_coat: "Vuna \u2014 Kaput",
    calc_prod_leather_shoes: "Ko\u017ea \u2014 Cipele",
    calc_prod_nylon_sneakers: "Najlon/mje\u0161avina \u2014 Tenisice",
    calc_prod_smartphone: "Veli\u010dina telefona (pametni telefon)",
    calc_prod_tablet: "Veli\u010dina tableta (10\u2033)",
    calc_prod_laptop: "Veli\u010dina laptopa (13\u201316\u2033)",
    calc_prod_monitor: "Veli\u010dina monitora (24\u201327\u2033)",
    calc_prod_tv: "Veli\u010dina TV-a (50\u201365\u2033)",
    calc_prod_desktop: "Stolno ra\u010dunalo (tower)",
    calc_prod_flight_short: "Let \u2014 kratki (<3h)",
    calc_prod_flight_long: "Let \u2014 dugi (>6h)",
    calc_prod_car_petrol: "Auto \u2014 benzin (prosj.)",
    calc_prod_car_diesel: "Auto \u2014 dizel (prosj.)",
    calc_prod_train: "Vlak (nacionalni)",
    calc_prod_bus: "Autobus (me\u0111ugradski)",
    calc_prod_petrol: "Benzin",
    calc_prod_diesel: "Dizel",
    calc_prod_natural_gas: "Prirodni plin (grijanje)",
    calc_prod_electricity_eu: "Elektri\u010dna energija (prosj. EU)",
    calc_note_beef: "Medijan globalnog LCA; raspon 20\u2013105 kg CO\u2082e/kg",
    calc_note_chicken: "Uklju\u010duje kori\u0161tenje zemlji\u0161ta, sto\u010dnu hranu, preradu",
    calc_note_cheese: "~10 litara mlijeka po kg sira",
    calc_note_milk: "Uklju\u010duje enteri\u010dku fermentaciju i kori\u0161tenje zemlji\u0161ta",
    calc_note_rice: "Dominira metan iz poplavljenih ri\u017einih polja",
    calc_note_coffee: "Raspon 3,5\u201328,5; sna\u017eno ovisi o kori\u0161tenju zemlji\u0161ta",
    calc_note_chocolate: "Visoka komponenta kr\u010denja \u0161uma u opskrbnom lancu kakaa",
    calc_note_tomatoes: "Vrijednost na otvorenom; grijani staklenik ~2,1",
    calc_note_potatoes: "Jedna od \u0161krobnih namirnica s najni\u017eim emisijama",
    calc_note_eggs: "~12 jaja po kg",
    calc_note_bread: "Standardni p\u0161eni\u010dni kruh",
    calc_note_cotton_tshirt: "Uzgoj pamuka \u2014 ~polovica otiska",
    calc_note_cotton_jeans: "Puni \u017eivotni ciklus: od uzgoja do kraja \u017eivotnog vijeka",
    calc_note_polyester_shirt: "Vlakno iz fosilnih goriva",
    calc_note_polyester_jacket: "Sintetička punjenje + omota\u010d na bazi nafte",
    calc_note_wool_sweater: "Metan ovaca + prerada",
    calc_note_wool_coat: "Te\u0161ka vuna; velik utjecaj metana + bojenja",
    calc_note_leather_shoes: "Uzgoj goveda + kemikalije za \u0161tavljenje",
    calc_note_nylon_sneakers: "Mje\u0161oviti materijali; dominira proizvodnja",
    calc_note_smartphone: "Proizvodnja ~80% otiska; \u017eivotni vijek 3 godine",
    calc_note_tablet: "Izme\u0111u telefona i laptopa po utjecaju",
    calc_note_laptop: "Raspon 150\u2013400 kg; ovisi o komponentama",
    calc_note_monitor: "Proizvodnja zaslona + vi\u0161egodi\u0161nja uporaba",
    calc_note_tv: "Veliki zaslon + 7-godi\u0161nja potro\u0161nja elektri\u010dne energije",
    calc_note_desktop: "Ve\u0107a potro\u0161nja energije; duži \u017eivotni vijek komponenti",
    calc_note_flight_short: "Po putniku, ekonomska klasa; uklju\u010duje radijativno forsiranje",
    calc_note_flight_long: "U\u010dinkovitiji po km na du\u017eim udaljenostima",
    calc_note_car_petrol: "Prosje\u010dan europski benzinski auto ~210g CO\u2082/km",
    calc_note_car_diesel: "Ne\u0161to ni\u017ei CO\u2082 po km od benzina",
    calc_note_train: "Uvelike varira ovisno o el. mre\u017ei; prosjek EU",
    calc_note_bus: "Po putniku; pretpostavljena visoka popunjenost",
    calc_note_petrol: "Od bu\u0161otine do kotača, uklju\u010duju\u0107i va\u0111enje",
    calc_note_diesel: "Ne\u0161to vi\u0161e po litri od benzina",
    calc_note_natural_gas: "Izgaranje + uzvodna curenja metana",
    calc_note_electricity_eu: "Prosjek mre\u017ee EU; varira po dr\u017eavama",
  },
};
