const TRANS_ASIAN = {
  ja: {
    nav_logo: "損害に価格を",
    nav_how: "仕組み",
    nav_principles: "基本原則",
    nav_examples: "具体例",
    nav_questions: "未解決の課題",
    nav_join: "参加する",
    hero_label: "気候危機に対する政策フレームワーク",
    hero_title: "汚染を<br><em>高くつくもの</em>にする。",
    hero_subtitle: "すべての製品には、目に見えない環境コストが含まれています。私たちは、サプライチェーン全体にCO₂換算の課金を導入することを提案します。生態系への損害を経済的圧力に変え、その収益を人々の保護に再分配します。",
    hero_btn_primary: "仕組みを見る ↓",
    hero_btn_secondary: "運動に参加する",
    how_label: "01 — メカニズム",
    how_title: "あらゆる段階で課金する",
    how_desc: "CO₂換算の課金は、サプライチェーンの各段階で上流から適用されます。総コストは最終価格に累積され、高排出製品は自然と割高になります。",
    stage1_title: "採掘",
    stage1_desc: "原材料の採掘、石油掘削、収穫",
    stage2_title: "生産",
    stage2_desc: "製造、精製、加工",
    stage3_title: "輸送",
    stage3_desc: "海運、貨物輸送、物流",
    stage4_title: "小売・使用",
    stage4_desc: "流通、消費者の使用段階",
    stage5_title: "廃棄",
    stage5_desc: "拡大生産者責任に基づく製品寿命の終了処理",
    stage_fee: "+ CO₂ 課金",
    pipeline_result: "データはすでに存在しています。<strong>ライフサイクルアセスメント（LCA）</strong>と製品カーボンフットプリントは、採掘から廃棄までの全工程をカバーしています。新たな科学は不要です。必要なのは政治的意志です。",
    manifesto: "環境への影響を<em>避けられない経済的圧力</em>に変え、その資金を再分配することで、市場に<em>脱炭素化</em>を迫りながら社会の安定を維持する。",
    principles_label: "02 — 基本原則",
    principles_title: "私たちが掲げるもの",
    principles_desc: "これは啓発キャンペーンや自主的な誓約の話ではありません。経済的インセンティブを根本から再設計することです。",
    p1_title: "啓発ではなく、価格を",
    p1_text: "数十年にわたる啓発キャンペーンは、排出曲線を変えることができませんでした。価格シグナルは、自動的に、普遍的に、そして即座に大規模な行動変容を促します。",
    p2_title: "汚染者ではなく、人々を守る",
    p2_text: "収益は公共財と最低所得保障に充てられ、物価上昇を相殺します。企業が「グリーン化」するための補助金はありません。汚染すれば対価を払う。その資金が市民を守ります。",
    p3_title: "炭素の社会的費用",
    p3_text: "1トンあたりの課金額は、CO₂がもたらす実際の損害に基づきます。価格が高いほど行動変容は強くなりますが、公平性を保つためにより強力な社会的再分配も必要になります。",
    p4_title: "EU全域での実施",
    p4_text: "一国のみの実施は域内市場の貿易を歪めます。EU全域の協調が必要です。あるいは、不公平な優位性を生まないよう慎重に設計された国内税制が求められます。",
    examples_label: "03 — 実際の数字",
    examples_title: "具体的にどうなるのか？",
    examples_desc: "既存のライフサイクルアセスメントデータと、CO₂換算1トンあたり$100の炭素価格を使用した場合。",
    ex_case: "ケーススタディ",
    ex_beef: "牛肉",
    ex_oil: "原油",
    ex_lifecycle: "ライフサイクル排出量",
    ex_carbon_price: "適用される炭素価格",
    ex_additional_kg: "1kgあたりの追加コスト",
    ex_additional_barrel: "1バレルあたりの追加コスト",
    ex_beef_insight: "飼料生産（石油由来の肥料）、牛のメタン、土地利用変化、加工が含まれます。排出の大部分はエネルギー投入だけでなく、生物学的プロセスから生じます。",
    ex_oil_insight: "価格への影響は大きいものの、石油が何千もの下流製品に分散されるためコストは希薄化します。最大の影響は産業投入財だけでなく、畜産のような高排出の集中プロセスに及びます。",
    questions_label: "04 — 率直な課題",
    questions_title: "未解決の課題",
    questions_desc: "すべての答えを持っているとは言いません。これらは集合知で解決すべき困難な問題です。",
    q1: "経済的ショックを引き起こすことなく、消費者と産業界の行動を有意に変えるために必要な正確な炭素価格はいくらか？",
    q2: "異なる基準を持つ数十か国にまたがるサプライチェーンにおいて、正確なライフサイクル会計をグローバルにどう実施するか？",
    q3: "非準拠国からの輸入品をどう扱うべきか？炭素国境調整は有望だが、政治的にも物流的にも複雑である。",
    q4: "EU の制度枠組みの中で政治的に実現可能な現実的な道筋は何か？そしてそのための連合をどう構築するか？",
    q5: "生活を不安定にすることなく、どれだけ速く移行できるか？緊急性と社会的安定の適切なバランスとはどのようなものか？",
    join_label: "05 — 行動を起こす",
    join_title: "運動に参加する",
    join_desc: "このアイデアには、罪悪感ではなく価格こそが世界を変えると信じる経済学者、政策立案者、活動家、市民が必要です。あなたの声を届けてください。",
    join_placeholder: "your@email.com",
    join_btn: "登録する",
    join_btn_done: "登録完了 ✓",
    join_note: "スパムはありません。政策の進捗、研究、あなたができるアクションに関する更新情報をお届けします。",
    footer_mechanism: "メカニズム",
    footer_data: "データ",
    calc_label: "03.5 \u2014 やってみよう",
    calc_title: "損害の価格を計算する",
    calc_desc: "環境への損害が価格に含まれていたら、日常的な製品は実際にいくらになるかを確かめましょう。",
    calc_cat_label: "カテゴリー",
    calc_prod_label: "製品",
    calc_qty_label: "数量",
    calc_unit_label: "単位",
    calc_price_label: "炭素価格",
    calc_cat_food: "食品・飲料",
    calc_cat_clothing: "衣類（素材別）",
    calc_cat_electronics: "電子機器（サイズ別）",
    calc_cat_travel: "旅行・移動",
    calc_cat_fuel: "燃料",
    calc_price_50: "$50 / トン",
    calc_price_100: "$100 / トン",
    calc_price_150: "$150 / トン",
    calc_price_200: "$200 / トン",
    calc_eco_label: "エコ認証・有機由来（推定値を約15%削減）",
    calc_result_label: "CO\u2082 フットプリント",
    calc_sources: "出典: Poore & Nemecek (2018), <a href=\"https://doi.org/10.1126/science.aaq0216\" target=\"_blank\" rel=\"noopener\"><em>Science</em> 360:987</a>（食品）\u00b7 <a href=\"https://www.gov.uk/government/collections/government-conversion-factors-for-company-reporting\" target=\"_blank\" rel=\"noopener\">UK DEFRA 2023</a>（燃料/航空）\u00b7 Apple/Levi\u2019s 製品環境報告書（電子機器/衣類）",
    calc_damage_cost: "損害コスト",
    calc_eco_note: "（エコ認証: \u221215%）",
    calc_prod_beef: "牛肉",
    calc_prod_chicken: "鶏肉",
    calc_prod_cheese: "チーズ",
    calc_prod_milk: "牛乳",
    calc_prod_rice: "米",
    calc_prod_coffee: "コーヒー（焙煎済み）",
    calc_prod_chocolate: "ダークチョコレート",
    calc_prod_tomatoes: "トマト",
    calc_prod_potatoes: "ジャガイモ",
    calc_prod_eggs: "卵",
    calc_prod_bread: "パン（小麦）",
    calc_prod_cotton_tshirt: "コットン \u2014 Tシャツ（250g）",
    calc_prod_cotton_jeans: "コットン \u2014 ジーンズ（デニム）",
    calc_prod_polyester_shirt: "ポリエステル \u2014 シャツ",
    calc_prod_polyester_jacket: "ポリエステル \u2014 ジャケット",
    calc_prod_wool_sweater: "ウール \u2014 セーター",
    calc_prod_wool_coat: "ウール \u2014 コート",
    calc_prod_leather_shoes: "レザー \u2014 靴",
    calc_prod_nylon_sneakers: "ナイロン/混合素材 \u2014 スニーカー",
    calc_prod_smartphone: "スマートフォンサイズ",
    calc_prod_tablet: "タブレットサイズ（10\u2033）",
    calc_prod_laptop: "ノートPCサイズ（13\u201316\u2033）",
    calc_prod_monitor: "モニターサイズ（24\u201327\u2033）",
    calc_prod_tv: "テレビサイズ（50\u201365\u2033）",
    calc_prod_desktop: "デスクトップPC（タワー型）",
    calc_prod_flight_short: "フライト \u2014 短距離（3時間未満）",
    calc_prod_flight_long: "フライト \u2014 長距離（6時間超）",
    calc_prod_car_petrol: "自動車 \u2014 ガソリン（平均）",
    calc_prod_car_diesel: "自動車 \u2014 ディーゼル（平均）",
    calc_prod_train: "鉄道（国内線）",
    calc_prod_bus: "バス（長距離）",
    calc_prod_petrol: "ガソリン",
    calc_prod_diesel: "ディーゼル",
    calc_prod_natural_gas: "天然ガス（暖房用）",
    calc_prod_electricity_eu: "電力（EU平均）",
    calc_note_beef: "世界中央値LCA; 範囲 20\u2013105 kg CO\u2082e/kg",
    calc_note_chicken: "土地利用、飼料、加工を含む",
    calc_note_cheese: "チーズ1kgに約10リットルの牛乳が必要",
    calc_note_milk: "腸内発酵と土地利用を含む",
    calc_note_rice: "湛水水田からのメタンが主因",
    calc_note_coffee: "範囲 3.5\u201328.5; 土地利用に大きく依存",
    calc_note_chocolate: "カカオ供給網における森林破壊要素が大きい",
    calc_note_tomatoes: "露地栽培の値; 加温温室では約2.1",
    calc_note_potatoes: "最も排出量の少ないでんぷん質食品の一つ",
    calc_note_eggs: "1kgあたり約12個",
    calc_note_bread: "標準的な小麦パン",
    calc_note_cotton_tshirt: "綿花栽培がフットプリントの約半分",
    calc_note_cotton_jeans: "全ライフサイクル: 栽培から廃棄まで",
    calc_note_polyester_shirt: "化石燃料由来の繊維",
    calc_note_polyester_jacket: "合成中綿 + 石油系シェル素材",
    calc_note_wool_sweater: "羊のメタン + 加工処理",
    calc_note_wool_coat: "厚手のウール; メタンと染色の影響が大きい",
    calc_note_leather_shoes: "畜産 + なめし薬品",
    calc_note_nylon_sneakers: "混合素材; 製造工程が主因",
    calc_note_smartphone: "製造がフットプリントの約80%; 3年使用想定",
    calc_note_tablet: "スマートフォンとノートPCの中間の影響",
    calc_note_laptop: "範囲 150\u2013400 kg; 部品構成により異なる",
    calc_note_monitor: "ディスプレイ製造 + 複数年使用",
    calc_note_tv: "大型ディスプレイ + 7年間の使用時電力消費",
    calc_note_desktop: "消費電力が高い; 部品寿命は長い",
    calc_note_flight_short: "旅客1人あたり、エコノミークラス; 放射強制力を含む",
    calc_note_flight_long: "長距離ほどkm当たりの効率は向上",
    calc_note_car_petrol: "欧州平均ガソリン車 約210g CO\u2082/km",
    calc_note_car_diesel: "ガソリンよりkm当たりのCO\u2082がやや低い",
    calc_note_train: "電力グリッドにより大きく異なる; EU平均値",
    calc_note_bus: "旅客1人あたり; 高乗車率を想定",
    calc_note_petrol: "上流の採掘を含むWell-to-Wheel値",
    calc_note_diesel: "1リットル当たりガソリンよりやや高い",
    calc_note_natural_gas: "燃焼 + 上流のメタン漏洩",
    calc_note_electricity_eu: "EUグリッド平均; 国により異なる",
  },
  zh: {
    nav_logo: "为损害定价",
    nav_how: "运作方式",
    nav_principles: "基本原则",
    nav_examples: "实例",
    nav_questions: "待解决问题",
    nav_join: "加入",
    hero_label: "应对气候危机的政策框架",
    hero_title: "让污染<br><em>付出代价</em>。",
    hero_subtitle: "每件产品都承载着隐性的环境成本。我们提议在整个供应链中征收CO₂当量费用——将生态损害转化为经济压力，同时将收入重新分配以保护民众。",
    hero_btn_primary: "了解运作方式 ↓",
    hero_btn_secondary: "加入运动",
    how_label: "01 — 机制",
    how_title: "在每个环节征收费用",
    how_desc: "CO₂当量费用在供应链的每个环节从上游征收。总成本逐步累积到最终价格中，使高排放产品自然变得更加昂贵。",
    stage1_title: "开采",
    stage1_desc: "原材料开采、石油钻探、收获",
    stage2_title: "生产",
    stage2_desc: "制造、精炼、加工",
    stage3_title: "运输",
    stage3_desc: "航运、货运、物流",
    stage4_title: "零售与使用",
    stage4_desc: "分销、消费者使用阶段",
    stage5_title: "处置",
    stage5_desc: "基于生产者延伸责任的产品终末处理",
    stage_fee: "+ CO₂ 费用",
    pipeline_result: "数据已经存在。<strong>生命周期评估（LCA）</strong>和产品碳足迹覆盖了从开采到处置的完整链条。我们不需要新的科学研究，我们需要的是政治意愿。",
    manifesto: "将环境影响转化为<em>不可回避的经济压力</em>，然后重新分配资金以维持社会稳定，同时迫使市场<em>脱碳</em>。",
    principles_label: "02 — 基本原则",
    principles_title: "我们的立场",
    principles_desc: "这不是关于宣传活动或自愿承诺，而是从根本上重新设计经济激励机制。",
    p1_title: "用价格，而非宣传",
    p1_text: "数十年的宣传活动未能扭转排放曲线。价格信号能够自动地、普遍地、即时地大规模改变行为。",
    p2_title: "保护民众，而非污染者",
    p2_text: "收入用于公共产品和最低收入保障，以抵消价格上涨。不向企业提供"绿色转型"补贴。谁污染，谁付费。资金用于保护公民。",
    p3_title: "碳的社会成本",
    p3_text: "每吨费用基于CO₂造成的实际损害。价格越高，行为改变越强烈——但也要求更强有力的社会再分配以确保公平。",
    p4_title: "欧盟范围内实施",
    p4_text: "仅在单一国家实施会扭曲单一市场内的贸易。这需要欧盟范围内的协调——或精心设计的国内税收，以避免造成不公平的竞争优势。",
    examples_label: "03 — 真实数据",
    examples_title: "实际效果如何？",
    examples_desc: "使用现有的生命周期评估数据，以每吨CO₂当量$100的碳价格计算。",
    ex_case: "案例研究",
    ex_beef: "牛肉",
    ex_oil: "原油",
    ex_lifecycle: "生命周期排放量",
    ex_carbon_price: "适用碳价格",
    ex_additional_kg: "每kg额外成本",
    ex_additional_barrel: "每桶额外成本",
    ex_beef_insight: "包括饲料生产（石油基肥料）、牛的甲烷排放、土地利用变化和加工过程。大部分排放源于生物过程，而不仅仅是能源投入。",
    ex_oil_insight: "对价格影响显著——但随着石油分散到数千种下游产品中，成本会被稀释。最大的影响落在畜牧业等高排放集中过程上，而不仅仅是工业投入。",
    questions_label: "04 — 坦诚面对差距",
    questions_title: "待解决问题",
    questions_desc: "我们不会假装拥有所有答案。这些是需要集体智慧来解决的难题。",
    q1: "究竟需要多高的碳价格才能有效改变消费者和工业行为，同时不引发经济冲击？",
    q2: "当供应链横跨数十个标准不同的国家时，如何在全球范围内确保准确的生命周期核算？",
    q3: "如何处理来自未合规国家的进口？碳边境调节机制前景可期，但在政治和物流上都十分复杂。",
    q4: "在欧盟制度框架内实现政治可行性的现实路径是什么？我们如何构建推动这一目标的联盟？",
    q5: "在不破坏民众生计的前提下，转型速度能有多快？紧迫性与社会稳定之间的恰当平衡是什么？",
    join_label: "05 — 立即行动",
    join_title: "加入运动",
    join_desc: "这个理念需要经济学家、政策制定者、活动人士和相信价格——而非愧疚——才能改变世界的公民。请发出你的声音。",
    join_placeholder: "your@email.com",
    join_btn: "注册",
    join_btn_done: "已加入 ✓",
    join_note: "绝无垃圾邮件。仅发送政策进展、研究动态和您可以采取的行动。",
    footer_mechanism: "机制",
    footer_data: "数据",
    calc_label: "03.5 \u2014 亲自试试",
    calc_title: "计算损害价格",
    calc_desc: "看看如果环境损害包含在价格中，日常产品的真实成本会是多少。",
    calc_cat_label: "类别",
    calc_prod_label: "产品",
    calc_qty_label: "数量",
    calc_unit_label: "单位",
    calc_price_label: "碳价格",
    calc_cat_food: "食品与饮料",
    calc_cat_clothing: "服装（按材质）",
    calc_cat_electronics: "电子产品（按尺寸）",
    calc_cat_travel: "出行",
    calc_cat_fuel: "燃料",
    calc_price_50: "$50 / 吨",
    calc_price_100: "$100 / 吨",
    calc_price_150: "$150 / 吨",
    calc_price_200: "$200 / 吨",
    calc_eco_label: "生态认证/有机来源（估算值降低约15%）",
    calc_result_label: "CO\u2082 足迹",
    calc_sources: "来源: Poore & Nemecek (2018), <a href=\"https://doi.org/10.1126/science.aaq0216\" target=\"_blank\" rel=\"noopener\"><em>Science</em> 360:987</a>（食品）\u00b7 <a href=\"https://www.gov.uk/government/collections/government-conversion-factors-for-company-reporting\" target=\"_blank\" rel=\"noopener\">UK DEFRA 2023</a>（燃料/航空）\u00b7 Apple/Levi\u2019s 产品环境报告（电子产品/服装）",
    calc_damage_cost: "损害成本",
    calc_eco_note: "（生态认证: \u221215%）",
    calc_prod_beef: "牛肉",
    calc_prod_chicken: "鸡肉",
    calc_prod_cheese: "奶酪",
    calc_prod_milk: "牛奶",
    calc_prod_rice: "大米",
    calc_prod_coffee: "咖啡（烘焙）",
    calc_prod_chocolate: "黑巧克力",
    calc_prod_tomatoes: "番茄",
    calc_prod_potatoes: "土豆",
    calc_prod_eggs: "鸡蛋",
    calc_prod_bread: "面包（小麦）",
    calc_prod_cotton_tshirt: "棉 \u2014 T恤（250g）",
    calc_prod_cotton_jeans: "棉 \u2014 牛仔裤（丹宁）",
    calc_prod_polyester_shirt: "涤纶 \u2014 衬衫",
    calc_prod_polyester_jacket: "涤纶 \u2014 夹克",
    calc_prod_wool_sweater: "羊毛 \u2014 毛衣",
    calc_prod_wool_coat: "羊毛 \u2014 大衣",
    calc_prod_leather_shoes: "皮革 \u2014 鞋",
    calc_prod_nylon_sneakers: "尼龙/混合材质 \u2014 运动鞋",
    calc_prod_smartphone: "手机尺寸（智能手机）",
    calc_prod_tablet: "平板尺寸（10\u2033）",
    calc_prod_laptop: "笔记本尺寸（13\u201316\u2033）",
    calc_prod_monitor: "显示器尺寸（24\u201327\u2033）",
    calc_prod_tv: "电视尺寸（50\u201365\u2033）",
    calc_prod_desktop: "台式电脑（塔式）",
    calc_prod_flight_short: "航班 \u2014 短途（<3小时）",
    calc_prod_flight_long: "航班 \u2014 长途（>6小时）",
    calc_prod_car_petrol: "汽车 \u2014 汽油（平均）",
    calc_prod_car_diesel: "汽车 \u2014 柴油（平均）",
    calc_prod_train: "火车（国内铁路）",
    calc_prod_bus: "大巴（长途）",
    calc_prod_petrol: "汽油",
    calc_prod_diesel: "柴油",
    calc_prod_natural_gas: "天然气（供暖）",
    calc_prod_electricity_eu: "电力（欧盟平均）",
    calc_note_beef: "全球中位数LCA; 范围 20\u2013105 kg CO\u2082e/kg",
    calc_note_chicken: "包括土地利用、饲料、加工",
    calc_note_cheese: "每公斤奶酪约需10升牛奶",
    calc_note_milk: "包括肠道发酵和土地利用",
    calc_note_rice: "淹水稻田产生的甲烷为主要来源",
    calc_note_coffee: "范围 3.5\u201328.5; 高度依赖土地利用方式",
    calc_note_chocolate: "可可供应链中森林砍伐因素占比高",
    calc_note_tomatoes: "露天种植值; 加温温室约2.1",
    calc_note_potatoes: "排放最低的淀粉类食品之一",
    calc_note_eggs: "每公斤约12个",
    calc_note_bread: "标准小麦面包",
    calc_note_cotton_tshirt: "棉花种植约占碳足迹一半",
    calc_note_cotton_jeans: "完整生命周期: 从种植到报废",
    calc_note_polyester_shirt: "化石燃料衍生纤维",
    calc_note_polyester_jacket: "合成填充物 + 石油基外壳",
    calc_note_wool_sweater: "绵羊甲烷 + 加工处理",
    calc_note_wool_coat: "厚羊毛; 甲烷和染色影响较大",
    calc_note_leather_shoes: "畜牧业 + 鞣制化学品",
    calc_note_nylon_sneakers: "混合材质; 制造工艺为主",
    calc_note_smartphone: "制造约占碳足迹80%; 按3年使用寿命计",
    calc_note_tablet: "介于手机和笔记本电脑之间",
    calc_note_laptop: "范围 150\u2013400 kg; 取决于组件配置",
    calc_note_monitor: "显示器制造 + 多年使用",
    calc_note_tv: "大屏幕 + 7年使用期电力消耗",
    calc_note_desktop: "功耗较高; 组件寿命较长",
    calc_note_flight_short: "每位旅客，经济舱; 含辐射强迫效应",
    calc_note_flight_long: "长途飞行每公里效率更高",
    calc_note_car_petrol: "欧洲平均汽油车约210g CO\u2082/km",
    calc_note_car_diesel: "每公里CO\u2082略低于汽油车",
    calc_note_train: "因电网差异很大; 欧盟平均值",
    calc_note_bus: "每位旅客; 假设高上座率",
    calc_note_petrol: "包括上游开采的全周期排放",
    calc_note_diesel: "每升略高于汽油",
    calc_note_natural_gas: "燃烧 + 上游甲烷泄漏",
    calc_note_electricity_eu: "欧盟电网平均值; 因国家而异",
  },
  hi: {
    nav_logo: "नुकसान की कीमत लगाओ",
    nav_how: "यह कैसे काम करता है",
    nav_principles: "सिद्धांत",
    nav_examples: "उदाहरण",
    nav_questions: "अनसुलझे प्रश्न",
    nav_join: "जुड़ें",
    hero_label: "जलवायु संकट के लिए एक नीतिगत रूपरेखा",
    hero_title: "प्रदूषण को<br><em>महँगा</em> बनाओ।",
    hero_subtitle: "हर उत्पाद एक छिपी हुई पर्यावरणीय लागत वहन करता है। हम संपूर्ण आपूर्ति श्रृंखला में CO₂-समतुल्य शुल्क का प्रस्ताव करते हैं — जो पारिस्थितिक क्षति को आर्थिक दबाव में बदले, और राजस्व का पुनर्वितरण कर लोगों की सुरक्षा करे।",
    hero_btn_primary: "देखें कैसे काम करता है ↓",
    hero_btn_secondary: "आंदोलन में शामिल हों",
    how_label: "01 — तंत्र",
    how_title: "हर चरण पर शुल्क",
    how_desc: "CO₂-समतुल्य शुल्क आपूर्ति श्रृंखला के प्रत्येक चरण में ऊपरी स्तर पर लागू किया जाता है। कुल लागत अंतिम मूल्य में संचित होती है — जिससे उच्च-उत्सर्जन उत्पाद स्वाभाविक रूप से अधिक महँगे हो जाते हैं।",
    stage1_title: "निष्कर्षण",
    stage1_desc: "कच्चे माल का खनन, तेल ड्रिलिंग, कटाई",
    stage2_title: "उत्पादन",
    stage2_desc: "विनिर्माण, शोधन, प्रसंस्करण",
    stage3_title: "परिवहन",
    stage3_desc: "शिपिंग, माल ढुलाई, रसद",
    stage4_title: "खुदरा एवं उपयोग",
    stage4_desc: "वितरण, उपभोक्ता उपयोग चरण",
    stage5_title: "निपटान",
    stage5_desc: "विस्तारित उत्पादक उत्तरदायित्व के तहत जीवन-अंत प्रबंधन",
    stage_fee: "+ CO₂ शुल्क",
    pipeline_result: "डेटा पहले से मौजूद है। <strong>जीवनचक्र मूल्यांकन (LCA)</strong> और उत्पाद कार्बन फुटप्रिंट पूरी श्रृंखला को कवर करते हैं — निष्कर्षण से लेकर निपटान तक। हमें नए विज्ञान की आवश्यकता नहीं है। हमें राजनीतिक इच्छाशक्ति की आवश्यकता है।",
    manifesto: "पर्यावरणीय प्रभाव को <em>अपरिहार्य आर्थिक दबाव</em> में बदलो, फिर बाज़ार को <em>डीकार्बनाइज़</em> करने के लिए बाध्य करते हुए समाज को स्थिर रखने के लिए धन का पुनर्वितरण करो।",
    principles_label: "02 — सिद्धांत",
    principles_title: "हम किसके पक्ष में खड़े हैं",
    principles_desc: "यह जागरूकता अभियानों या स्वैच्छिक प्रतिज्ञाओं के बारे में नहीं है। यह आर्थिक प्रोत्साहनों को जड़ से पुनर्रचित करने के बारे में है।",
    p1_title: "जागरूकता नहीं, कीमत",
    p1_text: "दशकों के जागरूकता अभियान उत्सर्जन वक्र को मोड़ नहीं पाए। मूल्य संकेत व्यवहार को बड़े पैमाने पर बदलते हैं — स्वचालित रूप से, सार्वभौमिक रूप से और तत्काल।",
    p2_title: "प्रदूषकों की नहीं, लोगों की रक्षा करो",
    p2_text: "राजस्व सार्वजनिक सेवाओं और न्यूनतम आय में जाता है ताकि बढ़ी हुई कीमतों की भरपाई हो सके। कंपनियों को \"हरित\" बनने के लिए कोई सब्सिडी नहीं। प्रदूषण करोगे तो भुगतान करोगे। यह धन नागरिकों की ढाल बनता है।",
    p3_title: "कार्बन की सामाजिक लागत",
    p3_text: "प्रति टन शुल्क CO₂ द्वारा होने वाली वास्तविक क्षति पर आधारित है। ऊँची कीमत का अर्थ है मज़बूत व्यवहार परिवर्तन — लेकिन इसके लिए निष्पक्षता बनाए रखने हेतु मज़बूत सामाजिक पुनर्वितरण भी आवश्यक है।",
    p4_title: "EU-व्यापी कार्यान्वयन",
    p4_text: "केवल राष्ट्रीय स्तर पर कार्यान्वयन एकल बाज़ार के भीतर व्यापार को विकृत करता है। इसके लिए EU-व्यापी समन्वय आवश्यक है — या सावधानीपूर्वक डिज़ाइन किए गए राष्ट्रीय कर जो अनुचित लाभ पैदा न करें।",
    examples_label: "03 — वास्तविक आँकड़े",
    examples_title: "यह कैसा दिखेगा?",
    examples_desc: "मौजूदा जीवनचक्र मूल्यांकन डेटा और प्रति टन CO₂-समतुल्य $100 की कार्बन कीमत का उपयोग करते हुए।",
    ex_case: "केस स्टडी",
    ex_beef: "गोमांस",
    ex_oil: "कच्चा तेल",
    ex_lifecycle: "जीवनचक्र उत्सर्जन",
    ex_carbon_price: "लागू कार्बन मूल्य",
    ex_additional_kg: "प्रति kg अतिरिक्त लागत",
    ex_additional_barrel: "प्रति बैरल अतिरिक्त लागत",
    ex_beef_insight: "इसमें चारा उत्पादन (तेल-आधारित उर्वरक), पशुओं से मीथेन, भूमि उपयोग परिवर्तन और प्रसंस्करण शामिल है। अधिकांश उत्सर्जन जैविक प्रक्रियाओं से होता है — केवल ऊर्जा इनपुट से नहीं।",
    ex_oil_insight: "मूल्य पर महत्वपूर्ण प्रभाव — लेकिन जैसे-जैसे तेल हज़ारों डाउनस्ट्रीम उत्पादों में वितरित होता है, लागत पतली हो जाती है। सबसे बड़ा प्रभाव केवल औद्योगिक इनपुट पर नहीं, बल्कि पशुपालन जैसी केंद्रित उच्च-उत्सर्जन प्रक्रियाओं पर पड़ता है।",
    questions_label: "04 — ईमानदार कमियाँ",
    questions_title: "अनसुलझे प्रश्न",
    questions_desc: "हम हर उत्तर रखने का दावा नहीं करते। ये कठिन समस्याएँ हैं जिन्हें सामूहिक बुद्धि से हल करना होगा।",
    q1: "आर्थिक आघात पहुँचाए बिना उपभोक्ता और औद्योगिक व्यवहार को सार्थक रूप से बदलने के लिए सटीक कार्बन मूल्य क्या होना चाहिए?",
    q2: "जब आपूर्ति श्रृंखलाएँ विभिन्न मानकों वाले दर्जनों देशों में फैली हों, तो वैश्विक स्तर पर सटीक जीवनचक्र लेखांकन कैसे लागू करें?",
    q3: "गैर-अनुपालक देशों से आयात को कैसे संभालें? कार्बन सीमा समायोजन आशाजनक है लेकिन राजनीतिक और रसद दोनों दृष्टियों से जटिल है।",
    q4: "EU संरचनाओं के भीतर राजनीतिक व्यवहार्यता का यथार्थवादी मार्ग क्या है — और वहाँ तक पहुँचने के लिए गठबंधन कैसे बनाएँ?",
    q5: "आजीविका को अस्थिर किए बिना हम कितनी तेज़ी से संक्रमण कर सकते हैं? तात्कालिकता और सामाजिक स्थिरता के बीच सही संतुलन कैसा दिखता है?",
    join_label: "05 — कार्रवाई करें",
    join_title: "आंदोलन में शामिल हों",
    join_desc: "इस विचार को अर्थशास्त्रियों, नीति निर्माताओं, कार्यकर्ताओं और उन नागरिकों की आवश्यकता है जो मानते हैं कि दुनिया को बदलने वाली चीज़ अपराधबोध नहीं — कीमत है। अपनी आवाज़ जोड़ें।",
    join_placeholder: "your@email.com",
    join_btn: "साइन अप करें",
    join_btn_done: "जुड़ गए ✓",
    join_note: "कोई स्पैम नहीं। नीतिगत प्रगति, शोध और आपके लिए उपलब्ध कार्रवाइयों पर अपडेट।",
    footer_mechanism: "तंत्र",
    footer_data: "डेटा",
    calc_label: "03.5 \u2014 स\u094dवयं आज\u093cमाएँ",
    calc_title: "नुकसान की कीमत लगाएँ",
    calc_desc: "देखें कि अगर पर्यावरणीय क्षति को कीमत में शामिल किया जाए तो रोज़मर्रा के उत\u094dपादों की असली लागत क\u094dया होगी।",
    calc_cat_label: "श\u094dरेणी",
    calc_prod_label: "उत\u094dपाद",
    calc_qty_label: "मात\u094dरा",
    calc_unit_label: "इकाई",
    calc_price_label: "कार\u094dबन मूल\u094dय",
    calc_cat_food: "खाद\u094dय एवं पेय",
    calc_cat_clothing: "वस\u094dत\u094dर (सामग\u094dरी के अनुसार)",
    calc_cat_electronics: "इलेक\u094dट\u094dरॉनिक\u094dस (आकार के अनुसार)",
    calc_cat_travel: "यात\u094dरा",
    calc_cat_fuel: "ईंधन",
    calc_price_50: "$50 / टन",
    calc_price_100: "$100 / टन",
    calc_price_150: "$150 / टन",
    calc_price_200: "$200 / टन",
    calc_eco_label: "इको-प\u094dरमाणित / जैविक स\u094dरोत (अनुमान में ~15% की कमी)",
    calc_result_label: "CO\u2082 फुटप\u094dरिंट",
    calc_sources: "स\u094dरोत: Poore & Nemecek (2018), <a href=\"https://doi.org/10.1126/science.aaq0216\" target=\"_blank\" rel=\"noopener\"><em>Science</em> 360:987</a> (खाद\u094dय) \u00b7 <a href=\"https://www.gov.uk/government/collections/government-conversion-factors-for-company-reporting\" target=\"_blank\" rel=\"noopener\">UK DEFRA 2023</a> (ईंधन/उड\u093cानें) \u00b7 Apple/Levi\u2019s उत\u094dपाद पर\u094dयावरण रिपोर\u094dट (इलेक\u094dट\u094dरॉनिक\u094dस/वस\u094dत\u094dर)",
    calc_damage_cost: "क\u094dषति लागत",
    calc_eco_note: "(इको-प\u094dरमाणित: \u221215%)",
    calc_prod_beef: "गोमांस",
    calc_prod_chicken: "मुर\u094dगा",
    calc_prod_cheese: "पनीर (चीज\u093c)",
    calc_prod_milk: "दूध (गाय)",
    calc_prod_rice: "चावल",
    calc_prod_coffee: "कॉफ\u093cी (भुनी हुई)",
    calc_prod_chocolate: "डार\u094dक चॉकलेट",
    calc_prod_tomatoes: "टमाटर",
    calc_prod_potatoes: "आलू",
    calc_prod_eggs: "अंडे",
    calc_prod_bread: "ब\u094dरेड (गेहूँ)",
    calc_prod_cotton_tshirt: "कपास \u2014 टी-शर\u094dट (250g)",
    calc_prod_cotton_jeans: "कपास \u2014 जीन\u094dस (डेनिम)",
    calc_prod_polyester_shirt: "पॉलिएस\u094dटर \u2014 शर\u094dट",
    calc_prod_polyester_jacket: "पॉलिएस\u094dटर \u2014 जैकेट",
    calc_prod_wool_sweater: "ऊन \u2014 स\u094dवेटर",
    calc_prod_wool_coat: "ऊन \u2014 कोट",
    calc_prod_leather_shoes: "चमड\u093cा \u2014 जूते",
    calc_prod_nylon_sneakers: "नायलॉन/मिश\u094dरित \u2014 स\u094dनीकर\u094dस",
    calc_prod_smartphone: "फ\u093cोन-आकार (स\u094dमार\u094dटफ\u093cोन)",
    calc_prod_tablet: "टैबलेट-आकार (10\u2033)",
    calc_prod_laptop: "लैपटॉप-आकार (13\u201316\u2033)",
    calc_prod_monitor: "मॉनिटर-आकार (24\u201327\u2033)",
    calc_prod_tv: "टीवी-आकार (50\u201365\u2033)",
    calc_prod_desktop: "डेस\u094dकटॉप PC (टावर)",
    calc_prod_flight_short: "उड\u093cान \u2014 लघु-दूरी (<3 घंटे)",
    calc_prod_flight_long: "उड\u093cान \u2014 दीर\u094dघ-दूरी (>6 घंटे)",
    calc_prod_car_petrol: "कार \u2014 पेट\u094dरोल (औसत)",
    calc_prod_car_diesel: "कार \u2014 डीज\u093cल (औसत)",
    calc_prod_train: "रेलगाड\u093cी (राष\u094dट\u094dरीय रेल)",
    calc_prod_bus: "बस (लंबी दूरी)",
    calc_prod_petrol: "पेट\u094dरोल / गैसोलीन",
    calc_prod_diesel: "डीज\u093cल",
    calc_prod_natural_gas: "प\u094dराकृतिक गैस (हीटिंग)",
    calc_prod_electricity_eu: "बिजली (EU औसत)",
    calc_note_beef: "वैश\u094dविक मध\u094dयक LCA; सीमा 20\u2013105 kg CO\u2082e/kg",
    calc_note_chicken: "भूमि उपयोग, चारा, प\u094dरसंस\u094dकरण शामिल",
    calc_note_cheese: "1 kg पनीर के लिए ~10 लीटर दूध",
    calc_note_milk: "आंत\u094dरिक किण\u094dवन और भूमि उपयोग शामिल",
    calc_note_rice: "जलमग\u094dन खेतों से मीथेन प\u094dरमुख कारक",
    calc_note_coffee: "सीमा 3.5\u201328.5; भूमि-उपयोग पर अत\u094dयधिक निर\u094dभर",
    calc_note_chocolate: "कोको आपूर\u094dति श\u094dरृंखला में वनों की कटाई का बड\u093cा योगदान",
    calc_note_tomatoes: "खुले मैदान का मान; गर\u094dम ग\u094dरीनहाउस ~2.1",
    calc_note_potatoes: "सबसे कम उत\u094dसर\u094dजन वाले स\u094dटार\u094dच खाद\u094dय पदार\u094dथों में से एक",
    calc_note_eggs: "प\u094dरति kg ~12 अंडे",
    calc_note_bread: "मानक गेहूँ की ब\u094dरेड",
    calc_note_cotton_tshirt: "कपास की खेती फुटप\u094dरिंट का ~आधा",
    calc_note_cotton_jeans: "पूर\u094dण जीवनचक\u094dर: खेती से जीवन-अंत तक",
    calc_note_polyester_shirt: "जीवाश\u094dम-ईंधन से प\u094dराप\u094dत फाइबर",
    calc_note_polyester_jacket: "सिंथेटिक भराव + पेट\u094dरोलियम-आधारित शेल",
    calc_note_wool_sweater: "भेड\u093c मीथेन + प\u094dरसंस\u094dकरण",
    calc_note_wool_coat: "भारी ऊन; उच\u094dच मीथेन + रंगाई प\u094dरभाव",
    calc_note_leather_shoes: "पशुपालन + चर\u094dमशोधन रसायन",
    calc_note_nylon_sneakers: "मिश\u094dरित सामग\u094dरी; विनिर\u094dमाण प\u094dरधान",
    calc_note_smartphone: "विनिर\u094dमाण फुटप\u094dरिंट का ~80%; 3 वर\u094dष उपयोग",
    calc_note_tablet: "फ\u093cोन और लैपटॉप के बीच का प\u094dरभाव",
    calc_note_laptop: "सीमा 150\u2013400 kg; घटकों पर निर\u094dभर",
    calc_note_monitor: "डिस\u094dप\u094dले विनिर\u094dमाण + बहु-वर\u094dषीय उपयोग",
    calc_note_tv: "बड\u093cा डिस\u094dप\u094dले + 7 वर\u094dष उपयोग-चरण बिजली",
    calc_note_desktop: "अधिक बिजली खपत; लंबा घटक जीवनकाल",
    calc_note_flight_short: "प\u094dरति यात\u094dरी, इकॉनमी; विकिरण बल शामिल",
    calc_note_flight_long: "लंबी दूरी पर प\u094dरति km अधिक कुशल",
    calc_note_car_petrol: "औसत यूरोपीय पेट\u094dरोल कार ~210g CO\u2082/km",
    calc_note_car_diesel: "पेट\u094dरोल से प\u094dरति km CO\u2082 थोड\u093cा कम",
    calc_note_train: "बिजली ग\u094dरिड के अनुसार बहुत भिन\u094dन; EU औसत",
    calc_note_bus: "प\u094dरति यात\u094dरी; उच\u094dच अधिभोग मान लिया गया",
    calc_note_petrol: "अपस\u094dट\u094dरीम निष\u094dकर\u094dषण सहित Well-to-Wheel",
    calc_note_diesel: "प\u094dरति लीटर पेट\u094dरोल से थोड\u093cा अधिक",
    calc_note_natural_gas: "दहन + अपस\u094dट\u094dरीम मीथेन रिसाव",
    calc_note_electricity_eu: "EU ग\u094dरिड औसत; देश के अनुसार भिन\u094dन",
  },
};
