const TRANS_NORDIC = {
  da: {
    nav_logo: "Prissæt skaden",
    nav_how: "Sådan virker det",
    nav_principles: "Principper",
    nav_examples: "Eksempler",
    nav_questions: "Åbne spørgsmål",
    nav_join: "Deltag",
    hero_label: "En politisk ramme for klimakrisen",
    hero_title: "Gør forurening<br><em>dyrt</em>.",
    hero_subtitle: "Ethvert produkt bærer en skjult miljøomkostning. Vi foreslår en CO₂-ækvivalent afgift gennem hele forsyningskæden — der omsætter økologisk skade til økonomisk pres, mens indtægterne omfordeles for at beskytte mennesker.",
    hero_btn_primary: "Se hvordan det virker ↓",
    hero_btn_secondary: "Deltag i bevægelsen",
    how_label: "01 — Mekanisme",
    how_title: "En afgift på hvert trin",
    how_desc: "CO₂-ækvivalente afgifter pålægges opstrøms på hvert punkt i forsyningskæden. De samlede omkostninger akkumuleres i den endelige pris — hvilket naturligt gør højemissionsprodukter dyrere.",
    stage1_title: "Udvinding",
    stage1_desc: "Råstofudvinding, olieboring, høst",
    stage2_title: "Produktion",
    stage2_desc: "Fremstilling, raffinering, forarbejdning",
    stage3_title: "Transport",
    stage3_desc: "Fragt, godstransport, logistik",
    stage4_title: "Detail &amp; forbrug",
    stage4_desc: "Distribution, forbrugsfase",
    stage5_title: "Bortskaffelse",
    stage5_desc: "Slutfase via udvidet producentansvar",
    stage_fee: "+ CO₂-afgift",
    pipeline_result: "Dataene findes allerede. <strong>Livscyklusvurderinger (LCA)</strong> og produkters CO₂-fodaftryk dækker hele kæden — fra udvinding til bortskaffelse. Vi behøver ikke ny videnskab. Vi behøver politisk vilje.",
    manifesto: "Omsæt miljøpåvirkning til <em>uundgåeligt økonomisk pres</em>, og omfordel derefter pengene for at holde samfundet stabilt, mens markedet tvinges til at <em>dekarbonisere</em>.",
    principles_label: "02 — Principper",
    principles_title: "Hvad vi står for",
    principles_desc: "Det handler ikke om oplysningskampagner eller frivillige løfter. Det handler om at redesigne økonomiske incitamenter fra bunden.",
    p1_title: "Pris, ikke oplysning",
    p1_text: "Årtiers oplysningskampagner har ikke bøjet udledningskurven. Prissignaler ændrer adfærd i stor skala — automatisk, universelt og øjeblikkeligt.",
    p2_title: "Beskyt mennesker, ikke forurenere",
    p2_text: "Indtægterne går til offentlige goder og minimumsindkomst for at kompensere for højere priser. Ingen subsidier til virksomheder for at \"blive grønne\". Hvis du forurener, betaler du. Pengene beskytter borgerne.",
    p3_title: "Samfundsomkostningen ved CO₂",
    p3_text: "Afgiften per ton er baseret på den reelle skade, CO₂ forårsager. Højere pris betyder stærkere adfærdsændring — men kræver også stærkere social omfordeling for at holde det retfærdigt.",
    p4_title: "EU-dækkende implementering",
    p4_text: "Kun national implementering forvrider handelen inden for det indre marked. Det kræver EU-dækkende koordinering — eller omhyggeligt designede nationale afgifter, der ikke skaber uretfærdige fordele.",
    examples_label: "03 — Konkrete tal",
    examples_title: "Hvordan ser det ud?",
    examples_desc: "Baseret på eksisterende livscyklusvurderinger og en CO₂-pris på $100 per ton CO₂-ækvivalent.",
    ex_case: "Case-studie",
    ex_beef: "Oksekød",
    ex_oil: "Råolie",
    ex_lifecycle: "Livscyklusudledninger",
    ex_carbon_price: "Anvendt CO₂-pris",
    ex_additional_kg: "Meromkostning per kg",
    ex_additional_barrel: "Meromkostning per tønde",
    ex_beef_insight: "Inkluderer foderproduktion (oliebaseret gødning), metan fra kvæg, ændret arealanvendelse og forarbejdning. De fleste udledninger kommer fra biologi — ikke kun energi-input.",
    ex_oil_insight: "Betydelig prispåvirkning — men omkostningerne fortyndes, når olie fordeles på tusindvis af downstream-produkter. Den største påvirkning rammer koncentrerede højemissionsprocesser som husdyrbrug, ikke blot industrielle input.",
    questions_label: "04 — Ærlige huller",
    questions_title: "Åbne spørgsmål",
    questions_desc: "Vi påstår ikke at have alle svar. Dette er de svære problemer, vi har brug for kollektiv intelligens til at løse.",
    q1: "Hvilken præcis CO₂-pris er nødvendig for meningsfuldt at ændre forbruger- og industriadfærd uden at forårsage økonomisk chok?",
    q2: "Hvordan håndhæver vi nøjagtig livscyklusregnskab globalt, når forsyningskæder spænder over snesevis af lande med forskellige standarder?",
    q3: "Hvordan bør vi håndtere import fra ikke-kompatible lande? CO₂-grænsetilpasninger er lovende, men politisk og logistisk komplekse.",
    q4: "Hvad er den realistiske vej til politisk gennemførlighed inden for EU's strukturer — og hvordan opbygger vi koalitionen til at nå dertil?",
    q5: "Hvor hurtigt kan vi omstille uden at destabilisere levebrød? Hvordan ser den rette balance mellem hastværk og social stabilitet ud?",
    join_label: "05 — Handling",
    join_title: "Deltag i bevægelsen",
    join_desc: "Denne idé har brug for økonomer, politiske beslutningstagere, aktivister og borgere, der tror på, at pris — ikke skyld — er det, der ændrer verden. Giv din stemme.",
    join_placeholder: "din@email.dk",
    join_btn: "Tilmeld dig",
    join_btn_done: "Tilføjet ✓",
    join_note: "Ingen spam. Opdateringer om politiske fremskridt, forskning og handlinger du kan tage.",
    footer_mechanism: "Mekanisme",
    footer_data: "Data",
  },
  sv: {
    nav_logo: "Prissätt skadan",
    nav_how: "Så fungerar det",
    nav_principles: "Principer",
    nav_examples: "Exempel",
    nav_questions: "Öppna frågor",
    nav_join: "Gå med",
    hero_label: "Ett politiskt ramverk för klimatkrisen",
    hero_title: "Gör föroreningar<br><em>dyra</em>.",
    hero_subtitle: "Varje produkt bär en dold miljökostnad. Vi föreslår en CO₂-ekvivalent avgift genom hela leveranskedjan — som omvandlar ekologisk skada till ekonomiskt tryck, samtidigt som intäkterna omfördelas för att skydda människor.",
    hero_btn_primary: "Se hur det fungerar ↓",
    hero_btn_secondary: "Gå med i rörelsen",
    how_label: "01 — Mekanism",
    how_title: "En avgift i varje steg",
    how_desc: "CO₂-ekvivalenta avgifter tillämpas uppströms vid varje punkt i leveranskedjan. Den totala kostnaden ackumuleras i slutpriset — vilket naturligt gör högutsläppsprodukter dyrare.",
    stage1_title: "Utvinning",
    stage1_desc: "Råvarubrytning, oljeborrning, skörd",
    stage2_title: "Produktion",
    stage2_desc: "Tillverkning, raffinering, bearbetning",
    stage3_title: "Transport",
    stage3_desc: "Sjöfrakt, godstransport, logistik",
    stage4_title: "Detaljhandel &amp; användning",
    stage4_desc: "Distribution, konsumentanvändningsfas",
    stage5_title: "Avfallshantering",
    stage5_desc: "Slutskede via utökat producentansvar",
    stage_fee: "+ CO₂-avgift",
    pipeline_result: "Datan finns redan. <strong>Livscykelanalyser (LCA)</strong> och produkters koldioxidavtryck täcker hela kedjan — från utvinning till avfallshantering. Vi behöver inte ny vetenskap. Vi behöver politisk vilja.",
    manifesto: "Omvandla miljöpåverkan till <em>oundvikligt ekonomiskt tryck</em> och omfördela sedan pengarna för att hålla samhället stabilt medan marknaden tvingas <em>avkarbonisera</em>.",
    principles_label: "02 — Principer",
    principles_title: "Vad vi står för",
    principles_desc: "Det handlar inte om informationskampanjer eller frivilliga löften. Det handlar om att omforma ekonomiska incitament från grunden.",
    p1_title: "Pris, inte medvetenhet",
    p1_text: "Årtionden av informationskampanjer har inte böjt utsläppskurvan. Prissignaler förändrar beteende i stor skala — automatiskt, universellt och omedelbart.",
    p2_title: "Skydda människor, inte förorenare",
    p2_text: "Intäkterna går till offentliga nyttigheter och minimiinkomst för att kompensera högre priser. Inga subventioner till företag för att \"bli gröna\". Förorenar du, betalar du. Pengarna skyddar medborgarna.",
    p3_title: "Samhällskostnaden för CO₂",
    p3_text: "Avgiften per ton baseras på den verkliga skada CO₂ orsakar. Högre pris innebär starkare beteendeförändring — men kräver också starkare social omfördelning för att hålla det rättvist.",
    p4_title: "EU-omfattande implementering",
    p4_text: "Enbart nationell implementering snedvrider handeln inom den inre marknaden. Det krävs EU-omfattande samordning — eller noggrant utformade nationella skatter som inte skapar orättvisa fördelar.",
    examples_label: "03 — Verkliga siffror",
    examples_title: "Hur ser det ut?",
    examples_desc: "Baserat på befintliga livscykelanalyser och ett koldioxidpris på $100 per ton CO₂-ekvivalent.",
    ex_case: "Fallstudie",
    ex_beef: "Nötkött",
    ex_oil: "Råolja",
    ex_lifecycle: "Livscykelutsläpp",
    ex_carbon_price: "Tillämpad koldioxidpris",
    ex_additional_kg: "Merkostnad per kg",
    ex_additional_barrel: "Merkostnad per fat",
    ex_beef_insight: "Inkluderar foderproduktion (oljebaserade gödselmedel), metan från nötkreatur, förändrad markanvändning och bearbetning. De flesta utsläppen kommer från biologi — inte bara energiinsatser.",
    ex_oil_insight: "Betydande prispåverkan — men kostnaderna späds ut när olja fördelas på tusentals nedströmsprodukter. Den största påverkan drabbar koncentrerade högutsläppsprocesser som djurhållning, inte bara industriella insatsvaror.",
    questions_label: "04 — Ärliga luckor",
    questions_title: "Öppna frågor",
    questions_desc: "Vi påstår inte att vi har alla svar. Det här är de svåra problemen som kräver kollektiv intelligens att lösa.",
    q1: "Vilket exakt koldioxidpris behövs för att meningsfullt förändra konsument- och industribeteende utan att orsaka ekonomisk chock?",
    q2: "Hur säkerställer vi korrekt livscykelredovisning globalt, när leveranskedjor spänner över dussintals länder med olika standarder?",
    q3: "Hur bör vi hantera import från icke-kompatibla länder? Koldioxidgränsjusteringar är lovande men politiskt och logistiskt komplexa.",
    q4: "Vad är den realistiska vägen till politisk genomförbarhet inom EU:s strukturer — och hur bygger vi koalitionen för att nå dit?",
    q5: "Hur snabbt kan vi ställa om utan att destabilisera försörjningsmöjligheter? Hur ser den rätta balansen mellan brådska och social stabilitet ut?",
    join_label: "05 — Agera",
    join_title: "Gå med i rörelsen",
    join_desc: "Denna idé behöver ekonomer, beslutsfattare, aktivister och medborgare som tror att pris — inte skuld — är det som förändrar världen. Lägg till din röst.",
    join_placeholder: "din@epost.se",
    join_btn: "Anmäl dig",
    join_btn_done: "Tillagd ✓",
    join_note: "Ingen spam. Uppdateringar om politiska framsteg, forskning och åtgärder du kan vidta.",
    footer_mechanism: "Mekanism",
    footer_data: "Data",
  },
  fi: {
    nav_logo: "Hinnoittele vahinko",
    nav_how: "Näin se toimii",
    nav_principles: "Periaatteet",
    nav_examples: "Esimerkit",
    nav_questions: "Avoimet kysymykset",
    nav_join: "Liity",
    hero_label: "Poliittinen viitekehys ilmastokriisille",
    hero_title: "Tee saastuttamisesta<br><em>kallista</em>.",
    hero_subtitle: "Jokaisella tuotteella on piilotettu ympäristökustannus. Ehdotamme CO₂-ekvivalenttimaksua koko toimitusketjuun — muuntaen ekologisen vahingon taloudelliseksi paineeksi ja jakaen tulot uudelleen ihmisten suojelemiseksi.",
    hero_btn_primary: "Katso miten se toimii ↓",
    hero_btn_secondary: "Liity liikkeeseen",
    how_label: "01 — Mekanismi",
    how_title: "Maksu jokaisessa vaiheessa",
    how_desc: "CO₂-ekvivalenttimaksut peritään alkupäässä jokaisessa toimitusketjun vaiheessa. Kokonaiskustannus kertyy lopulliseen hintaan — tehden korkean päästötason tuotteista luonnollisesti kalliimpia.",
    stage1_title: "Louhinta",
    stage1_desc: "Raaka-aineiden louhinta, öljynporaus, korjuu",
    stage2_title: "Tuotanto",
    stage2_desc: "Valmistus, jalostus, prosessointi",
    stage3_title: "Kuljetus",
    stage3_desc: "Laivaus, rahti, logistiikka",
    stage4_title: "Vähittäiskauppa &amp; käyttö",
    stage4_desc: "Jakelu, kuluttajan käyttövaihe",
    stage5_title: "Hävittäminen",
    stage5_desc: "Elinkaaren loppu laajennetun tuottajavastuun kautta",
    stage_fee: "+ CO₂-maksu",
    pipeline_result: "Data on jo olemassa. <strong>Elinkaariarvioinnit (LCA)</strong> ja tuotteiden hiilijalanjäljet kattavat koko ketjun — louhinnasta hävittämiseen. Emme tarvitse uutta tiedettä. Tarvitsemme poliittista tahtoa.",
    manifesto: "Muunna ympäristövaikutus <em>väistämättömäksi taloudelliseksi paineeksi</em> ja jaa sitten rahat uudelleen pitääksesi yhteiskunnan vakaana samalla kun markkinat pakotetaan <em>irtautumaan hiilestä</em>.",
    principles_label: "02 — Periaatteet",
    principles_title: "Mitä kannatamme",
    principles_desc: "Kyse ei ole tiedotuskampanjoista tai vapaaehtoisista lupauksista. Kyse on taloudellisten kannustimien uudelleensuunnittelusta perustasolta lähtien.",
    p1_title: "Hinta, ei tietoisuus",
    p1_text: "Vuosikymmenten tiedotuskampanjat eivät ole taivuttaneet päästökäyrää. Hintasignaalit muuttavat käyttäytymistä laajassa mittakaavassa — automaattisesti, yleismaailmallisesti ja välittömästi.",
    p2_title: "Suojele ihmisiä, älä saastuttajia",
    p2_text: "Tulot ohjataan julkisiin palveluihin ja vähimmäistuloon korkeampien hintojen kompensoimiseksi. Ei tukia yrityksille \"vihertyäkseen\". Jos saastutat, maksat. Rahat suojaavat kansalaisia.",
    p3_title: "CO₂:n yhteiskunnallinen kustannus",
    p3_text: "Maksu per tonni perustuu CO₂:n todelliseen aiheuttamaan vahinkoon. Korkeampi hinta tarkoittaa voimakkaampaa käyttäytymisen muutosta — mutta vaatii myös vahvempaa sosiaalista uudelleenjakoa oikeudenmukaisuuden säilyttämiseksi.",
    p4_title: "EU:n laajuinen toteutus",
    p4_text: "Pelkästään kansallinen toteutus vääristää kauppaa sisämarkkinoilla. Tämä vaatii EU:n laajuista koordinointia — tai huolellisesti suunniteltuja kansallisia veroja, jotka eivät luo epäreiluja etuja.",
    examples_label: "03 — Todelliset luvut",
    examples_title: "Miltä tämä näyttää?",
    examples_desc: "Olemassa olevien elinkaariarviointien ja $100 per tonni CO₂-ekvivalentti -hiilihinnan perusteella.",
    ex_case: "Tapaustutkimus",
    ex_beef: "Naudanliha",
    ex_oil: "Raakaöljy",
    ex_lifecycle: "Elinkaaren päästöt",
    ex_carbon_price: "Sovellettu hiilihinta",
    ex_additional_kg: "Lisäkustannus per kg",
    ex_additional_barrel: "Lisäkustannus per tynnyri",
    ex_beef_insight: "Sisältää rehuntuotannon (öljypohjaiset lannoitteet), karjan metaanipäästöt, maankäytön muutoksen ja prosessoinnin. Suurin osa päästöistä tulee biologiasta — ei pelkästään energiapanoksista.",
    ex_oil_insight: "Merkittävä hintavaikutus — mutta kustannukset laimeutuvat, kun öljy jakautuu tuhansiin jatkotuotteisiin. Suurin vaikutus kohdistuu keskittyneisiin korkeiden päästöjen prosesseihin kuten karjankasvatukseen, ei pelkästään teollisiin panoksiin.",
    questions_label: "04 — Avoimet aukot",
    questions_title: "Avoimet kysymykset",
    questions_desc: "Emme väitä, että meillä on kaikki vastaukset. Nämä ovat vaikeita ongelmia, joiden ratkaiseminen vaatii yhteistä älykkyyttä.",
    q1: "Mikä tarkka hiilihinta tarvitaan kuluttaja- ja teollisuuskäyttäytymisen merkitykselliseen muuttamiseen aiheuttamatta taloudellista sokkia?",
    q2: "Miten valvomme tarkkaa elinkaarikirjanpitoa maailmanlaajuisesti, kun toimitusketjut ulottuvat kymmeniin maihin, joilla on erilaiset standardit?",
    q3: "Miten meidän tulisi käsitellä tuontia sääntöjä noudattamattomista maista? Hiilirajamekanismit ovat lupaavia, mutta poliittisesti ja logistisesti monimutkaisia.",
    q4: "Mikä on realistinen polku poliittiseen toteutettavuuteen EU:n rakenteiden puitteissa — ja miten rakennamme koalition sen saavuttamiseksi?",
    q5: "Kuinka nopeasti voimme siirtyä horjuttamatta elinkeinoja? Miltä oikea tasapaino kiireellisyyden ja sosiaalisen vakauden välillä näyttää?",
    join_label: "05 — Toimi",
    join_title: "Liity liikkeeseen",
    join_desc: "Tämä idea tarvitsee ekonomisteja, päätöksentekijöitä, aktivisteja ja kansalaisia, jotka uskovat, että hinta — ei syyllisyys — muuttaa maailman. Lisää äänesi.",
    join_placeholder: "sinun@sahkoposti.fi",
    join_btn: "Rekisteröidy",
    join_btn_done: "Lisätty ✓",
    join_note: "Ei roskapostia. Päivityksiä politiikan edistymisestä, tutkimuksesta ja toimista, joihin voit ryhtyä.",
    footer_mechanism: "Mekanismi",
    footer_data: "Data",
  },
  et: {
    nav_logo: "Hinnasta kahju",
    nav_how: "Kuidas see toimib",
    nav_principles: "Põhimõtted",
    nav_examples: "Näited",
    nav_questions: "Avatud küsimused",
    nav_join: "Liitu",
    hero_label: "Poliitiline raamistik kliimakriisile",
    hero_title: "Muuda saastamine<br><em>kulukaks</em>.",
    hero_subtitle: "Igal tootel on varjatud keskkonnamaksumus. Me pakume CO₂-ekvivalentset tasu kogu tarneahela ulatuses — muutes ökoloogiline kahju majanduslikuks surveks, samal ajal jaotades tulu ümber inimeste kaitseks.",
    hero_btn_primary: "Vaata, kuidas see toimib ↓",
    hero_btn_secondary: "Liitu liikumisega",
    how_label: "01 — Mehhanism",
    how_title: "Tasu igal etapil",
    how_desc: "CO₂-ekvivalentsed tasud rakendatakse tarneahela igal punktil ülesvoolu. Kogumaksumus koguneb lõpphinda — muutes suure heitega tooted loomulikult kallimaks.",
    stage1_title: "Kaevandamine",
    stage1_desc: "Toorainete kaevandamine, nafta puurimine, koristamine",
    stage2_title: "Tootmine",
    stage2_desc: "Valmistamine, rafineerimine, töötlemine",
    stage3_title: "Transport",
    stage3_desc: "Laevandus, kaubavedu, logistika",
    stage4_title: "Jaemüük &amp; kasutamine",
    stage4_desc: "Jaotamine, tarbija kasutamisfaas",
    stage5_title: "Kõrvaldamine",
    stage5_desc: "Elutsükli lõpp laiendatud tootjavastutuse kaudu",
    stage_fee: "+ CO₂-tasu",
    pipeline_result: "Andmed on juba olemas. <strong>Olelusringi hindamised (LCA)</strong> ja toodete süsiniku jalajäljed katavad kogu ahela — kaevandamisest kõrvaldamiseni. Me ei vaja uut teadust. Me vajame poliitilist tahet.",
    manifesto: "Muuda keskkonnamõju <em>vältimatuks majanduslikuks surveks</em>, seejärel jaota raha ümber, et hoida ühiskonda stabiilsena, sundides turgu samal ajal <em>dekarboniseeruma</em>.",
    principles_label: "02 — Põhimõtted",
    principles_title: "Mille eest me seisame",
    principles_desc: "See ei puuduta teadlikkuse kampaaniaid ega vabatahtlikke lubadusi. See puudutab majanduslike stiimulite ümberkujundamist nullist.",
    p1_title: "Hind, mitte teadlikkus",
    p1_text: "Aastakümnete pikkused teadlikkuse kampaaniad pole heitkõverat painutanud. Hinnasignaalid muudavad käitumist laiaulatuslikult — automaatselt, universaalselt ja kohe.",
    p2_title: "Kaitse inimesi, mitte saastajaid",
    p2_text: "Tulu läheb avalikele hüvedele ja miinimumsissetulekule kõrgemate hindade kompenseerimiseks. Ei mingeid toetusi ettevõtetele, et \"muutuda roheliseks\". Kui saastad, maksad. Raha kaitseb kodanikke.",
    p3_title: "CO₂ sotsiaalne maksumus",
    p3_text: "Tasu tonni kohta põhineb CO₂ tegelikul kahjul. Kõrgem hind tähendab tugevamat käitumismuutust — kuid nõuab ka tugevamat sotsiaalset ümberjaotust, et hoida see õiglasena.",
    p4_title: "EL-ülene rakendamine",
    p4_text: "Ainult riiklik rakendamine moonutab kaubandust ühisturul. See vajab EL-ülest koordineerimist — või hoolikalt kavandatud riiklikke makse, mis ei loo ebaõiglasi eeliseid.",
    examples_label: "03 — Tegelikud arvud",
    examples_title: "Kuidas see välja näeb?",
    examples_desc: "Olemasolevate olelusringi hindamiste ja $100 tonni CO₂-ekvivalendi kohta süsinikuhinna põhjal.",
    ex_case: "Juhtumiuuring",
    ex_beef: "Veiseliha",
    ex_oil: "Toornafta",
    ex_lifecycle: "Olelusringi heited",
    ex_carbon_price: "Rakendatud süsinikuhind",
    ex_additional_kg: "Lisakulu kg kohta",
    ex_additional_barrel: "Lisakulu barreli kohta",
    ex_beef_insight: "Hõlmab söödatootmist (naftapõhised väetised), veiste metaani, maakasutuse muutust ja töötlemist. Enamik heiteid tuleb bioloogiast — mitte ainult energiasisenditest.",
    ex_oil_insight: "Märkimisväärne hinnmõju — kuid kulud hajuvad, kuna nafta jaotub tuhandete järeltoodete vahel. Suurim mõju langeb kontsentreeritud suure heitega protsessidele nagu loomakasvatus, mitte ainult tööstuslikele sisenditele.",
    questions_label: "04 — Ausad lüngad",
    questions_title: "Avatud küsimused",
    questions_desc: "Me ei teeskle, et meil on kõik vastused. Need on rasked probleemid, mille lahendamiseks vajame kollektiivset intelligentsi.",
    q1: "Milline täpne süsinikuhind on vajalik tarbija- ja tööstuskäitumise sisukaks muutmiseks ilma majandusliku šoki tekitamiseta?",
    q2: "Kuidas tagame täpse olelusringi arvestuse globaalselt, kui tarneahelad ulatuvad kümnetesse riikidesse erinevate standarditega?",
    q3: "Kuidas peaksime käsitlema importi mittevastavatelt riikidelt? Süsiniku piirimeetmed on paljulubavad, kuid poliitiliselt ja logistiliselt keerukad.",
    q4: "Milline on realistlik tee poliitilise teostatavuseni EL-i struktuurides — ja kuidas ehitame koalitsiooni selle saavutamiseks?",
    q5: "Kui kiiresti saame üle minna elatusallikaid destabiliseerimata? Milline näeb välja õige tasakaal kiireloomulisuse ja sotsiaalse stabiilsuse vahel?",
    join_label: "05 — Tegutse",
    join_title: "Liitu liikumisega",
    join_desc: "See idee vajab majandusteadlasi, poliitikakujundajaid, aktiviste ja kodanikke, kes usuvad, et hind — mitte süütunne — on see, mis muudab maailma. Lisa oma hääl.",
    join_placeholder: "sinu@email.ee",
    join_btn: "Registreeru",
    join_btn_done: "Lisatud ✓",
    join_note: "Ei rämpsposti. Uuendused poliitika edenemise, uuringute ja tegevuste kohta, mida saad ette võtta.",
    footer_mechanism: "Mehhanism",
    footer_data: "Andmed",
  },
  lv: {
    nav_logo: "Novērtē kaitējumu",
    nav_how: "Kā tas darbojas",
    nav_principles: "Principi",
    nav_examples: "Piemēri",
    nav_questions: "Atklāti jautājumi",
    nav_join: "Pievienojies",
    hero_label: "Politikas ietvars klimata krīzei",
    hero_title: "Padari piesārņošanu<br><em>dārgu</em>.",
    hero_subtitle: "Katram produktam ir slēptas vides izmaksas. Mēs piedāvājam CO₂-ekvivalenta maksu visā piegādes ķēdē — pārvēršot ekoloģisko kaitējumu ekonomiskā spiedienā, vienlaikus pārdalot ieņēmumus cilvēku aizsardzībai.",
    hero_btn_primary: "Uzzini, kā tas darbojas ↓",
    hero_btn_secondary: "Pievienojies kustībai",
    how_label: "01 — Mehānisms",
    how_title: "Maksa katrā posmā",
    how_desc: "CO₂-ekvivalenta maksas tiek piemērotas augšpus katrā piegādes ķēdes punktā. Kopējās izmaksas uzkrājas gala cenā — dabiski padarot augstu emisiju produktus dārgākus.",
    stage1_title: "Ieguve",
    stage1_desc: "Izejvielu ieguve, naftas urbšana, ievākšana",
    stage2_title: "Ražošana",
    stage2_desc: "Rūpnieciskā ražošana, rafinēšana, apstrāde",
    stage3_title: "Transports",
    stage3_desc: "Kuģošana, kravas pārvadājumi, loģistika",
    stage4_title: "Mazumtirdzniecība &amp; lietošana",
    stage4_desc: "Izplatīšana, patērētāja lietošanas fāze",
    stage5_title: "Utilizācija",
    stage5_desc: "Dzīves cikla beigas ar paplašinātu ražotāja atbildību",
    stage_fee: "+ CO₂ maksa",
    pipeline_result: "Dati jau pastāv. <strong>Dzīves cikla novērtējumi (LCA)</strong> un produktu oglekļa pēdas nospiedumi aptver visu ķēdi — no ieguves līdz utilizācijai. Mums nav vajadzīga jauna zinātne. Mums ir vajadzīga politiskā griba.",
    manifesto: "Pārvērt vides ietekmi <em>neizbēgamā ekonomiskā spiedienā</em>, pēc tam pārdali naudu, lai uzturētu sabiedrību stabilu, kamēr tirgus tiek spiests <em>dekarbonizēties</em>.",
    principles_label: "02 — Principi",
    principles_title: "Par ko mēs iestājamies",
    principles_desc: "Runa nav par informēšanas kampaņām vai brīvprātīgiem solījumiem. Runa ir par ekonomisko stimulu pārveidošanu no pamatiem.",
    p1_title: "Cena, nevis informētība",
    p1_text: "Gadu desmitiem ilgas informēšanas kampaņas nav liektušas emisiju līkni. Cenu signāli maina uzvedību plašā mērogā — automātiski, universāli un nekavējoties.",
    p2_title: "Aizsargā cilvēkus, nevis piesārņotājus",
    p2_text: "Ieņēmumi tiek novirzīti sabiedriskiem labumiem un minimālajiem ienākumiem, lai kompensētu augstākas cenas. Nekādu subsidiju uzņēmumiem, lai \"kļūtu zaļi\". Ja piesārņo — maksā. Nauda aizsargā iedzīvotājus.",
    p3_title: "CO₂ sociālās izmaksas",
    p3_text: "Maksa par tonnu ir balstīta uz reālo kaitējumu, ko rada CO₂. Augstāka cena nozīmē spēcīgāku uzvedības maiņu — bet prasa arī spēcīgāku sociālo pārdali, lai saglabātu taisnīgumu.",
    p4_title: "ES mēroga ieviešana",
    p4_text: "Tikai valsts līmeņa ieviešana kropļo tirdzniecību vienotajā tirgū. Tam nepieciešama ES mēroga koordinācija — vai rūpīgi izstrādāti valsts nodokļi, kas nerada negodīgas priekšrocības.",
    examples_label: "03 — Reāli skaitļi",
    examples_title: "Kā tas izskatās?",
    examples_desc: "Izmantojot esošos dzīves cikla novērtējumus un oglekļa cenu $100 par tonnu CO₂-ekvivalenta.",
    ex_case: "Gadījuma izpēte",
    ex_beef: "Liellopu gaļa",
    ex_oil: "Jēlnafta",
    ex_lifecycle: "Dzīves cikla emisijas",
    ex_carbon_price: "Piemērotā oglekļa cena",
    ex_additional_kg: "Papildu izmaksas par kg",
    ex_additional_barrel: "Papildu izmaksas par barelu",
    ex_beef_insight: "Ietver barības ražošanu (naftas bāzes mēslojumi), liellopu metānu, zemes izmantošanas maiņu un apstrādi. Lielākā daļa emisiju nāk no bioloģijas — ne tikai enerģijas ieguldījumiem.",
    ex_oil_insight: "Būtiska ietekme uz cenu — taču izmaksas izšķīst, kad nafta sadalās tūkstošiem pakārtotu produktu. Lielākā ietekme skar koncentrētus augstu emisiju procesus kā lopkopību, ne tikai rūpnieciskos ieguldījumus.",
    questions_label: "04 — Godīgas nepilnības",
    questions_title: "Atklāti jautājumi",
    questions_desc: "Mēs neizliekamies, ka mums ir visas atbildes. Šīs ir grūtās problēmas, kuru risināšanai nepieciešams kolektīvais intelekts.",
    q1: "Kāda precīza oglekļa cena ir nepieciešama, lai jēgpilni mainītu patērētāju un rūpniecības uzvedību, neizraisot ekonomisku šoku?",
    q2: "Kā mēs nodrošinām precīzu dzīves cikla uzskaiti globālā mērogā, ja piegādes ķēdes aptver desmitiem valstu ar dažādiem standartiem?",
    q3: "Kā mums būtu jārīkojas ar importu no neatbilstošām valstīm? Oglekļa robežkorekcijas ir daudzsološas, bet politiski un loģistiski sarežģītas.",
    q4: "Kāds ir reālistisks ceļš uz politisko īstenojamību ES struktūrās — un kā mēs veidojam koalīciju, lai to sasniegtu?",
    q5: "Cik ātri mēs varam pāriet, nedestabilizējot iztiku? Kā izskatās pareizais līdzsvars starp steidzamību un sociālo stabilitāti?",
    join_label: "05 — Rīkojies",
    join_title: "Pievienojies kustībai",
    join_desc: "Šai idejai ir nepieciešami ekonomisti, politikas veidotāji, aktīvisti un pilsoņi, kas tic, ka cena — nevis vainas apziņa — ir tas, kas maina pasauli. Pievieno savu balsi.",
    join_placeholder: "tavs@epasts.lv",
    join_btn: "Reģistrēties",
    join_btn_done: "Pievienots ✓",
    join_note: "Nekāda surogātpasta. Jaunumi par politikas virzību, pētījumiem un darbībām, ko vari veikt.",
    footer_mechanism: "Mehānisms",
    footer_data: "Dati",
  },
  lt: {
    nav_logo: "Įkainok žalą",
    nav_how: "Kaip tai veikia",
    nav_principles: "Principai",
    nav_examples: "Pavyzdžiai",
    nav_questions: "Atviri klausimai",
    nav_join: "Prisijunk",
    hero_label: "Politikos sistema klimato krizei",
    hero_title: "Padaryk taršą<br><em>brangią</em>.",
    hero_subtitle: "Kiekvienas produktas turi paslėptą aplinkosauginę kainą. Siūlome CO₂-ekvivalento mokestį visoje tiekimo grandinėje — paverčiant ekologinę žalą ekonominiu spaudimu ir perskirstant pajamas žmonių apsaugai.",
    hero_btn_primary: "Sužinok, kaip tai veikia ↓",
    hero_btn_secondary: "Prisijunk prie judėjimo",
    how_label: "01 — Mechanizmas",
    how_title: "Mokestis kiekviename etape",
    how_desc: "CO₂-ekvivalento mokesčiai taikomi prieš srovę kiekviename tiekimo grandinės taške. Bendra kaina kaupiasi galutinėje kainoje — natūraliai brangindama didelių išmetimų produktus.",
    stage1_title: "Gavyba",
    stage1_desc: "Žaliavų kasimas, naftos gręžimas, derliaus nuėmimas",
    stage2_title: "Gamyba",
    stage2_desc: "Pramoninė gamyba, rafinavimas, apdorojimas",
    stage3_title: "Transportas",
    stage3_desc: "Laivyba, krovinių pervežimas, logistika",
    stage4_title: "Mažmeninė prekyba &amp; naudojimas",
    stage4_desc: "Platinimas, vartotojo naudojimo fazė",
    stage5_title: "Šalinimas",
    stage5_desc: "Gyvavimo ciklo pabaiga pagal išplėstinę gamintojo atsakomybę",
    stage_fee: "+ CO₂ mokestis",
    pipeline_result: "Duomenys jau egzistuoja. <strong>Gyvavimo ciklo vertinimai (LCA)</strong> ir produktų anglies pėdsakai apima visą grandinę — nuo gavybos iki šalinimo. Mums nereikia naujo mokslo. Mums reikia politinės valios.",
    manifesto: "Paverskite aplinkos poveikį <em>neišvengiamu ekonominiu spaudimu</em>, tada perskirstykite pinigus, kad visuomenė išliktų stabili, kol rinka priverčiama <em>dekarbonizuotis</em>.",
    principles_label: "02 — Principai",
    principles_title: "Už ką mes pasisakome",
    principles_desc: "Tai ne apie informavimo kampanijas ar savanoriškus įsipareigojimus. Tai apie ekonominių paskatų pertvarkymą iš pagrindų.",
    p1_title: "Kaina, ne sąmoningumas",
    p1_text: "Dešimtmečiai informavimo kampanijų nepalenkė išmetimų kreivės. Kainų signalai keičia elgesį dideliu mastu — automatiškai, universaliai ir nedelsiant.",
    p2_title: "Saugok žmones, ne teršėjus",
    p2_text: "Pajamos skiriamos viešosioms gėrybėms ir minimalioms pajamoms, kad kompensuotų aukštesnes kainas. Jokių subsidijų įmonėms \"tapti žaliomis\". Jei terši — moki. Pinigai saugo piliečius.",
    p3_title: "Socialinė CO₂ kaina",
    p3_text: "Mokestis už toną grindžiamas realia CO₂ daroma žala. Aukštesnė kaina reiškia stipresnį elgesio pokytį — bet taip pat reikalauja stipresnio socialinio perskirstymo, kad tai būtų teisinga.",
    p4_title: "ES masto įgyvendinimas",
    p4_text: "Vien tik nacionalinis įgyvendinimas iškraipo prekybą bendrojoje rinkoje. Tam reikia ES masto koordinavimo — arba kruopščiai suprojektuotų nacionalinių mokesčių, kurie nesukuria nesąžiningų pranašumų.",
    examples_label: "03 — Tikri skaičiai",
    examples_title: "Kaip tai atrodo?",
    examples_desc: "Remiantis esamais gyvavimo ciklo vertinimais ir $100 už toną CO₂-ekvivalento anglies kaina.",
    ex_case: "Atvejo analizė",
    ex_beef: "Jautiena",
    ex_oil: "Žaliavinė nafta",
    ex_lifecycle: "Gyvavimo ciklo išmetimai",
    ex_carbon_price: "Taikoma anglies kaina",
    ex_additional_kg: "Papildoma kaina už kg",
    ex_additional_barrel: "Papildoma kaina už barelį",
    ex_beef_insight: "Apima pašarų gamybą (naftos pagrindu pagamintų trąšų), galvijų metaną, žemės naudojimo pokytį ir perdirbimą. Dauguma išmetimų kyla iš biologijos — ne vien iš energijos sąnaudų.",
    ex_oil_insight: "Reikšmingas poveikis kainai — tačiau išlaidos praskiedžiamos, kai nafta pasiskirsto tarp tūkstančių tolesnių produktų. Didžiausias poveikis tenka koncentruotiems didelių išmetimų procesams, tokiems kaip gyvulininkystė, o ne vien pramoninėms žaliavoms.",
    questions_label: "04 — Sąžiningos spragos",
    questions_title: "Atviri klausimai",
    questions_desc: "Mes neapsimetame, kad turime visus atsakymus. Tai sudėtingos problemos, kurioms spręsti reikia kolektyvinio intelekto.",
    q1: "Kokia tiksli anglies kaina reikalinga, kad prasmingai pakeistų vartotojų ir pramonės elgesį nesukeliant ekonominio šoko?",
    q2: "Kaip užtikrinsime tikslią gyvavimo ciklo apskaitą globaliai, kai tiekimo grandinės apima dešimtis šalių su skirtingais standartais?",
    q3: "Kaip turėtume elgtis su importu iš neatitinkančių šalių? Anglies pasienio koregavimai yra perspektyvūs, bet politiškai ir logistiškai sudėtingi.",
    q4: "Koks yra realistinis kelias į politinį įgyvendinamumą ES struktūrose — ir kaip suformuosime koaliciją tam pasiekti?",
    q5: "Kaip greitai galime pereiti nedestabilizuodami pragyvenimo šaltinių? Kaip atrodo tinkama pusiausvyra tarp skubos ir socialinio stabilumo?",
    join_label: "05 — Veik",
    join_title: "Prisijunk prie judėjimo",
    join_desc: "Šiai idėjai reikia ekonomistų, politikos formuotojų, aktyvistų ir piliečių, kurie tiki, kad kaina — ne kaltė — yra tai, kas keičia pasaulį. Pridėk savo balsą.",
    join_placeholder: "tavo@elpastas.lt",
    join_btn: "Registruotis",
    join_btn_done: "Pridėta ✓",
    join_note: "Jokio brukalų. Naujienos apie politikos pažangą, tyrimus ir veiksmus, kurių galite imtis.",
    footer_mechanism: "Mechanizmas",
    footer_data: "Duomenys",
  },
};
